### ISSUE TITLE
Alpine armv7

### ISSUE THREAD

**Issue by anweiss** [vercel/pkg#100]
Any plans to include an alpine-armv7 target?

**Comment by TooTallNate** [comment]
Doesn't `pkg` fall back to self-compiling the Node.js version in that case though?

It could be possible to add pre-compiled binaries in the future. I'm curious what Alpine ARM image you're using.

**Comment by anweiss** [comment]
It doesn't seem to in this case. Trying to run pkg in this image -> https://hub.docker.com/r/armhf/alpine/.

**Comment by igorklopov** [comment]
@anweiss Please try with `pkg@4`. If the issue is still there, please provide full log.

**Comment by kerberjg** [comment]
Is this issue still present?

**Comment by jesec** [comment]
armv7 has been deprecated.
