### ISSUE TITLE
Is it possible to compile the app to a version of it that don't come with the nodejs executable?

### ISSUE THREAD

**Issue by litch0** [vercel/pkg#1000]
I am making an app that will be run by people that have nodejs installed on their computer, is there any way to compile the program to a specific file (like jsc |Javascript compiled| ) and then using a function (inside another javascript file) load this file and run it?

**Comment by redbrain** [comment]
If you use `module.exports` to export the program's functions, you can then `require()` it inside another js file and run it that way.
pkg isn't needed for this, as it's meant to compile binaries that are bundled with Node.

**Comment by litch0** [comment]
OK Thanks
