### ISSUE TITLE
sql executable path gets changed due to __dirname manipulation by pkg

### ISSUE THREAD

**Issue by rthangam** [vercel/pkg#1001]
We have developed a tool using node js, the tool needs to invoke sql executables. The tool works fine, but when we try to package it using pkg module we see that it changes __dirname variable.
For example "/Users/rthangam/src/sql" becomes "/snapshot/rthangam/src/sql" 

How to avoid this manipulation by pkg?

Is there any substitue for __dirname because we need the path of the file which is getting executed to get executable path.

**Comment by somuelle-tmt** [comment]
For example, you can write your executable files somewhere in the normal file system before executing them, e.g. TEMP

**Comment by rthangam** [comment]
Are you saying we need to create a TEMP directory ? Can it pickup from there ? Can you explain in detail ?

**Comment by miraclx** [comment]
That's probably the case, pkg probably just intercepts fs calls to `/snapshot` and resolves it with internal data.

For this use case, the first time your executable is run, you can get readable streams to the assets (binaries) you want, and write them into an external staged directory (maybe even a temp dir), or if you embedded a zip file, extract that into your staged dir.

Then you can spawn the executables with that path on your actual local filesystem.

To speed things up (especially at startup), maybe don't use a random temp dir for each run.

So you can use the assets from the previous extraction. (to save having to extract on every run)
