### ISSUE TITLE
How to change the snapshot path with build  ？

### ISSUE THREAD

**Issue by pxim** [vercel/pkg#1003]
Now my project is in disk E. after PKG is packaged and generated, his snapshot address is locked in disk E. if other computers do not have e-disk, an error will be reported. I do not want to change the project disk directory. I want to change the snapshot address to Disk C or relative path.
Is there any way ?

pkg：v4.4.9

**Comment by lselden** [comment]
That sounds like you have a path hardcoded somewhere - pkg doesn't care about the drive it was originally located on. Check out the [Snapshot filesystem](https://github.com/vercel/pkg#snapshot-filesystem) for how to resolve paths relatively (`process.execPath` is your friend).

**Comment by pxim** [comment]
> That sounds like you have a path hardcoded somewhere - pkg doesn't care about the drive it was originally located on. Check out the [Snapshot filesystem](https://github.com/vercel/pkg#snapshot-filesystem) for how to resolve paths relatively (`process.execPath` is your friend).

thank you very much
