### ISSUE TITLE
Why I get error

### ISSUE THREAD

**Issue by chenfan19** [vercel/pkg#1004]
It says  "Error! connect ETIMEDOUT 192.30.255.113:443"

If I try it again, the ip address will be changed.

**Comment by chenfan19** [comment]
full text:

> pkg@4.4.9
> Targets not specified. Assuming:
  node12-linux-x64, node12-macos-x64, node12-win-x64
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.18.1-linux-x64   [                    ] 0%
> Error! connect ETIMEDOUT 52.216.10.83:443
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.18.1-linux-x64"}
> Error! connect ETIMEDOUT 192.30.255.116:443

**Comment by rthangam** [comment]
Check if you are on VPN and you haven't set proxy ?
