### ISSUE TITLE
Can this be used outside of a container?

### ISSUE THREAD

**Issue by dland512** [vercel/pkg#1011]
The top of the readme says

> Disclaimer: pkg was created for use within containers . . .

However I am writing an app that targets Linux running on an ARMv7 device. There are no containers involved. Will this module work for that case?

Here is the device info:

```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

processor	: 0
model name	: ARMv7 Processor rev 10 (v7l)
BogoMIPS	: 3.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc09
CPU revision	: 10
```

**Comment by iba-jsykes** [comment]
Yes, I'm deploying on Windows, Linux and Mac, no containers.

**Comment by leerob** [comment]
Closing as the question has been resolved!
