### ISSUE TITLE
Using PKG with Webpack => why /snapshot/project/node_modules ?

### ISSUE THREAD

**Issue by panpansh** [vercel/pkg#1019]
I have no error all is working fine.

Looking inside /snapshot/project/ : I don't know why there is some node_modules here.

would there be a possibility not to include any node_modules please ? (because using webpack).

Wishing you happy holidays <3

**Comment by shinylightdev** [comment]
You may want to post your package.json and how you're calling pkg.

**Comment by panpansh** [comment]
```js
"scripts": {
    ...
    "win:pkg": "cross-env NODE_ENV=production pkg --targets=win ./bundle.js --output ./dist/client.exe --config ./package.json",
    ...
},
"pkg": {
    "assets": [
         "assets/**/*"
    ]
}
```
is there a simple way to force to not import any node_modules ?

**Comment by panpansh** [comment]
Ok so, I just need to move my bundle.js inside my dist folder by example. and dont let him next to node_modules.
Thats all.
Regards
