### ISSUE TITLE
Change hardcoded "snapshot" directory to be relative to executable

### ISSUE THREAD

**Issue by shinylightdev** [vercel/pkg#1020]
Can't find in the docs, the appropriate config so that **rather than having** the following:

```
c:\app-dir\app.exe
c:\snapshot\app-dir  [generated by pkg]
```

I **just have this**:

```
c:\app-dir\app.exe
c:\app-dir\snapshot\app-dir
```

Basically, I want to house the entire app under just **one dir - not have two**. Is this even possible? I'm on **node14-win-x64**,

Thanks

**Comment by panpansh** [comment]
can I ask you why you asked me for more informations regarding this post https://github.com/vercel/pkg/issues/1019 ?
Was it in order to inform ME about or rather in order to inform YOU ... ?

**Comment by shinylightdev** [comment]
It was to help someone else troubleshoot/help you more affectively. That would probably be their next question. Unfortunately, I don't have an answer for you.

**Comment by dverzolla** [comment]
I'm writing a backup system, when I run backup.exe (packaged with pkg) the user can see the fake c:\snapshot\ folder created by pkg. I am using fs.readdir. 

This 'c:\snapshot' hardcoded makes a bug in my software, once the user couldn't never use a real folder called snapshot.

Any ideas how to overcome this.

**Comment by robertsLando** [comment]
@jsec is this fixed?

**Comment by jsec** [comment]
> @jsec is this fixed?

Did you tag the wrong person here?

**Comment by robertsLando** [comment]
Ops, sorry. Was looking for @jesec

**Comment by jesec** [comment]
This is not an issue. 

By convention, it is `/snapshot` on Unix and `C:\snapshot` on Windows. The behavior is very clearly documented in README, and I don’t see a reason to change that. Additionally, it would be a breaking change.
