### ISSUE TITLE
[QUESTION] How to resolve PWD?

### ISSUE THREAD

**Issue by BlackYuzia** [vercel/pkg#1027]
#89 I find only this issue about process.env about PWD. 
But, currently I can say what I can't find this too.

If I write this code and use `pkg` for build: 
```
process.cwd()      // this is work fine
process.env.PWD // undefined | I required this one because I want get folder from exec with symlink.
```
when I try debug **process.env** I didn't find any phrases (keys) PWD. 

If I didn't run it in `pkg` - `process.env.PWD` work fine.

What I should to do? [**More details about symlink and pwd / cwd**](https://stackoverflow.com/questions/24112452/node-dirname-process-cwd-are-reporting-actual-directory-instead-of-symlinke/55012688)

@igorklopov 

Note: If `PWD` is exist in `pkg`, can you give me example of resolving him?

**Comment by BlackYuzia** [comment]
F

**Comment by robertsLando** [comment]
If you didn't set the `PWD` env var on start it will not be present
