### ISSUE TITLE
discord.js functionality impaired when packaged

### ISSUE THREAD

**Issue by AxxlForce** [vercel/pkg#1028]
When packaged as executable the functionality of discord.js is impaired. It still connects to a server but communication afterwards does not work but no error is thrown. Running the app directly with node works fine, so it must be related to pkg. Something fails silently and a way is required to debug it.

**Comment by 64ZooLane** [comment]
Yeah I had a similar issue. You can use discord.js v11 instead of v12 as a fix for now.

`npm i discord.js@11.6.4 --save`

**Comment by leerob** [comment]
We would love your help contributing back on this 🙏 I'm going to close as "wont fix" for now, but if you would like to take a shot, we'd greatly appreciate it. 

Thank you!
