### ISSUE TITLE
1.5-2 times more memory consumption compare with Enclose.js

### ISSUE THREAD

**Issue by lsm** [vercel/pkg#103]
The source code for compilation are same for both.

`pkg: node@6.10.0, linux, x64`
`enclose: node@6.3.1, linux, x64`

The binary compiled by `pkg requires 130Mb` of memory to start while the one compiled by `enclose only requires 50~60Mb`.

What could be the problem? @igorklopov

**Comment by igorklopov** [comment]
Please output the list of files that are packaged by each product. I am sure `pkg` takes more files into executable to avoid more run time issues.

**Comment by lsm** [comment]
I tried to compile again using `pkg` with `-d` and the output log was 2.5Mb with 36k lines of content.  So, basically 18k file included?  That sounds pretty much all the files in my `node_modules` folder.

**Comment by lsm** [comment]
Btw, just found my `node_modules` has 25k files.

**Comment by igorklopov** [comment]
How big is the log from `enclose` ?

**Comment by lsm** [comment]
Only 77k in size and 1.4k lines of content.  Way smaller.  Looks like `pkg` bundles most of the packages and this indeed make it convenience for first time usage or small projects.  But, I also found `enclose` + `scripts` option was enough for me to get all necessary files included.  Maybe we can have a flag to switch between these two preferences?

**Comment by igorklopov** [comment]
I will be very grateful if you find essential difference in packaged files list. As for me - i will willingly explain to you any difference you find. Ok? 😉

**Comment by lsm** [comment]
You meant send you the two files?  I can do that.  Is that okay to email them to your enclose paypal email?

**Comment by igorklopov** [comment]
I mean find the difference between two files.

**Comment by lsm** [comment]
I did find the difference.  For example, we have following file:

```js
var micromono = require('micromono')
```

- For `enclose` only packages which explicitly required from code will be compiled/bundled. 

- For `pkg` looks like it compiles everything (at least most of them) in the `node_modules`.  And one of the big difference is it includes the `jspm` package which has huge dependencies.  But, `jspm` is not directly required if you just `require('micromono')`.

I hope my explanation is clear enough for you to spot the problem.  Please let me know if you need more info.

**Comment by anhoev** [comment]
any news ?
