### ISSUE TITLE
i18next compatibility

### ISSUE THREAD

**Issue by absalomedia** [vercel/pkg#1030]
I'm working on some projects that extensively use i18next through Node and the filesystem. That means I'm using i18next-fs-backend and the use of __dirname to resolve translation files.

Packaging the apps using PKG keeps failing to resolve i18next inside the apps as the path get changed to /snapshot/

I would like to continue to use i18next and pkg together if possible. Has Vercel or anyone else use PKG managed to find a solution where both work together in harmony?

**Comment by leerob** [comment]
Hey! I'm sorry you had a bad experience here trying to use pkg with i18next. This project has been unmaintained for awhile, and I'm trying to clean things up. I'm going to close this as won't fix, but if you end up doing a deep dive and figuring this out, I'd be happy to review / merge PRs. 

Thank you! 🙏
