### ISSUE TITLE
 versioning?

### ISSUE THREAD

**Issue by DevRafaelCena** [vercel/pkg#1031]
hello, can i create version of my application?
the .exe contains the version of the node, I would like to insert my version of the package.json

**Comment by lselden** [comment]
If you want to read the version of your application then just be sure to include your code's `package.json` in your list of [assets](https://github.com/vercel/pkg#assets). Then you can read the file (something like `JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), { encoding: 'utf8' }))` should do the trick) and display your application version as needed.

**Comment by DevRafaelCena** [comment]
I didn’t exactly want to read this value, I wanted it in the .exe, when I right clicked and went to properties, the correct name and version of my application should be listed, not nodejs

**Comment by suresh-rajen** [comment]
Facing the same issue, please let me how to update the metadata?

![image](https://user-images.githubusercontent.com/41784383/105462951-664b9f00-5cb5-11eb-85f9-8f189226bc90.png)

**Comment by pspaulding** [comment]
Agreed, this would be a nice feature.

**Comment by boring10** [comment]
This would be a nice addition. I would propose that the file description be the name from package.json and the file version be the version from package.json and leave the rest of the information alone.

**Comment by leerob** [comment]
Currently not planning to add this, unless someone from the community makes a PR. Closing, but will reopen if a PR is made. Thanks!
