### ISSUE TITLE
Continue to keep this project alive

### ISSUE THREAD

**Issue by Bellisario** [vercel/pkg#1033]
This project is no longer mantained from 9 aug 2018 with package updades. Please, return to keep alive this wonderful project, or someone will clone it...

**Comment by pedropalhari** [comment]
Well they integrated into their own solution, feel free to clone and improve it, that's what open source is about. If you keep it up to date, I promise I'll use it!

**Comment by trevyn** [comment]
There is some discussion of forking over here, in the context of wanting to pull in a PR for bundling of native addons: https://github.com/vercel/pkg/pull/837#issuecomment-775362263

**Comment by Bellisario** [comment]
Thank you @trevyn!!!

**Comment by leerob** [comment]
I will be helping review / merge PRs now! 👋
