### ISSUE TITLE
Can PKG package .JSC files?

### ISSUE THREAD

**Issue by Hello-GBY** [vercel/pkg#1034]
Hi
I want to change server.jsc to server.exe

### package.json ：
{
    "bin": "./server.jsc",
    "pkg": {
		"targets": [
		"x64"
		]
    }
}
perform：  pkg  -t  win package.json
result： The generated.exe has no response

The purpose of this is to：
I want the binary file to be visible to the user after decompiling

Thanks

**Comment by robertsLando** [comment]
I suggest to use ncc as first step and then pkg
