### ISSUE TITLE
fs.writefilesync() Error: EPERM: operation not permitted, open

### ISSUE THREAD

**Issue by DavidC001** [vercel/pkg#1037]
whenever i try to save a file to whatever location it gives this error.
Initialy i was trying to save a canvas image but even trying to save a text file gives error.
To save the file i use this piece of code:
					salva = './immagini_classifica/' + posizione/9 + '.txt';
					await fs.writeFileSync(salva, "text");
any idea?

**Comment by muralik296** [comment]
Hi were you able to solve the issue?
