### ISSUE TITLE
pkg with source pointing to vercel instead of zeit

### ISSUE THREAD

**Issue by PriyaSivaraj1987** [vercel/pkg#1039]
At work i'm behind a proxy and i got the following error message :
https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.18.1-win-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.18.1-win-x64"}

Redirect doesn't work for us. If there is a way to pass in corporate proxy location for github.com or point the source to use github.com/vercel that would be great.

Currently we are forced to download the pkg and use CACHE_PATH in pipelines as mentioned in https://github.com/vercel/pkg/issues/744

But it is a manual step that needs to be performed by the project each time they need to upgrade.

**Comment by leerob** [comment]
This will be fixed as soon as a release it cut. Which is being here https://github.com/vercel/pkg/issues/1061
