### ISSUE TITLE
Build with multiple processors

### ISSUE THREAD

**Issue by PaserSRL** [vercel/pkg#1045]
Maybe I've missing something in documentation but is not possible to compile using multiple processors?
I know that NodeJS doesn't allow core management but during building I've found that Pkg runs "make" command.

Is not possible to run it as "make -j$(nproc)"?

Thanks

**Comment by jesec** [comment]
https://github.com/vercel/pkg-fetch/commit/93431471c6e8d3824f3350641f6ec05ab1dfc350
