### ISSUE TITLE
Setting output or out-path in package.json has no impact

### ISSUE THREAD

**Issue by binarykitchen** [vercel/pkg#1048]
If I have something like this in my package.json

```
  "pkg": {
    "assets": [
      "target/resources/public/**/*"
    ],
    "output": "packages",
    "out-path": "packages"
  },
```

I still don't see them in the packages subfolder. Tried all combinations and sorry, documentation is a bit poor. Any help?

**Comment by skaneprime** [comment]
+1 same issue

**Comment by robertsLando** [comment]
The correct property should be `"outputPath"`

**Comment by skaneprime** [comment]
> The correct property should be `"outputPath"`

even `"outputPath"` is not working. It creates it at root directory 

Tried `"outputPath": "./bin"`, `"outputPath": "./bin/myfile.exe"`, `"outputPath": "myfile.exe"` it ignores all of it and creates exe with name specified in package.json

**Comment by robertsLando** [comment]
Did you try to create the directory first?

**Comment by skaneprime** [comment]
> Did you tried to create the directory first?

Yes. I tried

**Comment by skaneprime** [comment]
Solved. I was using 4.4.9 which completely ignored this param
