### ISSUE TITLE
the sourceless flag, more docs on this?

### ISSUE THREAD

**Issue by navigator117** [vercel/pkg#1055]
I found `sourceless` flag added in your patch file to node.js source code, but it's not documented in your npm site. Could you please add some explain & usage for this flag?

**Comment by leerob** [comment]
We'd be happy to have you contribute if you'd like to add this! Thanks 🙏

**Comment by navigator117** [comment]
Sorry, I'm afraid I can't, cause I don't understand means of this option. I just check the executable file output by pkg with some hexdisplay tools, but I found there are javascript text code inside the binary, not bytecode as expect. So I check the patch code and found this option.

**Comment by robertsLando** [comment]
Sourceless is a flag added in order to be able to run node without source code, it's the main reason why patch files are needed right now
