### ISSUE TITLE
PKG will ignore half of my code

### ISSUE THREAD

**Issue by JarnoXYZ** [vercel/pkg#1072]
hello, i am trying to use PKG for the first time. But it won't work for my discord message part. 

client.on('message', msg => {
  if (msg.content === '!hello') {
    msg.reply(`hey`);
  }
});
 

It will ignore that code above. I am using ''pkg myapp.js''

**Comment by JeffJassky** [comment]
it looks to me like ```hey``` is a missing variable and not a string. Is ```hey``` defined as a variable somewhere beforehand?

**Comment by robertsLando** [comment]
pkg doens't ignore any code, does it actually work if you run the app with node myapp.js?
