### ISSUE TITLE
Node 8.10 breaking

### ISSUE THREAD

**Issue by absalomedia** [vercel/pkg#1091]
Doing a clean install on a Node 8 platform and PKG is reporting this
`/usr/local/lib/node_modules/pkg/node_modules/globby/index.js:28
	} catch {
	        ^

SyntaxError: Unexpected token {`

Any ideas why globby is broken inside PKG?

**Comment by robertsLando** [comment]
It depends on the version of globby you are using but in its readme it reports compatibility with node >= 10 so that could be the root cause https://github.com/sindresorhus/globby/blob/main/package.json#L14

**Comment by shivam222** [comment]
As a workaround to get it working with node 8 you can simply change catch to catch(e)

**Comment by absalomedia** [comment]
@shivam222  unsure why you're replying to a closed topic. How did you find this?
