### ISSUE TITLE
Not finding binary

### ISSUE THREAD

**Issue by NikosFotiadis** [vercel/pkg#1098]
Error from docker
```
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH

> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.16.0-alpine-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.16.0-alpine-x64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.16.0-alpine-x64"}
> Building base binary from source:
  built-v14.16.0-alpine-x64
> Error! Not able to build for 'alpine' here, only for 'linux'
```
Using the exact same code I was using to build 4 hours ago and It was working fine until then.

I am targeting alpine. This is the command I am using
```
pkg ./index.js --output exec --targets alpine
```
From what I can see this `uploaded-v2.6-node-v14.16.0-alpine-x64` is missing entirely from the assets

**Comment by robertsLando** [comment]
In the command please specify node14.4.0 instead of node14

**Comment by NikosFotiadis** [comment]
Thanks, that works.

**Comment by BarelyAliveMau5** [comment]
I had the same issue, using `pkg -t node14.4.0` worked

**Comment by robertsLando** [comment]
Will fix this tomorrow btw, for now take that

**Comment by robertsLando** [comment]
Please refer to: https://github.com/vercel/pkg-fetch/issues/137
