### ISSUE TITLE
 node-v12.21.0 404 Not Found 

### ISSUE THREAD

**Issue by novast** [vercel/pkg#1101]
pkg .
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.21.0-linux-x64   [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.21.0-linux-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.21.0-linux-x64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.21.0-linux-x64"}
> Building base binary from source:
  built-v12.21.0-linux-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v12.21.0
> Applying patches
> Compiling Node.js from sources...
  make                         [                    ] 0

**Comment by robertsLando** [comment]
Please use fixed version `12.2.0` for node to fix this

**Comment by robertsLando** [comment]
Please refer to: https://github.com/vercel/pkg-fetch/issues/137
