### ISSUE TITLE
Better error messages with hyperlinks

### ISSUE THREAD

**Issue by rauchg** [vercel/pkg#1104]
![image](https://user-images.githubusercontent.com/13041/112664463-3afd4180-8e17-11eb-8680-d6f73cc09440.png)

- It took me a while to understand this error message. I thought it meant I didn't have Node 15 locally
- It'd be great to link all error messages to markdown files in the repo so that we can expand and improve them over time

**Comment by robertsLando** [comment]
@rauchg would you like to send a pr?

**Comment by leerob** [comment]
I was talking with @rauchg about this - he wanted to open an issue here to track it (he won't be doing the coding for it I'd assume).

It's a good first issue for folks looking to contribute back!

**Comment by robertsLando** [comment]
Yeah not so hard to implement, will see if someone shows up. IMO the most important thing to sort out is the pkg-fetch flow to build binaries
