### ISSUE TITLE
Cannot run pkg . behind a proxy

### ISSUE THREAD

**Issue by brendon-flanagan** [vercel/pkg#1110]
Hi, how do I run this behind a proxy.

Keep getting errors of

pkg .
> pkg@4.5.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v8.17.0-win-x64      [                    ] 0%(node:13720) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure
by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

> Error! tunneling socket could not be established, statusCode=504
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v8.17.0-win-x64"}
  fetched-v8.17.0-win-x64      [                    ] 0%
> Error! tunneling socket could not be established, statusCode=504

**Comment by DaMavius** [comment]
looks like it can not download the nodejs behind your proxy.
I am curious what is the reason behind building your package with proxy?

**Comment by jesec** [comment]
https://github.com/vercel/pkg-fetch/commit/6e5bccd731d3929688115c1432d3d5707c1fbdea may help with this issue.

**Comment by mib008** [comment]
Same problem...but

```
npx pkg ./index.js --options "agent=http://<proxy_host>:<proxy_port>"
```

works for me.
