### ISSUE TITLE
Unable to compile due to node version

### ISSUE THREAD

**Issue by reesericci** [vercel/pkg#1112]
I have node version v15.12.0 but i get this error when compiling: 

`Error! No available node version satisfies 'node15'`

**Comment by robertsLando** [comment]
it's not an error, it just means you need to chose a different node version or build your own :)

**Comment by reesericci** [comment]
what do I do to make it work? @robertsLando

**Comment by robertsLando** [comment]
Could you use nodjs 12/14? If you need to use node15 you can build it your own (takes some hours)

**Comment by reesericci** [comment]
yay it worked! I installed 14 and it worked fine
