### ISSUE TITLE
uploaded-v2.6-node-v12.21.0-linux-x64 version is not available for download 

### ISSUE THREAD

**Issue by ashi100sh** [vercel/pkg#1116]
uploaded-v2.6-node-v12.21.0-linux-x64 version is not available for download , please make it available .
it is causing issue if in system python is not available 

+ pkg@4.4.8
updated 1 package in 3.019s
pkg package.json --targets host --output test-platform
> pkg@4.4.8
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.21.0-linux-x64   [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.21.0-linux-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.21.0-linux-x64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.21.0-linux-x64"}
> Building base binary from source:
  built-v12.21.0-linux-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v12.21.0
> Applying patches
> Compiling Node.js from sources...
./configure: 4: exec: python: not found
> Error! Error: ./configure failed with code 127
    at ChildProcess.<anonymous> (/usr/lib/node_modules/pkg/node_modules/pkg-fetch/lib-es5/spawn.js:68:23)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
make[1]: *** [Makefile:63: install] Error 2

**Comment by robertsLando** [comment]
Available binaries are listed here: https://github.com/vercel/pkg-fetch/releases/tag/v2.6

**Comment by ashi100sh** [comment]
I know. But why suddenly existing package has been moved.

**Comment by robertsLando** [comment]
Just saw you are using pkg version 4.4.8, I think you made a fresh intall of it, in this case it will be shipped with pkg-fetch 2.6.10 that has new patches like the one for node 12.21.0. I suggest you to update pkg to latest version and iut will be back working again as we made pkg-fetch a static dep
