### ISSUE TITLE
Typing Mistake

### ISSUE THREAD

**Issue by Rizwan-Hasan** [vercel/pkg#1119]
There is a simple typing mistake on example readme's package.json on the released version on npm.

![Screenshot from 2021-04-06 02-59-19](https://user-images.githubusercontent.com/16849373/113626593-2e34e500-9684-11eb-8699-3f99c874c3e2.png)

**Comment by erossignon** [comment]
It seems to be a weird coloring issue in npmjs.com, I would not bother about this. Or report the issue to them.

**Comment by Rizwan-Hasan** [comment]
It's not a weird color issue. The block contains a JSON and the outputPath key has only on double quotation on starting. Ending double quotation is missing. That's why that red color has occured. It's indicating an error in JSON syntax.

**Comment by robertsLando** [comment]
It's just a bug on npm as if you cehck readme the quote is there

**Comment by Rizwan-Hasan** [comment]
I created this issue seeing that npm has a pkg version of 4.5.1 and pkg's 4.5.1 branch on GitHub also has the same double quotation issue as I've mentioned earlier. Anyway, Thanks.

**Comment by robertsLando** [comment]
![Schermata da 2021-04-07 11-41-59](https://user-images.githubusercontent.com/11502495/113845964-501e8c80-9796-11eb-9f65-bedcec906d89.png)

**Comment by Rizwan-Hasan** [comment]
So, it seems the next release will solve that on npm, and till then it will be as it is now. Thanks. 😊
