### ISSUE TITLE
Possibility to make the exe run as Admin (Manifest)

### ISSUE THREAD

**Issue by luizhrios** [vercel/pkg#1125]
I have a script that does some "setx /m" and it only works as admin, I would like to change the requestedExecutionLevel to requireAdministrator, I tried with some resource tools but it completely breaks the script. Is it possible?

**Comment by luizhrios** [comment]
This should not be that hard

**Comment by einsqing** [comment]
Did you solve it?

**Comment by luizhrios** [comment]
No, kinda sad no answers

**Comment by luizhrios** [comment]
No, kinda sad no answers

**Comment by ThinhVu** [comment]
necromancer

**Comment by ThinhVu** [comment]
> No, kinda sad no answers

I think you can try running cmd as administrator, then open your app.exe from it.
