### ISSUE TITLE
create a node child_process by spawn,  can't support --require

### ISSUE THREAD

**Issue by hongxiyu** [vercel/pkg#1126]
example: 

spawn('node', [
    '--require',
    '/snapshot/hdsp-server/node_modules/source-map-support/register.js',
    '/snapshot/hdsp-server/node_modules/egg-scripts/lib/start-cluster',
    '{"baseDir":"/snapshot/hdsp-server","framework":"/snapshot/hdsp-server/node_modules/@tencent/asgard","title":"egg-server-hdsp-server"}',
    '--title=egg-server-hdsp-server'
  ], {});

this comes error:   

Error: Cannot find module '/Users/xxx/code/hdsp-server/dist/--require'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1027:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1459:46)
    at Function.Module._load (internal/modules/cjs/loader.js:896:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1488:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by hacke2** [comment]
I got the same error 😊

**Comment by hacke2** [comment]
Maybe it has something to do with this line： https://github.com/eggjs/egg-scripts/blob/ad585eb4e25e3b07320419b36f68174af9ad235a/lib/cmd/start.js#L157

**Comment by hacke2** [comment]
Is there a good solution to this problem? Thank you @mojoaxel @erossignon

**Comment by hacke2** [comment]
Temporary solution: take a look https://github.com/eggjs/egg-scripts/blob/ad585eb4e25e3b07320419b36f68174af9ad235a/lib/command.js#L47

we can disable egg.typescript

```json
{
 "egg": {
      "typescript": false
  }
}
```

**Comment by hacke2** [comment]
There is actually a solution here https://github.com/vercel/pkg/issues/107#issuecomment-563942572

**Comment by hacke2** [comment]
maybe this pr can fix it https://github.com/vercel/pkg/pull/1157

**Comment by hacke2** [comment]
![image](https://user-images.githubusercontent.com/6399899/121770208-9a5b2a00-cb9a-11eb-8559-2b8eaa3740fb.png)

Why is process.execPath the current directory? It should be  `/deploy/ app-x64`

**Comment by hacke2** [comment]
![image](https://user-images.githubusercontent.com/6399899/121770606-ce374f00-cb9c-11eb-8c17-d79703755e8a.png)


it will execute /xx/xx--require

**Comment by muyichuanqi** [comment]
我也遇到相同问题
