### ISSUE TITLE
pkg targets parsed not correct.

### ISSUE THREAD

**Issue by liudonghua123** [vercel/pkg#1127]
I have a simple node cli app which I want to build some executable using `pkg -t node14-win-x86,node14-linux-x64,node14-macos-x64 --out-path build .`. However I got the following errors (https://github.com/liudonghua123/ldap-simple-tool/runs/2321109091?check_suite_focus=true).
```shell
$ pkg -t node14-win-x86,node14-linux-x64,node14-macos-x64 --out-path build .
> pkg@4.5.1
> Fetching base Node.js binaries to PKG_CACHE_PATH


> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.4.0-linux-x86
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-x86"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-x86"}
> Building base binary from source:
  built-v14.4.0-linux-x86
> Error! Not able to build for 'x86' here, only for 'x64'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 2.
```

I have also tried `pkg -t node14-win-x86,node14-linux,node14-macos --out-path build .` (https://github.com/liudonghua123/ldap-simple-tool/runs/2321194176?check_suite_focus=true), but the same errors shown.

If I use `pkg -t node14-win,node14-linux,node14-macos --out-path build .`, then it worked (https://github.com/liudonghua123/ldap-simple-tool/runs/2321206570?check_suite_focus=true).

I just want to build win-x86, linux-x64, macos-x64 binaries.

**Comment by robertsLando** [comment]
Available binaries for 2.6 are here: https://github.com/vercel/pkg-fetch/releases/tag/v2.6.

Choose one from there

**Comment by liudonghua123** [comment]
@robertsLando I have checked https://github.com/vercel/pkg-fetch/releases/tag/v2.6. The problem is about parsing `node14-win-x86,node14-linux-x64,node14-macos-x64`, one of the parsed result is `node-v14.4.0-linux-x86`, the correct should be `node-v14.4.0-linux-x64`.

**Comment by robertsLando** [comment]
Ok it may be related to some wrong target parsing. I think it will be fixed in 5.0.0 version. BTW `x86` suppoort will be dropped in next versiono

**Comment by liudonghua123** [comment]
I tested `pkg --debug -t node14-win-x86,node14-linux-x64,node14-macos-x64 --out-path build .` and `pkg --debug -t node14-win-x64,node14-linux-x64,node14-macos-x64 --out-path build .`, both of them worked on windows. But on Linux, the former failed with the following errors, the latter worked. It's really strange!
```shell
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.4.0-linux-x86
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-x86"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-x86"}
> Building base binary from source:
  built-v14.4.0-linux-x86
> Error! Not able to build for 'x86' here, only for 'x64'
```

**Comment by liudonghua123** [comment]
Finally, I found the problem is around `f.binaryPath = await needViaCache(f)` in https://github.com/vercel/pkg/blob/c332fbb468c3918b13e742edd256776786081072/lib/index.js#L422-L431

The parsed `node14-win-x86` target is 
```json
  {
    "nodeRange": "node14",
    "platform": "win",
    "arch": "x86",
    "output": "/home/runner/work/ldap-simple-tool/ldap-simple-tool/build/ldap-simple-tool-win-x86.exe",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node14",
      "platform": "linux",
      "arch": "x86"
    }
  }
```

And when it try to execute `f.binaryPath = await needViaCache(f)`, it will try to download/cache `node-v14.4.0-linux-x86` which is not available.

It seemed related to the bytecode compiling restrictions.

**Comment by liudonghua123** [comment]
I changed the ci OS from Linux to Windows, now it worked.

See https://github.com/liudonghua123/ldap-simple-tool/commit/0dce290f08bd57719bfe58696c691f530af0ba2d.

**Comment by robertsLando** [comment]
Can we close the issue so?

**Comment by liudonghua123** [comment]
@robertsLando Thanks 😄
