### ISSUE TITLE
How could I minify the size of binary file

### ISSUE THREAD

**Issue by wrjcs** [vercel/pkg#1129]
Hello,
I have the project like this
![image](https://user-images.githubusercontent.com/7202194/114522385-a468b700-9c43-11eb-958e-edf017892580.png)
and this is the config of package.json
"pkg": {
    "scripts": [
      "models/*.js",
      "routers/*.js",
      "routers/controllers/*.js",
      "routers/plugins/*.js"
    ],
    "targets": [
      "linux-x64"
    ],
    "assets": "report/*"
  },
But when I run pkg package.json
I got the binary file is so big 150M.

if I run just like pkg server.js -t linux-x64, I got the file is just 51M.

What's the reason?

Thanks.

**Comment by wrjcs** [comment]
even if I remove all in the parameters in scripts, I got the same size.

**Comment by wrjcs** [comment]
by the way, I didn't compile the node_modules into binary file.

**Comment by robertsLando** [comment]
Most of binary size is nodejs size

**Comment by wrjcs** [comment]
@robertsLando ,I test with the commande just like
pkg server.js -t linux-x64
and I got the size 51M. 
So I think that the nodejs is 51M.
But the rest, where is it come from?

**Comment by erossignon** [comment]
> What's the reason? 

pkg also incorporates the packages referenced by the script files that you pass to pkg ( recursively), you end up adding a lot of stuff coming from the ./node_modules/ folder.

You can run pkg with `--debug` options to see the files that are included on the console.

pr#1115  will introduce a --compress options that will allow you to reduce the size of the payload.

**Comment by erossignon** [comment]
--compress option is now in place in version 5 3
