### ISSUE TITLE
Error! Not more than one entry file/directory is expected

### ISSUE THREAD

**Issue by realrecordzLab** [vercel/pkg#1131]
I have a simple cli script that will spawn a child process that run a bot. I'm trying to package it using this command 

```js
host:~ dev$ pkg /Users/dev/Desktop/myscript/ --targets node14-macos-x64 node14-linux-x64 node14-win-x64
```
Unfortuately I will always get this error 
```js
> Error! Not more than one entry file/directory is expected
```

My script entry point is the `index.js` file, and it's declared inside the `package.json` bin field 

```json
{
  "name": "myscript",
  "version": "1.3.0",
  "bin": "index.js",
  "dependencies": {
    "chalk": "^4.1.0",
    "commander": "^7.1.0",
    "dotenv": "^8.2.0",
    "forever-monitor": "^3.0.3",
    "node-notifier": "^9.0.0"
  }
}
```

What's wrong with the command and how I can fix it?

**Comment by robertsLando** [comment]
`host:~ dev$ pkg /Users/dev/Desktop/myscript/ --targets node14-macos-x64,node14-linux-x64 node14-win-x64
`

**Comment by realrecordzLab** [comment]
> `pkg -t node14-macos-x64,node14-linux-x64,node14-win-x64 /Users/dev/Desktop/myscript/`

Thank you for the reply. I will try as you've suggested
