### ISSUE TITLE
--no-bytecode is currently broken

### ISSUE THREAD

**Issue by Hypfer** [vercel/pkg#1139]
At some point, `--no-bytecode` broke.
Unfortunately, I cannot pinpoint exactly when that happend, however what I can say is that it did work at some point, since I've been using it for the last three(?) years

A very basic example to reproduce this is to use the hello world code of expressjs

<details>
<summary>package.json</summary>

```json
{
  "name": "pkg_bytecode_broken_test",
  "version": "1.0.0",
  "main": "app.js",
  "bin": "app.js",
  "dependencies": {
    "express": "4.17.1",
    "pkg": "git+https://github.com/vercel/pkg.git#4.5.1"
  }
}
```

</details>

<details>
<summary>app.js</summary>

```js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
    res.send('Hello World!')
})

app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
})

```

</details>

As you can see, it doesn't work

```
PS D:\WebstormProjects\pkg_bytecode_broken_test> pkg --target win --no-bytecode .
> pkg@4.5.1
> Error! --no-bytecode and no source breaks final executable
  D:\WebstormProjects\pkg_bytecode_broken_test\node_modules\uid2\index.js
  Please run with "-d" and without "--no-bytecode" first, and make
  sure that debug log does not contain "was included as bytecode".
```

Interestingly, I can get it to build successfully by editing this code so that it sets `record[STORE_CONTENT]` to true if the record does have a body instead of throwing. That is of course a hack and may cause problems later on, however the resulting binary does seem to work just fine at first glance.
https://github.com/vercel/pkg/blob/63f4ce03f71f926521eb8f94dd49b24fb58190ed/lib/packer.ts#L86-L97

iirc I had a similar issue a while ago and it was magically fixed by installing the dependencies via yarn instead of npm. Unfortunately, this doesn't seem to help now though.

Anways, I'm fairly certain that it's a bug in the walker. Symlinks? Issues with case-sensitive stuff? Something like that maybe

**Comment by Hypfer** [comment]
Honestly, I don't really see the point of that `throw` at all, because it doesn't seem to matter if its `STORE_CONTENT` or `STORE_BLOB`, because they're handled exactly the same

https://github.com/vercel/pkg/blob/8756fc1b95360d7668895e68e3d50268e2dcf375/lib/packer.ts#L110-L120

Why is that even there in the first place? Shouldn't it actually check if it's native code or JS when passing `--no-bytecode`?

**Comment by CMCDragonkai** [comment]
This started to work once I added `--public` and not just `--public-packages` but I don't understand why this is the case.

**Comment by thecowmilk** [comment]
I have also this error showing, what could be the fix of this?

**Comment by nbriz** [comment]
i'm also running into this same issue
- pkg 5.6.0
- node v16.14.2
- Ubuntu 20.04.4 LTS 

testing on a super simple script
```js
// main.js
console.log('hello world')
```
running
```
pkg --no-bytecode main.js
```
getting
```
> Error! --no-bytecode and no source breaks final executable
  /path/to/folder/main.js
  Please run with "-d" and without "--no-bytecode" first, and make
  sure that debug log does not contain "was included as bytecode".

```

**Comment by iba-jsykes** [comment]
Same here with 5.8.  --public and --public-packages didn't have any effect.
