### ISSUE TITLE
Detecting packaged app __dirname at runtime (macOS)

### ISSUE THREAD

**Issue by TuomoKu** [vercel/pkg#1147]
Hey, I have read all the docs carefully and all the issues, but haven't been able to figure this out...

I am developing a cross-platform NodeJS server/app. At start-up, the app should generate a default `config.json` to the application directory. I'm detecting the current, start-up folder of the app with:

```
var startUpPath = process.cwd();
```
and this works on Windows, and Linux, but on macOS this fails and the file is generated to the user's home directory instead.

Further notes on macOS:
* this **works** when running the source code with `node myApp.js`
* this **works** when running the binary from command line with `./myApp`
* this **fails** when myApp is started by double-clicking in the Finder

Using `__dirname` returns `/snapshot/`which doesn't help me.

Any hints on how to get the real filesystem current directory at runtime (on macOS)?

**Comment by robertsLando** [comment]
I usually use this function:

```js
const appRoot = require('app-root-path')

/**
 *  Get the base root path to application directory. When we are in a `pkg` environment
 *  the path of the snapshot is not writable
 *
 * @param {boolean} write
 * @returns {string}
 */
function getPath (write) {
  if (write && process.pkg) return process.cwd()
  else return appRoot.toString()
}
```

**Comment by TuomoKu** [comment]
I finally managed to do it - with quite a similar function:
```js
if ( process.pkg ) {
    startUpPath = path.resolve(process.execPath + '/..');
} else {
    startUpPath = process.cwd();
}
```
All good here now, thanks  👍

**Comment by robertsLando** [comment]
I suggest to use that function for all the functions that need to access snapshot or disk file system so if something will change in future everything is centralized and youy can easy fix it there :)
