### ISSUE TITLE
Node 14.4 not found with PKG 5.0.0

### ISSUE THREAD

**Issue by nrfribeiro** [vercel/pkg#1150]
Hi,
with PKG 5.0.0 I am having this error.

#25 2.575 > pkg@5.0.0
#25 2.664 > Error! No available node version satisfies 'node14.4'

**Comment by b00tsy** [comment]
I believe the `nodeRange` parameter does only support major versioning as in `node14` or `node12` and will pick the node version based on version shipped with a specific pkg release. Meaning if you want node 14.4 you will have to use pkg@4.5.1

**Comment by robertsLando** [comment]
I suggest to don't use specific nodejs versions as they change on every pkg-fetch bump. Use node14 instead

**Comment by nrfribeiro** [comment]
Thanks. 
How do I know which node version comes with each PKG version?

**Comment by robertsLando** [comment]
Check pkg-fetch release assets page for available versions
