### ISSUE TITLE
Debian Packaging of the executable not working

### ISSUE THREAD

**Issue by jatinderkumargupta** [vercel/pkg#1154]
I am using pkg to create an executable for ubuntu, from a node.js project. It works fine when I used the generated executable directly.
I am packaging it with dpkg-buildpackage to get Debian installable package.

Now the problem is:
1. When the packager installs the executable, it is not of the original size. Which the dpkg-buildpackage is doing for other executables as well built in c++.
2. But the executable build in c++ is working fine after it gets installed, and the file built with pkg does not work. I get the following message when I try to execute it:
"Pkg: Error reading from file."

I am using following command to build the executable from node.js
pkg index.js --targets node10-linux-x64

And following command to build debian package:
dpkg-buildpackage -rfakeroot -b -uc -us

Does it work with debian packaging?
Please help me to resolve this issue.

Thanks

**Comment by robertsLando** [comment]
I think @jesec can help you with that

**Comment by jesec** [comment]
The final executable can not be stripped, as your Node program is considered the "extra" data by `strip`.

`DEB_BUILD_OPTIONS += nostrip` or set "override_dh_strip" to no-op.

**Comment by jatinderkumargupta** [comment]
ok, let me try that
Thanks

**Comment by jatinderkumargupta** [comment]
It worked.
Thanks a lot for the quick solution.
