### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by prathviraj080** [vercel/pkg#1160]
We use pkg to bundle nodejs server code for linux environment. When we execute the bundled file, the references made to `node_module` paths errors out. 

For example, we have a puppeteer server where we inject javascript resources from `node_module` to puppeteer headless browser. Something like below.

`${path.dirname(require.main.filename)}/node_modules/highcharts/highstock.js`

When we run the executable, we encounter error like this 

```"error_type":"Error","message":"ENOENT: no such file or directory, open '/snapshot/project-x/node_modules/highcharts/highstock.js'```

This server works fine when we run it locally without bundling with pkg.

I used --debug while bundling the project. I can see that the following log 
```
[debug] The file was included as DISCLOSED code (with sources)
  /Users/user.x/project-x/node_modules/highcharts/highstock.js
```

Any helps or hints to debug this would be highly appreciated.

**Comment by erossignon** [comment]
There is no way that pkg can figure out you want to include highcharts/highstock.js from puppeteer.

You need to explicitly add the `./node_modules/highcharts/**.js` files as an asset as a workaround.
