### ISSUE TITLE
`fs.promises` provided by Pkg does not implement the same API as defined in Node.js

### ISSUE THREAD

**Issue by janka102** [vercel/pkg#1162]
Node.js has had `fs.promises` since [v10](https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_promises_api). The definition seems to remain the same between versions all the way up to [v16](https://nodejs.org/docs/latest-v16.x/api/fs.html#fs_promises_api). It says that there is a FileHandle class and that `fsPromises.open()` returns an instance of that class. However, in [pkg's bootstrap.js](https://github.com/vercel/pkg/blob/ea7d72bc2052e717bd89ab1714d5894dd5e9bfa7/prelude/bootstrap.js#L1342) the `fs.promises.open` function is just a promisified version of the normal `fs.open`, which uses file descriptor numbers instead of the FileHandler class.

This makes it difficult to write code that uses `fs.promises` and have it run with node directly and with pkg. Also, `fs.promises` is essentially unusable with typescript now since it can't tell there is a different API. I searched the readme and other issues but have not found this called out anywhere.

It would be nice if this was at least called out in the readme. It took me some time to finally track down why my code wasn't working when `pkg`ed and having it called out in the readme might save others the trouble. Ideally though, I imagine it would be good to have a more compatible API for `fs.promises`.

I can start working on implementing a compatible API if there are no objections from any of the maintainers.

**Comment by robertsLando** [comment]
@janka102 I think that [this](https://github.com/vercel/pkg/pull/1158/files#diff-0c3f42fd6825d8d5b4d0422402a89ff11dc1d1cfb52ee5901f4774e503783c27R1419-R1428) PR may fix your problems. @erossignon right?

**Comment by erossignon** [comment]
Correct !

**Comment by realrecordzLab** [comment]
I'm using `fs.promises` module in my script, is the issue solved or I need to refactor the code?

**Comment by erossignon** [comment]
>I can start working on implementing a compatible API if there are no objections from any of the maintainers. 
Thank you @janka102,  one way to help would be to test the #1158 TR and check that it  is actually fixing the problem you described..


@realrecordzLab, please wait for the version that will incorporate #1158 if you can.

**Comment by janka102** [comment]
Awesome, I'll check out that PR

**Comment by janka102** [comment]
@erossignon Tested the PR and it works well for my use case, super cool! However I do see that only some of the promise functions are overwritten and I'm not sure if that is intended or not

**Comment by robertsLando** [comment]
maybe a forin loop could be useful?

**Comment by realrecordzLab** [comment]
> > I can start working on implementing a compatible API if there are no objections from any of the maintainers.
> 
> Thank you @janka102, one way to help would be to test the #1158 TR and check that it is actually fixing the problem you described..
> 
> @realrecordzLab, please wait for the version that will incorporate #1158 if you can.

No problem, I'm working on the code so I can wait. I'm using the `fs.writeFile` and the `fs.mkdtemp` functions not sure if these are affected from the bug.

**Comment by squidfunk** [comment]
Any update on when this will be released?

**Comment by robertsLando** [comment]
Soon
