### ISSUE TITLE
How to use a config.ini file outside of compiled file

### ISSUE THREAD

**Issue by PNourian** [vercel/pkg#1165]
Hi I have a question that how can I call and check a config file outside of compiled exe that might be changed by client everytime that app starts so I searched I couldn't find anything

Your help would be so appreciated

**Comment by robertsLando** [comment]
Where is this file located?

**Comment by PNourian** [comment]
in the same folder of the exe file

**Comment by robertsLando** [comment]
Use `process.cwd()` to refer the folder of the executable

**Comment by PNourian** [comment]
can you show me an example because it's my first time using this command

**Comment by PNourian** [comment]
no need to give an example I found some tutorial on internet
