### ISSUE TITLE
How to ignore some module?

### ISSUE THREAD

**Issue by hacke2** [vercel/pkg#1166]
My project is both frontend and backend。it will throw error when use pkg, like #590  and #1134.

![image](https://user-images.githubusercontent.com/6399899/117260382-9ba18480-ae81-11eb-861a-64411469c8a3.png)

I think there might be a problem with the following code:
![image](https://user-images.githubusercontent.com/6399899/117259738-ebcc1700-ae80-11eb-82e8-a549d79e5df4.png)

these third party module both frontend and backend, I can't simply remove these dependencies.

I tried assets too, but it didn't work as I wanted.

```js
"assets": [
    "./app/web/**/*",
    "./app/view/**/*",
    "./node_modules/xx-components/**/*"
  ],
```

 What is the right way to use this？can I skip some module ? or filter *.less ? or support options like webpack resolve ？

**Comment by jesec** [comment]
Yes you can remove them temporarily. Just restore them later. 

I recommended you to run `webpack`, `babel` and other things first, and then run `pkg` on the processed/bundled files.

**Comment by hacke2** [comment]
The back-end application is not suitable for webpack 😹
