### ISSUE TITLE
Getting info about a generated pkg

### ISSUE THREAD

**Issue by PaddyOl** [vercel/pkg#1168]
Any possibility to get the pkg 'unpackaged' ?

The use case:
- I have a component being automatically built by jenkins. One of the dependency has a version like: "^1.2.0" , so i don't know precisely which version is embedded in the pkg node_modules.

So unpacking, or querying the pkg to get info about embedded module would be greatly appreciated/

**Comment by Hypfer** [comment]
If you only need this info once, there are various ways to pull them out of the binary as long as it's actually in there.

Throwing it into a hex editor and searching for the string will work. `strings` from the GNU binutils is also an option.

**Comment by jesec** [comment]
Run `npm la` as a part of your workflow, if you want to be certain about the dependency tree used at a given time.
