### ISSUE TITLE
Upload files to the server

### ISSUE THREAD

**Issue by aryeh-at-lls** [vercel/pkg#1170]
Hello,
I'm using pkg to pack my server into compact executable file.
All went well - problem is - once the server is on and I upload new files to the server's filesystem, the files are not included in the snapshot file system, but as siblings to the exe file.
Because of that - reading them is not possible.
How can I upload files and read them from the client?

For more clarification - my file system looks like this:

![image](https://user-images.githubusercontent.com/59227766/117473678-e2b37680-af62-11eb-8b8e-b47dc9fdba5f.png)

Thanks,

**Comment by jesec** [comment]
You have to make the files available before you run `pkg` if you want them to be bundled into executable. 

Otherwise, read files as if they came from external sources instead.

**Comment by neody** [comment]
you can use code
`if(BASEURL == ""){
//  console.log(__dirname);
//  console.log(process.cwd());
  app.use(express.static(path.join(__dirname, "public")));  
  app.use(express.static(path.join(process.cwd(), "saved")));
}
else{
  app.use(BASEURL, express.static(__dirname + '/public'));
  app.use(BASEURL, express.static(process.cwd() + '/saved'));
}`

sorry for my bad english.
answer from [this](https://github.com/vercel/pkg/issues/1187)
