### ISSUE TITLE
auto-update for my PKG app

### ISSUE THREAD

**Issue by Zabrane** [vercel/pkg#1172]
Hi guys

I've successfully created an exectutable app, thanks to PKG.

What i'd like to do now is to let users that a newer version is available whenever they run my app.
Could PKG helps in this regard? Any pointer please?

Help appreciated.

**Comment by robertsLando** [comment]
PKG cannot help with this anyway, you should create your auto update server where you store the pkg executable and provides apis that your app can use to check for new updates and eventually download and install them. 

For example: https://github.com/Automattic/auto-update-server

About how to update an application you could simply overrde the old executable with the new one
