### ISSUE TITLE
How to change the output name file for the 3 default targets?

### ISSUE THREAD

**Issue by SrBrahma** [vercel/pkg#1174]
`pkg ./lib/index.js` will generate **index-linux**, **index-macos** and **index-win.exe**. How to have as output, **myProgram-linux**, etc? I tried `-o` flag, but it will only generate the linux build.

**Comment by davidwlhlm** [comment]
I don't know if thats possible with CLI arguments. But if you use a `package.json` with a `name` and the `bin` attribute pointing to your entrypoint, you should be able to generate a `myProgram-<target>` executable for each target when executing `pkg .`

For example:

```
{
    "name": "myProgram",
    "bin": "lib/index.js",
    "pkg": {
            "outputPath": "dist"
    }
}
```

**Comment by SrBrahma** [comment]
Works!
