### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by junsik** [vercel/pkg#1175]
Today, I noticed "pkg -t node14-win-x86 ." does not work.  Instead of fetching a binary, pkg tried to compile nodejs.
I encountered some compile errors.

> pkg@5.1.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.16.1-win-x86            [                    ] 0%
> Error! 404
> Not found in remote cache:
  {"tag":"v3.0","name":"node-v14.16.1-win-x86"}
....

Through pkg-fetch sources,  I found out x86 prebuilt binary doesn't exist at https://github.com/zeit/pkg-fetch/releases.

**Comment by jesec** [comment]
x86 is not supported. See vercel/pkg-fetch#173.
