### ISSUE TITLE
How to don't autoclose Windows executable?

### ISSUE THREAD

**Issue by SrBrahma** [vercel/pkg#1178]
I ain't too familiar with Windows development. When running my program via the .exe, the program will autoclose when it finishes. I don't want this, as there is some text on the program ending that is good for the user to read.

For now, to finish my quick contract, I have a "Press any key to exit.". But, this wouldn't be too good for linux users, as we usually run those CLI programs via terminal and we don't like having to ack the program ending. (I don't  care about linux now, as the client is a Windows-only user, but I want this info for future projects)

I don't know the behaviour on MacOS.

Is there anyway to keep the program alive on Windows upon its finish?

**Comment by jesec** [comment]
```
console.log('Press any key to exit');
process.stdin.setRawMode(true);
process.stdin.on('data', () => process.exit(0));
```

or (Windows only)

```
require("child_process").execSync("pause", { stdio: "inherit" });
```
