### ISSUE TITLE
pkg + pupeteer stealth plugin support

### ISSUE THREAD

**Issue by 4passenger** [vercel/pkg#1179]
recently tried to run pkg with puppeteer stealth plugin however its just giving me the error with "A plugin listed 'puppeteer-extra-plugin-stealth/evasions/chrome.runtime' as dependency,
which is currently missing. Please install it:"

I also tried to add assets to package.json but it did not work.

**Comment by DaMavius** [comment]
you can include it by using the assets config for pkg in package.json file

 "pkg": {
    "assets": `${replace_with_your_desired_package_path}`,
  }
