### ISSUE TITLE
Question: Prompts

### ISSUE THREAD

**Issue by WickedWizard3588** [vercel/pkg#1185]
Hey,

Can `pkg` ask for prompts/questions when installing? Like, where is the final directory, and so on?

Thanks

**Comment by robertsLando** [comment]
Could be a possible feature

**Comment by WickedWizard3588** [comment]
So, it is not an available feature, as of today?

**Comment by robertsLando** [comment]
Nope

**Comment by WickedWizard3588** [comment]
Ok, thank you
