### ISSUE TITLE
Accessing downloaded files in EJS web page

### ISSUE THREAD

**Issue by petersem** [vercel/pkg#1187]
Hi, my app downloads images that are later used in a EJS web page. The images download ok, and are visible in a directory next to the windows exe however, the app itself can't seem to reference the path to these files. All other assets (static images, css, js, etc) that are in my public folder are accessible, just not the new ones downloaded.  This works natively, just not when it is bundled. 
[Posterr](https://github.com/petersem/posterr)

Sorry if this is a silly question. I'm new to node, and this has me stumped.

**Comment by robertsLando** [comment]
Could you show the code you use to refer the path to public folder images and the error shown?

**Comment by robertsLando** [comment]
@erossignon @jesec Could this be caused to recent changes made in code?

**Comment by jesec** [comment]
You have to treat those newly downloaded files as “external” files, so you can not refer to them via relative path.

Instead of `'./path/to/a/file'`, explicitly use `path.join(process.cwd(), 'path/to/a/file')`.

**Comment by petersem** [comment]
thanks. All sorted now. By adding the following, its now functional for referencing downloaded files from the web page. 

`//sets public folder for assets
if(BASEURL == ""){
//  console.log(__dirname);
//  console.log(process.cwd());
  app.use(express.static(path.join(__dirname, "public")));  
  app.use(express.static(path.join(process.cwd(), "saved")));
}
else{
  app.use(BASEURL, express.static(__dirname + '/public'));
  app.use(BASEURL, express.static(process.cwd() + '/saved'));
}`

**Comment by robertsLando** [comment]
@petersem you could also add a check `if(process.pkg)` to do some operations just when the app is running in a packaged environment

**Comment by petersem** [comment]
@robertsLando Nice idea. Thanks for the tip! :)
