### ISSUE TITLE
Error thrown with pkg@5.2.1 Error: EISDIR

### ISSUE THREAD

**Issue by cowlicks** [vercel/pkg#1191]
This error started being thrown this morning. And only with 5.2.1. It is not thrown on 5.2.0.
```
pkg/prelude/bootstrap.js:1614
      throw error;
      ^

Error: EISDIR: illegal operation on a directory, read
    at error_EISDIR (pkg/prelude/bootstrap.js:553:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:894:33)
    at Object.readFileSync (pkg/prelude/bootstrap.js:938:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1095:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module.require (pkg/prelude/bootstrap.js:1593:31)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/snapshot/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15) {
  errno: -21,
  code: 'EISDIR',
  path: '/snapshot/app/node_modules/sqlite3/lib///',
  pkg: true
}
there was a problem running the executable
```

**Comment by tinoks** [comment]
Same error when updating to 5.2.0 from 5.1.0.


```
pkg/prelude/bootstrap.js:1614
      ^

Error: EISDIR: illegal operation on a directory, read
    at error_EISDIR (pkg/prelude/bootstrap.js:553:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:894:33)
    at Object.readFileSync (pkg/prelude/bootstrap.js:938:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1095:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module.require (pkg/prelude/bootstrap.js:1593:31)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (D:\snapshot\ogcapi-fast2\node_modules\bindings\bindings.js:112:48) {
  code: 'EISDIR',
  path: 'D:\\snapshot\\ogcapi-fast2\\node_modules\\better-sqlite3\\\\\\',
  pkg: true
```


I am using node version v14.15.0, pkg target "node14-win-x64".

Can be reproduced with a index.js file containing:
`
const db = require('better-sqlite3')("test.sqlite");
`

**Comment by jesec** [comment]
Maybe related: #1192 

See my comment there: https://github.com/vercel/pkg/issues/1192#issuecomment-847849055.

**Comment by xyklex** [comment]
@jesec it is happening to me too with Node 14.17.0 in Linux, I'm running the exec and placing the `bindings.node` in the same directory.

**Comment by xyklex** [comment]
Full output log
<details>
  <summary>Click to expand!</summary>
{
  "error": {
    "errno": -21,
    "code": "EISDIR",
    "path": "/snapshot/tmp/node_modules/@serialport/bindings//",
    "pkg": true
  },
  "level": "error",
  "message": "uncaughtException: EISDIR: illegal operation on a directory, read\nError: EISDIR: illegal operation on a directory, read\n    at error_EISDIR (pkg/prelude/bootstrap.js:553:17)\n    at readFileFromSnapshot (pkg/prelude/bootstrap.js:894:33)\n    at Object.readFileSync (pkg/prelude/bootstrap.js:938:18)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1095:18)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Module.require (internal/modules/cjs/loader.js:957:19)\n    at Module.require (pkg/prelude/bootstrap.js:1593:31)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at bindings (/snapshot/tmp/node_modules/bindings/bindings.js:112:48)\n    at Object.<anonymous> (/snapshot/tmp/node_modules/@serialport/bindings/lib/linux.js:2:36)\n    at Module._compile (pkg/prelude/bootstrap.js:1686:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Module.require (internal/modules/cjs/loader.js:957:19)\n    at Module.require (pkg/prelude/bootstrap.js:1593:31)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at Object.<anonymous> (/snapshot/tmp/node_modules/@serialport/bindings/lib/index.js:14:22)\n    at Module._compile (pkg/prelude/bootstrap.js:1686:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n    at Module.load (internal/modules/cjs/loader.js:933:32)",
  "stack": "Error: EISDIR: illegal operation on a directory, read\n    at error_EISDIR (pkg/prelude/bootstrap.js:553:17)\n    at readFileFromSnapshot (pkg/prelude/bootstrap.js:894:33)\n    at Object.readFileSync (pkg/prelude/bootstrap.js:938:18)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1095:18)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Module.require (internal/modules/cjs/loader.js:957:19)\n    at Module.require (pkg/prelude/bootstrap.js:1593:31)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at bindings (/snapshot/tmp/node_modules/bindings/bindings.js:112:48)\n    at Object.<anonymous> (/snapshot/tmp/node_modules/@serialport/bindings/lib/linux.js:2:36)\n    at Module._compile (pkg/prelude/bootstrap.js:1686:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Module.require (internal/modules/cjs/loader.js:957:19)\n    at Module.require (pkg/prelude/bootstrap.js:1593:31)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at Object.<anonymous> (/snapshot/tmp/node_modules/@serialport/bindings/lib/index.js:14:22)\n    at Module._compile (pkg/prelude/bootstrap.js:1686:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n    at Module.load (internal/modules/cjs/loader.js:933:32)",
  "exception": true,
  "date": "Fri May 28 2021 15:55:41 GMT-0700 (Pacific Daylight Time)",
  "process": {
    "pid": 26706,
    "uid": 0,
    "gid": 0,
    "cwd": "/home/putty/apps",
    "execPath": "/home/putty/apps/api_app",
    "version": "v14.17.0",
    "argv": [
      "/home/putty/apps/api_app",
      "/snapshot/tmp/bin/www"
    ],
    "memoryUsage": {
      "rss": 42496000,
      "heapTotal": 18137088,
      "heapUsed": 13764700,
      "external": 1834235,
      "arrayBuffers": 254764
    }
  },
  "os": {
    "loadavg": [
      0.41,
      0.37,
      0.33
    ],
    "uptime": 191092.03
  },
  "trace": [
    {
      "column": 17,
      "file": "pkg/prelude/bootstrap.js",
      "function": "error_EISDIR",
      "line": 553,
      "method": null,
      "native": false
    },
    {
      "column": 33,
      "file": "pkg/prelude/bootstrap.js",
      "function": "readFileFromSnapshot",
      "line": 894,
      "method": null,
      "native": false
    },
    {
      "column": 18,
      "file": "pkg/prelude/bootstrap.js",
      "function": "Object.readFileSync",
      "line": 938,
      "method": "readFileSync",
      "native": false
    },
    {
      "column": 18,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._extensions..js",
      "line": 1095,
      "method": ".js",
      "native": false
    },
    {
      "column": 32,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.load",
      "line": 933,
      "method": "load",
      "native": false
    },
    {
      "column": 14,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._load",
      "line": 774,
      "method": "_load",
      "native": false
    },
    {
      "column": 19,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.require",
      "line": 957,
      "method": "require",
      "native": false
    },
    {
      "column": 31,
      "file": "pkg/prelude/bootstrap.js",
      "function": "Module.require",
      "line": 1593,
      "method": "require",
      "native": false
    },
    {
      "column": 18,
      "file": "internal/modules/cjs/helpers.js",
      "function": "require",
      "line": 88,
      "method": null,
      "native": false
    },
    {
      "column": 48,
      "file": "/snapshot/tmp/node_modules/bindings/bindings.js",
      "function": "bindings",
      "line": 112,
      "method": null,
      "native": false
    },
    {
      "column": 36,
      "file": "/snapshot/tmp/node_modules/@serialport/bindings/lib/linux.js",
      "function": null,
      "line": 2,
      "method": null,
      "native": false
    },
    {
      "column": 22,
      "file": "pkg/prelude/bootstrap.js",
      "function": "Module._compile",
      "line": 1686,
      "method": "_compile",
      "native": false
    },
    {
      "column": 10,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._extensions..js",
      "line": 1097,
      "method": ".js",
      "native": false
    },
    {
      "column": 32,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.load",
      "line": 933,
      "method": "load",
      "native": false
    },
    {
      "column": 14,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._load",
      "line": 774,
      "method": "_load",
      "native": false
    },
    {
      "column": 19,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.require",
      "line": 957,
      "method": "require",
      "native": false
    },
    {
      "column": 31,
      "file": "pkg/prelude/bootstrap.js",
      "function": "Module.require",
      "line": 1593,
      "method": "require",
      "native": false
    },
    {
      "column": 18,
      "file": "internal/modules/cjs/helpers.js",
      "function": "require",
      "line": 88,
      "method": null,
      "native": false
    },
    {
      "column": 22,
      "file": "/snapshot/tmp/node_modules/@serialport/bindings/lib/index.js",
      "function": null,
      "line": 14,
      "method": null,
      "native": false
    },
    {
      "column": 22,
      "file": "pkg/prelude/bootstrap.js",
      "function": "Module._compile",
      "line": 1686,
      "method": "_compile",
      "native": false
    },
    {
      "column": 10,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._extensions..js",
      "line": 1097,
      "method": ".js",
      "native": false
    },
    {
      "column": 32,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.load",
      "line": 933,
      "method": "load",
      "native": false
    }
  ],
  "service": "api-app",
  "machine": "violet-grand-limpet",
  "timestamp": "Fri May 28 15:55:41 -0700 2021"
}
</details>

**Comment by xyklex** [comment]
@jesec as my goal was to try `armv7` which last binaries updated were `linuxstatic` I can't confirm this now, but will test soon when I move devices to `arm64`.

**Comment by ngustavo** [comment]
I'm getting this same error, also version 5.2.1. It seems to happen when you are using sqlite3.
