### ISSUE TITLE
Cannot download s390x binary

### ISSUE THREAD

**Issue by ssh24** [vercel/pkg#1195]
Any idea why it cannot download the s390x binary even when s390x is supported in the known archs here:

https://github.com/vercel/pkg-fetch/blob/b30cbad6ea4297dcc28a2024e322971ec7e49c0b/lib/system.ts#L133-L135

On the latest release assets, there is none for s390x arch

**Comment by jesec** [comment]
https://github.com/vercel/pkg-fetch/pull/63#issuecomment-847054023
