### ISSUE TITLE
Cannot specify assets in CLI

### ISSUE THREAD

**Issue by RangerMauve** [vercel/pkg#1196]
This tool is super useful, thank you for the hard work in putting it together!

It seems that the only way to specify assets is in the package.json, however I need to specify different assets for different platforms (as a result of prebuilt binaries).

Would it be possible to add this as an option? If it's already possible, are there any examples I can add to the docs?

Thank you!

**Comment by robertsLando** [comment]
It's not possible to set 'conditional assets' ATM. What I suggest you is to create an sh or nodejs script that handles pkg builds and copies the required assets in a temporary folder based on the arch and add this folder as an asset, once the package process ends

**Comment by RangerMauve** [comment]
Thanks for the heads up. I still think that enabling people to specify assets using a `--asset` flag would be useful, but I've done a workaround in the meantime where I dynamically change the `pkg` field in the package.json to have different sets of assets based on the build. 😁

My build script: https://github.com/RangerMauve/hyper-gateway/blob/cfd79208ceede44c0a5a1a5f4c1427f53f9987dc/build.js

My package.json setup: https://github.com/RangerMauve/hyper-gateway/blob/cfd79208ceede44c0a5a1a5f4c1427f53f9987dc/package.json#L17

**Comment by Nisthar** [comment]
> This is still something that would be nice to have.

I been trying to pass `--assets ./../assets/**/*` option through my cli. no wonder why it didn't worked.

**Comment by RangerMauve** [comment]
This is still relevant and would help ease a bunch of pain. 😅

**Comment by robertsLando** [comment]
@RangerMauve PR ?

**Comment by RangerMauve** [comment]
This is still an issue. I've been working around it by modifying the package.json as part of my build script. Sadly haven't had time to do a proper fix.

**Comment by RangerMauve** [comment]
Still something that would be nice to have. 😁
