### ISSUE TITLE
PKG module not found using worker threads

### ISSUE THREAD

**Issue by JacobLoeve** [vercel/pkg#1198]
Hello all,

I have used pkg in the past on smaller projects which worked out really well for us. Right now i want to compile a big nodejs project (v14) into a single exe. In the project we are using worker threads as https://nodejs.org/api/worker_threads.html.

In the code we have the following lines:
worker = new Worker('./some/path/to/file.js');

When i compile the project with pkg i get the below error when i run the created exe. I tried putting the files in the assests and/or scripts in package.json but that does not work like it does for other scripts and assets we use.
Error: Cannot find module 'C:\some\path\to\file.js' with code: 'MODULE_NOT_FOUND'. 

Does anyone know how to compile nodejs to exe (w/ pkg) while using worker threads? Or is this simply not possible (yet)?

Thanks a lot for your help!

**Comment by hackermondev** [comment]
@JacobLoeve How did you fix this?
