### ISSUE TITLE
Cross compilation support

### ISSUE THREAD

**Issue by scriptnull** [vercel/pkg#1218]
Hi, I am looking to understand the cross-compilation support in pkg.

Here are my questions:

1. If I try to build for `linux-arm64` on my ubuntu machine (which is `linux-x64`), I am facing errors. Is it because pkg does not have cross-compile support for building `linux-arm64` on a host machine running `linux-x64`
2. Is cross-compiling to `macos-arm64` possible while trying to run pkg on x64 linux machine? or would we need a Apple M1 mac to compile for this target?

**Comment by jesec** [comment]
Read README again.

**Comment by scriptnull** [comment]
Thanks @jesec - reading the README carefully solved my questions.
