### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by robertsLando** [vercel/pkg#1219]
Got this error when try to execute the builded executable with pkg@5.2.1 (latest) 

`./zwavejs2mqtt`

Output:

```
pkg/prelude/bootstrap.js:1614
      throw error;
      ^

Error: Module did not self-register: '/tmp/5f4c060ba9c1f9628cfe4279683ff34d28321ad003e651052fda2cd17d91ce8d/bindings.node'.
    at tryImporting (pkg/prelude/bootstrap.js:1969:37)
    at tryImporting (pkg/prelude/bootstrap.js:2021:16)
    at tryImporting (pkg/prelude/bootstrap.js:2021:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2044:7)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1168:18)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at Module.require (pkg/prelude/bootstrap.js:1593:31)
    at require (node:internal/modules/cjs/helpers:93:18) {
  code: 'ERR_DLOPEN_FAILED'
}

```

package.json:

```js
"pkg": {
    "scripts": [
      "server/**/*"
    ],
    "assets": [
      "views/**/*",
      "static/**/*",
      "dist/**/*",
      "/node_modules/@serialport/bindings/**"
    ]
  },
```

Command: `npx pkg package.json -t node16-linux-x64 --out-path ./pkg`

Project: https://github.com/zwave-js/zwavejs2mqtt

I also tried without the `"/node_modules/@serialport/bindings/**"` in `assets`

**Comment by robertsLando** [comment]
@erossignon Any clue?

**Comment by erossignon** [comment]
That is what I got when I compile it with main branch version and `-t host` or  `-t node16`

```
~/zwavejs2mqtt$ node ../pkg/lib-es5/bin.js package.json --out-path ./pkg -t host
> pkg@5.2.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v16.2.0-linux-x64           [====================] 100%

~/zwavejs2mqtt$ ./pkg/zwavejs2mqtt
2021-06-15 16:32:43.289 INFO APP: Version: 5.0.2.a6ab926
2021-06-15 16:32:43.289 INFO APP: Application path:/home/etienne/zwavejs2mqtt

 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|

2021-06-15 16:32:43.295 WARN STORE: settings.json not found
2021-06-15 16:32:43.298 WARN STORE: scenes.json not found
2021-06-15 16:32:43.298 WARN STORE: nodes.json not found
2021-06-15 16:32:43.299 WARN STORE: users.json not found
2021-06-15 16:32:43.302 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
2021-06-15 16:32:43.339 ERROR GATEWAY: Zwave settings are not valid
````

do you have a /tmp folder ?

**Comment by robertsLando** [comment]
> do you have a /tmp folder ?

Yes I have it in my system as all linux based OS, I still don't get what's the problem here

**Comment by robertsLando** [comment]
After running the application I get the folder created on `/tmp`:

```
/zwavejs2mqtt/pkg$ ls /tmp/b41fe5a697721afad70f6c5b960c03fa229955c1b7e3042db38185e5b32ce662/
bindings.node
```

The binding node is there, the problem is even if I remove that folder I get the same error when starting the application

**Comment by robertsLando** [comment]
Wait, LOL. I feel so stupid, my local node version is not 16, the problem is that local version is 12 and target is 16 that's the reason behind that error. Sorry for wasting your time and thanks @erossignon

**Comment by btsimonh** [comment]
Seems maybe that .node module depends on other .dl files which are not available on that system?
You can maybe test this by going to that folder and running 'ldd binding.node'?

(just a very small side note.  I'm following but not using package, but use something very similar.  Beware of /tmp on linux and OSX, as on linux it is emptied (and I'm sure too on OSX).  I moved to using the equivalent of 'Program Data' so that my binary assets (.node, .exe, etc) were not deleted once the application had been running for a few weeks.)

**Comment by robertsLando** [comment]
@btsimonh Nope, as I said the problem was that the `.node` was builded with nodejs 12 and I was packaging the app using nodejs 16 so the versions are not compatible.

BTW now I have another error with express but it will be likely fixed by latest PR merged on master
