### ISSUE TITLE
Update pkg-fetch to 3.2 to support linuxstatic-armv7

### ISSUE THREAD

**Issue by schlomo** [vercel/pkg#1220]
to support armv7 static builds from vercel/pkg-fetch/issues/109

Or, provide instructions for setting pkg-fetch version manually. I tried to use the `PKG_IGNORE_TAG` feature but it didn't work:

```shell
$ PKG_IGNORE_TAG=1 node_modules/.bin/pkg-fetch -n node14 -p linuxstatic -a armv7
  fetched-v14.17.0-linuxstatic-armv7  [====================] 100%

> /work/.pkg-cache/fetched-v14.17.0-linuxstatic-armv7
$ pkg --output dist/updateprice."$(<VERSION)".arm --targets node14-linuxstatic-armv7 --public functions/updateprice.js
> pkg@5.2.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
> Binary hash does NOT match. Re-fetching...
  fetched-v14.17.0-linuxstatic-armv7  [                    ] 0%
> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.1","name":"node-v14.17.0-linuxstatic-armv7"}
```

The problem seems to be that pkg@5.2.1 is hard-coded to use pkg-fetch@3.1.1...

**Comment by schlomo** [comment]
I tried to add this [workaround](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to my `package.json` file:

```json
{
  "resolutions": {
    "pkg/pkg-fetch": "^3.2"
  }
}
```

The effect was indeed that pkg would use pkg-fetch@3.2, but then I ran into another problem:

```shell
$ npx pkg --debug --output dist/updateprice."$(<VERSION)".arm --targets node14-linuxstatic-armv7 --public functions/updateprice.js
> pkg@5.2.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.17.0-macos-armv7        [                    ] 0%
> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.2","name":"node-v14.17.0-macos-armv7"}
> Building base binary from source:
  built-v14.17.0-macos-armv7
> Cloning Node.js repository from GitHub...
Cloning into bare repository 'node/.git'...
```

It seems like the architecture `linuxstatic` is not passed to pkg-fetch as that tries to download a **macos-armv7** binary instead of the expected **linuxstatic-armv7** binary.

As I don't know the internal workings of pkg and pkg-fetch I am a bit at a loss here, any help would be much appreciated.

**Comment by schlomo** [comment]
I have the feeling that the problem is between me working on Mac and trying to build for a Linux NodeJS target.

**Comment by QuickJack** [comment]
> It seems like the architecture `linuxstatic` is not passed to pkg-fetch as that tries to download a **macos-armv7** binary instead of the expected **linuxstatic-armv7** binary.
> 

Yes, that seems to be true. I added the resolutions field to my package.json. Now, the build works as expected. However, I had to specifiy linux instead of linuxstatic:

`pkg -t node14.17.0-linux-armv7 index.js -o xxx`

By the way, you cannot use pkg to build for a different architecture. I am using arm32v7/node:14.

**Comment by Hypfer** [comment]
Why would you open an issue for this?

`pkg` will _of course_ be upgraded to `pkg-fetch` 3.2 at some point. `pkg-fetch` literally only exists for `pkg`.

There is no need for this unless you want to pressure FOSS maintainers to work harder which is an incredibly shitty thing to do.
It's no surprise that this repository was unmaintained for years considering the amount of garbage issues people have to put up with.

There even is a PR which does exactly what you're requesting: https://github.com/vercel/pkg/pull/1215
It's more than a week older than this issue and one of currently 5(!) open PRs.
There is no way to miss that PR. There just isn't.

This FOSS. If you want something done in time you have exactly two options:

- Do it yourself
- Hire someone to do it


Note that 

- pressuring maintainers to spend more of their free time working for your personal commercial benefit

is not part of that list.
