### ISSUE TITLE
Allow entry point in package.json config

### ISSUE THREAD

**Issue by rightaway** [vercel/pkg#1224]
Why do we need to provide "bin" in package.json? If we use command line options to `pkg` you can specify an entry point instead.

To be consistent there should be an "entry" possible to specify under "pkg" so that we can provide the exact same options as we do on the command line but can put it in package.json so we don't need to specify it every time.

**Comment by rightaway** [comment]
Also allow `--public`. I have to put it on the command line but I should be able to add `"public": true` in the package.json to do the same thing.

**Comment by rightaway** [comment]
Also `"compress": "brotli"` and `"output": "filename"` don't do anything in package.json.

Any arguments that are accepted on the command line should be accepted in package.json and vice-versa.

This is confusing otherwise and the options we want it to work with get split between 3 places. `"bin"` in package.json, `"pkg"` in package.json and command line options. We should be able to look just in `"pkg"` and see everything that will be used to process the command, including the entry point and all options.

`"bin"` really shouldn't be required since it is meant for something else https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin. It's for installing something to the PATH, which isn't the intention here. It shouldn't be misused by `pkg`.

**Comment by Christilut** [comment]
Just ran into the same thing... With a `bin` property it will break `npm install` so you really can't re-use `bin` for pkg

**Comment by rightaway** [comment]
keep open
