### ISSUE TITLE
how to write package.json version to executable binary as custom property？

### ISSUE THREAD

**Issue by lling1105** [vercel/pkg#1226]
after the build action,the  exe file display node version as product version , but i wanna dispaly the version whitch from package.json, any config option for pkg to do that? thx

**Comment by ingles98** [comment]
This will probably fall into the same ICON discussion...

**Comment by Hypfer** [comment]
Same as #1238

You'll probably want to try to use https://www.npmjs.com/package/resedit or similar in your build pipeline
