### ISSUE TITLE
node js app to exe error ENOENT

### ISSUE THREAD

**Issue by hasanyel** [vercel/pkg#1233]
Hello to everyone
I convert mediasoup node js app to exe .
When I run the exe the worker gives an error.
i used pkg to make exe.

```
package.json
 "pkg": {
    "assets": [
      "node_modules/",
      "node_modules/**/*",
      "node_modules/mediasoup/**/*"
    ],
    "outputPath": "dist"
  }
```
`command => pkg build/index.js --config package.json --targets node16-linux-x64
`when i run the exe ,
error => spawn /snapshot/MediaServer-Ts/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT

do you have any idea about this issue?

**Comment by hasanyel** [comment]
[debug] The file was included as asset content
/home/hd/Desktop/MediaServer-Ts/node_modules/mediasoup/worker/out/Release/mediasoup-worker
[debug] The file was included as asset content
/home/hd/Desktop/MediaServer-Ts/node_modules/mediasoup/worker/out/Release/mediasoup-worker
[debug] The file was included as asset content

**Comment by hasanyel** [comment]
import { createWorker as createWorker } from "/home/hd/Desktop/MediaServer-Ts/node_modules/mediasoup";
this is how it works

import { createWorker as createWorker } from "mediasoup";
it doesn’t work that way

**Comment by BCsabaEngine** [comment]
> import { createWorker as createWorker } from "/home/hd/Desktop/MediaServer-Ts/node_modules/mediasoup";
> this is how it works
> 
> import { createWorker as createWorker } from "mediasoup";
> it doesn’t work that way

Try use relative path with __dirname and path.join. Pkg will transpile/compile/refactor it to a valid virtual path. You should try some combination and debug with console.log(mediasoupfile).

Always try it on another computer to be sure in environment independency. Hide all nodemodules and any other dump file.
