### ISSUE TITLE
PKG exe w/compression cannot itself create another pkg executable from itself

### ISSUE THREAD

**Issue by ingles98** [vercel/pkg#1236]
This might look strange at first glance, I know, but what I'm saying is that I have this piece of software that I generate an executable with it. This specific software itself also uses PKG to generate an executable.

This has been working quite nicely, but as soon as I get compression on the first executable, the first one gets badly generated.

Using --debug looks like it finishes but the pkg task never really finishes at all.

Any idea os a way to work this out ? I'd like to use compression for this as it tends to get way too large for what it does.

(Tested with both Gzip and Brotli)

**Comment by BCsabaEngine** [comment]
Gzip is a little slow and Brotli is very slow. At the end of compilation. If you use pkg api, you use only one thread and make process slower. Try gzip first and wait 1-5minutes.

**Comment by ingles98** [comment]
> Gzip is a little slow and Brotli is very slow. At the end of compilation. If you use pkg api, you use only one thread and make process slower. Try gzip first and wait 1-5minutes.

As mentioned, I tried using both. Tested for over an hour on both.
