### ISSUE TITLE
Operation not permitted (MacOS 11.4)

### ISSUE THREAD

**Issue by Brwinded** [vercel/pkg#1240]
Build index.js with console.log("Hello world") inside

then open this file> zsh: operation not permitted: ...

I made Terminal file access, and try with sudo

MacOS Big Sur 11.4
Host Node: 16.4
Target Node: 14.0

**Comment by jesec** [comment]
chmod +x

**Comment by Brwinded** [comment]
> chmod +x

the same

**Comment by Mostafa-Davoodi** [comment]
@Brwinded Did you find a solution for this issue?
