### ISSUE TITLE
EPIPE error caused at the fabricate function

### ISSUE THREAD

**Issue by CMCDragonkai** [vercel/pkg#1242]
I tried running `pkg` on TypeScript-Demo-Lib https://github.com/MatrixAI/TypeScript-Demo-Lib

Relevant PR: https://github.com/MatrixAI/TypeScript-Demo-Lib/pull/25

After building the application with `npm run build`, I have a `dist` directory containing all the relevant JS code.

Now running `pkg` gives me:

```
[nix-shell:~/Projects/Typescript-Demo-Lib]$ pkg dist/bin/typescript-demo-lib.js --targets node14-linux-x64 --debug
...
> [debug] Targets:
  [
  {
    "nodeRange": "node14",
    "platform": "linux",
    "arch": "x64",
    "output": "/home/cmcdragonkai/Projects/Typescript-Demo-Lib/typescript-demo-lib",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node14",
      "platform": "linux",
      "arch": "x64",
      "binaryPath": "/home/cmcdragonkai/.pkg-cache/v3.1/fetched-v14.17.0-linux-x64"
    },
    "binaryPath": "/home/cmcdragonkai/.pkg-cache/v3.1/fetched-v14.17.0-linux-x64"
  }
]
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at fabricate (/home/cmcdragonkai/Projects/Typescript-Demo-Lib/node_modules/pkg/lib-es5/fabricator.js:111:17)
    at Object.fabricateTwice (/home/cmcdragonkai/Projects/Typescript-Demo-Lib/node_modules/pkg/lib-es5/fabricator.js:120:5)
    at MultiStream._queue (/home/cmcdragonkai/Projects/Typescript-Demo-Lib/node_modules/pkg/lib-es5/producer.js:266:49)
    at MultiStream._next (/home/cmcdragonkai/Projects/Typescript-Demo-Lib/node_modules/multistream/index.js:86:12)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

All the earlier debug logs didn't seem useful. But this error seems like a stream writing error.

**Comment by CMCDragonkai** [comment]
The erro seems to be coming from:

https://github.com/vercel/pkg/blob/58130161bf31558ea03fc871eaa546d5f56431e3/lib/fabricator.ts#L144

I'm on a NixOS Linux Distribution if that makes any difference here.

**Comment by CMCDragonkai** [comment]
After some debugging, I've found that the error seems to be about bundling the JS source code with the actual downloaded node runtime. Because even when there's an EPIPE error, there's an output executable. The problem being that this executable is just the same executable fetched from `pkg-fetch`.

So now I'm going to be debugging why EPIPE is being thrown here during the child process write call. But I'm also checking on Ubuntu Virtualbox to see if this a NixOS specific error, or general to Linux.

Note that on WSL Ubuntu, it worked fine.

**Comment by CMCDragonkai** [comment]
I've found that if I disable bytecode generation, everything works fine.

```
[nix-shell:~/Projects/Typescript-Demo-Lib]$ pkg . --no-bytecode
> pkg@5.3.0
> Targets not specified. Assuming:
  node14-linux-x64, node14-macos-x64, node14-win-x64
```

**Comment by CMCDragonkai** [comment]
With the `--no-bytecode` option, I want to point out that the exact binary executable produced on WSL Ubuntu + nix-shell is not the same as that produced on NixOS + nix-shell even when both are using the same nix-shell.

```
[nix-shell:/mnt/c/Users/CMCDragonkai/Projects/TypeScript-Demo-Lib]$ md5sum ./typescript-demo-lib-linux
30bdd44842f01ed1f41031f16e6d537f  ./typescript-demo-lib-linux
```

vs

```
[nix-shell:~/Projects/Typescript-Demo-Lib]$ md5sum ./typescript-demo-lib-linux 
a64168d7e1b1b95af38de33d7755f5f1  ./typescript-demo-lib-linux
```

However both work the same and the working directory git repo shows no differences.

**Comment by yshui** [comment]
@CMCDragonkai did you find a solution? i am seeing the same problem.

**Comment by CMCDragonkai** [comment]
Disabling byte code generation.

**Comment by yshui** [comment]
`--no-bytecode` does not work for me. I got `Error! --no-bytecode and no source breaks final executable`

**Comment by minikN** [comment]
> `--no-bytecode` does not work for me. I got `Error! --no-bytecode and no source breaks final executable`

I am having the exact same problem.

**Comment by TimBeyer** [comment]
The same problem of `Error! --no-bytecode and no source breaks final executable` still exists and no combination of it and `--public` or `--public-packages "*"` gets rid of it for me.

**Comment by Strum355** [comment]
Using something like https://github.com/nix-community/nix-ld-rs/ should solve this on NixOS. The problem afaik is that pkg fetches some prebuild dynamically linked nodejs binaries that fail at the dynamic loading step. Hope Im not confusing this issue with a different one :grimacing:

**Comment by CMCDragonkai** [comment]
That's cool, have you tried?

**Comment by Strum355** [comment]
Double checking, I get EPIPE when using the standard https://github.com/Mic92/nix-ld that `programs.nix-ld.enable = true;` uses in NixOS. Using specifically https://github.com/nix-community/nix-ld-rs/ solves the EPIPE issue for me (using neither will give you ENOENT due to /lib64/ld-linux-x86-64.so.2 missing because the binary never even starts, EPIPE is due to the process/dynamic loader starting but then exiting due to the dynamic loader aka nix-ld not being able to find the dynamic libraries due to the NIX_LD and NIX_LD_LIBRARY_PATH env vars not being propagated i believe [here](https://github.com/vercel/pkg/blob/main/lib/fabricator.ts#L71-L74)).

Hopefully I was able to recreate my situation correctly to convey the info correctly
