### ISSUE TITLE
Need to manually codesign output binary for arm64 macs when building from linux/arm64

### ISSUE THREAD

**Issue by JohnnyLufa** [vercel/pkg#1243]
Hi, I need to build my script for `macos-arm64` using Docker, but the final output binary doesn't work yet.

Here is my Dockerfile:
```
FROM node:16-slim as builder

# Setup NODE_PATH and pkg
RUN npm i pkg -g

# Copy source file(s) and build
COPY src/arclego.js /src/arclego.js
RUN mkdir /out/ && cd /src/ && pkg arclego.js -t node16-macos-arm64 ---out-path /out/

# Copy output files to scratch container (sorta like an empty hard disk) for buildx to copy it back to the host machine
FROM scratch as output
COPY --from=builder /out .
```
The docker command:
`docker buildx build --no-cache --platform linux/arm64 --output type=local,dest=$(pwd)/dist .`
Once ran, the binary is then built successfully, but when I run it it gives me this output:
```
johnnylufa@REMOTE-M1-01 dist % ./arclego
zsh: killed     ./arclego
```

I need to manually execute
`codesign -s - ./arclego`
Then the binary file will work.

I got this solution from [here](https://github.com/golang/go/issues/42684)

I want `pkg` to be able to build node programs into already codesigned binaries for arm64 macs, hope it can be done.

**Comment by jesec** [comment]
This is not an issue. As far as I know, there is no codesign utility (or alternative) on other platforms. 

pkg gives you clear warning and instructions when it fails to sign the binary: 

https://github.com/vercel/pkg/blob/58130161bf31558ea03fc871eaa546d5f56431e3/lib/index.ts#L677

```
Unable to sign the macOS executable on non-macOS host
Due to the mandatory code signing requirement, before the
executable is distributed to end users, it must be signed with
the "codesign" utility of macOS, otherwise, it will be immediately
killed by kernel on launch. An ad-hoc signature is sufficient.
To do that, "codesign --sign - <executable>" on a Mac.
```

README mentions it as well.
