### ISSUE TITLE
PKG running executable not working on every client?

### ISSUE THREAD

**Issue by Rapid1898-code** [vercel/pkg#1244]
Hello - i am using PKG to create an executable from a node.js program -
this worked fine on windows 10 clients - but when a try to run the program on another client (with windows 8) - i get this a little bit weird error message:

Node.js is only supported on Windows 8.1., Windows Server 2012 R2, or higher. Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this check, but Node.js might not execute correctly. Any issues encountered on unsupported platform will not be fixed.

Is there any reason or workaround so this executable is also working on Windows 8?
Do i have to use a different node-version for making the executable?

**Comment by jesec** [comment]
The warning message says it all. 

No action would be taken. Please upgrade your system to a supported version.

**Comment by Rapid1898-code** [comment]
Yes thanks - with that
`pkg prg.js --targets node12-win-x64`
it seems to work also on Win8.1.

**Comment by BCsabaEngine** [comment]
> Yes thanks - with that
> `pkg prg.js --targets node12-win-x64`
> it seems to work also on Win8.1.

Base nodejs droped support for win7: https://github.com/nodejs/node/pull/31954
