### ISSUE TITLE
Error! This experimental syntax requires enabling the parser plugin: 'classPrivateMethods' (406:2)

### ISSUE THREAD

**Issue by hcldan** [vercel/pkg#1248]
I understand that a parser is being used at a low level here.
I've turned off bytecode generation and I really just want these files packed as-is as node can handle this syntax on the chosed target.

How do I turn this off?

**Comment by hcldan** [comment]
`pkg --public --public-packages '*' --no-bytecode --debug .`
btw I still see tons of messages about bytecode in the debug logs

**Comment by mblodorn** [comment]
+1 having troubles with node-webpmux + pkg

Error! This experimental syntax requires enabling the parser plugin: 'classPrivateMethods' (441:2)
  ********\node_modules\node-webpmux\webp.js

**Comment by LinkTree3** [comment]
> +1 having troubles with node-webpmux + pkg
> 
> Error! This experimental syntax requires enabling the parser plugin: 'classPrivateMethods' (441:2)
> ********\node_modules\node-webpmux\webp.js

Exactly the same issue for me with the node-webpmux package. I am able to build if I delete this package but that's not a great solution and is prone to break..

Did you manage to resolve this?
