### ISSUE TITLE
Use `ldid` to sign macOS binaries on other platforms.

### ISSUE THREAD

**Issue by asdfugil** [vercel/pkg#1251]
If `ldid` is available in PATH, pkg should use it to codesign the final macOS executable when the build  platform is not macOS.

**Comment by jesec** [comment]
Great idea. However, `ldid` does not officially support Linux, and the binary package is not widely available on common Linux distributions.

**Comment by jesec** [comment]
I manage to compile a binary for Linux.

It works quite well.

**Comment by asdfugil** [comment]
another alterantive is `zsign`

**Comment by asdfugil** [comment]
(but it has more stuff that we don't need)

**Comment by jesec** [comment]
`zsign` does not use an OSI-approved license. We will not endorse a proprietary source-available software.

**Comment by asdfugil** [comment]
Probably should mention in readme, also [this](https://github.com/tpoechtrager/ldid) is the recommended fork because it has linux support.

**Comment by asdfugil** [comment]
this can be closed

**Comment by jesec** [comment]
https://github.com/jesec/ldid-static

I made some useful binaries. The program is rather simple, and it is possible to compile it with a one-liner. 

I would rather not add a link in the README, though. (as `codesign` remains the recommended way, and I don't really want to support the case personally when there is no upstream support)

**Comment by asdfugil** [comment]
Just FYI, there are forks that are easier to compile for Linux, like this one https://github.com/tpoechtrager/ldid

This fork is actually intented to run on Linux and BSD [and is used in conjunction with an iOS toolchain on Linux and BSD](https://github.com/tpoechtrager/cctools-port)

**Comment by q0rban** [comment]
> zsign does not use an OSI-approved license. We will not endorse a proprietary source-available software.

Looks like as of Oct 2021, zsign is BSD licensed: https://github.com/zhlynn/zsign/blob/master/LICENSE

I've been really struggling to get ldid to compile so maybe zsign would be useful to list in the README as well, in case others are running into similar issues with ldid?

**Comment by asdfugil** [comment]
There are binaries at https://github.com/ProcursusTeam/ldid/actions

**Comment by jesec** [comment]
> > zsign does not use an OSI-approved license. We will not endorse a proprietary source-available software.
> 
> Looks like as of Oct 2021, zsign is BSD licensed: https://github.com/zhlynn/zsign/blob/master/LICENSE
> 
> I've been really struggling to get ldid to compile so maybe zsign would be useful to list in the README as well, in case others are running into similar issues with ldid?

Unfortunately, the license assignment is invalid. That project incorporated contributions when there is no license or CLA in place, and there did not appear to be an agreement by all contributors to add the license. 

ldid is quite easy to compile. It has much fewer dependencies than zsign. 

You may check https://github.com/jesec/ldid-static.

**Comment by caligo-erik** [comment]
I bumped into this topic since I'd like to create node16-macos-arm64 binaries on my Linux machine.
I got plenty of error messages with the following pattern:
`
Warning Failed to make bytecode node16-arm64 for file /snapshot/server/node_modules/has-flag/index.js
`
And one final message telling to install ldid in the PATH.
I have found the ldid binary linked above, and it is included in the path. 
But I still get plenty of errors with the pattern described above. The only difference is that now the last ldid message disappeared.

These are the targets I have specified in the package.json pkg section:
``` javascript
    "targets": [
      "node16-win-x64",
      "node16-linux-x64",
      "node16-macos-x64",
      "node16-macos-arm64"
    ]
```

If I delete the last target for arm64 macos, then it runs through without any error, and I can run those binaries on a Mac.

Any help very much appreciated.

FYI: I have recently bought a Mac Mini and an Apple Developer license, and I would also like to add my own signature to those mac binaries.

**Comment by asdfugil** [comment]
`ldid` accepts p12 certificates with the -K option:

example: `ldid -Cruntime -Sentitlements.xml -Kcertificate.p12`

**Comment by caligo-erik** [comment]
> `ldid` accepts p12 certificates with the -K option:
> 
> example: `ldid -Cruntime -Sentitlements.xml -Kcertificate.p12 macho_file1 macho_file2`
> 
> Anyways I do not think the error you received are really related to ldid.

Thanks for the usage example.
I was, however, more interested into how to configure pkg into using my own certificates.

**Comment by jesec** [comment]
> I bumped into this topic since I'd like to create node16-macos-arm64 binaries on my Linux machine. I got plenty of error messages with the following pattern: `Warning Failed to make bytecode node16-arm64 for file /snapshot/server/node_modules/has-flag/index.js` And one final message telling to install ldid in the PATH. I have found the ldid binary linked above, and it is included in the path. But I still get plenty of errors with the pattern described above. The only difference is that now the last ldid message disappeared.
> 
> These are the targets I have specified in the package.json pkg section:
> 
> ```js
>     "targets": [
>       "node16-win-x64",
>       "node16-linux-x64",
>       "node16-macos-x64",
>       "node16-macos-arm64"
>     ]
> ```
> 
> If I delete the last target for arm64 macos, then it runs through without any error, and I can run those binaries on a Mac.
> 
> Any help very much appreciated.
> 
> FYI: I have recently bought a Mac Mini and an Apple Developer license, and I would also like to add my own signature to those mac binaries.

Please read [README](https://github.com/vercel/pkg#targets).

"If you want to generate executable for different architectures, note that by default pkg has to run the executable of the **target** arch to generate bytecodes."

**Comment by asdfugil** [comment]
> > `ldid` accepts p12 certificates with the -K option:
> > example: `ldid -Cruntime -Sentitlements.xml -Kcertificate.p12 macho_file1 macho_file2`
> > Anyways I do not think the error you received are really related to ldid.
> 
> Thanks for the usage example. I was, however, more interested into how to configure pkg into using my own certificates.

The point of pkg is to create runnable executable files from javascript, which it has already done. If you want to sign it with your certificates (which is out of the scope of `pkg`) , you should invoke `ldid` itself directly. You can use a wrapper script to do that.
