### ISSUE TITLE
Cannot build application for armv6 in a Raspbian Pi4

### ISSUE THREAD

**Issue by DrCWO** [vercel/pkg#1253]
Hello,
I am stuck building an application with pkg for **armv6** and would really appreciate your help.
Until now I ran node 8.16 with pkg 4.4.9 but need to upgrade to a newer version. 

**My Environemnt:**
Raspberry RPI4 2GB/16GB running minimal Raspbian
node v14.4.0 for armv6 from here: https://unofficial-builds.nodejs.org/download/release/
pkg 5.3.0, installed with "npm install -g pkg"

**My application hello.js**
console.log ("hello World!");

**My command:**
pkg -t node14-linux-armv6 hello.js

**Output at Beginning starts with a lot of warnings:**
> pkg@5.3.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.17.0-linux-armv6        [                    ] 0%
> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.1","name":"node-v14.17.0-linux-armv6"}
> Building base binary from source:
  built-v14.17.0-linux-armv6
> Cloning Node.js repository from GitHub...
Cloning into bare repository 'node/.git'...
remote: Enumerating objects: 34157, done.
remote: Counting objects: 100% (34157/34157), done.
remote: Compressing objects: 100% (27814/27814), done.
remote: Total 34157 (delta 7908), reused 15788 (delta 5128), pack-reused 0
Receiving objects: 100% (34157/34157), 75.67 MiB | 9.63 MiB/s, done.
Resolving deltas: 100% (7908/7908), done.
> Checking out v14.17.0
Checking out files: 100% (34498/34498), done.
HEAD is now at aa15690b 2021-05-11, Version 14.17.0 'Fermium' (LTS)
> Applying patches
patching file common.gypi
patching file deps/v8/include/v8.h
patching file deps/v8/src/api/api.cc
patching file deps/v8/src/codegen/compiler.cc
patching file deps/v8/src/objects/js-objects.cc
patching file deps/v8/src/objects/shared-function-info-inl.h
patching file deps/v8/src/parsing/parsing.cc
patching file deps/v8/src/snapshot/code-serializer.cc
patching file lib/child_process.js
patching file lib/internal/bootstrap/pkg.js
patching file lib/internal/bootstrap/pre_execution.js
patching file lib/internal/modules/cjs/loader.js
patching file lib/internal/modules/package_json_reader.js
patching file lib/vm.js
patching file node.gyp
patching file src/inspector_agent.cc
patching file src/node.cc
patching file src/node_contextify.cc
patching file src/node_main.cc
patching file src/node_options.cc
patching file tools/icu/icu-generic.gyp
> Compiling Node.js from sources...
> Warning Cross compiling!
> Warning You are responsible for appropriate env like CC, CC_host, etc.
Node.js configure: Found Python 3.7.3...
INFO: configure completed successfully
make -C out BUILDTYPE=Release V=0
tools/v8_gypfiles/generate_bytecode_builtins_list.target.mk:13: warning: overriding recipe for target '/tmp/pkg.4dccd60b7db5367c66d7bff9/node/out/Release/obj/gen/generate-bytecode-output-root/builtins-generated/bytecodes-builtins-list.h'
tools/v8_gypfiles/generate_bytecode_builtins_list.host.mk:13: warning: ignoring old recipe for target '/tmp/pkg.4dccd60b7db5367c66d7bff9/node/out/Release/obj/gen/generate-bytecode-output-root/builtins-generated/bytecodes-builtins-list.h'
tools/v8_gypfiles/postmortem-metadata.target.mk:13: warning: overriding recipe for target '/tmp/pkg.4dccd60b7db5367c66d7bff9/node/out/Release/obj/gen/debug-support.cc'
tools/v8_gypfiles/postmortem-metadata.host.mk:13: warning: ignoring old 
...

**Hours later the output ended with an error:**
  g++ -o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/snapshot-empty.o ../deps/v8/src/snapshot/snapshot-empty.cc '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_ARM' '-DV8_EMBEDDER_STRING="-node.63"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_CONCURRENT_MARKING' '-DV8_ARRAY_BUFFER_EXTENSION' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj/gen/generate-bytecode-output-root -I/tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj/gen/torque-output-root -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil  -pthread -Wno-unused-parameter -Wno-return-type -fno-strict-aliasing -mfloat-abi=hard -marm -O3 -fno-omit-frame-pointer -flto=4 -ffat-lto-objects -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/.deps//tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/snapshot-empty.o.d.raw   -c
  g++ -o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/mksnapshot -pthread -rdynamic -flto=4 -ffat-lto-objects   -Wl,--start-group /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/embedded/embedded-empty.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/embedded/embedded-file-writer.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/embedded/platform-embedded-file-writer-aix.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/embedded/platform-embedded-file-writer-base.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/embedded/platform-embedded-file-writer-generic.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/embedded/platform-embedded-file-writer-mac.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/embedded/platform-embedded-file-writer-win.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/mksnapshot.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/mksnapshot/deps/v8/src/snapshot/snapshot-empty.o /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/v8_gypfiles/libv8_base_without_compiler.a /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/v8_gypfiles/libv8_init.a /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/v8_gypfiles/libv8_libbase.a /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/v8_gypfiles/libv8_libplatform.a /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/icu/libicutools.a /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/v8_gypfiles/libv8_libsampler.a /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/v8_gypfiles/libv8_zlib.a /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/v8_gypfiles/libv8_compiler.a /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/obj.host/tools/v8_gypfiles/libv8_initializers.a -latomic -ldl -lrt -Wl,--end-group
In member function ‘Resize’,
    inlined from ‘_ZN2v88internal16DetachableVectorINS0_7ContextEE9push_backERKS2_.isra.815’ at ../deps/v8/src/utils/detachable-vector.h:57:1,
    inlined from ‘Enter’ at ../deps/v8/src/api/api.h:486:30:
../deps/v8/src/utils/detachable-vector.h:91:20: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
     T* new_data_ = new T[new_capacity];
                    ^
../deps/v8/src/utils/detachable-vector.h: In member function ‘Enter’:
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
In member function ‘Resize’,
    inlined from ‘_ZN2v88internal16DetachableVectorINS0_7ContextEE9push_backERKS2_.isra.815’ at ../deps/v8/src/utils/detachable-vector.h:57:1,
    inlined from ‘Enter’ at ../deps/v8/src/api/api.h:471:28:
../deps/v8/src/utils/detachable-vector.h:91:20: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
     T* new_data_ = new T[new_capacity];
                    ^
../deps/v8/src/utils/detachable-vector.h: In member function ‘Enter’:
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
In member function ‘Resize’,
    inlined from ‘_ZN2v88internal16DetachableVectorINS0_7ContextEE9push_backERKS2_.isra.815’ at ../deps/v8/src/utils/detachable-vector.h:57:1,
    inlined from ‘SaveContext’ at ../deps/v8/src/api/api.h:471:28,
    inlined from ‘__ct_base ’ at ../deps/v8/src/api/api.cc:291:26:
../deps/v8/src/utils/detachable-vector.h:91:20: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
     T* new_data_ = new T[new_capacity];
                    ^
../deps/v8/src/utils/detachable-vector.h: In member function ‘__ct_base ’:
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
In member function ‘Resize’,
    inlined from ‘_ZN2v88internal16DetachableVectorINS0_7ContextEE9push_backERKS2_.isra.815’ at ../deps/v8/src/utils/detachable-vector.h:57:1,
    inlined from ‘SaveContext’ at ../deps/v8/src/api/api.h:471:28,
    inlined from ‘__ct_base ’ at ../deps/v8/src/api/api.cc:291:26:
../deps/v8/src/utils/detachable-vector.h:91:20: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
     T* new_data_ = new T[new_capacity];
                    ^
../deps/v8/src/utils/detachable-vector.h: In member function ‘__ct_base ’:
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
In member function ‘CreateAndExecuteEvacuationTasks’,
    inlined from ‘EvacuatePagesInParallel’ at ../deps/v8/src/heap/mark-compact.cc:5176:60:
../deps/v8/src/heap/mark-compact.cc:3132:28: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
   Evacuator** evacuators = new Evacuator*[wanted_num_tasks];
                            ^
../deps/v8/src/heap/mark-compact.cc: In member function ‘EvacuatePagesInParallel’:
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
In member function ‘CreateAndExecuteEvacuationTasks.constprop’,
    inlined from ‘EvacuatePagesInParallel’ at ../deps/v8/src/heap/mark-compact.cc:3220:49:
../deps/v8/src/heap/mark-compact.cc:3132:28: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
   Evacuator** evacuators = new Evacuator*[wanted_num_tasks];
                            ^
../deps/v8/src/heap/mark-compact.cc: In member function ‘EvacuatePagesInParallel’:
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
../deps/v8/src/deoptimizer/deoptimizer.cc: In member function ‘DoComputeOutputFrames’:
../deps/v8/src/deoptimizer/deoptimizer.cc:784: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
   output_ = new FrameDescription*[count];

/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
In member function ‘Resize’,
    inlined from ‘_ZN2v88internal16DetachableVectorINS0_7ContextEE9push_backERKS2_.isra.815’ at ../deps/v8/src/utils/detachable-vector.h:57:3,
    inlined from ‘EnterMicrotaskContextWrapper’ at ../deps/v8/src/api/api.h:503:30:
../deps/v8/src/utils/detachable-vector.h:91:20: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
     T* new_data_ = new T[new_capacity];
                    ^
../deps/v8/src/utils/detachable-vector.h: In function ‘EnterMicrotaskContextWrapper’:
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
../deps/v8/src/heap/item-parallel-job.cc: In member function ‘Run’:
../deps/v8/src/heap/item-parallel-job.cc:79:46: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
       new CancelableTaskManager::Id[num_tasks];
                                              ^
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
../deps/v8/src/wasm/wasm-interpreter.cc: In member function ‘EnsureStackSpace’:
../deps/v8/src/wasm/wasm-interpreter.cc:3840:68: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
     std::unique_ptr<StackValue[]> new_stack(new StackValue[new_size]);
                                                                    ^
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
../deps/v8/src/wasm/wasm-objects.cc: In function ‘UpdateDispatchTables’:
../deps/v8/src/wasm/wasm-objects.cc:561:74: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
   std::unique_ptr<wasm::ValueType[]> reps(new wasm::ValueType[total_count]);
                                                                          ^
/usr/include/c++/8/new:122:7: note: in a call to allocation function ‘operator new []’ declared here
 void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
       ^
/tmp/cc7qwvvM.s: Assembler messages:
/tmp/cc7qwvvM.s:60776: Error: invalid literal constant: pool needs to be closer
make[2]: *** [/tmp/ccgnfGPE.mk:53: /tmp/ccnhH6wg.ltrans17.ltrans.o] Error 1
make[2]: *** Waiting for unfinished jobs....
**lto-wrapper: fatal error: make returned 2 exit status**
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[1]: *** [tools/v8_gypfiles/mksnapshot.host.mk:191: /tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/mksnapshot] Error 1
rm e3191e06f6f0bd9481300bdf835bfac92d7e98d5.intermediate 49579f5272bc55d7904f8e2f60a4edb5f2f93611.intermediate ea46b706a789d0b53133cddbf5fab162a7d30a10.intermediate a7d34756d8d0173f852fc45bc298b01042f1793e.intermediate
make: *** [Makefile:104: node] Error 2
strip: '/tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/node': No such file
> Error! Error: ENOENT: no such file or directory, open '/tmp/pkg.e6945473c481fbd614c74ab6/node/out/Release/node'

**Comment by jesec** [comment]
The platform is not supported, and we have no plan to support it. 

Please upgrade to a supported platform like arm64.

**Comment by 564064202** [comment]
> The platform is not supported, and we have no plan to support it.
> 
> Please upgrade to a supported platform like arm64.

pi4b is arm64,this is a famous platform

**Comment by maxpavlov** [comment]
> > The platform is not supported, and we have no plan to support it.
> > Please upgrade to a supported platform like arm64.
> 
> pi4b is arm64,this is a famous platform

Just recently "late 2021" Raspberry PI OS images began to be real arm64. 90% of PI4 users have armv7 I suppose or did a kernel upgrade with retaining the 32biit userland.

So no, it's not common to have arm64 on Pi4 these days, not yet.

**Comment by 564064202** [comment]
> > > The platform is not supported, and we have no plan to support it.
> > > Please upgrade to a supported platform like arm64.
> > 
> > 
> > pi4b is arm64,this is a famous platform
> 
> Just recently "late 2021" Raspberry PI OS images began to be real arm64. 90% of PI4 users have armv7 I suppose or did a kernel upgrade with retaining the 32biit userland.
> 
> **So no, it's not common to have arm64 on Pi4 these days, not yet.**
sir,please don't speak something you don't know
