### ISSUE TITLE
Is there a way to run the .EXE in the background?

### ISSUE THREAD

**Issue by gilbertoalbino** [vercel/pkg#1256]
Hi, there!

I think this is one of the most amazing projects ever created for Node.JS.

However, it may be reasonable to run the console in the background since the end-user may think he or she should close the console (cmd, powershell,etc).

Is there such a way to pkg run the console in the background?

**Comment by BCsabaEngine** [comment]
Try this newage package, include in your app.
https://github.com/hetrodoo/hetrodo-node-hide-console-window-napi#readme

**Comment by soonsam123** [comment]
No answer for this?
