### ISSUE TITLE
problem at the usage with pictures

### ISSUE THREAD

**Issue by boostrrr** [vercel/pkg#1258]
I coded a few little scripts to upload pictures to Googledrive just by draging them in a folder. The first is a python script, that changes the name of the file to  x.jpg. The second is a js script that uploads x.jpg to drive via the api. the last file is also a python script that simply deletes the picture x.jpg from the folder after it got uploaded. My problem: if I run the js script from the console everything works fine, but when I compile it to an .exe, the .exe always uploads the picture that was in the folder while I created the .exe. 
Example: 
In the folder is a picture of a Mountain while I create the .exe. After I created the .exe I replace the Mountainpicture with a Seapicture (that has the same name as the Mountainpicture). In the folder is now a picture of a Sea, but when I run the .exe its still uploading the picture of the Mountain.
Is there anybody that knows more about this? I would be super thankful

**Comment by BCsabaEngine** [comment]
If your js code references (hard coded) to the picture, pkg will pack the picture in exe. And every run will get the same picture. Try use file without __dirname and pkg will show a warning. File wont be included static.
