### ISSUE TITLE
Warning Failed to make bytecode node14-x64 for file /snapshot/nominate-client/node_modules/@polkadot/api/index.js

### ISSUE THREAD

**Issue by GopherJ** [vercel/pkg#1262]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/33961674/126162654-ad88071e-aaac-46a7-b235-8c188c8e9acf.png">

**Comment by aboe026** [comment]
I'm seeing the same issue. @GopherJ, why did you close this? Did you find a resolution?
