### ISSUE TITLE
Can't delete/copy pkg-cache folder (windows 10 19043.1110)

### ISSUE THREAD

**Issue by kageyoshiyo** [vercel/pkg#1263]
### Can't delete/copy pkg-cache folder

![image](https://user-images.githubusercontent.com/49963615/126395273-f0f140c2-4019-450b-90b8-8d20033a9692.png)
![image](https://user-images.githubusercontent.com/49963615/126395153-51a1251f-4263-4402-aaef-831c450710f3.png)

**Comment by BCsabaEngine** [comment]
Did you tried at after close cmd window, vscode, total commander, etc?

**Comment by kageyoshiyo** [comment]
Solved, just delete this folder through vs code
