### ISSUE TITLE
Warnings when bundling leveldown.

### ISSUE THREAD

**Issue by tegefaulkes** [vercel/pkg#1264]
I'm trying to bundle a simple node program that includes some native modules. One of these modules is level witch includes leveldown.

When trying to use pkg to build I receive the following error.
```
pkg . --targets linux-x64 --no-bytecode --public-packages "*" --output linprog
> pkg@5.3.1
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/leveldown/prebuilds
  %2: path-to-executable/prebuilds
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/leveldown/prebuilds
  %2: path-to-executable/prebuilds
```
The built executable works if I include the prebuilds with it.

Now as far as I know, pkg should detect and include these native modules properly now. So I shouldn't need to include these manually. Is there any reason why this isn't working?

When I try to add the files as an asset in the package.json with:
```
"pkg": {
    "assets": [
      "node_modules/leveldown/**/*",
    ]
  }
```
I can confirm the files are being added when I check the log with the `--debug` flag.

The odd thing is, this project also includes utp-native witch seems to be bundled just fine.

**Comment by tegefaulkes** [comment]
Some more details.

Here is the repository i'm testing.
https://github.com/MatrixAI/TypeScript-Demo-Lib/pull/29
https://github.com/MatrixAI/TypeScript-Demo-Lib/tree/pkg-integration

I should be able to run the command `pkg . --targets linux-x64 --no-bytecode --public-packages "*" --output linprog` and have it package the program without the warnings. the program should be able to run leveldown with no issues then.

Using utp-native as a comparison for the expected behaviour. utp-native had to be added as an asset, but it never packaged with the warning like above.

**Comment by tegefaulkes** [comment]
This relates to #837.
While node support was added, no changes were made to the files inside the `dictionary` folder.
leveldown.js is specifying prebuilds in `deployFiles`
```ts
'use strict';

module.exports = {
  pkg: {
    patches: {
      'binding.js': ['__dirname', "require('path').dirname(process.execPath)"],
    },
    deployFiles: [['prebuilds', 'prebuilds', 'directory']],
  },
};
```

**Comment by tegefaulkes** [comment]
I've confirmed that this is the problem.

I replaced `dictionary/leveldown.js` with 
```js 
'use strict';

module.exports = {};
```
Packaged the program with `pkg . --targets linux-x64 --no-bytecode --public-packages "*" --output linprog` and it runs fine now.
This should be tested and pulled in now.

**Comment by CMCDragonkai** [comment]
@tegefaulkes In the future for this sort of work you would want to create the forks under MatrixAI group in github rather than your personal account: https://github.com/tegefaulkes/pkg

It makes it easier for us to maintain forks and maintain overrides in our nixpkgs overlay.
