### ISSUE TITLE
Is there a way to get a pinned version from cache?

### ISSUE THREAD

**Issue by jc-lab** [vercel/pkg#1265]
To use https://github.com/yao-pkg/pkg-binaries/releases etc.

**Comment by CMCDragonkai** [comment]
I've done this in our demo repository that uses vercel/pkg: https://github.com/MatrixAI/TypeScript-Demo-Lib/blob/master/utils.nix#L49-L64

You can see I use these 2 settings: https://github.com/MatrixAI/TypeScript-Demo-Lib/blob/master/release.nix#L14-L15

To ensure that my pkg always uses a specific binary release.

```
      PKG_CACHE_PATH = utils.pkgCachePath;
      PKG_IGNORE_TAG = 1;
```

**Comment by jclab-joseph** [comment]
Thank you.
My account has been changed and cannot be closed. Please close.
