### ISSUE TITLE
Socket.IO not working in windows build

### ISSUE THREAD

**Issue by alexs-sb** [vercel/pkg#1266]
My application is using socket.io ver 2, I also tried ver 4.
When I build for mac everything is working as expected.
But when I run the built exe on windows socket.io part of code disconnects with "transport close" error.
I tried to run the code on windows directly from Node and it works as expected.

im using node 14, tried to build exe on mac and windows.

any ideas what might be the issue?

**Comment by hygohil** [comment]
@alexs-sb  what was the issue, And how did you fixed it

**Comment by thiagohagy** [comment]
Having same problem here, a way to solve it, is making the socket.io files static on your project
