### ISSUE TITLE
How to obfuscate source code?

### ISSUE THREAD

**Issue by GirkovArpa** [vercel/pkg#1267]
In the resulting executable, the source code of `index.js` is visible in a hex editor, and adding `"private": true"` to `package.json` makes no difference.

**Comment by ryanemax** [comment]
I use webpack to obfuscate my code & copy my assets, before pkg -t node16-linux-amd64 dist/server.js.

**Comment by GirkovArpa** [comment]
Judging by the word "web" in "webpack", I doubt it compiles JavaScript to V8 bytecode, like pkg is supposed to do.

**Comment by jesec** [comment]
Make sure that the `license` field of your `package.json` does not specify a OSS license.

**Comment by GirkovArpa** [comment]
It doesn't specify any license.

**Comment by Nisthar** [comment]
any update on this? I thought the bytecode in pkg is not easily visible. @jesec

**Comment by jesec** [comment]
I am not able to reproduce this issue. The clear source sections you found in the binary most likely come from the OSS dependencies or Node.js internal functions, which are not obfuscated.
