### ISSUE TITLE
UPX Support

### ISSUE THREAD

**Issue by BlackYuzia** [vercel/pkg#1269]
Hi there.

I try use [upx (app for compress binary files)](https://upx.github.io/) but when I compress binary file from `pkg` and try execute I get error:
```bash
Pkg: Error reading from file.
```

**Any suggestions?** I suppose that trouble would be with any binary (.exe) file generated via `pkg` package.

**Comment by Hypfer** [comment]
Duplicate of #50

See also https://github.com/vercel/pkg-fetch/pull/175
