### ISSUE TITLE
[BUG] Unexpected character in app icon

### ISSUE THREAD

**Issue by tackelua** [vercel/pkg#1274]
I have the same issue  https://github.com/microsoft/playwright/issues/5627

```
Error! Unexpected character '?' (1:0)
\node_modules\playwright\lib\server\chromium\appIcon.png
```

<img width="926" alt="Screen Shot 2021-08-05 at 00 45 42" src="https://user-images.githubusercontent.com/22250123/128229176-263a7945-ab11-4335-b1b3-0c94069c5d8c.png">

**Comment by ngustavo** [comment]
Any news on this? I have the same issue.

**Comment by ngustavo** [comment]
Any news on this? I have the same issue.
I tried specifying `appIcon` as an asset but it still gives me the same error.
```js
// pkg.config.js
const { version } = require("./package.json");

module.exports = {
  name: `helper-v${version}.exe`,
  pkg: {
    assets: [
      "client/dist/**/*",
      "node_modules/playwright-core/lib/server/chromium/appIcon.png",
    ],
    targets: ["win"],
    outputPath: "bin",
  },
};
```
