### ISSUE TITLE
Native build for armv7 architecture does not work anymore

### ISSUE THREAD

**Issue by QuickJack** [vercel/pkg#1275]
When trying to build a target for the armv7 architecture using arm32v7/node:14 the output is as follows:

```
root@852eaa293a88:/builds# pkg -t node14-linuxstatic-armv7 index.js -o test
> pkg@5.3.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.17.2-linux-armv7        [                    ] 0%
> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.2","name":"node-v14.17.2-linux-armv7"}
> Building base binary from source:
  built-v14.17.2-linux-armv7
> Cloning Node.js repository from GitHub...
Cloning into bare repository 'node/.git'...
^C
root@852eaa293a88:/builds# ls -l ~/.pkg-cache/v3.2/
total 29088
-rwxr-xr-x 1 root root 29783164 Aug  6 08:28 fetched-v14.17.2-linuxstatic-armv7
```
The image is downloaded correctly. However, further processing fails.

Obviously, fabPlatform is not correctly set to 'linuxstatic' at https://github.com/vercel/pkg/blob/d65eb64e896bc4d9c95713dc4467306684c23b46/lib/index.ts#L164.

The issue can be fixed by adding `|| hostArch === 'armv7'`

**Comment by jesec** [comment]
armv7 is supported on best-effort basis.

**Comment by pfried** [comment]
@jesec Would accepting a PR go against a best-effort practice? In my case this issue is also the problem and without the fix there is no way using the mainline version

**Comment by robertsLando** [comment]
@jesec I agree with them about the armv7 native build, it doesn't cost anything to us to add that line of code to allow them do native builds.

**Comment by jesec** [comment]
The line does not make any sense on its own. It adds unnecessary complexity. 

I found it extremely unlikely to have a scenario where people would only generate executable for `armv7` (w/o support for `x86` or `arm64`). It is equally unlikely for developers to use an `armv7` as the main machine where they bundle and publish their packages. 

Additionally, only `linuxstatic` is available for `armv7`, and it does not support any native addons, so "I need to build my native addon" argument won't make sense, either. 

So, find a normal `x86` and `arm64` machine instead. Set up QEMU, and generate executables for all architectures you need to support at once. `pkg` does allow you to generate executables for different architectures. `armv7` is dead and no one uses it in production.

**Comment by QuickJack** [comment]
armv7 is dead and no one uses it in production.

**Comment by QuickJack** [comment]
> I found it extremely unlikely to have a scenario where people would only generate executable for armv7 (w/o support for x86 or arm64).

Why would an Embedded developer targeting an armv7 device even think about producing code for a different platform?

> armv7 is dead and no one uses it in production.

The armv7 platform is used widely in the Embedded area. I found this study from 2019 https://www.embedded.com/wp-content/uploads/2019/11/EETimes_Embedded_2019_Embedded_Markets_Study.pdf. Take a look at page 66. Please also note that IoT devices produced today should be supported with updates for the years to come. This is the reason why this architecture is fully supported by the Linux Kernel as well as all major distributions including Debian (https://www.debian.org/releases/stable/armel/ch02s01.en.html).

**Comment by thanpolas** [comment]
> armv7 is dead and no one uses it in production.

So, @jesec you are rejecting this PR our of your personal opinion? What is the cost to you sir to allow this to build on an rpi? 

What solution do you offer to target rpi armv7?

**Comment by kerwitz** [comment]
Well, this issue was a depressing read.

**Comment by benkyllo** [comment]
Agree with @kerwitz , depressing.  I'm developing on embedded systems using armv7, couldn't figure out why it wasn't working...  I'll have to find a different tool/path I guess.

**Comment by ssmethurst** [comment]
@benkyllo  Did you find another tool that works for ArmV7?
