### ISSUE TITLE
Kaspersky detected Trojan-PSW.Win32.Stelega.gen in the fetched build

### ISSUE THREAD

**Issue by dushyantbangal** [vercel/pkg#1286]
My Kaspersky just detected this:

![image](https://user-images.githubusercontent.com/13764676/129305333-9f3c6c87-503d-40a1-bfb1-6b202266af9d.png)

pkg version: 4.4.9
npm version: 6.14.8
Node js version: 12.20.0 and 14.15.1 using nvm.

**Comment by jesec** [comment]
See #1384 .
