### ISSUE TITLE
Unable to package binary with v5.3.1

### ISSUE THREAD

**Issue by brikendr** [vercel/pkg#1287]
We are using pkg for packaging a command line tool for interacting with usb cameras. We have been able to successfully use the package for packaging our binary for node10 and node12 so far. After trying to add support for node14, i have been encountering issues with pkg.

Here is the non verbose output of packaging with node14 on linux (i.e. running command `./node_modules/.bin/pkg . --targets node14-linux-x64`:
```
> pkg@5.3.1
prebuild-install WARN install No prebuilt binaries found (target=v14.17.2 runtime=node arch=x64 libc= platform=linux)
prebuild-install WARN install No prebuilt binaries found (target=v14.17.2 runtime=node arch=x64 libc= platform=linux)
prebuild-install WARN install No prebuilt binaries found (target=v14.17.2 runtime=node arch=x64 libc= platform=linux)
```

The package.json configuration for pkg looks like this:
```
...
"pkg": {
    "scripts": "cmds/*.js",
    "assets": "node_modules/**/node-83.node"
  }
...
```

I spent several hours debugging this and initially thought that we were not correctly providing the prebuilds necessary for running our executable but everything seems to be correct in that front. After several attempts i was able to discover that using an older version of pkg (specifically v4.4.9, i was able to get rid of those warnings and the binary was packaged correctly and could be used afterwards without any issues). Unfortunately with pkg v4.4.9 we do not get the change that allows code-signing the binary for macos. 

Would appreciate having some feedback on this and a potential solution/fix.

**Comment by CMCDragonkai** [comment]
Try adding `npm_config_build_from_source="true"` and see if that helps?
