### ISSUE TITLE
Adding icon to exe 

### ISSUE THREAD

**Issue by dominusmars** [vercel/pkg#1289]
I've been trying to compile my program with pkgnpm for the last 2 days. I haven't found a reliable way to change the icon and file info. Nexe has a way to do it but it doesn't compile into bytecode. is there a way to change the icon without using something like resourcehacker or rcedit? both of them have just corrupted the exe causing it to not work

**Comment by si458** [comment]
@dominusmars i have the same issue,
i wrote a module which changes the metadata and icon https://github.com/si458/changeexe
changing the metadata works perfectly HOWEVER changing the icon corrupts it still 👎

**Comment by si458** [comment]
@dominusmars i wrote another script which uses a json and it builds perfectly, give it a go 👍 
https://gist.github.com/si458/8571e8435f0bf6ece31c118e459ab780

**Comment by sir-reynolds** [comment]
> @dominusmars saya menulis skrip lain yang menggunakan json dan dibangun dengan sempurna, cobalah👍
> [https://Gist.github.com/si458/8571e8435f0bf6ece31c118e459ab780](https://gist.github.com/si458/8571e8435f0bf6ece31c118e459ab780)

I just tested it and it worked, thank you

**Comment by dchumak** [comment]
Got this please help
>Applying patches
(node:29804) UnhandledPromiseRejectionWarning: Error: spawnSync patch ENOENT
    at Object.spawnSync (internal/child_process.js:1074:20)
    at Object.spawnSync (child_process.js:629:24)
    at Object.<anonymous> (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:148:37)
    at step (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
    at Object.next (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
    at C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
    at Object.spawn (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:145:12)
    at C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\build.js:174:50
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a 
catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag 
`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:29804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ozelotcode** [comment]
> Got this please help
> 
> > Applying patches
> > (node:29804) UnhandledPromiseRejectionWarning: Error: spawnSync patch ENOENT
> > at Object.spawnSync (internal/child_process.js:1074:20)
> > at Object.spawnSync (child_process.js:629:24)
> > at Object. (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:148:37)
> > at step (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:33:23)
> > at Object.next (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:14:53)
> > at C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:8:71
> > at new Promise ()
> > at __awaiter (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:4:12)
> > at Object.spawn (C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\utils.js:145:12)
> > at C:\Projects\myapp\node_modules\pkg-fetch\lib-es5\build.js:174:50
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > (node:29804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a
> > catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag
> > `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> > (node:29804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

In your package.json use 
`"node_version": "14.17.6",`

**Comment by zyme-xd** [comment]
> 
> 
> updated my build script for others - https://gist.github.com/si458/8571e8435f0bf6ece31c118e459ab780 only requires `pkg` and `resedit` im also thinking about making a new module to simply import this script to help others out or edit my existing changexe module
Tried your tool, got an error n```
handledPromiseRejectionWarning: Error: spawn patch ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by si458** [comment]
@zyme-xd it appears a command is failing and I'm not catching the errors to display them

What versions of software are u using? OS? Node? pkg? I'll try replicate it
