### ISSUE TITLE
"Cannot mkdir in a snapshot. Try mount points instead."

### ISSUE THREAD

**Issue by jakobrosenberg** [vercel/pkg#1293]
How do I try a mount point?

**Comment by theoutlander** [comment]
What is the best way to support creating directories dynamically? Is it possible to mkdir in one of the assets/mountpoint folders?

**Comment by maxpavlov** [comment]
Relevant question. Completely unclear how to mkdir while executing packed.

**Comment by robertsLando** [comment]
@maxpavlov check: https://github.com/vercel/pkg/blob/main/prelude/bootstrap.js#L1505

**Comment by JackGou1029** [comment]
Same problem, any solution?

**Comment by risharde** [comment]
Same thing on my side - had great hopes for this, highly disappointed at the moment by this error

**Comment by JackGou1029** [comment]
> 
I solved this problem by using process.cwd() to get your pkg execute path, which you can use this to create new dir.
Because pkg use snapshot filesystem, orign __dirname, __filename were hijacked.. see README  Snapshot filesystem part..

**Comment by amiralam0** [comment]
any fix?

**Comment by gunyakov** [comment]
Any suggestion to fix this issue???

**Comment by guatemartin** [comment]
In case anyone comes across this.  I was having an issue using "winston" to log my files.
I was using <code>filename: path.join(__dirname, "./logs/error.log")</code>
What solved it for me, was to change it to <code>filename: path.join(process.cwd(), "./logs/error.log")</code>
If you console log both __dirname and process.cwd() in a working executable package (make a simple project and test it), you will see why.
Good luck!
