### ISSUE TITLE
Compiled exe file doesn't work properly only the uncompiled version that works properly

### ISSUE THREAD

**Issue by I2rys** [vercel/pkg#1296]
So I'm creating an open source undetectable [virus](https://github.com/I2rys/Eater) but the v1.0.1 version of it. And the virus works properly If you run it via **node index.js** but If you compile it to pkg It won't work properly.

Source code: https://transfer.sh/1esuuux/Sourcecode.rar

You might ask:
Why node_modules isn't on the folder?
Because I found an easier way to use the NPM packages globally without installing them again in each project folder you make, by making a folder & a file name **index.js** then install all the NPM packages you need on that directory. Make a folder with the thingy that you want to make then just run it. It would work without the **npm init** and Installing the NPM packages on the folder.

Will the file virs.exe & network.vbs on the assets folder damage my computer?
No they are 100% safe, because they are unfinished because I'm stuck in this problem but they properly work.
The virus source code If you think It's still dangerous to do some test to fix my problem because of those files(Disable anti virus If you can't open the code):  [Source code](https://github.com/vercel/pkg/files/7029273/virus.sourcecode.zip)

**Comment by btsimonh** [comment]
Hi i2rys,

hmm..  the biggest problem with this is that if it became a recognised way of distributing viral code, then the anti-virus programs will block us all.  Every self-compiled nodejs would be blocked until long negotiations with all the anti-virus companies had been completed for each exe.  Even then, the same negotiations every time you want to update?
I have often referred to my own version of packaged nodejs apps with dynamic delivery of compressed and encrypted code as an ideal viral vector - and indeed have already had it identified by MS as viral (they were very quick to correct this).

Please be careful and be mindful of those who wish to use this style of packaged node apps for real applications which need to pass anti-viral tests and be deliverable to customers' machines.

br,

Simon

**Comment by I2rys** [comment]
> Hi i2rys,
> 
> hmm.. the biggest problem with this is that if it became a recognised way of distributing viral code, then the anti-virus programs will block us all. Every self-compiled nodejs would be blocked until long negotiations with all the anti-virus companies had been completed for each exe. Even then, the same negotiations every time you want to update?
> I have often referred to my own version of packaged nodejs apps with dynamic delivery of compressed and encrypted code as an ideal viral vector - and indeed have already had it identified by MS as viral (they were very quick to correct this).
> 
> Please be careful and be mindful of those who wish to use this style of packaged node apps for real applications which need to pass anti-viral tests and be deliverable to customers' machines.
> 
> br,
> 
> Simon

Hello btsimonh,
I understand what you are trying to tell & thank you for telling me this. By the way the fact that I like creating this kind of stuff is because I want to explore on what NodeJS is capable of that I don't know I don't have any bad intension with it, In quote "Expect the unexpected.".
