### ISSUE TITLE
Any way to set custom app title?

### ISSUE THREAD

**Issue by ttodua** [vercel/pkg#1297]
Any ways to solve problems shown [on this screenshot](https://i.imgur.com/JC3dQ8F.png) : 

1) Set custom logo (instead of node logo)
2) Set custom title (instead of "Nodejs javascript runtime" and publisher "Node.js") ?

**Comment by iitsuraj** [comment]
Use this build script. Thanks to @si458 

https://gist.github.com/si458/8571e8435f0bf6ece31c118e459ab780

**Comment by ttodua** [comment]
many thanks! I will try.
