### ISSUE TITLE
Possible to symlink into snapshot?

### ISSUE THREAD

**Issue by devinivy** [vercel/pkg#131]
I have a process that creates a temp directory using [tmp](https://github.com/raszi/node-tmp) then creates symlinks in that directory to some modules to be used (`require()`d) later.  In pkg-land that means that I'm attempting to create symlinks from my machine's temp directory to modules inside `/snapshot`, which naturally doesn't work.

Any suggestions?  Is there anything I can do or anything pkg can do to help handle this use-case?

**Comment by igorklopov** [comment]
So is it really the only way to modify your `node_modules` directory? I mean can that modules use `tmp`? Or can you pass some directory name to them in order to make them work in that dir only?

**Comment by devinivy** [comment]
I'm not sure I understand your suggestions/questions.  Maybe I can be more clear with the setup.  I have several folders in my project: `A/`, `B/`, `C/`.  These end-up in my binary's snapshot.  They contain plain js files (`A/x.js`, `B/y.js`, `C/z.js`).  My program needs to use all those files, but only after they live in a single directory together.  So I create a temp directory on my machine, and make symlinks, `/temp/x.js -> A/x.js`, `/temp/y.js -> B/y.js`, `/temp/z.js -> C/x.js`.  Then my program will `require()` and use `/temp/x.js`, `/temp/y.js`, `/temp/z.js`.  But the symlinks are broken because `/temp` is on the machine, yet `A/`, `B/`, and `C/` live in the snapshot.

Does that make sense?  Concretely, it's because I'm using [knex migrations](http://knexjs.org/#Migrations), which only operate on a single directory, but I have my migrations split into many directories.  My solution is to aggregate all migrations into a single temp directory then tell knex to use that.

**Comment by devinivy** [comment]
I'm bumping this, just in case there's a solution now that some time has passed.  If you don't see a way forward, feel free to close.

**Comment by erossignon** [comment]
symlinks is not supported in pkg@5.
