### ISSUE TITLE
Cant open the compiled app because of possible require issues.

### ISSUE THREAD

**Issue by InfinityDevTech** [vercel/pkg#1310]
So whenever I first launch my program it launches index.js just fine and I can go through that, but when it gets to the part to launch the bot it crashes immediately and I belive its because I'm using '${process.cwd()}/commands/${command_name}" to require my file, is this an issue? It does not seem like it because if I change it everything works perfectly.

**Comment by coolbossinator** [comment]
^^

**Comment by coolbossinator** [comment]
Bump :)
