### ISSUE TITLE
centos 2.9 Device or resource busy

### ISSUE THREAD

**Issue by 564064202** [vercel/pkg#1316]
22/Sep/2021 08:11:10 [edge.c:1085] use manually set IP address
22/Sep/2021 08:11:10 [tuntap_linux.c:136] ERROR: tuntap ioctl(TUNSETIFF, IFF_TAP) error: Device or resource busy[-1]

**Comment by jesec** [comment]
Please check the binary compatibility table: https://github.com/vercel/pkg-fetch#binary-compatibility
