### ISSUE TITLE
`child_process.spawn("node", ["--version"])` is inconsistent

### ISSUE THREAD

**Issue by itssamuelrowe** [vercel/pkg#1320]
I am trying to execute a locally installed Node executable to determine the version.

```js
child_process.spawn("node", ["--version"])
```

When I run my code without using pkg, I get the following standard output as expected:
```
"v16.8.0\n"
```

However, when I run my code as an executable, I get the following standard error output:
```
"Error: Cannot find module '/home/samuel/project/rover/dist/--version'\n" +
    '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n' +
    '    at Function._resolveFilename (pkg/prelude/bootstrap.js:1776:46)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n' +
    '    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)\n' +
    '    at node:internal/main/run_main_module:17:47 {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    '  requireStack: []\n' +
    '}\n'
```

For some reason, Node treats "--version" as if it were a module name rather than an option. I tried invoking "gcc --version", it works as expected in both cases.

 Can somebody please explain why this is happening? Thank you.

**Comment by Daniel-Olivier** [comment]
try `child_process.spawn(process.argv[0], ['--version'])` and `child_process.spawn('node',['--','--version'])`
