### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by Nisthar** [vercel/pkg#1326]
I am able to successfully figure out the assets path that pkg uses after a long time. I had to console log the paths everytime and figure out the path to my assets folder. Now i can bundle assets into my exe and app is running correctly. But the websocket never connects.

The same code without pkg works for the websocket. 

Sorry for the bad english.

**Comment by BlackYuzia** [comment]
You close this issue by reason - resolved?

**Comment by Nisthar** [comment]
> Did you close this issue by reason - resolved?

I resolved it myself. I tried different methods. But i got it fixed now.

**Comment by BlackYuzia** [comment]
Pls, share any methods for fix, if any body have the same troubles they can find that issue and fixes.

**Comment by Nisthar** [comment]
I will post the code sample here maybe someone can explain how it works.

This was my code 
```js
const Fastify = require("fastify");
const fastifyStatic = require("fastify-static");
const log = require("./logger.js");
const fastifyWebsocket = require("fastify-websocket");
const appRoot = require("app-root-path");
const fastify = Fastify({
  logger: log,
});
fastify.register(fastifyWebsocket);
fastify.register(dbPlugin);
fastify.register(fastifyStatic, {
  root: appRoot.resolve("./../client/dist"),
  prefix: "/", 
});
fastify.register(routes);
```
The websocket route was inside the `routes` variable. For some reason, the websocket never connects when i bundle it with pkg.
So i tried replacing the websocket routes directly below the `fastify.register(dbPlugin);` and it started working. I don't know why its not working if i place it inside routes variable.

**Comment by BlackYuzia** [comment]
@Nisthar did that code work without pkg?

**Comment by Nisthar** [comment]
> @Nisthar did that code work without pkg?
> 
> I mean, code before apply fixes.

Yeah it works if i run it without using pkg.
