### ISSUE TITLE
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'args' is invalid. Received 

### ISSUE THREAD

**Issue by KkjusTkk7074** [vercel/pkg#1332]
![Screenshot_2021-10-08-20-31-07-212_com microsoft rdc android](https://user-images.githubusercontent.com/88614346/136595473-530ed237-86d9-49d0-a7b2-d03d83cae3c7.jpg)
How to fix this error....

Full Error:-

(node:8228) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'args' is invalid. Received {
  env: {
    windir: 'C:\\Windows',
    USERPROFILE: 'C:\\Users\\Administrator',
    USERNAME: 'Administrator',
    USERDOMAIN...
    at Object.execFile (child_process.js:294:11)
    at Object.execFile (pkg/prelude/bootstrap.js:1958:30)
    at Object.exec (child_process.js:212:25)
    at exec (pkg/prelude/bootstrap.js:1972:26)
    at C:\snapshot\grabbed\node_modules\tree-kill\index.js:29:9
    at C:\snapshot\grabbed\main.js
    at Array.forEach (<anonymous>)
    at C:\snapshot\grabbed\main.js
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `gae --trace-warnings ...` to show where the warning was created)
(node:8228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FIREguardSPB** [comment]
I have the same problem. And it occurs when trying to kill a child process.

**Comment by FIREguardSPB** [comment]
For myself, I found the following solution - to use "terminate" instead of "tree-kill".
https://www.npmjs.com/package/terminate
