### ISSUE TITLE
Error: spawnSync patch ENOENT

### ISSUE THREAD

**Issue by Matheus8174** [vercel/pkg#1337]
i've been trying to build to a windows 7 starter 32bits and i got this issue 

my pkg config:

`"assets": [
      "**",
      "**"
    ],
    "targets": [
      "node14",
      "x86"
    ],
    "outputPath": "dist",
    "scripts": "build/**/*.js"
  }`

**Comment by phorcys420** [comment]
Install the ``patch`` utility -> https://sourceforge.net/projects/gnuwin32/files/patch/
if you have Chocolatey installed, then you can simply run ``choco install patch`` in an elevated command prompt.

**Comment by rcjiang** [comment]
Add `C:\WINDOWS\system32` to the environment variable `Path`

**Comment by phorcys420** [comment]
> Try to add `C:\WINDOWS\system32` to the environment variable `Path`

No. My solution is the one to use.
Windows' PATH contains the following chain : ``C:\Windows;``**``C:\Windows\System32;``**``C:\Windows\System32\Wbem; C:\Windows\System32\WindowsPowerShell\v1.0`` by default.
+ System32 does not contain any file named `patch.exe`.
You have to install GNU Patch.

**Comment by leeeeeeeee2** [comment]
> 

work, thanks
