### ISSUE TITLE
Getting an error why trying to launch cli tool on any MacOS machine except the one it was built on.

### ISSUE THREAD

**Issue by maxpavlov** [vercel/pkg#1338]
I would like to use pkg as a "package it into a single file cli tool" builder for any platform, to package my nodejs based cli application.

I am able to package for MacOS as well, but when I try to run the packaged file on any other MacOS machine except the one it was packaged on, I get the following error: "tool: can't be opened because Apple can't check if it's for malicious software".
<img width="895" alt="Screenshot 2021-10-15 at 23 23 52" src="https://user-images.githubusercontent.com/669701/137550197-0af4ab3f-30b0-43e6-b580-e6bfff232dee.png">

I do "sign" my packaged cli tool with codesign tool and a valid Application Developer certificate, but I don't yet know how to notarize the pkg-generated file, perhaps that is what I need to be able to run the tool on other machines?

Any suggestions would be much appreciated.

**Comment by gilad-vonage** [comment]
I'm having exactly the same issue.

Would be nice to have a guide on how we should use our certificates and sign the final binary as the usual `codesign -s <identety> -fv /path/to/packaged` isn't working

**Comment by maxpavlov** [comment]
I actually resolved this by packaging my cli tool into an installer, and notarized the installer. When installed, cli tool runs well on target computers.

The process is not a breeze but thing is doable
