### ISSUE TITLE
Error! Cannot read file, ENOENT   node:events

### ISSUE THREAD

**Issue by AdolfRoxler** [vercel/pkg#1340]
This error happens when I install discord.js in node_modules and require it via app.js

Any help?

**Comment by Default-01** [comment]
Does anyone know how to fix this issue?

**Comment by robertsLando** [comment]
As said, pkg doesn't support esm yet

**Comment by Default-01** [comment]
so does it only support CommonJS? if so can I change my project so it does work?

**Comment by robertsLando** [comment]
> so does it only support CommonJS

Yes

**Comment by robertsLando** [comment]
Actually this could also be fixed by #1405
