### ISSUE TITLE
Error no such file or directory, open

### ISSUE THREAD

**Issue by nutzakungz** [vercel/pkg#1346]
I try fix this bug of hour i use devtools  Visual Studio 2019 Developer Command Prompt but no fix this bug 
Error 
```
Error! Error: ENOENT: no such file or directory, open 'C:\Users\nutza\AppData\Local\Temp\pkg.336d76f485351706a5cb69ef\node\out\Release\node.exe'
```

**Comment by tatujan** [comment]
Having same problem on linux machine.  Have anyone found a workaround for this?

**Comment by robertsLando** [comment]
I think that the problem is the `.` after `pkg` that should be a `\` instead. Check dlopen method in bootstrap to see what's going on

**Comment by tatujan** [comment]
No, I don't think that's the issue. There was another issue about ver. 5.4.1 breaking the linux binaries. So I've downgraded to 5.4.0. And that just worked fine.

**Comment by robertsLando** [comment]
Did you tried with 5.5.1?

**Comment by tatujan** [comment]
No, I was not aware 5.5.1 was out. When I did npm install, npm installed 5.4.1. So I just assumed 5.4.1 is the latest version. I'll try with 5.5.1 and share the results.

**Comment by JulioYu** [comment]
I tried with v5.5.1 and got the same error message while building a x86 version of node 14. Is there any update for this issue?

**Comment by stainleebakhla** [comment]
It seems a lot of people are facing similar issue. Reverting to `~5.2.0` solves the issue.
