### ISSUE TITLE
Surprised by terminal window in macos & windows

### ISSUE THREAD

**Issue by richb-hanover** [vercel/pkg#135]
I am really impressed by `pkg` - it seems to do a very finicky task just as described.

I had a pretty easy time building the express-based "hello world" app, and the resulting files actually worked when I double-clicked their icons on the respective desktops.

But I was surprised to see that both macos and win binaries opened a terminal window/console before running the app. Linux did not, though.

Is there a way to avoid the terminal window on the first two OS's? Thanks!

**Comment by CherryDT** [comment]
It would be nice to have a command line flag which sets the subsystem of the EXE file to "GUI" instead of "Console" for Windows.

Not sure how that works in Mac.

**Comment by CanRau** [comment]
not too bad, but i would love to suppress the terminal as well, as i wrote a little blog article scaffolder and people using it might be a little overwhelmed by the terminal, as they're not used to it, a little briefing helps of cause, but hiding it could be even more elegantly as they don't need to close a totally , for them, useless window ;-)

but anyways, i love pkg, so in all cases, thanks for the nice tool!

**Comment by TobiaszCudnik** [comment]
Any known workarounds for this? Im getting the terminal window only on windows while packing a [Carlo app](https://github.com/GoogleChromeLabs/carlo).

**Comment by zoell** [comment]
Any update on this?

**Comment by StiliyanKushev** [comment]
I would also like an update. This is such a great suggestion. I'm sure it won't be much work to implement. Anyways, great tool regardless!

**Comment by ahgsql** [comment]
Creating Web-Based UIs and debugging or setting everything from there. Console window is ugly and there has to be option to disable it.

**Comment by CherryDT** [comment]
Workaround: https://stackoverflow.com/questions/2435816/how-do-i-poke-the-flag-in-a-win32-pe-that-controls-console-window-display/14806704

**Comment by CherryDT** [comment]
I believe to bake this into `pkg` permanently (again, for Windows only - I don't know how it works with Mac), a node patch must be added to the `pkg-fetch` repo to change [this line](https://github.com/nodejs/node/blob/e46c680bf2b211bbd52cf959ca17ee98c7f657f5/deps/uv/common.gypi#L115) to `'SubSystem': 2,` (see [this enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.vcprojectengine.subsystemoption?view=visualstudiosdk-2022)).

**Comment by soonsam123** [comment]
It would be good to have a solution for this

**Comment by joulgs** [comment]
@CherryDT thank you for your solution, use CFF worked for me
