### ISSUE TITLE
Antivirus giving false positives

### ISSUE THREAD

**Issue by KCGD** [vercel/pkg#1350]
I made an executable that takes some parameters and generates a list of random numbers, but when I scanned it in hybrid analysis, it was flaring up some antiviruses, despite the executable not being malware. Is there any way to fix this?

https://www.hybrid-analysis.com/sample/99c020d378e41a46a92a41e6d9071d4cf81fabd0a9b36c1412ffef11b8613fbc

**Comment by jesec** [comment]
Sign your software. 

Node.js runtime can be used to run arbitrary JavaScript software. There is definitely a possibility for a cyber criminal to write a JavaScript malware. AV uses binary similarity detection and other risk factors to decide whether or not to block a program. Code signature is the easiest way to increase the "trust score" of your software.
