### ISSUE TITLE
How set package.js configuration data?

### ISSUE THREAD

**Issue by tufik2** [vercel/pkg#1352]
Hi, I want use pkg in my project and I want to know if is possible support this feature.
Regularly in package.json we can set "type":"module", that give us the posibility to import packages using ES6 specification

Example: 
`import cluster from "cluster";
import {Server} from "./src/vp/Server.js";`

package.json
`{
  "name": "vantage-point-html",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
}`

But when I use> **pkg --no-bytecode --public-packages "*" --public -t node16-win-x64 index.js** and run the .exe file I have the next error: 
`(node:14484) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`
that error is usually because we need to set the type in package.json....
Any idea how solve it?, Thanks....

**Comment by jesec** [comment]
#782
