### ISSUE TITLE
Create a new pkg release with pkg-fetch 3.2.4

### ISSUE THREAD

**Issue by renkei** [vercel/pkg#1354]
Although pkg-fetch 3.2.4 with Node.js 12.22.7, 14.18.1 and 16.12.0 binaries was released on the same day as pkg 5.4.0 it is unfortunately not part of the pkg 5.4.0 release, it still points to pkg-fetch 3.2.3.

@jesec has already updated the package.json to pkg-fetch 3.2.4 on master, could you please create a new pkg release, for example 5.4.1?

**Comment by leerob** [comment]
Done!
