### ISSUE TITLE
npm ERR! could not determine executable to run

### ISSUE THREAD

**Issue by mwt** [vercel/pkg#1355]
Vercel fails when running `vercel dev` with jekyll on Linux. This was encountered inside a GitHub Workspace with jekyll installed through bundler.

~~~sh
Vercel CLI 23.1.2 dev (beta) — https://vercel.com/feedback
> Running Dev Command “bundle exec jekyll serve --watch --port $PORT”
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codespace/.npm/_logs/error.log
~~~

[error.log](https://github.com/vercel/pkg/files/7463096/error.log)
[Gemfile.lock](https://github.com/vercel/pkg/files/7463110/Gemfile.lock.txt)

**Comment by jesec** [comment]
You may want to open the issue in vercel.
