### ISSUE TITLE
PKG is super slow in wsl2 environment

### ISSUE THREAD

**Issue by Hareis** [vercel/pkg#1362]
PKG is super slow in wsl2 environment

I am using wsl2 environment, packaging is super slow
I thought it was a problem with my own computer and laptop, but it was the same slow when I switched to a desktop computer.

I don’t know what factors affect the packing speed of pkg

**Comment by jesec** [comment]
Don't use Windows filesystem/partition in WSL 2. It is bound to be slow, not just for pkg.

**Comment by Hareis** [comment]
> Don't use Windows filesystem/partition in WSL 2. It is bound to be slow, not just for pkg.

ok ,i got it  
thx
