### ISSUE TITLE
No available node version satisfies 'node17'

### ISSUE THREAD

**Issue by jim-king-2000** [vercel/pkg#1364]
See `No available node version satisfies 'node17'` when I type `pkg app.mjs`. How to fix it?

**Comment by jim-king-2000** [comment]
Never use old version. Is it possible to build it myself?

**Comment by jesec** [comment]
No. There is no patch available for Node 17 yet.

**Comment by jim-king-2000** [comment]
Then when would it be ready?

**Comment by jesec** [comment]
I am working on Node 17. If everything goes well, we would have patched binaries available for Node 17 soon. 

Note that support for odd-versions (non-LTS) are not protected by semver, and they could be removed as soon as the next designated LTS (in this case, 18) comes out.

**Comment by jim-king-2000** [comment]
> I am working on Node 17. If everything goes well, we would have patched binaries available for Node 17 soon.
> 
> Note that support for odd-versions (non-LTS) are not protected by semver, and they could be removed as soon as the next designated LTS (in this case, 18) comes out.

Fantastic! Good wish to pkg, the great tool.

By the way, there is another extremely important feature, ESM support, which we expect eagerly.

**Comment by Alex-Roux** [comment]
> Never use old version. Is it possible to build it myself?

FYI Node 17 has been released 2-3 months ago so it may not be widely supported. Node 16 is the current version to this date and is perfectly okay to use.

**Comment by jesec** [comment]
Resolved.
