### ISSUE TITLE
Updated readme for example application, and a question

### ISSUE THREAD

**Issue by richb-hanover** [vercel/pkg#138]
I updated the examples/express/readme.md to provide more detailed instructions for trying out `pkg` and making the demo application work. The new description is at https://github.com/richb-hanover/pkg/blob/master/examples/express/readme.md

1. Is that text substantially correct?

2. I had trouble building the "big three" - Linux, macOS, and Windows. Although I understood that the default would build all three, typing `pkg .` created only a single file `express-example` that's exactly the same size as the `express-example-macos` file generated when I used the `--targets...` option. Am I missing something?

Once the text is good, I'll update any errors and create a PR for these edits.

**Comment by leerob** [comment]
Closing this as stale 🙏 Thank you anyway!
