### ISSUE TITLE
 fs.readdirSync(buffer, { encoding: 'buffer' }) return a string instead of buffer

### ISSUE THREAD

**Issue by daoshenjay** [vercel/pkg#1399]
### What version of pkg are you using?

5.4.1

### What version of Node.js are you using?

12.16.1

### What operating system are you using?

windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node12-win-x64

### Describe the Bug

why i run the exe file,  fs.readdirSync(buffer, { encoding: 'buffer' }) return a string instead of buffer. And i found this log:
`> [debug] prebuild-install failed[E:\NodeWS\MyProjectName\node_modules\fsevents\fsevents.node]:
  Error: spawnSync C:\Program Files\nodejs\node_modules\pkg\node_modules\.bin\prebuild-install ENOENT`

PS: C:\Program Files\nodejs\node_modules\pkg\node_modules\.bin\prebuild-install this file is exsit in my computer.
How could i fix this? Thanks!

### Expected Behavior

I expect fs.readdirSync(buffer, { encoding: 'buffer' }) could return buffer data, and there is no error in pkg package logs.

### To Reproduce

Maybe use fs.readdirSync(buffer, { encoding: 'buffer' }) somewhere.

**Comment by lukaswilkeer** [comment]
Following the api, the fs.readdirSync takes two parameters, and the second is the encoding, not an object with options.

This parameters can be ```utf8``` or ```buffer```, that is what's wrong with your code.

**Comment by daoshenjay** [comment]
@lukaswilkeer Thanks for replay. I've tried like this:
`const list = fs.readdirSync(bufdir, 'buffer')`
But list is string array too.

**Comment by lukaswilkeer** [comment]
I compared against v12, 14 and 16 and the results are the same. Sorry for the mistake on the api, you can set a string with ```utf8``` or a object with the encoding and the withFileTypes option.

On other hand, bundle the package for linux with node v12 works perfectly.

**Comment by daoshenjay** [comment]
@lukaswilkeer Hi, i upload a demo project [here](https://github.com/daoshenjay/DemoEggPkg)
step 1:
`npm install`

step 2:
`npm run pkg-linux `  // linux system
or
`npm run pkg-win`  // windows

step 3:
`cd dist`
`DemoEgg.exe start --daemon`

and you will see the error at "\dist\logs\master-stderr.log":
` [egg-core] load file: C:\snapshot\DemoEggPkg\app\router.js, error: The "list[2]" argument must be an instance of Buffer or Uint8Array. Received type string ('home.js')
    at Function.concat (buffer.js:571:13)
    at onDirRead (C:\snapshot\DemoEggPkg\node_modules\node-dir\lib\paths.js:135:28)
    at onStat (C:\snapshot\DemoEggPkg\node_modules\node-dir\lib\paths.js:154:14)
    at Object.files (C:\snapshot\DemoEggPkg\node_modules\node-dir\lib\paths.js:162:12)
    at C:\snapshot\DemoEggPkg\node_modules\require-context\index.js:17:6
    at Object.<anonymous> (C:\snapshot\DemoEggPkg\app\router.js)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
code: "ERR_INVALID_ARG_TYPE"
pid: 14636
hostname: DESKTOP-O20K12N`

**call stack:**
\app\router.js line 5
  => require-context package
  => node-dir package
  =>\node_modules\node-dir\lib\paths.js  line 153 

could you try this project? Thank you very much!

**Comment by lukaswilkeer** [comment]
You will need to talk with the egg team. The problem occur with a package named node-dir. Bundle with egg he don't works on  windows but works on linux, but alone is another story.

**Comment by daoshenjay** [comment]
@lukaswilkeer  I got it. Thanks!
