### ISSUE TITLE
Executables with target node16-linux-arm64 are broken

### ISSUE THREAD

**Issue by Niek** [vercel/pkg#1400]
### What version of pkg are you using?

5.4.1

### What version of Node.js are you using?

v17.0.1

### What operating system are you using?

macOS

### What CPU architecture are you using?

arm64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux-arm64

### Describe the Bug

Files compiled with target `node16-linux-arm64` are broken - after starting the executable, it quits silently.

### Expected Behavior

It should run normally, like e.g. with the target `node14-linux-arm64`.

### To Reproduce

```bash
$ cat test.js 
console.log('hello world')
$ pkg -t node16-linux-arm64,node14-linux-arm64 test.js
$ ./test-node14
hello world
$ ./test-node16
```

**Comment by yseymour** [comment]
I also see this issue with pkg 5.5.1. Furthermore, going the opposite way (building for `node16-macos-arm64` on Linux ARM64, and running the resulting binary on MacOS Monterey) gives the same result.

**Comment by Niek** [comment]
In addition, cross-building on linux-amd64 targeting linux-arm64  seems to be broken as well.

**Comment by jesec** [comment]
I can confirm the issue with cross compiling for Node 16 binaries.

You may workaround this with `--public-packages "*" --public`. Note that the arguments disable bytecode generation, and, as a result, the source code obfuscation.

Or simply run pkg on a machine that has the same architecture as the target.

**Comment by thanpolas** [comment]
Soooo, what is the current remedy @jesec? Do we wait? Something we can do (use the branch?)

**Comment by jesec** [comment]
It requires a new minor release to change the binaries, which could take a substantial amount of time for me to queue the CI tasks, validate the binaries and reupload them.

I have some other commitments this week, so you will have to wait.

**Comment by thanpolas** [comment]
fwiw, I managed to build for Arm64 using an Arm64 Ubuntu docker image and some scripting.

**Comment by Niek** [comment]
This seems to be fixed in `pkg@5.5.2` / `pkg-fetch@3.2.6`, at least in my tests:
```bash
docker run --rm -it --platform=linux/arm64 node bash -c 'echo "console.log(\"hello world\")" > test.js && npx -y pkg -t node16-linux-arm64,node14-linux-arm64 test.js && ./test-node14; ./test-node16'
hello world
hello world
```

**Comment by jesec** [comment]
This issue only presents when `macos-arm64` is involved, either as the host or the target.

**Comment by GrahamCampbell** [comment]
I think this has been fixed in v5.6.0.

**Comment by Niek** [comment]
I can confirm this is fixed in v5.6.0. However, cross-building (arm64 on x64) is still broken.

**Comment by jesec** [comment]
You may not build for arm64 on x64, unless an emulator has been configured. Please read README.

**Comment by Niek** [comment]
> You may not build for arm64 on x64, unless an emulator has been configured. Please read README.

Oh wow, I didn't think of this. The fix was so simple, added to my GH workflow:
```yaml
- name: Set up QEMU
  uses: docker/setup-qemu-action@v1
  with:
    platforms: arm64
```
Thanks!
