### ISSUE TITLE
Unsupported 16-bit app on win

### ISSUE THREAD

**Issue by storm1er** [vercel/pkg#1414]
### What version of pkg are you using?

5.4.1

### What version of Node.js are you using?

16.13.0

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-win-x64

### Describe the Bug

While building https://gitlab.com/crypto-raider-tools/fight-simulator-cli/-/merge_requests/3 everything is okay

(see https://gitlab.com/crypto-raider-tools/fight-simulator-cli/-/jobs/1816145966, same result locally)

But when executing the binary I'm getting this error message:
![image](https://user-images.githubusercontent.com/9821946/143268841-d9a873d7-6a18-4d6a-92c3-076a812e0e7a.png)

### Expected Behavior

Executable should work

### To Reproduce

Checkout https://gitlab.com/crypto-raider-tools/fight-simulator-cli/-/merge_requests/3

```bash
npm install
npm run all
```

binaries will be in `./bin`

You can test with `./bin/fight-simulator-cli.exe --help`

**Comment by storm1er** [comment]
I should precise, I'm trying to run the executable on win11 x64

**Comment by vicapow** [comment]
what ever ended up being the issue?
