### ISSUE TITLE
The specified module could not be found. (even tho the file exists on the exact path)

### ISSUE THREAD

**Issue by kokarn** [vercel/pkg#1427]
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

16.13.1

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-win-x64

### Describe the Bug

```
Error: The specified module could not be found. 
```
Pops up even tho the file is exactly on that require path

### Expected Behavior

It loads as expected

### To Reproduce

I'm using opencv4nodejs-prebuild and just loading that.

I've added the assets to my pkg config
```
  "pkg": {
    "assets": ["./node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs.node"],
    "targets": [ "node16-win-x64" ]
  }
  ```

This is the full error message
```
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: The specified module could not be found.
C:\Users\kokarn\AppData\Local\Temp\pkg\b10b86575277b74e79b3d109fed58d17fe17deec98ca815bf9ea43d066456a8d\opencv4nodejs-prebuilt\build\Release\opencv4nodejs.node
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\my-project\node_modules\opencv4nodejs-prebuilt\lib\cv.js:11:8)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```
But you can see the file clearly exists
![image](https://user-images.githubusercontent.com/1373940/144684129-1bc6de57-68c0-45f3-a021-9797ef4f12b4.png)

**Comment by robertsLando** [comment]
Assets should be an array of strings

**Comment by kokarn** [comment]
Thanks! I tried that out, but the exact same error pops up I'm afraid.

Also, if the input is malformed, wouldn't that mean that the .node module _wouldn't_ be copied to the temp directory?

**Comment by robertsLando** [comment]
I have no idea, you should try to debug this by adding some logs in dlopen method of bbotstrap. As you shown in your image the file is correctly copied in the folder... the other try you could do is to copy the entire module instead of just the `.node` file in assets:

```
./node_modules/opencv4nodejs-prebuilt/**
```

**Comment by kokarn** [comment]
I will try that, thanks!

It does do some funky runtime loading https://github.com/nut-tree/opencv4nodejs/blob/master/lib/cv.js#L4-L16 but my understanding of the docs is that this should be covered by my assets inclusion?

**Comment by robertsLando** [comment]
>  but my understanding of the docs is that this should be covered by my assets inclusion?

IMO by including the entire folder it could work based on what you linked here, assets cannot correctly guess all the times where a module is, expecially for `.node` files the thing is difficult as we need to copy them from snapshot to a temp directory

**Comment by kokarn** [comment]
Sadly that didn't work either.
Tried to make it as small & easy as possible, so here's how to reproduce.

A different computer this time around, so seems to be 100% reproducible.

Commands:

```
npm i
npx pkg .
failed-build.exe
```

package.json
```
{
  "name": "failed-build",
  "version": "1.0.0",
  "main": "index.js",
  "bin": "index.js",
  "dependencies": {
    "@nut-tree/nut-js": "^1.7.0"
  },
  "pkg": {
    "assets": [
      "./node_modules/opencv4nodejs-prebuilt/**"
    ],
    "targets": [
      "node16-win-x64"
    ]
  }
}
```

index.js
```
const { mouse, Button, Point, keyboard, Key, screen, clipboard, getActiveWindow, getWindows } = require('@nut-tree/nut-js');

console.log('hello world');
```

**Comment by robertsLando** [comment]
@kokarn What I can suggest is to add some log here: https://github.com/vercel/pkg/blob/main/prelude/bootstrap.js#L2063

And do some debugging your own. Unfortunally I have not time for this

**Comment by kokarn** [comment]
Totally understandable that you don't have time to dig deep into this specific issue, always bigger fish to fry.

The same goes for me as well I'm afraid, tried another packager instead that solved it off the bat.

**Comment by maxpavlov** [comment]
There is no point in troubling the dlopen in bootstrap.js.

.node files don't get packed up even if specified as assets. The dlopen throws an error that the file is not found because it is not found. 

Debug actually shows that the .node files are a part of the packed bundle, so the problem, speaking more precisely, is that they don't appear in an unpacked folder structure in /var/folders/z4....

**Comment by cheul123a** [comment]
@kokarn 
which packager did u use? i got same problem

**Comment by kokarn** [comment]
> @kokarn which packager did u use? i got same problem

I ended up using https://github.com/nexe/nexe but it has it's own issue, just not this one :D

**Comment by cheul123a** [comment]
> > @kokarn which packager did u use? i got same problem
> 
> I ended up using https://github.com/nexe/nexe but it has it's own issue, just not this one :D

it works thx! :D

**Comment by y0unjin0h** [comment]
그래서 어떻게 하면 해결할 수 있나요?
