### ISSUE TITLE
How do I pull a dotenv file in as an asset?

### ISSUE THREAD

**Issue by lukeh990** [vercel/pkg#1430]
I need to get some dotenv data I have tried to use assets but it returns undefined if I leave the folder with the .env the asset glob I used is:
```
  "pkg": {
    "assets": ".env",
  }
```
I execute pkg with `pkg .` and my bin entry is setup as is.
```
  "bin": {
    "bot":"./src/bot.js"
  }
```

**Comment by JackGou1029** [comment]
Same problem, any solution?

**Comment by tomdotenv** [comment]
I managed to get it to work by doing two things:
1. I added the reference to my .env files in the assets array as follows (I have multiple .envs):
`"pkg": {
    "scripts": [],
    "assets": [
      ".env*",
      "node_modules/castv2/**/*"
    ]
  }`

2. I used the variable `__dirname` as basepath when accessing the .env file in my project.

As described [here](https://github.com/vercel/pkg#snapshot-filesystem), this is what happens: 

> During packaging process pkg collects project files and places them into executable. It is called a snapshot. At run time the packaged application has access to snapshot filesystem where all that files reside.

 ... 

> Hence, in order to make use of a file collected at packaging time (require a javascript file or serve an asset) you should take __filename, __dirname, process.pkg.defaultEntrypoint or require.main.filename as a base for your path calculations.


Therefore you should be able to access any imported asset by using the variable `__dirname` as the basepath. For your .env file it should be something like `__dirname + ".env"`.

Hope this helps.

**Comment by JackGou1029** [comment]
It works ! Many thanks!!

**Comment by JackGou1029** [comment]
> I managed to get it to work by doing two things:
> 
> 1. I added the reference to my .env files in the assets array as follows (I have multiple .envs):
>    `"pkg": { "scripts": [], "assets": [ ".env*", "node_modules/castv2/**/*" ]   }`
> 2. I used the variable `__dirname` as basepath when accessing the .env file in my project.
> 
> As described [here](https://github.com/vercel/pkg#snapshot-filesystem), this is what happens:
> 
> > During packaging process pkg collects project files and places them into executable. It is called a snapshot. At run time the packaged application has access to snapshot filesystem where all that files reside.
> 
> ...
> 
> > Hence, in order to make use of a file collected at packaging time (require a javascript file or serve an asset) you should take __filename, __dirname, process.pkg.defaultEntrypoint or require.main.filename as a base for your path calculations.
> 
> Therefore you should be able to access any imported asset by using the variable `__dirname` as the basepath. For your .env file it should be something like `__dirname + ".env"`.
> 
> Hope this helps.

It works! Many thanks!
