### ISSUE TITLE
worker thread requires not found

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [vercel/pkg#1431]
### What version of pkg are you using?

latest

### What version of Node.js are you using?

14

### What operating system are you using?

Win

### What CPU architecture are you using?

64

### What Node versions, OSs and CPU architectures are you building for?

win

### Describe the Bug

I'm using worker threads in my application and the worker files import various modules.
When running the binary node complains that it can't find the modules.

How do I make pkg detect such imports? 

### Expected Behavior

-

### To Reproduce

-

**Comment by hackermondev** [comment]
How did you fix this? @hp8wvvvgnj6asjm7
