### ISSUE TITLE
Including .node modules

### ISSUE THREAD

**Issue by ForbiddenEra** [vercel/pkg#1433]
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

10.22+

### What operating system are you using?

Linux

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node10-linux-x64, node14-linux-x64

### Describe the Bug

When compiling an app that includes a module that has .node files, I get:

```
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → /snapshot/gpumgr/src/node_modules/node-expat/build/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/build/Debug/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/build/Release/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/out/Debug/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/Debug/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/out/Release/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/Release/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/build/default/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/compiled/10.24.1/linux/x64/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/addon-build/release/install-root/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/addon-build/debug/install-root/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/addon-build/default/install-root/node_expat.node
 → /snapshot/gpumgr/src/node_modules/node-expat/lib/binding/node-v64-linux-x64/node_expat.node
    at bindings (/snapshot/gpumgr/src/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/snapshot/gpumgr/src/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:25:18)

```

I've tried adding that folder with 'scripts' and 'assets' with no luck, am I missing something?

### Expected Behavior

Expected to package up any npm modules regardless of their type and include them no differently than if I ran it without compiling

### To Reproduce

I'm specifically using the xml2json npm module, which includes other modules such as expat which is the one causing the issue it seems.

If I copy node_modules to the same dir as the executale, it works.. just doesn't seem to be packaging them inside the executable :(

**Comment by ForbiddenEra** [comment]
I guess this was my own issue;
```
  "pkg" : {
        "assets": "src/**/*"
  }
```
seems to have helped; not sure if this is the most appropriate fix but it works?

**Comment by robertsLando** [comment]
pkg does it's best to guess what needs to be placed inside the executable, to be sure everything is added you could help him by including in assets and scripts the things needed by your application

**Comment by maxpavlov** [comment]
> I guess this was my own issue;
> 
> ```
>   "pkg" : {
>         "assets": "src/**/*"
>   }
> ```
> 
> seems to have helped; not sure if this is the most appropriate fix but it works?

Yeah, but most likely you had entire node_modules included which was in your src after npm install or something. It got fixes (I am happy for you, for me adding required folders to assets doesn't help), but at which cost of the package size? It has probably grown significantly.

**Comment by ForbiddenEra** [comment]
It didn't seem to grow the package very much. I suppose including the full source is kind of silly and I actually think I fixed the issue completely.

`npm` wasn't happy with node_modules being under `./src/` for some reason but with some restructuring I no longer need to include the asset.

My current app, previously, compiled to ~39,445,965 bytes w/out compression and ~34,155,458 with compression.

Now that it's fixed, the executable is 33,595,477 w/out compression and 32,938,835 bytes with. `node_modules` was ~7mb.

`console.log("Hello, World!");` compiled to ~32mb for me to begin with..? Enabling compression only saved ~500 bytes. This actually seemed quite large to me, and I was considering making a post about it.

If I then zip that file, it's ~13,864,100 (deflated 59%), ~13,863,070 for gzip and ~12,716,044 for bzip2 (67.7% smaller).

So, there may be possibility for more compression to be had? I'm not sure how you're compressing things, is it just the content/bytecode on the way in..?

Maybe we could wrap the final executable in some sort of self-extracting wrapper..?
