### ISSUE TITLE
Warning Entry 'main' not found in %1

### ISSUE THREAD

**Issue by cekvenich2** [vercel/pkg#1444]
### What version of pkg are you using?

latest

### What version of Node.js are you using?

latest LTS (16)

### What operating system are you using?

linux

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux-x64

### Describe the Bug

root@vultr:~/cur# pkg -t node16-linux-x64 datVService.js
> pkg@5.4.0
> Warning Entry 'main' not found in %1
  %1: /root/proj/ani-software/datS/node_modules/lmdb/package.json
  %2: /root/proj/ani-software/datS/lib/tableFile.js
root@vultr:~/cur# 

### Expected Behavior

compile

### To Reproduce

try to build.

**Comment by robertsLando** [comment]
Add this to your package.json (you need to edit it based on your application)
```
"bin": {
    "app": "path/to/entrypoint.js"
  },
```

**Comment by cekvenich2** [comment]
@robertsLando 
I did that. Samer error.

**Comment by cekvenich2** [comment]
It seems a problem with some packages, lmdb in this case. When I do hello world it works. But if I required lmdb it has that same error. Here is the code I try to compile:
const { open } = require('lmdb')

console.log('oh hi')

let myDB = open({
	path: 'delme'
})


Help?

**Comment by robertsLando** [comment]
Sorry, no clue
