### ISSUE TITLE
Cross-CPU compilation (kind of). ARM. Raspberry Pi

### ISSUE THREAD

**Issue by Pupix** [vercel/pkg#145]
Hello!

I am trying to automate the building and deploying process from my machine to a PI. 

Currently I am developing on Ubuntu, deploying the source code to Raspberry and compiling there, since CPU cross compilation is not available.

Every build takes somewhere between 30 to 60 seconds, even for a single change I have to rebuild everything from the ground up.

Is there any way to make this process faster? Perhaps incremental builds ? Monkey patching on top of an already existing binary?

Thanks!

**Comment by igorklopov** [comment]
Since pkg@4 there is one way. But you will need to ship the sources of your application inside executable. I mean machine-code-only feature will not work because Ubuntu-x64 can not generate ARM machine code. So, please wait. I will try to figure out the setup.

**Comment by igorklopov** [comment]
There is a way to cross-compile to ARM cpu in `pkg@4.1.1`. Instructions:
* Open `examples/express`. Open `package.json`
* Pay attention to `license` field and it's value. It must be set to open source to make `pkg` include the source code of all files of the package into executable.
* Compile the project with `pkg package.json -t node8-linux-armv6 --no-bytecode`
* The resulting executable will work on Raspberry Pi.
If there are any compile-time or run-time errors with your project, post them here.

**Comment by Pupix** [comment]
After updating to the latest version, any build results in:
```
pkg@4.1.1
> Fetching base Node.js binaries to: ~/.pkg-cache
  fetched-v8.0.0-linux-x64     [                    ] 0%> Asset 'v2.3/uploaded-v2.3-node-v8.0.0-linux-x64' not found by direct link
> Error! AssertionError [ERR_ASSERTION]: false == true
    at Log.enableProgress (/home/USER/.npm-global/lib/node_modules/pkg/node_modules/pkg-fetch/lib-es5/log.js:103:28)
    at GitHub.downloadUrl (/home/USER/.npm-global/lib/node_modules/pkg/node_modules/pkg-fetch/lib-es5/github.js:173:16)
    at Cloud._callee3$ (/home/USER/.npm-global/lib/node_modules/pkg/node_modules/pkg-fetch/lib-es5/cloud.js:279:32)
    at tryCatch (/home/USER/.npm-global/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/USER/.npm-global/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/USER/.npm-global/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/USER/.npm-global/lib/node_modules/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/USER/.npm-global/lib/node_modules/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by Pupix** [comment]
It only happens when the binary is not found and it tries to download it from github.

**Comment by Pupix** [comment]
Downloaded and renamed the binaries manually.

Now whenever I run `pkg package.json -t node8-linux-armv6 --no-bytecode` I get the following error:
```
 Error! --no-bytecode and no source breaks final executable
```

**Comment by Pupix** [comment]
I can confirm that the express example works. The problem might be somewhere else and it silently fails without setting the content.

**Comment by igorklopov** [comment]
`STORE_BLOB` - what file in what package has only `STORE_BLOB`? Your project or npm dependency?

**Comment by Pupix** [comment]
It is my `bin` file.

```
{ '0': true,
  '3': 
   Stats {
     dev: 64512,
     mode: 33204,
     nlink: 1,
     uid: 1000,
     gid: 1000,
     rdev: 0,
     blksize: 4096,
     ino: 393274,
     size: 7388,
     blocks: 16,
     atimeMs: 1498575401147.5488,
     mtimeMs: 1498575394763.496,
     ctimeMs: 1498575394767.496,
     birthtimeMs: 1498575394767.496,
     atime: 2017-06-27T14:56:41.148Z,
     mtime: 2017-06-27T14:56:34.763Z,
     ctime: 2017-06-27T14:56:34.767Z,
     birthtime: 2017-06-27T14:56:34.767Z },
  file: '/var/www/bff847b8c0f04ba9/server.bin.js',
  marker: 
   { config: 
      { name: 'bff847b8c0f04ba9',
        description: 'experiments',
        private: true,
        license: 'MIT',
        version: '1.0.0',
        bin: 'server.bin.js',
        main: 'server.js',
        dependencies: [Object],
        scripts: [Object],
        pkg: [Object] },
     base: '/var/www/bff847b8c0f04ba9',
     toplevel: true,
     permissive: false,
     activated: true },
  body: '...' }
```

The difference between `server.js` and `server.bin.js` is that one uses `__dirname` and the other used `process.cwd/process.execPath`

**Comment by igorklopov** [comment]
@Pupix good job! My plan was to discover packages with non-`permissive` setup, but you already did that. You can patch `pkg` and make `isPermissive` have `return true;` as it's first line. Then you will probably compile successfully. However, this way you disclose the source of your private/non-published npm packages. Probably it is not what users expect (they can prefer building from RPi host), so i hesitate introducing any such flag.

**Comment by Pupix** [comment]
I did just that, and it's finally building on ubuntu and running on RPi without any troubles. Thanks!

**Comment by jnj16180340** [comment]
I've enjoyed some success in cross-compiling kernel modules w/ `qemu`, following [this guide from resin.io](https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/). I'm currently looking into what changes were made on qemu since 2015, maybe it could be a route to cross-compilation?

**Comment by jflayhart** [comment]
Mine just hangs for HOURS: 
<img width="762" alt="screen shot 2018-02-22 at 6 50 12 pm" src="https://user-images.githubusercontent.com/6808172/36572426-59b04184-1801-11e8-9ba8-85e27f5193ef.png">

**Comment by jflayhart** [comment]
@igorklopov, in fact, I can't even get express example to run on the Pi using node7:
```
> pkg . -o startServer --no-bytecode

> pkg@4.3.0
> Error! No available node version satisfies 'node7'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! express-example@ dist: `pkg . -o startServer --no-bytecode`
npm ERR! Exit status 2
```

And then while setting target to node8+ it just hangs on the "compiling node from sources" step. I would REALLY love for pkg to work here, it potentially would fulfill a very big need here, but it doesn't work right now, which is disappointing. It compiles fine on my Mac using node8-macos target.

**Comment by jflayhart** [comment]
UPDATE

So when running on Pi or through Docker QEMU, it turns out the `make` step that I thought was hanging was actually working, but it takes 22 hours to compile!! What can I do to make sure I don't have to compile everything from node.js source because it takes 20+ hours!

**Comment by jnj16180340** [comment]
@jflayhart For me,
`pkg . --public -b -d --targets node8-linux-armv7`
appeared to hang but finished ~overnight. arm64/armv8 or whatever it's called here took about the same. Absolutely no idea what the bottleneck is-- Doesn't look like cpu, ram nor disk

**Comment by jflayhart** [comment]
My assumption is that the bottleneck has to do with downloading and compiling node from source, which takes time "over the wire". What makes no sense to me is that, if the same version of node exists locally, then use that. Can we make that happen? I'd love to help with a PR, but I don't know where to start with binary packaging.

**Comment by wilmardo** [comment]
I am hitting this problem as wel trying to build a multiarch Docker image which uses the Docker QEMU trick from [multiarch/alpine](https://hub.docker.com/r/multiarch/alpine).
See the repo https://github.com/LANsible/docker-zigbee2mqtt

This is reproducible by:

```
git clone https://github.com/LANsible/docker-zigbee2mqtt.git
cd docker-zigbee2mqtt
docker run --rm --privileged multiarch/qemu-user-static:register --reset
docker build . --build-arg ARCH=arm64 --tag test --no-cache
```

@igorklopov

**Comment by wilmardo** [comment]
After a whole night leaving it with the --debug flag this is the result:

```
Step 8/17 : RUN if [ "${ARCH}" = "x86_64" ]; then       pkg --debug --targets node10-alpine-x64 --options expose-gc --output zigbee2mqtt index.js;     elif [ "${ARCH}" = "aarch64" ]; then       pkg --debug --targets node10-alpine-arm64 --options expose-gc --output zigbee2mqtt index.js;     fi;
 ---> Running in 45a6200ae1f8
> pkg@4.4.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-alpine-arm64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-alpine-arm64"}
> Building base binary from source:
  built-v10.15.3-alpine-arm64
> Cloning Node.js repository from GitHub...

> Checking out v10.15.3
> Applying patches
> Compiling Node.js from sources...

> Error! Error: spawn paxctl ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by wilmardo** [comment]
This seems an issue with arm64. Now using Drone CI to build on native arm64 and I am seeing the same error, only way faster :)
https://cloud.drone.io/LANsible/docker-zigbee2mqtt/8/2/2

```
Step 8/21 : RUN if [ "${ARCH}" = "amd64" ]; then pkg --targets node10-alpine-x64 --options expose-gc --output zigbee2mqtt index.js; elif [ "${ARCH}" = "arm64" ]; then pkg --targets node10-alpine-arm64 --options expose-gc --output zigbee2mqtt index.js; fi;
---> Running in 8047bf383dd9
> pkg@4.4.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
> Warning Cannot resolve '`object-assign-deep`'
/zigbee2mqtt/lib/util/settings.js
Dynamic require may fail at run time, because the requested file
is unknown at compilation time and not included into executable.
Use a string literal as an argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option.
internal/child_process.js:366
throw errnoException(err, 'spawn');
^
Error: spawn Unknown system error -8
at ChildProcess.spawn (internal/child_process.js:366:11)
at spawn (child_process.js:551:9)
at fabricate (/usr/lib/node_modules/pkg/lib-es5/fabricator.js:64:54)
at fabricateTwice (/usr/lib/node_modules/pkg/lib-es5/fabricator.js:138:3)
at MultiStream.cb [as _queue] (/usr/lib/node_modules/pkg/lib-es5/producer.js:182:53)
at MultiStream._next (/usr/lib/node_modules/pkg/node_modules/multistream/index.js:73:10)
at Meter.onEnd (/usr/lib/node_modules/pkg/node_modules/multistream/index.js:120:10)
at Object.onceWrapper (events.js:286:20)
at Meter.emit (events.js:198:13)
at endReadableNT (_stream_readable.js:1129:12)
The command '/bin/sh -c if [ "${ARCH}" = "amd64" ]; then pkg --targets node10-alpine-x64 --options expose-gc --output zigbee2mqtt index.js; elif [ "${ARCH}" = "arm64" ]; then pkg --targets node10-alpine-arm64 --options expose-gc --output zigbee2mqtt index.js; fi;' returned a non-zero code: 1
time="2019-07-11T06:03:40Z" level=fatal msg="exit status 1" 
```

**Comment by wilmardo** [comment]
Some further Googling and I came across this issue:
https://github.com/brenden/node-webshot/issues/192

Where @dsagal states:
> One reason this error may happen is if you spawn() is trying to run a non-Linux binary. E.g. if you package files from a Mac into your Docker container, and they include a native binary.

Could this be the case @igorklopov?

**Comment by Muzzamil1** [comment]
Hi @jflayhart! I am facing the same problem.
Did you find the solution?
![PKG problem](https://user-images.githubusercontent.com/53085438/64470893-9eefe480-d163-11e9-8348-3d79fc8c0075.PNG)

**Comment by corey-mitchell** [comment]
@jflayhart @Muzzamil1 did either of you find a solution to this? I'm experiencing the same issue.

**Comment by Muzzamil1** [comment]
Hi @corey-mitchell  This might be helpful
node10 Binary for Armv6 = https://github.com/zeit/pkg/issues/784#issuecomment-563171218
and https://github.com/robertsLando/pkg-binaries
