### ISSUE TITLE
Unable to use 'stream/web' with pkg

### ISSUE THREAD

**Issue by PeterTrotter** [vercel/pkg#1451]
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

16.13.1

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16.13 linux-x64

### Describe the Bug

Using node's Web Streams API causes pkg to fail.

This happened for us when we included undici as a dependency.

The minimum example below does not reference undici at all but in the actual project the only difference between working and not working was the inclusion of undici which uses the Web Streams API.

### Expected Behavior

pkg should terminate successfully as Web Streams API is from node as of 16.5

### To Reproduce

index.js
````javascript
const { ReadableStream } = require('stream/web');

console.log(!!ReadableStream);
````
package.json
````JSON
{
  "name": "pkg-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "bin": "./index.js",
  "pkg": {
      "targets": [
          "node16.13-linux-x64"
      ],
      "outputPath": "dist"
  },
  "devDependencies": {
    "pkg": "^5.5.1"
  }
}
````
After install `npx pkg . --debug` returns:
````
> pkg@5.5.1
> [debug] Bytecode of {pathToDir}/pkg-test/index.js is added to queue.
> [debug] Content of {pathToDir}/pkg-test/package.json is added to queue.
> [debug] Stat info of {pathToDir}/pkg-test/index.js is added to queue.
> [debug] Bytecode of stream/web is added to queue. It was required from {pathToDir}/pkg-test/index.js
> [debug] Stat info of {pathToDir}/pkg-test/package.json is added to queue.
> [debug] Directory {pathToDir}/pkg-test is added to queue.
> [debug] Stat info of stream/web is added to queue.
> Error! Cannot read file, ENOENT
  stream/web
> Error! ENOENT: no such file or directory, open 'stream/web'
````

**Comment by robertsLando** [comment]
It may be that resolve actually try top resolve `stream/web` as a path instead of a module, I suggest you to try require it using `require('stream').web`

**Comment by PeterTrotter** [comment]
Thanks @robertsLando , that does make the minimal example I posted work.

Unfortunately that won't actually help with using libraries (such as `undici`) where I may not be able to easily change the way import/require is handled.

Should top resolving `stream/web` as a path instead of a module be considered a bug for `pkg` or should I raise this with the `undici` team as something which should be changed?

**Comment by robertsLando** [comment]
You can actually fix this using patches, add this to package.json

```json
"pkg": {
... // assets, scripts if needed
"patches": {
			"./node_modules/undici/...": ["require('stream/web')", "require('stream').web"],
		}
}
```

Change `./node_modules/undici/...` with the path to the file that you need to patch

**Comment by PeterTrotter** [comment]
I've added the patches to `undici` and the build is back on track which is great - thank you.
````JSON
	"pkg": {
		...
		"patches": {
			"./node_modules/undici/lib/fetch/body.js": ["require('stream/web')", "require('stream').web"],
			"./node_modules/undici/lib/core/util.js": ["require('stream/web')", "require('stream').web"],
			"./node_modules/undici/lib/fetch/request.js": ["require('stream/web')", "require('stream').web"],
			"./node_modules/undici/lib/fetch/index.js": ["require('stream/web')", "require('stream').web"]
		}
	},
````
Is this something that should be fixed in `pkg` or `undici` longer term?

**Comment by robertsLando** [comment]
> Is this something that should be fixed in pkg or undici longer term?

I think this will be automatically solved on pkg side once we add esm modules support. The problem is with `resolve` module that doesn't support latest `require` syntax and also it doesn't work with `import`

**Comment by peterp** [comment]
@PeterTrotter I've run into this as well, but I'm unable to fix the issue with the "patches" section above. I can't determine: a) the module that's causing the problem, and
b) how the patches are resolved (I'm using a monorepo.)

**Comment by peterp** [comment]
Does "patches" have documentation?

**Comment by PeterTrotter** [comment]
Sorry @peterp I took the suggestion from robertsLando and made assumptions about how it would work.

Looks like you had a good result though :smile:

**Comment by peterp** [comment]
No worries, thanks for the help you two, I'll happily report what I discover here for others.
