### ISSUE TITLE
Pkg not supporting AppDynamics Node js Agent 

### ISSUE THREAD

**Issue by CrazyMonkk** [vercel/pkg#1460]
### What version of pkg are you using?

5.3.1

### What version of Node.js are you using?

14.15.5

### What operating system are you using?

Windows

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

node14-win-arm64

### Describe the Bug

I am integrating my Node js application with Appdynamics [docs](https://docs.appdynamics.com/21.12/en/application-monitoring/install-app-server-agents/node-js-agent)

Before that am using pkg to bundle my node js application and making it a windows executable.

So when I try the run the application I am getting the below error

![image](https://user-images.githubusercontent.com/93310574/147666805-9839fbc2-593d-4cb8-8f9c-19096f6b63ad.png)

When am trying to run the application without packing, then am not facing any issue and am able to receive the metrics in Appdynamics dashboard perfectly

So I think this has something to do with pkg packaging

### Expected Behavior

Should work like when source code is not packaged with pkg

### To Reproduce

Create a sample node js application

npm install appdynamics@21.4.0

Pacakage it with pkg

Now run the executable

**Comment by robertsLando** [comment]
Try using latest

**Comment by CrazyMonkk** [comment]
@robertsLando  even tried with latest version but still no luck

**Comment by robertsLando** [comment]
add `node_modules/appdynamics/**` to pkg assets

**Comment by CrazyMonkk** [comment]
hi added in package.json

`"pkg": {
    "assets": ["node_modules/appdynamics/**", "node_modules/appdynamics-libagent-napi/**", "node_modules/appdynamics-native/**", "node_modules/appdynamics-protobuf/**", "node_modules/appdynamics-zmq/**"]
  }`

but still no luck...facing the same issue

**Comment by robertsLando** [comment]
You should check where that required file is required and try to fix it your own, I cannot help anymore here I'm sorry

**Comment by CrazyMonkk** [comment]
@robertsLando  any suggestion on  how to debug on this....coz I can do nothing when exe is generated

**Comment by CrazyMonkk** [comment]
@robertsLando  ran **pkg package.json --d** and came up with more log...can you please look into this and help me out

![image](https://user-images.githubusercontent.com/93310574/148045845-963368bf-1dcd-4ac5-90a2-2bf93bb21225.png)

**Comment by robertsLando** [comment]
@CrazyMonkk you shold check what's the missing `.node` file that is not mapped into the snapshot
