### ISSUE TITLE
native addone load fail on centos with pkg@5.5.1 and @5.4.1 

### ISSUE THREAD

**Issue by yu-tou** [vercel/pkg#1466]
### What version of pkg are you using?

5.5.1 & 5.4.1

### What version of Node.js are you using?

v16.11.1

### What operating system are you using?

macOS

### What CPU architecture are you using?

 Apple M1

### What Node versions, OSs and CPU architectures are you building for?

node16-linux-x64

### Describe the Bug

i build a nodejs project with prisma query engine, it's a Native addons for nodejs like `node_modules/.prisma/client/libquery_engine-rhel-openssl-1.1.x.so.node`

the pack commend is 

```bash
pkg package.json --out-path bin/ --targets node16-linux-x64   --public --public-packages '*' --debug
``` 
when i build a pkg binary file，i run is in  ubuntu , it's functioning normally。

but in some centos system , will throw error .

system version: 

```
Linux xxx 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Wed Sep 15 15:39:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
the error info:

```
spawn /snapshot/xxx/node_modules/.prisma/client/query-engine-rhel-openssl-1.1.x ENOENT
```

when i  run `DEBUG_PKG=1 xxxx`, i can find the file in file list.

cd /tmp/pkg/xxx , only can see .prisma/client folder, but have no file.

but in ubuntu, i can see native addone files.

this happen in  pkg@5.5.1 and pkg@5.4.1, when is use 5.3.1 ,it's all functioning normally, have no error.

### Expected Behavior

load native addon normally

### To Reproduce

i build a nodejs project with prisma query engine, it's a Native addons for nodejs like `node_modules/.prisma/client/libquery_engine-rhel-openssl-1.1.x.so.node`

the pack commend is 

```bash
pkg package.json --out-path bin/ --targets node16-linux-x64   --public --public-packages '*' --debug
``` 
when i build a pkg binary file，i run is in  ubuntu , it's functioning normally。

but in some centos system , will throw error .

system version: 

```
Linux xxx 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Wed Sep 15 15:39:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
the error info:

```
spawn /snapshot/xxx/node_modules/.prisma/client/query-engine-rhel-openssl-1.1.x ENOENT
```

when i  run `DEBUG_PKG=1 xxxx`, i can find the file in file list.

cd /tmp/pkg/xxx , only can see .prisma/client folder, but have no file.

but in ubuntu, i can see native addone files.

this happen in  pkg@5.5.1 and pkg@5.4.1, when is use 5.3.1 ,it's all functioning normally, have no error.

**Comment by jesec** [comment]
Ubuntu usually has a higher version GNU C Library (glibc). The binary linked with higher version glibc can't be used on systems with lower version glibc. To ensure best compatibility, you should compile native addons on systems with lower version glibc.
