### ISSUE TITLE
Binary runs on host’s machine but aren’t runnable on guest’s machine

### ISSUE THREAD

**Issue by keinsell** [vercel/pkg#1473]
### What version of pkg are you using?

`5.2.0` - `5.5.1`

### What version of Node.js are you using?

`12.22.9`

### What operating system are you using?

`macOS`

### What CPU architecture are you using?

`x86_64`

### What Node versions, OSs and CPU architectures are you building for?

`node-macos-latest`, `node-win-latest`

### Describe the Bug

`pkg` creates a package with native bindings (as it should) but sadly when I take a created binary and move it to another machine with the same operating system and `node` version - it doesn't work because it doesn't find a native module file which is stored in system's home instead directory where the binary is.

```
❯ yarn build:pkg
> pkg@5.5.1
compression:  Brotli
prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=win32)
prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=linux)
❯ ./dist/pkg/typecraft-macos
$2b$05$xdRXV/OW6yLjSa.3ui6kIOQCBJNYRBIhToUAVMq5qHstDYqzCRSbe
```

CI-generated package returns following error.

```
❯ ./typecraft-macos
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: dlopen(/var/folders/l5/h496nf451jn0s0sby600v1q40000gn/T/pkg/f3abe3f652cbae3169dcf4bee342439bd68c6003d1d6aa9b217d4610fe57bb66/bcrypt/lib/binding/napi-v3/bcrypt_lib.node, 0x0001): tried: '/var/folders/l5/h496nf451jn0s0sby600v1q40000gn/T/pkg/f3abe3f652cbae3169dcf4bee342439bd68c6003d1d6aa9b217d4610fe57bb66/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' (not a mach-o file), '/usr/local/lib/bcrypt_lib.node' (no such file), '/usr/lib/bcrypt_lib.node' (no such file), '/private/var/folders/l5/h496nf451jn0s0sby600v1q40000gn/T/pkg/f3abe3f652cbae3169dcf4bee342439bd68c6003d1d6aa9b217d4610fe57bb66/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' (not a mach-o file), '/usr/local/lib/bcrypt_lib.node' (no such file), '/usr/lib/bcrypt_lib.node' (no such file)
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/typecraft/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

### Expected Behavior

Binary created with `pkg` should runnable on host's machine and as well somebody's other machine (if ex. I build a binary in CI, I want to download it and run it on my computer).

```
❯ ./typecraft-macos
$2b$05$xdRXV/OW6yLjSa.3ui6kIOQCBJNYRBIhToUAVMq5qHstDYqzCRSbe
```

### To Reproduce

- Check https://github.com/keinsell/typecraft
- Download artifacts from CircleCI/GithubCI
- Check if they are running well (no error output)
- Clone [actual](https://github.com/keinsell/typecraft) repository
- Install repository using `yarn`
- Build binary packages using `yarn build:pkg`
- Check the package for your OS and its output (`dist/pkg`)

**Comment by robertsLando** [comment]
@keinsell You should try to add reequired addons as assets in package.json

**Comment by keinsell** [comment]
> @keinsell You should try to add required addons as assets in package.json

I had everything under `pkg.assets` in my `package.json` but it doesn't have any effect at all so I've decided to try explicit requiring inside my script. It has the same effect afaik.

```ts
import bcrypt from 'bcrypt'
import path from 'path'

require('bcrypt/lib/binding/napi-v3/bcrypt_lib.node')

export function main() {
	const salt = bcrypt.genSaltSync(5)
	const hash = bcrypt.hashSync('password', salt)
	console.log(hash)
	return hash
}

main()
```

**Comment by jesec** [comment]
The message is clear:

```
prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=win32)
prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=linux)
```

You cannot compile native addons for macOS on Linux. Use a macOS machine or provide the prebuilt native modules.

**Comment by keinsell** [comment]
> The message is clear:
> 
> ```
> prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=darwin)
> prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=win32)
> prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=linux)
> ```
> 
> You cannot compile native addons for macOS or Windows on Linux. Use the macOS machine and Windows machine respectively. Otherwise, provide the prebuilt native modules.

Thanks for the response mate, I'll prepare a matrix build in my CI for `pkg` and we'll see what will happen (I was using Linux at my CI, where I'm using OSX so it makes sense to me).

**Comment by keinsell** [comment]
> The message is clear:
> 
> ```
> prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=darwin)
> prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=win32)
> prebuild-install WARN install No prebuilt binaries found (target=v16.13.0 runtime=node arch=x64 libc= platform=linux)
> ```
> 
> You cannot compile native addons for macOS or Windows on Linux. Use the macOS machine and Windows machine respectively. Otherwise, provide the prebuilt native modules.

Okay, this doesn't make sense for me actually. I prepared the package on a Windows machine, and it's still doesn't work. In fact, I no longer get `prebuild-install WARN` but the package doesn't work. I've set up a `caxa` build for additional testing and it seems just `pkg` has a problem with the native module. I can try specifying `.node` in `assets` but I do not really get how to do that, do I specify a path like `node_modules/bcrypt/<path_to_binary>` or more like `bcrypt/...`. I'm so confused right now.

https://github.com/keinsell/typecraft/actions/runs/1695913878
