### ISSUE TITLE
config requires license field

### ISSUE THREAD

**Issue by AzazelloB** [vercel/pkg#1485]
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

16.13.1

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

default

### Describe the Bug

selenium-webdriver package started failing on el.getAttribute('href') call with error 
![image](https://user-images.githubusercontent.com/43464264/150366762-1bd8897a-8b88-4f2e-9175-2821a1823613.png)

This is only the case for packaged version. If you run code with node everything works as expected. This started happening after I started using config file instead of `pkg .` command. After debugging I figured out that config file needs "license" field set to one of the public licenses. Probably has something to do with this function pkg/lib-es5/walker.js isPublic.

I would like to have `--config` flag better documented. As of right know it's not clear how it should look like.

### Expected Behavior

Expected everything to work and not throw such undebuggable errors.

### To Reproduce

Don't know. My project is private.

**Comment by jesec** [comment]
If there is no license or the license is proprietary, `pkg` generates the bytecodes to obfuscate the sources. That may not work well with certain programs. You should add `--public` flag if that's the case.
