### ISSUE TITLE
Executable will not run on Arm64 rpi

### ISSUE THREAD

**Issue by thanpolas** [vercel/pkg#1486]
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

16.12.0

### What operating system are you using?

MacOS 12.1

### What CPU architecture are you using?

Apple M1

### What Node versions, OSs and CPU architectures are you building for?

Node v16, ARM64, Ubuntu

### Describe the Bug

I am building for the Raspberry Pi 4 Ubuntu Server edition with Arm64 architecture:

```
uname -a
Linux ubuntu 5.13.0-1008-raspi #9-Ubuntu SMP PREEMPT Wed Sep 29 08:27:44 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

My program is:

```js
console.log('hello world');
```

### Expected Behavior

I would expect, the produced binary, to echo "hello world". Instead it does nothing, no error, just exits silently.

### To Reproduce

create "test.js" with "console.log('hello world');"

Run pkg:

```
pkg -t node16-linux-arm64 test.js
```

copy the file to the target machine and run.

**Comment by jesec** [comment]
See https://github.com/vercel/pkg/issues/1400#issuecomment-1012686078. 

This only happens when Apple Silicon Mac was involved.

**Comment by thanpolas** [comment]
closing this and moving to #1400
