### ISSUE TITLE
I using Windows , how to building for linux or linuxstatic?

### ISSUE THREAD

**Issue by feijihong** [vercel/pkg#1489]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

v17.3.1

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node10-linuxstatic-armv7 && node10-linux-arm64

### Describe the Bug

![image](https://user-images.githubusercontent.com/27736975/150628165-35ad2ec4-b76d-48bd-b331-5c303dac55f6.png)

![image](https://user-images.githubusercontent.com/27736975/150628192-3e98153a-3245-4aee-ab90-e8f6126cf621.png)

![image](https://user-images.githubusercontent.com/27736975/150628516-a7e543e6-7a39-4d83-8cee-14f133ae7f7a.jpg)

### Expected Behavior

I want to building for linux-armv7 or linuxstatic-armv7

### To Reproduce

![image](https://user-images.githubusercontent.com/27736975/150628192-3e98153a-3245-4aee-ab90-e8f6126cf621.png)

pkg index.js -t node10-linuxstatic-armv7 -o test

**Comment by jesec** [comment]
No. That's not possible. See https://github.com/vercel/pkg#targets. 

`pkg` has to run the binary of the **target** architecture to generate bytecodes. There is no way to run arm64 binary on x86 Windows. 

You can workaround that by disabling the bytecode generation.
