### ISSUE TITLE
Source code reveal

### ISSUE THREAD

**Issue by skaneprime** [vercel/pkg#1491]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.13.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux, node16-win

### Describe the Bug

You can reveal source code of app If you're executing untrusted code by using snapshot file system 
this is the same issue as using node vm

### Expected Behavior

This shouldn't be available.  Don't know what more I should describe 

If it's not a bug. And I have to execute untrusted code then how to avoid it? 

Also Using vm2 or isolated-vm is not a solution They have issues with waiting process to gracefully finish

### To Reproduce

There's multiple ways to do it

First. Easiest 
```js
console.log(readFileSync(`${process?.mainModule?.filename}`, 'utf-8'))
```
Second
```js
this.constructor.constructor("return process.mainModule.require(\'fs\').readFileSync(process.mainModule.filename,\'utf-8\')")()
```

**Comment by skaneprime** [comment]
btw I thought code was transformed into bytecode which is not accessible in runtime

**Comment by robertsLando** [comment]
You have to set `"private": true` in your package.json

**Comment by skaneprime** [comment]
> You have to set `"private": true` in your package.json

Ooooohhh.. Well It's kinda akward
Thanks!
