### ISSUE TITLE
require a node_module from inside a plugin

### ISSUE THREAD

**Issue by rejetto** [vercel/pkg#1503]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.13.1

### What operating system are you using?

windows 10

### What CPU architecture are you using?

intel i7

### What Node versions, OSs and CPU architectures are you building for?

node 10, x86_64

### Describe the Bug

My app uses some node_modules, like lodash.
I built an exe that's running quite smoothly.
My app requires some plugins (js) at run-time.
If a plugin requires a module that I'm already using, like require('lodash')
I get an error: Cannot find module 'lodash'

is this expected?
is there any project/example/documentation I can look at to see what's the correct way to do this kind of things?
i've seen a vague hint on what to do in the warning message, but i've been unable a code that consistently works both launching node and using the generated exe.
thanks

### Expected Behavior

I expect the "require" to look into the node_modules and find it.

### To Reproduce

`require('lodash')`
executed from inside a plugin (a dynamically required js that's not part of original the package)

**Comment by rejetto** [comment]
My latest attempt at workarounding the problem seems to be working well and it's not that bad, so I want to share it:

my plugin exposes an 'init' function that I call with an an object with several goods.
I added to these goods a reference to _my_ `require` , and that's just working.

So, what I do in the plugin is just this
```
exports.init = api => {
    const _ = api.require('lodash')
...
```

I'm still interested in knowing if you have a different official/best-practice solution for me.

**Comment by robertsLando** [comment]
The reason is that require is patched by pkg in bootstrap in order to allow catching all your project require calls and handle requires to modules that are inside snapshot. 

Check yourself starting from: https://github.com/vercel/pkg/blob/main/prelude/bootstrap.js#L1802

In [this](https://stackoverflow.com/a/46918260) answer  you can see how require works under the hood. Essentially we patch all those steps in bootstrap to be able to load modules inside the snapshot filesystem

**Comment by skaneprime** [comment]
Is there any workarounds for this? except this

> My latest attempt at workarounding the problem seems to be working well and it's not that bad, so I want to share it:
> 
> my plugin exposes an 'init' function that I call with an an object with several goods. I added to these goods a reference to _my_ `require` , and that's just working.
> 
> So, what I do in the plugin is just this
> 
> ```
> exports.init = api => {
>     const _ = api.require('lodash')
> ...
> ```
> 
> I'm still interested in knowing if you have a different official/best-practice solution for me.

```ts
// my-plugin.ts 
import canvas from 'canvas';
```
throws error that Cannot file module "canvas";

**Comment by skaneprime** [comment]
> 

My issue was that require followed path like `<execPath>/build/Release/canvas.node` which had to be `node_modules/canvas/build/Release/canvas.node` with some string "manipulation" I made my way to file, but still think it's incorrect way to do it. 
```ts
(str: string) => {
	/** TEMPORAL FIX. NOT CORRECT
	 * PLUGIN requires SUBPLUGIN which requires CANVAS = FAILED TO REQUIRE due to invalid path
	 */
	let mod = {};
	try {
		return (mod = require(str));
	} catch (error) {
		if (error instanceof Error && error.message.includes("Cannot find module")) {
			const nodePath = path.relative(`${path.dirname(entry)}`, str);
			const modName = path.basename(str).replace(path.extname(str), "");
			const pathToModule = `${process.cwd()}/node_modules/${modName}/${nodePath}`;
			// INVALID WAY TO REQUIRE NODE_MODULE. Others can require different .node or other files which will fail cause this one was named canvas.node which is why it worked 
			console.log(pathToModule);
			return (mod = require(pathToModule));
		}
		return mod;
	}
},
```

**Comment by skaneprime** [comment]
Issue with finding path was solved really simple dunno why I did such dumb mistake I guess you shouldn't write something when you're tired Otherwise spaghetti like above will be 
```ts
(e: string) => {
    const mod_path = require.resolve(e, { paths: [ process.cwd(), `${process.cwd()}/node_modules` ] });
    return require(e);
}
```
