### ISSUE TITLE
fs.stat not working

### ISSUE THREAD

**Issue by rejetto** [vercel/pkg#1505]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.13.1

### What operating system are you using?

windows 10

### What CPU architecture are you using?

intel i7

### What Node versions, OSs and CPU architectures are you building for?

node 10, x86_64

### Describe the Bug

if I try to fs.readFile an asset it works
but if I do fs.stat with same path, I get an error
ENOENT: no such file or directory, stat 'C:\snapshot\hfs3\dist\admin\index.html'

### Expected Behavior

to work as before packing

### To Reproduce

call fs.stat on an asset

**Comment by rejetto** [comment]
this is in my package.json 
```
  "bin": {
    "hfs": "dist/src/index.js"
  },
  "pkg": {
    "assets": ["dist/admin/*", "dist/frontend/*"],
    "targets": [
      "node16-win"
    ],
    "outputPath": "dist"
  },
```

and this is how I build the path

    const fullPath = path.join(__dirname, '..', 'admin', ctx.path.includes('.') ? ctx.path : '/index.html')

**Comment by rejetto** [comment]
Ok, I've found the source of the problem.
I was using fs/promises (standard in node.js) while you are "trapping" only the classic fs.

I workarounded in my case by using promisify(stat) on the "fs" module, so to not renounce to the convenience of the `await`.

You can decide if you want to consider this as an issue for those who are going to be in my situation.
I wasted 4-5 hours on this, and understood the truth only by studying pkg's sources.

Please, warn people on this, as the async/await is going to be more and more common.
And if you can, support the fs/promises.

**Comment by robertsLando** [comment]
@rejetto Could you submit a pr to fix this please? Just patch the fs stat from propmises in bootstrap.js
