### ISSUE TITLE
Possibility to add a custom icon on the generated package

### ISSUE THREAD

**Issue by kennethpdev** [vercel/pkg#151]
I think it would be good if it can also add a custom icon for the exe file. I'm not sure if thats possible already but would be a good feature.

**Comment by sharathbaddam** [comment]
You can add resources (icon) to executables on Windows (ResourceHacker, etc)  with pkg >4.0.

If you are asking about having a resource file that pkg can directly refer to it while building executable, may be @igorklopov can answer it.

**Comment by kenma9123** [comment]
@sharathbaddam yes it should be while building the executable. I haven't tried ResourceHacker myself, but would love to try it. Thanks for your suggestion.

**Comment by tonywoode** [comment]
Resource Hacker worked for me on pkg executables, however you have to make sure the ico you're using is a specific and valid size or the executable corrupts.

@sharathbaddam I don't understand the point you are making: since ResourceHacker is external to pkg and run after pkg has generated an executable, why would the version of pkg be important? why must it be > v4?

For osx, it should work to simply add an icon to a resources/plist so this should work: https://stackoverflow.com/a/646676/3536094

**Comment by sharathbaddam** [comment]
@tonywoode I was referring to this issue #91 when i said pkg > v4.

**Comment by tonywoode** [comment]
thanks - yes my comments above about Resource Hacker should now be redundant then...great!

**Comment by soniagandhi** [comment]
Need help in setting the customized icon during packaging on windows using pkg.

I am packaging node service into exe using pkg (pkg package.json --output ./dist/test.exe)
It sets the icon as nodejs icon.
I also tried with pkg package.json --icon ./src/testIcon.ico --output ./dist/test.exe
But still it sets the icon as default nodejs icon.

Can you please help in setting the customized icon while packaging using pkg.

I tried with ResourceHacker, it corrupts my exe.

**Comment by KingRial** [comment]
@soniagandhi please understand that to "overwrite" the current iconset, you need to prepare the an iconset with the same "dimensions" (otherwise you'll overwrite also part of the real executable, corrupting it).

Currently the default "iconset.ico" is composed by the following dimensions:
- 16x16
- 32x32
- 48x48
- 64x64
- 128x128

If you create a new "iconset.ico"with different dimensions you corrupt the executable.

I used the following [URL](http://icoconvert.com/) to create an "iconset.ico" with the correct dimensions.

I hope this can help you!

**Comment by FrankenApps** [comment]
This is possible if you edit the node base binary in `.pkg-cache` with ResourceHacker (not the executable) and then build your app again.
You can also edit stuff like manufacturer, etc. (Version Info).
The cache folder should be located in `C:\Users\<username>\.pkg-cache\<version>\` be sure to edit the node binary, that you specified in --targets.
This was initially discussed [here](https://github.com/vercel/pkg/issues/91#issuecomment-302853037).

**Comment by DanDev95** [comment]
> This is possible if you edit the node base binary in `.pkg-cache` with ResourceHacker (not the executable) and then build your app again.
> You can also edit stuff like manufacturer, etc. (Version Info).
> The cache folder should be located in `C:\Users\<username>\.pkg-cache\<version>\` be sure to edit the node binary, that you specified in --targets.
> This was initially discussed [here](https://github.com/vercel/pkg/issues/91#issuecomment-302853037).

But the binary gets replaced as soon as you run the pkg command, since it downloads a new version of it.

**Comment by renandecarlo** [comment]
I only managed to change the icon in recent versions using the Icon Maker - Icon Changer software. It seems there is a new 256x256 dimension which messed things

**Comment by cayanxk** [comment]
> I only managed to change the icon in recent versions using the Icon Maker - Icon Changer software. It seems there is a new 256x256 dimension which messed things

Hey, may I have the link of these softwares you are using? Thank you.

**Comment by renandecarlo** [comment]
> > I only managed to change the icon in recent versions using the Icon Maker - Icon Changer software. It seems there is a new 256x256 dimension which messed things
> 
> Hey, may I have the link of these softwares you are using? Thank you.
This one 

https://www.icon-maker.com/download.htm

**Comment by KK-Designs** [comment]
> @soniagandhi please understand that to "overwrite" the current iconset, you need to prepare an "iconset.ico" with the same "dimensions" (otherwise you'll overwrite also part of the real executable, corrupting it).
> 
> Currently the default "iconset.ico" is composed by the following dimensions:
> 
> * 16x16
> * 32x32
> * 48x48
> * 64x64
> * 128x128
> 
> If you create a new "iconset.ico"with different dimensions you corrupt the executable.
> 
> I used the following [URL](http://icoconvert.com/) to create an "iconset.ico" with the correct dimensions.
> 
> After creating a correct "iconset.ico" I changed the icon using [node-resourcehacker](https://github.com/evshiron/node-resourcehacker) For example:
> 
> ```
> ...
> resourceHacker({
>       operation: 'addoverwrite',
>       input: 'PathToOriginalExe',
>       output: 'PatToUpdatedExe',
>       resource: 'PathToNew_iconset.ico',
>       resourceType: 'ICONGROUP',
>       resourceName: '1'
>     },
>     error => {
>       ... callback to call when everything is done ...
>     }
>   );
> ```
> 
> I hope this can help you!
> 
> P.S. the ability to configure icon/details just using directly pkg would be very nice!

What do I put in `input` and `output` ?

**Comment by cayank** [comment]
> > @soniagandhi please understand that to "overwrite" the current iconset, you need to prepare an "iconset.ico" with the same "dimensions" (otherwise you'll overwrite also part of the real executable, corrupting it).
> > Currently the default "iconset.ico" is composed by the following dimensions:
> > 
> > * 16x16
> > * 32x32
> > * 48x48
> > * 64x64
> > * 128x128
> > 
> > If you create a new "iconset.ico"with different dimensions you corrupt the executable.
> > I used the following [URL](http://icoconvert.com/) to create an "iconset.ico" with the correct dimensions.
> > After creating a correct "iconset.ico" I changed the icon using [node-resourcehacker](https://github.com/evshiron/node-resourcehacker) For example:
> > ```
> > ...
> > resourceHacker({
> >       operation: 'addoverwrite',
> >       input: 'PathToOriginalExe',
> >       output: 'PatToUpdatedExe',
> >       resource: 'PathToNew_iconset.ico',
> >       resourceType: 'ICONGROUP',
> >       resourceName: '1'
> >     },
> >     error => {
> >       ... callback to call when everything is done ...
> >     }
> >   );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this can help you!
> > P.S. the ability to configure icon/details just using directly pkg would be very nice!
> 
> What do I put in `input` and `output` ?

You can put the path where you want to print.

Example,
input -> Put the path to keep original exe "./original"
output -> Updated exe file "./updated"

So you need to mkdir them first.

**Comment by KK-Designs** [comment]
ok thanks @cayank !

**Comment by cayank** [comment]
> ok thanks @cayank !

You're welcome.

**Comment by fdciabdul** [comment]
> Hello @cayank, Using your method in changing the compiled pkg icon doesn't seem to work. :/

same with me , the app crashed after changin the icon

**Comment by hp8wvvvgnj6asjm7** [comment]
why is this not built into pkg ?

**Comment by elliot-huffman** [comment]
Using resource hacker is a hack/workaround and not a best practice for enterprise environments...

**Comment by Gu7z** [comment]
It is a nice feature to have when working with production apps

@leerob Any plans to do this?

**Comment by scaevitas** [comment]
I've been trying to change the icon for a really long time now, I am 100% sure I have the right icon sizes but it keeps corrupting my file somehow...

**Comment by fdciabdul** [comment]
Found the library to change the icon for pkg 
`@angablue/exe`

```javascript
const exe = require('@angablue/exe');

const build = exe({
    entry: './index.js',
    out: './reminder.exe',
    pkg: [ '--public'], // Specify extra pkg arguments
    version: '2.4.2',
    target: 'node16-win-x64',
    icon: './icon/reminder.ico', // Application icons must be in .ico format
    properties: {
        FileDescription: 'Abdul Muttaqin',
        ProductName: 'Reminder',
        LegalCopyright: 'Reminder https://taqin.tech',
        OriginalFilename: 'Reminder.exe'
    }
});

build.then(() => console.log('Build completed!'));
```

**Comment by afalahi** [comment]
> Found the library to change the icon for pkg `@angablue/exe`
> 
> ```js
> const exe = require('@angablue/exe');
> 
> const build = exe({
>     entry: './index.js',
>     out: './reminder.exe',
>     pkg: [ '--public'], // Specify extra pkg arguments
>     version: '2.4.2',
>     target: 'node16-win-x64',
>     icon: './icon/reminder.ico', // Application icons must be in .ico format
>     properties: {
>         FileDescription: 'Abdul Muttaqin',
>         ProductName: 'Reminder',
>         LegalCopyright: 'Reminder https://taqin.tech',
>         OriginalFilename: 'Reminder.exe'
>     }
> });
> 
> build.then(() => console.log('Build completed!'));
> ```

I'm running into the same issue for a CLI I'm building for our SaaS app. Where do I define this code? I'm currently doing everything manually, but moving to gulp and github actions to automate the build process.

**Comment by fdciabdul** [comment]
> 

just create a new file and run that , example `node build.js`

**Comment by kennethpdev** [comment]
after almost 6 years, I'm revisiting this issue 😀 and it's still not a built-in feature.
But anyway the `@angablue/exe` helped, thanks a lot!

**Comment by 9de** [comment]
The @angablue/exe doesn't work for me again

**Comment by 9de** [comment]
> 

Again Not working it's just close the app

**Comment by fdciabdul** [comment]
> > 
> 
> Again Not working it's just close the app

try look up the error by opening the binary app with terminal or command line in windows

**Comment by 9de** [comment]
Pkg: Error reading from file.

**Comment by ConsultantsCombined** [comment]
Just add the damn icon to pkg vercel or tell us why we should not use pkg at the top of this page.

**Comment by KDot227** [comment]
bump
