### ISSUE TITLE
Packaged apps crash with zero messaging when NODE_OPTIONS is set

### ISSUE THREAD

**Issue by gluxon** [vercel/pkg#1517]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

v17.5.0

### What operating system are you using?

macOS, Ubuntu 20.04.3

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-linux-x64, node14-macos-x64

### Describe the Bug

Hi, this is a duplicate of #484. It doesn't look like the community can re-open issues, so I'd like to create a new issue to get visibility from the team on a serious vercel/pkg bug.

> With latest Node 16, the binary built with pkg exits immediately. We have no warning "Pkg: FLAGS_MISMATCH".

https://github.com/vercel/pkg/issues/484#issuecomment-971735816

We're seeing this over in the pnpm repo: https://github.com/pnpm/pnpm/issues/4319. Thanks in advance for any help.

---

@BlackHole1 compiled a list of existing closed issues. Copying for visibility.

* https://github.com/vercel/pkg/issues/484
* https://github.com/vercel/pkg/issues/1217
* https://github.com/vercel/pkg/issues/932
* https://github.com/vercel/pkg/issues/954
* https://github.com/vercel/pkg/issues/447
* https://github.com/vercel/pkg/issues/709
* https://github.com/vercel/pkg/issues/921

### Expected Behavior

A warning for mismatched `NODE_OPTIONS` flags is printed.

### To Reproduce

```
❯ NODE_OPTIONS="--max-old-space-size=4096" pnpm

❯ echo $?           
4
```

I'm using the `pnpm` binary as an example, but I believe this will happen for any `pkg` binary from looking over previous tickets.

**Comment by robertsLando** [comment]
@gluxon Are you running it from vscode terminal? If so try with another terminal not in vscode application

@jesec Any clue about what could cause this?

**Comment by timonag** [comment]
I can add that an app packaged with `--public` flag does not fail when NODE_OPTIONS is not empty.

**Comment by gluxon** [comment]
> Are you running it from vscode terminal? If so try with another terminal not in vscode application

Hey @robertsLando, thanks for the help. Apologies for missing the comment until now. I switched to the regular JavaScript version of `pnpm` personally, but was looking to deploy the vercel version on our team's development container. Some of my teammates use VS Code's integrated terminal from that development container, and I'd like them to continue to be able to do that?

**Comment by robertsLando** [comment]
@gluxon I said that because when you try to run a packaged app from vscode terminal it will not work, dunno the reason but I think it's because vscode has some env var that cause it to crash

**Comment by aerben** [comment]
We observed this issue today as well with pkg 5.3.3 wrapping Node 16 for a Ubuntu 20.04 host.
Using the env var
`NODE_OPTIONS="--max-old-space-size=4096"`

**Comment by gluxon** [comment]
> I said that because when you try to run a packaged app from vscode terminal it will not work, dunno the reason but I think it's because vscode has some env var that cause it to crash

Hey @robertsLando, I was looking over this issue again and I realized I forgot to respond. Although VS Code is setting an environment variable that causes it to crash (i.e `NODE_OPTIONS`), I'd consider it a `vercel/pkg` bug since I believe `vercel/pkg` binaries should work in these environments. Please correct me if I'm wrong.

It looks like https://github.com/vercel/pkg-fetch/commit/52d32ed4fe31469c0a135580e9220dc115c2f3ad may fix the problem though. Going to check and close this issue if so.

**Comment by gluxon** [comment]
Confirmed that `pkg-fetch` 3.4 fixes the problem. 🎉 Thanks @robertsLando and @jesec
