### ISSUE TITLE
Error with Dynamic Requires

### ISSUE THREAD

**Issue by FC5570** [vercel/pkg#1518]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

17.3.1

### What operating system are you using?

Windows

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

node17-win-x64

### Describe the Bug

I have a folder in which all the files are required dynamically. For example, I have an `events` folder inside which are .js files, all these files are loaded using dynamic require.

```js
const { resolve, join } = require('node:path');
const { readdirSync } = require('node:fs');

const dir = resolve('./dist/listeners');
const files = readdirSync(dir);

for (const file of files) {
    const { default: loaded } = require(join(dir, file));
    
    /*
    other code
    */
}
```

The above code loads all the files in the dist/listeners folder, everything works fine when I execute the code. However, when I run `pkg -t node17-win-x64 .` in the root dir, I get an error saying:
```
> Warning Cannot resolve '(0, import_node_path.join)(dir, file)'
  full-path\dist\index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```

Since all the files inside the events folder are loaded, I tried specifying this as the config:
```json
	"pkg": {
		"scripts": "./dist/listeners/*.js"
	}
```

I have also tried creating a js file which requires all the files inside dist/listeners, and then passing the js file into the scripts option, however, that didn't work aswell.

What could be done to fix this?

### Expected Behavior

The .exe's are generated with no warnings/errors.

### To Reproduce

1. Install pkg - `yarn add pkg` (npm can be used too, I use yarn in this case)
2. Create any folder with some js files inside it.
3. Use the above code block and execute the code, which requires all the files you created in the folder created in step 2.
4. Use `yarn pkg .`, a warning is emitted to the console as above.

**Comment by robertsLando** [comment]
scripts must be an array of globs

**Comment by FC5570** [comment]
Thanks. However, my issue was different. I had to add `file://` to the beginning of the load path instead of supplying an absolute path. Doing this fixed my issue.
