### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed

### ISSUE THREAD

**Issue by suntong** [vercel/pkg#1529]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-linux

### Describe the Bug

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

```
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xafedf0 node::Abort() [node]
 2: 0xa1814d node::FatalError(char const*, char const*) [node]
 3: 0xce792e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xce7ca7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeb1685  [node]
 6: 0xeb2174  [node]
 7: 0xec05e7 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xec3925 v8::internal::Heap::HandleGCRequest() [node]
 9: 0xe55697 v8::internal::StackGuard::HandleInterrupts() [node]
10: 0x11f2355 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x15c9eb9  [node]
Aborted
```

### Expected Behavior

compile should be successful.

### To Reproduce

I've provided a 2-file example:

- `git clone https://gist.github.com/suntong/14a3427a72c7023ef1c5148bd1be6d9a`
- `npm install`
- `pkg .`

**Comment by suntong** [comment]
I've also prepared the minimum-set to duplicated this problem as a Dockerfile file, so we won't have a _it-works-for-me_ case.

```Dockerfile
FROM node:14-bullseye

RUN npm install -g pkg

RUN mkdir /src; git clone --depth 1 https://gist.github.com/14a3427a72c7023ef1c5148bd1be6d9a.git /src

WORKDIR /src
RUN npm install; npm audit fix
RUN pkg . || true
```

will get:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa3aaf0 node::Abort() [node]
 2: 0x970199 node::FatalError(char const*, char const*) [node]
 3: 0xbba45e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xbba7d7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd769e5  [node]
 6: 0xd7756f  [node]
 7: 0xd853ab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd87a65 v8::internal::Heap::HandleGCRequest() [node]
 9: 0xd2df77 v8::internal::StackGuard::HandleInterrupts() [node]
10: 0x109f663 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1448e19  [node]
Aborted (core dumped)
```

**Comment by robertsLando** [comment]
Does this happen only when the app is packaged using pkg?

**Comment by suntong** [comment]
Yeah, for sure, it runs fine by itself without packaging by pkg.

**Comment by robertsLando** [comment]
Try to add

export NODE_OPTIONS="--max-old-space-size=8192"

Right before running pkg

**Comment by suntong** [comment]
Bravo!! Thanks!

**Comment by suntong** [comment]
BTW, a warning of failed to make bytecode of one _**single**_ file won't be a problem right?

> Warning Failed to make bytecode node14-x64 for file /snapshot/src/node_modules/wechaty-puppet-padlocal/node_modules/quick-lru/index.js

Even if that particular failed to make bytecode, it'll still work in its source form, right?

**Comment by robertsLando** [comment]
> Even if that particular failed to make bytecode, it'll still work in its source form, right?

From my experience, nope
