### ISSUE TITLE
pkg.exec silent mode

### ISSUE THREAD

**Issue by pcnate** [vercel/pkg#1536]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.14.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-win-x64

### Describe the Bug

pkg@version is displayed with no way to turn it off.

https://github.com/vercel/pkg/blob/a67c92667b110b8cfca6a759e7875385c384f13f/lib/index.ts#L271

### Expected Behavior

no logs should be generated

### To Reproduce

```javascript
  let targetFile = 'testFile.js';
  let build = false;
  let targetArch = 'node16-win-x64'
  let fullOutputPath = __dirname + '/TestFile.exe';
  let options = [
    targetFile,
    build ? '--build' : null,
    '--target', targetArch,
    '--output', fullOutputPath
  ].filter( x => !!x );
  const shellCommand = `pkg ${ options.join(' ') }`;
  console.info( shellCommand );
  console.info(`${ ( new Date() ).toISOString() } Building ${ targetFile } for ${ targetArch }`)
  return new Promise( async resolve => {
    await exec( options );
    resolve();
  })
```

**Comment by robertsLando** [comment]
@pcnate what about  `pkg ..... > /dev/null` ?

**Comment by pcnate** [comment]
its hard to do > /dev/null on windows inside of javascript when not calling a command line script
