### ISSUE TITLE
Node cli script packaged with pkg in github actions giving Trojan:Script/Wacatac.B!ml detected

### ISSUE THREAD

**Issue by kkibria** [vercel/pkg#1540]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.14.0

### What operating system are you using?

windows

### What CPU architecture are you using?

x86_64, github actions

### What Node versions, OSs and CPU architectures are you building for?

node16-win-x64

### Describe the Bug

I have built a node CLI script and using github actions to make a exe file using node pkg module. The intent is that people can download a zip file and extract the exe and run the cli on their machine without going thru the complexities of manually installing node and running npm steps.

the build goes fine and the exe file gets zipped and released as an asset. I tried downloading the zip to test on my machine, but windows defender is throwing complaints about `Trojan:Script/Wacatac.B!ml` malware detected and quarantining the download. Of course that would scare people who would like to use the CLI exe.

The github release URL <https://github.com/kkibria/slideshow-dist/releases/tag/v0.1.0-987630f>.

The pkg configuration in `package.json`,
```
  "pkg": {
    ...
    "targets": [
      ...
      "node16-win-x64"
      ...
    ],
    ...
  }
```

I am not sure what is going on, trying to figure out the root cause. Any help will be highly appreciated. If anyone have seen this before and figured out, what steps would help my situation? 

### Expected Behavior

Do not expect to see a virus warning. What is triggering this warning?

### To Reproduce

fork and clone <https://github.com/kkibria/slideshow-dist>
tag on origin, tag name should start with letter "v", which will trigger github action.
download zip file with pkg produced binary on a windows machine.

Locally built exe does not get caught by the virus detection, it only happens when I build on github actions.

**Comment by kkibria** [comment]
This is most probably not a pkg problem. I extracted the file and ran virus scan on it. The scan was negative. Most likely if a zip file is downloaded and and it has a exe in it and the exe has certain pattern in it the scan gives a positive result. I am still not sure what causes it. I am closing this issue.

**Comment by johannes85** [comment]
I have the same problem but it also happens with locally build executables.

**Comment by johannes85** [comment]
VirusTotal result: https://www.virustotal.com/gui/file/9763f7f72108428ae4a8a2f4173395ab09027d3d1d7d931f870954fd1aa0eb64?nocache=1
Of: https://github.com/johannes85/pnpcardmaster/releases/tag/v1.0.1
Can be build with: npm install && npm run pkg

**Comment by jayohf** [comment]
Also seeing this with my project. https://github.com/jayohf/defi-cli

I've tried pkg 5.5.2-5.0 and node 17-14. VirusTotal is showing something for all builds for Windows. No issues for Linux or macOS binaries.
