### ISSUE TITLE
Could not detect node-abi version

### ISSUE THREAD

**Issue by Craftzman7** [vercel/pkg#1543]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

17.6.0

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node17-win,node17-linux

### Describe the Bug

When attempting to build for the above targets I get this following error:

```
Error: Could not detect abi for version 17.3.1 and runtime node.  Updating "node-abi" might help solve this issue if it is a new release of node
```

### Expected Behavior

This error doesn't happen and the executable builds successfully.

### To Reproduce

Matching the above environment run:
`pkg -d --compress GZip -t node17-linux,node17-win src/package.json`

**Comment by Craftzman7** [comment]
Downgraded node version. Now getting `[debug] prebuild-install failed[/root/xxxx/node_modules/cpu-features/build/Release/cpufeatures.node]`

**Comment by Craftzman7** [comment]
Fixed

**Comment by fhodun** [comment]
> Fixed

could you write how?

**Comment by Craftzman7** [comment]
I opened this issue a long time ago. I don't really remember. It had to do with upgrading/downgrading Node.

**Comment by fhodun** [comment]
No problem, thank for tip.

**Comment by meoyawn** [comment]
downgrading target from node18 to node16 solved the problem

**Comment by istealth** [comment]
I also used node16 because of that, but now to make it work for node18?:)))
