### ISSUE TITLE
Security: prebuild-install dependency with high security issue

### ISSUE THREAD

**Issue by julianpoemp** [vercel/pkg#1544]
According to my security alerts the dependency `prebuild-install` uses an old version of `simple-get` that creates a high security issue. Can you please update `prebuild-install` to the latest version?

![Bildschirmfoto 2022-03-03 um 11 05 00](https://user-images.githubusercontent.com/25926588/156542589-78e449ee-4f96-4729-a5e4-24346b758555.png)

**Comment by robertsLando** [comment]
PR?

**Comment by jesec** [comment]
We have already pushed the fix: #1512 .

Note that in our use case, this security issue is not going to have an impact.
