### ISSUE TITLE
can't prebuild-install node-canvas

### ISSUE THREAD

**Issue by luoxzhg** [vercel/pkg#1545]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

14.18.3

### What operating system are you using?

macOS

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-linux-x64

### Describe the Bug

```
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=linux)
```

node-canvas in linux need `libc` to be specified as `glibc`

```
canvas-v2.9.0-node-v83-darwin-unknown-x64.tar.gz 
canvas-v2.9.0-node-v83-linux-glibc-x64.tar.gz 
canvas-v2.9.0-node-v83-win32-unknown-x64.tar.gz 
```

### Expected Behavior

can prebuild-install `canvas` module

### To Reproduce

everytime using canvas module in node.js

**Comment by luoxzhg** [comment]
also having some problem on target `node14-macos-x64`
```
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
```

**Comment by robertsLando** [comment]
you can ignore that warning if you are not cross-building. That just tells you that node-canvas doesn't provide pre-built binaries for that target/arch
