### ISSUE TITLE
How to put pkg'd nodejs server under forever running or as daemon?

### ISSUE THREAD

**Issue by codeofnode** [vercel/pkg#155]
I have nodejs server.

I have pkg'd it.

I make it running up.

At some point, it get crashed.

To restart automatically
Usually i put the node process under [forever](npmjs.com/package/forever)

How would i do the same when the its pkg'd?

**Comment by mchanton** [comment]
Forever supports monitoring binaries too.

**Comment by tauqeer81** [comment]
@mchanton How to run pkg binary file with pm2? any idea
