### ISSUE TITLE
pkg with socket.io does not work in browser (client side)

### ISSUE THREAD

**Issue by bonurb** [vercel/pkg#1551]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

v16.11.1

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

 x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-win-x64

### Describe the Bug

When using socket.io in an express app with pkg, the socket.io.js is not sent from server to the browser.
In dev-tools of the browser you see the following error:
`Failed to load resource: net::ERR_EMPTY_RESPONSE socket.io.js`

![image](https://user-images.githubusercontent.com/84138399/158059930-624e45ff-d3ba-43d2-bde0-2ce364ba7ba7.png)

### Expected Behavior

When running the compiled app with pkg and opening http://localhost:8080 in a browser, I expect the following text:
`response from server: Hello Bob`

And in the dev-tools  console of the browser, I expect to see no errors (except for an eventual `Failed to load resource` for favicon.ico).

see readme.md in my example project:
https://github.com/bonurb/pkg-express-example.git

### To Reproduce

see readme.md in my example project:
https://github.com/bonurb/pkg-express-example.git

This is the express example from https://github.com/vercel/pkg.git, slightly modified and extended to do a socket.io call from client in browser to the server and from server back to the client.

**Comment by dirkk0** [comment]
I didn't try your project yet, but in my minimal project also using socket.io, this comment helped me:
https://github.com/vercel/pkg/issues/689#issuecomment-499261982

My full package is:
```{
  "name": "express-example",
  "license": "ISC",
  "bin": "server/server.js",
  "dependencies": {
    "express": "^4.17.3",
    "socket.io": "^4.4.1"
  },
  "assets": [
    "node_modules/@socket.io/**/*"
  ]
}
```
and now socket.io is working just fine.

**Comment by bonurb** [comment]
Thank you Dirk for your response.
But it did not work in my project.

I found a working solution:

Add the line `./node_modules/socket.io/client-dist/**/*` in package.json:
```  
"pkg": {
    "assets": [
      "views/**/*",
      "./node_modules/socket.io/client-dist/**/*"
    ],
    "targets": [
      "node16"
    ]
}
```
