### ISSUE TITLE
Problem with symlinks inside node_modules

### ISSUE THREAD

**Issue by Mall0c** [vercel/pkg#1555]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.14.0

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux-x64

### Describe the Bug

The library [node-rdkafka ](https://github.com/Blizzard/node-rdkafka/) has four symlinks in their code. If you install this package and try to package the code into a binary, the build freezes at the point where it reaches the symlinks. Nothing happens after this, you need to hit Ctrl+C.

` [debug]  Adding asset : .... `
 `<path-to-project>/node_modules/node-rdkafka/build/deps/librdkafka++.so`
 `[debug] Content of <path-to-project>/node_modules/node-rdkafka/build/deps/librdkafka++.so.1 is added to queue. It was required from <path-to-project>/package.json`
`^C`
`richards@richards:<path-to-project>$ `

### Expected Behavior

The build should succeed with the symlinks resolved correctly to the files inside the binary. Most likely the issue is that the symlink files are simply copied into the binary, still referencing to the old files.

Example:
/path-to-project-on-my-local-machine/node_modules/node-rdkafka/build/deps/librdkafka++.so points to path-to-project-on-my-local-machine/node_modules/node-rdkafka/build/deps/librdkafka++.so.1 on my local machine. Once built, the librdkafka++.so must not point to path-to-project-on-my-local-machine/node_modules/node-rdkafka/build/deps/librdkafka++.so.1 anymore, but to something like /snapshot/path-to-project/node_modules/node-rdkafka/build/deps/librdkafka++.so.1, so inside the virtual file system of the binary.

### To Reproduce

See https://github.com/Mall0c/node-rdkafka-pkg-demo.

**Comment by Zubnix** [comment]
Still hitting this...
