### ISSUE TITLE
Build from macOs to node16-linux-arm64 dont work on Dockerized Debian

### ISSUE THREAD

**Issue by snips-dev** [vercel/pkg#1556]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.14.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

arm64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux-arm64

### Describe the Bug

Launching the command `pkg . -t node16-linux-arm64` and moving the binary on a dockerized Debian and launching it fails to start with 0 messages if i run `echo $?` the result is 4.
Moving the whole project in dockerized Debian with the same version of pkg and node and launching `pkg . -t node16-linux-arm64` the binary created work fine

Launching the command `pkg . -t node14-linux-arm64`and moving the binary on a dockerized Debian and launching it work fine

### Expected Behavior

Launching the command `pkg . -t node16-linux-arm64`and moving the binary on a dockerized Debian and launching it work fine

### To Reproduce

Launching the command `pkg . -t node16-linux-arm64`and moving the binary on a dockerized Debian on a M1 pro

**Comment by Gkiokan** [comment]
If you have a solution to this I might be interested.  
  
Docs say you have to have a trusted apple developer ID or the gatekeeper process will kill the build process - which it dues by saying codesign not found or configured properly.  
  
However, could you share your docker build script?

**Comment by jesec** [comment]
#1400

Make sure that you are using the latest pkg.
