### ISSUE TITLE
Bin file cannot exec by spawn unref

### ISSUE THREAD

**Issue by CheneyWong** [vercel/pkg#1562]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

16.14.0

### What operating system are you using?

Ubuntu 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

default

### Describe the Bug

I packaged an executable file `test` with pkg and it runs directly, no problem.
Strangely, I can't call `test` from the background via another daemon program.
My daemon program directly call the js source file `node test.js`. But then I package test.js as `test`, the daemon program cannot call it.

### Expected Behavior

I don't know how the pkg packaged program handles stdio stdout stderr, I want the program to run without stdio stdout stderr.

### To Reproduce

use /tmp as workdir
Write all to the index.js file.
run `node index.js`， /tmp/test.log may add 2 line log.
pkg . -t linux -o ./test
run `test`， /tmp/test.log add just1 line log.

```
const fs = require("fs")
const {spawn} = require("child_process");

function log( msg ){
    fs.appendFileSync("/tmp/test.log", msg )
    console.log( msg )
}

function daemon( cmd ){
    console.log("cmd", cmd)
    let arr = cmd.split(" ")
    let [ c , ...argv ] = arr
    let options = {
        encoding: 'buffer',
        shell : true,
        detached: true,
        stdio:  ['pipe', 'pipe', 'pipe'],
        windowsHide : true
    }
    console.log( "spawn", c, argv , options )

    p = spawn( c, argv, options );
    p.on("error", function (e) {
        console.log( "process error : " +  e)
    })
    p.unref();
}



// main
let n = Number( process.argv[2] )
if ( !n ){
    n = 0
}



// next
n += 1;
if ( n < 3 ) {

    let cmd = ""
    if ( process.argv[0].endsWith("node") ) {
        // node js mode
        cmd = `node ${ process.argv[1] } ${n}`
    } else {
        // pkg mode
        cmd = `${ process.argv[0] } ${n}`
    }

    daemon( cmd )

    log( `${n} ${process.argv}\r\n` )
}

```

**Comment by introspection3** [comment]
same as https://github.com/vercel/pkg/issues/1866

**Comment by introspection3** [comment]
anyone else?
