### ISSUE TITLE
ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by LeandroMarceddu** [vercel/pkg#1568]
Hey, trying to use pkg to create a binary for our little app. On linux and macos everything works great, on Windows not so much.

We keep getting this error:

```
 leand on  D:/github/PlaterFlow main
# pkg index.js
> pkg@5.5.2
> Targets not specified. Assuming:
  node17-linux-x64, node17-macos-x64, node17-win-x64
> Warning Cannot resolve 'resolve(process.cwd() + '/' + process.argv[3])'
  D:\github\PlaterFlow\index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'resolve(process.cwd() + '/' + process.argv[2])'
  D:\github\PlaterFlow\index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
 leand on  D:/github/PlaterFlow main
# ./index-win.exe ./frominput.js ./baseconfig.js
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: The specified module could not be found.
C:\Users\leand\AppData\Local\Temp\pkg\16638feda37ef9e531ec3613a42ee5e920fd79c011dd7a465c2c878a17192550\canvas\build\Release\canvas.node
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1179:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\PlaterFlow\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v17.3.1
```

We have no idea why it works on the other platforms, just not Windows?

**Comment by traviscollins** [comment]
I get the same error after installing a new version of the PKG built binary on a mac. It's like the build sees the temporary cache top level directory, but doesn't check that the current version is the same as the cached version and has a different hash name for the node module directory?

**Comment by LeandroMarceddu** [comment]
> I get the same error after installing a new version of the PKG built binary on a mac. It's like the build sees the temporary cache top level directory, but doesn't check that the current version is the same as the cached version and has a different hash name for the node module directory?

I figured it out for my issue; it doesn't like node17, downgrading to node14 worked (the canvas requirement is 83 and on node17 is a higher number, thus canvas returns a higher number thus the DLOPEN_FAILED error)

**Comment by mreis1** [comment]
I didn't get it @LeandroMarceddu .

The error `ERR_DLOPEN_FAILED` doesn't relate to the second error:  `module "X" was compiled against a different Node.js version ...`

In fact I know how to handle the second error but until now I couldn't figure out, what's causing ERR_DLOPEN_FAILED after upgrading to node16 and node17. 

I tried to isolate the problem by creating a separate project with the dependency that seems to be causing the problem and worked ..... So in the context of my bigger and much more complex project, I'm getting that error. 

Any thoughts on this subject? 

As I said, tried multiple pkg versions (from 5.2.1 to 5.5.X) . Same error. 
What did change from pkg@4.4.9 to pkg@5.X.X ? 

Because using --targets=node14-win-x64 in the same project works just fine.

**Comment by LeandroMarceddu** [comment]
To us it always happens with canvas in node17. I'm not the main developer; I'm just the guy the main developer puts onto stuff like this. I've just deleted node17 and went with 14 and everything's running smoothly after that.

If I can help with providing logs or other information of any kind, please let me know.

**Comment by traviscollins** [comment]
Update: I'm seeing this error sporadically after installing new versions of a PKG built binary. The /var/folders/..../pkg directory it's trying to access doesn't exist.
