### ISSUE TITLE
No output for simple console.log()

### ISSUE THREAD

**Issue by joelmoss** [vercel/pkg#1571]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

17.7.2

### What operating system are you using?

macOS

### What CPU architecture are you using?

Apple M1

### What Node versions, OSs and CPU architectures are you building for?

default

### Describe the Bug

Just trying pkg out, so started by creating a js file...

```js
console.log('hello world')
```

When running `node ./index.js`, "hello world" is output. But after building with pkg (`pkg ./index.js`), and running it, nothing is output.

### Expected Behavior

See above ^^

### To Reproduce

See above ^^

**Comment by cshotton** [comment]
Second -- M1 Mac Studio, running x86 node v16 (LTS). Built a mac-x86 binary and no messages sent to console.log are appearing in the terminal. Messages emitted by debug (which has console bound to its log method) work, as do messages from Morgan. But straight up console.log messages never appear. Also, it seems that even debug messages don't start being emitted until some while after app launch.

**Comment by bayerlse** [comment]
Experiencing the same, any updates on this?

**Comment by lrNas** [comment]
With same problem here.

**Comment by Prez1313** [comment]
same
