### ISSUE TITLE
Executable file can not run without source code

### ISSUE THREAD

**Issue by chuongneon** [vercel/pkg#1572]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

14.18.3

### What operating system are you using?

macos

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-macos-x64

### Describe the Bug

I have a sailsjs project and build executable file from [project directory], After building, i got executable file in [project directory]/dist, if i run the file from  [project directory] (store original source code), it can be run normally, i can access to my resources. but if i run the file from other directory (not store origin source code), it can not be run as expected, i can not access to my resources.

### Expected Behavior

I expected that i can put the file at anywhere and run it from anywhere, not depend on origin source code.

Please help me about that.

### To Reproduce

Here is build command: 
   pkg "./app.js" --config "./package.json" --out-path "./dist" && cp "./node_modules/opn/xdg-open" "./dist/xdg-open" --options max_old_space_size=4096,expose-gc,use-strict=true

Here is my build script in package.json file:
   "pkg": {
    "scripts": ["api/**/*.js", "config/**/*.js", "migration/*.js"],
    "assets": ["config/**/*","templates/**/*", "node_modules/**/*"],
    "targets": [ "node14-macos-x64" ],
    "outputPath": "dist"
  },
  "bin": "app.js",

**Comment by chuongneon** [comment]
also, during packaging, i got these log:
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/opn/xdg-open
  %2: path-to-executable/xdg-open
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  %1: node_modules/opn/xdg-open
  %2: path-to-executable/xdg-open
> Warning Failed to make bytecode node14-x64 for file /snapshot/DEMO-BACKEND/api/models/Service.js
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
prebuild-install WARN install No prebuilt binaries found (target=v14.18.3 runtime=node arch=x64 libc= platform=darwin)
> Warning Failed to make bytecode node14-x64 for file /snapshot/DEMO-BACKEND/node_modules/@sailshq/upgrade/index.js

**Comment by skaneprime** [comment]
`"assets": ["config//*","templates//", "node_modules/**/"],`
didn't you forget an extra `*` ?
Just an assumption from first look.
`"assets": ["config//*","templates//", "node_modules/**/*"],`
