### ISSUE TITLE
Adding Custom Icon To Exe

### ISSUE THREAD

**Issue by IJR9** [vercel/pkg#1590]
### What version of pkg are you using?

5.5.2

### What version of Node.js are you using?

17.6.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

 node14-win-arm64

### Describe the Bug

I HAVE TESTED THE FOLLOWING METHODS:

> 1. ResourceHacker 
> 2. [Resedit](https://www.npmjs.com/package/resedit)

! AND NOT WORKING !

**_And The Exe Just Got Broken_**

### Expected Behavior

Change the icon and working without problem

### To Reproduce

1. pkg index.js
2. ResourceHacker Method
3. Resedit Method If ResourceHacker Not Working

**Comment by PromiseAll** [comment]
I wrote a small plugin to do this  : https://github.com/PromiseAll/pkg-exe-build

**Comment by namedx1234** [comment]
> I wrote a small plugin to do this : https://github.com/PromiseAll/pkg-exe-build

bro didnt work i tried, make a video on that sir
