### ISSUE TITLE
Specify how to handle ts files in README

### ISSUE THREAD

**Issue by floofywoofles** [vercel/pkg#1596]
Please specify in README that you do need to convert all ts files to js files before compilation. Or add a workaround for ts files.

**Comment by fuka-g** [comment]
> you do need to convert all ts files to js files before compilation.

Isn't that common sense ?

You have to compile .ts files before running them with `node`, same thing with pkg; pkg itself is not supposed to do the TS compilation work for you. You can add `tsc` in your build script (`"build": "tsc && pkg ."`), assuming you have incremental compilation disabled.
