### ISSUE TITLE
README needs to say Vercel does not maintain this package anymore

### ISSUE THREAD

**Issue by rightaway** [vercel/pkg#1600]
People who want to choose this package might think it's being maintained by Vercel but they have stopped maintaining it a long time ago. It should be moved to a different github organization or the README needs to say this so users don't think there's a company like Vercel behind it.

> @XFaonAE this package is not maintained by Vercel anymore from a long time, it's maintained by outside collaborators in their free time like me @jesec @erossignon. If you find a bug consider opening a PR and fix it, this is what I do when i find one

https://github.com/vercel/pkg/issues/262#issuecomment-1098162018=

**Comment by XFaonAE** [comment]
I agree

**Comment by panulogic** [comment]
Who decides which pull-requests are accepted into the next version? And who decides and does publish the releases?  Vercel, or the outside collaborators?

**Comment by XFaonAE** [comment]
> Who decides which pull-requests are accepted into the next version? Who decides and does publish the releases? Vercel, or the outside collaborators?
Non vercel associated maintainers, from what I'm seeing

**Comment by jesec** [comment]
I review pull requests and make technical decisions. I also make release calls.

Vercel is still the steward of the project, and an authorized Vercel employee reviews and publishes the release to npm. 

Please read the [license](https://github.com/vercel/pkg/blob/main/LICENSE) of the project carefully:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.

It is not appropriate to proclaim entitlement to free support, in any open source project. Maintainers maintain the project in a best-effort basis with good faith. Please contribute to the project with a PR if the matter is of particular urgency to you.

**Comment by rightaway** [comment]
> It is not appropriate to proclaim entitlement to free support, in any open source project. Maintainers maintain the project in a best-effort basis with good faith. Please contribute to the project with a PR if the matter is of particular urgency to you.

No need to be oversensitive and quote the license Jesse. Nobody is demanding free support.

> this package is not maintained by Vercel anymore from a long time, it's maintained by outside collaborators in their free time like me

It's already clear Vercel doesn't maintain this project anymore. Why not be transparent about that so people can be aware of that when deciding whether this is a package they want to use?
