### ISSUE TITLE
uf.readBigUInt64LE is not a function

### ISSUE THREAD

**Issue by JohnAlexCO** [vercel/pkg#1602]
### What version of pkg are you using?

5.6.0

### What version of Node.js are you using?

10.19.0

### What operating system are you using?

Linux Mint (Ubuntu) 20.04

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node10-linux-x64, node10-macos-x64, node10-win-x64

### Describe the Bug

When I run
```
pkg cli.js
```
I get the following error
```
> pkg@5.6.0
> Targets not specified. Assuming:
  node10-linux-x64, node10-macos-x64, node10-win-x64
> Error! TypeError: buf.readBigUInt64LE is not a function
    at patchCommand (/usr/local/lib/node_modules/pkg/lib-es5/mach-o.js:17:33)
    at patchMachOExecutable (/usr/local/lib/node_modules/pkg/lib-es5/mach-o.js:41:9)
    at exec (/usr/local/lib/node_modules/pkg/lib-es5/index.js:515:63)
```
The program works fine in node, and my program doesn't use any special big numbers or the readBigUInt64LE function, so I have no idea why this is happening, but I'm assuming it's something to do with how pkg internally represents data.

### Expected Behavior

I expected either the program to compile to machine code, or for a clear error to be logged to the terminal. I don't know what the error I've been given means, especially because my code doesn't include any use of `readBigUInt64LE` or any special `types`.

### To Reproduce

I've gotten this error any time I try to compile literally anything.  I tried writing a script named `test.js` who's entire content was 
```
console.log("Hello, world!")
```
and I got the same exact error, again.
```
> Error! TypeError: buf.readBigUInt64LE is not a function
    at patchCommand (/usr/local/lib/node_modules/pkg/lib-es5/mach-o.js:17:33)
    at patchMachOExecutable (/usr/local/lib/node_modules/pkg/lib-es5/mach-o.js:41:9)
    at exec (/usr/local/lib/node_modules/pkg/lib-es5/index.js:515:63)
```

**Comment by rickymohk** [comment]
Having this issue too with node 16.16.0, pkg 5.8.0, on macOS 12.5

**Comment by jack828** [comment]
It looks like pkg itself does not support building on node v10. I swapped to node v14 and this error is gone.
