### ISSUE TITLE
Create /tmp/pkg each time you start, if you start multiple worker_threads it will be an error

### ISSUE THREAD

**Issue by luckyyyyy** [vercel/pkg#1607]
### What version of pkg are you using?

5.6.0

### Describe the Bug

Multiple processes operate on files at the same time. This gives various errors

![image](https://user-images.githubusercontent.com/9210430/165740179-6f70302c-4912-4b6f-87c9-aa9bf15d60f0.png)

![image](https://user-images.githubusercontent.com/9210430/165740261-de04d2fb-a6a0-4dd9-b2da-c534cd9f9afe.png)

**Comment by robertsLando** [comment]
Would you like to submit a PR to fix this issue

**Comment by cwilling** [comment]
Is this the same problem - a permissions issue of some sort? It occurs when a new user attempts to execute the application. If I remove 'rm -rf /tmp/pkg' then the new user is able to run the application. However now /tmp/pkg is owned by the new user so the first user (or any other new user) is unable to run the application.

Read permissions all look OK, so is this a write permission problem?

The ERROR is:
`/snapshot/xkeys-server/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: EACCES: permission denied, open '/tmp/pkg/2956fd55d094eac8718642cca941fe696b75c16ba420086a65e56dd080e18f6b/node-hid/.gitmodules'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:753:32)
    at copyInChunks (pkg/prelude/bootstrap.js:170:26)
    at Object.copyFileSync (pkg/prelude/bootstrap.js:1142:5)
    at pkg/prelude/bootstrap.js:201:12
    at Array.forEach (<anonymous>)
    at copyFolderRecursiveSync (pkg/prelude/bootstrap.js:196:11)
    at process.dlopen (pkg/prelude/bootstrap.js:2193:9)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/tmp/pkg/2956fd55d094eac8718642cca941fe696b75c16ba420086a65e56dd080e18f6b/node-hid/.gitmodules'
}`
