### ISSUE TITLE
asset folder not working

### ISSUE THREAD

**Issue by jothimoorthy** [vercel/pkg#1610]
### What version of pkg are you using?

5.6.0

### What version of Node.js are you using?

16.15

### What operating system are you using?

windows 10

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

 node12

### Describe the Bug

 package.json 

"pkg": {
    "assets": "views/**/*.*",
    "targets": [
      "node16-win-x64"
    ],
    "outputPath": "dist"
  },

  
  I am trying to run a batch file 
  
const bat = spawn(
  `"${path.join(__dirname, '/views/ziptutorial.bat')}"`,
  ['/y'],
  {
    shell: true,
  }
);

when I run the exe I get this error
C:\snapshot\node split\views\ziptutorial.bat
The system cannot find the path specified.

### Expected Behavior

how to add the bat file has a asset 

### To Reproduce

 package.json 

"pkg": {
    "assets": "views/**/*.*",
    "targets": [
      "node16-win-x64"
    ],
    "outputPath": "dist"
  },

 
  
const bat = spawn(
  `"${path.join(__dirname, '/views/ziptutorial.bat')}"`,
  ['/y'],
  {
    shell: true,
  }
);

**Comment by robertsLando** [comment]
Assets must be an array of paths
