### ISSUE TITLE
Checksum issue with built binary

### ISSUE THREAD

**Issue by rainwashed** [vercel/pkg#1625]
### What version of pkg are you using?

5.6.0

### What version of Node.js are you using?

v16.14.2

### What operating system are you using?

Windows 10 Build 19044

### What CPU architecture are you using?

amd64

### What Node versions, OSs and CPU architectures are you building for?

node14-win-x64

### Describe the Bug

**pkg** is providing different checksums for the same, unmodified, JavaScript project. 

I am using PowerShell's default ``Get-FileHash .\binary.exe | Format-List`` yet every time I build a new binary with ``pkg .``, a new checksum is created even though nothing has changed.

### Expected Behavior

The compiled binary should provide the same checksum rather than different ones if the source code for the JavaScript was never changed.

### To Reproduce

First build:
![image](https://user-images.githubusercontent.com/60084007/167740192-1db0452e-0404-40b2-9704-9b552587756d.png)

Second build:
![image](https://user-images.githubusercontent.com/60084007/167740248-d128deb4-11b4-4d66-97f4-d456b810fbbe.png)

Code that is being "compiled":
```js
console.log("Hello World!");
```

**Comment by robertsLando** [comment]
https://github.com/vercel/pkg#why-would-you-want-to-do-this
