### ISSUE TITLE
Node 18.1.0

### ISSUE THREAD

**Issue by lucenelletenebre** [vercel/pkg#1630]
### What version of pkg are you using?

5.6.0

### What version of Node.js are you using?

v18.1.0

### What operating system are you using?

Debian 11

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node18

### Describe the Bug

Compilation fails (does not even start)
> pkg@5.6.0
> Error! No available node version satisfies 'node18'

### Expected Behavior

Compilation success.
I expected that after adding node18 to pkg-fetch it should be available to pkg.

### To Reproduce

You can use the example in
[pkg](https://github.com/vercel/pkg)/[examples](https://github.com/vercel/pkg/tree/main/examples)/[express](https://github.com/vercel/pkg/tree/main/examples/express)

substitute inside [pkg](https://github.com/vercel/pkg)/[examples](https://github.com/vercel/pkg/tree/main/examples)/[express](https://github.com/vercel/pkg/tree/main/examples/express)/package.json
`"targets": [
      "node8"
    ]`
with
`"targets": [
      "node18"
    ]`

**Comment by hellower** [comment]
I'm also waiting for new PKG release.

**Comment by Leoff00** [comment]
I think that they're still working in one new release for latest node versions, meanwhile you need to generate in previous versions.

**Comment by lucenelletenebre** [comment]
> I think that they're still working in one new release for latest node versions, meanwhile, you need to generate in previous versions.

No problem, I just thought that it should be traced somewhere that it does still not work on node 18.
There was a pull request #1594 and it was clear that we needed to wait for node 18 in
 [pkg-fetch](https://github.com/vercel/pkg-fetch)... but now it seems that node 18 is available there... hopefully it is just an issue of not having enough time to work on this and not some strange compatibility issue...

**Comment by jesec** [comment]
pkg now supports Node 18.

**Comment by OmgImAlexis** [comment]
Should the range in the README be updated to show node18 support?

```
nodeRange (node8), node10, node12, node14, node16 or latest
```

https://github.com/vercel/pkg/blob/main/README.md#targets

**Comment by tisonkun** [comment]
It seems that the node versions that can be selected on the General page are still "14" and "16":

![image](https://user-images.githubusercontent.com/18818196/194538540-338427e2-1b7c-4f47-83b1-b062f8e3e6ac.png)

I don't know whether this issue can infer an upgrade to release this restriction?

My use case is also to use the bundled `fetch` instead of `node-fetch` that causes several issues.

**Comment by donhessman** [comment]
@jesec I see that you closed this issue but I am still unable to use Node 18 in my deploys. (See @tisonkun 's screenshot above). Any updates on when we can expect to be able to select 18 in this dropdown?

**Comment by whyboris** [comment]
Confirming I was unable to use node 18 
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/17264277/201708863-af0ee33a-0db3-4ebe-b78c-c33e25530f47.png">

**Comment by whyboris** [comment]
Thank you @wadehammes -- looks like AWS Lambda is supporting it with a _beta_ image already and should support  _Node 18_ within "a few more weeks"

https://github.com/aws/aws-lambda-base-images/issues/47#issuecomment-1292011841 🤞

**Comment by whyboris** [comment]
@jesec -- unsure if _this_ issue should be re-opened until _Vercel_ supports _Node 18_ 🤔 

If you happen to know the expected timeline, could you comment? 😊
