### ISSUE TITLE
Error! No available node version satisfies ...

### ISSUE THREAD

**Issue by ludydoo** [vercel/pkg#1636]
### What version of pkg are you using?

5.7.0

### Which version(s) of pkg work for you?

5.6.0

### What version of Node.js are you using?

lts-slim

### What operating system are you using?

Linux a2c29b7ee5c7 5.17.6-300.fc36.x86_64 #1 SMP PREEMPT Mon May 9 15:47:11 UTC 2022 x86_64 GNU/Linux

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14.19.1-alpine-x64

### Describe the Bug

We have an automated pipeline that was running on 5.6.0. 
We didn't pin it so it started using 5.7.0 yesterday
We fail to fetch the node binaries now 

> Error! No available node version satisfies 'node14.19.1'

### Expected Behavior

Be able to fetch node binaries

### To Reproduce

npx pkg bla.js --target node14.19.1-alpine-x64 --output /main

**Comment by jesec** [comment]
You have to use 14.19.2 by now.
