### ISSUE TITLE
.node files not being bundled properly.

### ISSUE THREAD

**Issue by Lucky38i** [vercel/pkg#1638]
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

16.14.1

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-win-x64

### Describe the Bug

I'm using `skia-canvas` for some image maniupulation work however PKG doesn't seem to be including the `index.node` when copying over to the temp pkg folder
![Screenshot 2022-05-19 at 18 45 50](https://user-images.githubusercontent.com/26572019/169364389-ca832528-5d4d-4706-8b7c-b8f443f4bcb3.png)
.

### Expected Behavior

the node executable should be bundled properly.

### To Reproduce

I don't really have a reproducible example. 
my assets just in case.
![Screenshot 2022-05-19 at 18 51 55](https://user-images.githubusercontent.com/26572019/169365420-cf4fadbd-7ad6-4a25-9389-ae4282990d09.png)
.

**Comment by robertsLando** [comment]
Try to put /** instead of `/*` and enable debug in pkg using `-d` flag to see if it is packaged into the executable

**Comment by Luka-2005** [comment]
I am getting the same error, the module is packaged and if I open the folder in the windows explorer the .node file is there, but nodejs is not able to require it.

**Comment by Lucky38i** [comment]
So after running debug I'm getting this error
![Screenshot 2022-05-24 at 15 37 50](https://user-images.githubusercontent.com/26572019/170062363-6af494d0-7538-4c0c-a34b-67471a539c24.png)

**Comment by erm3nda** [comment]
Sorry, didn't pay attention to the windows claim, try with correct path slashes `"assets": ["node_modules\\skia-canvas\\lib\\**\\*.*"]`

**Comment by Lucky38i** [comment]
Unfortunately no luck. same issue and same error when trying to execute the output .exe

**Comment by Lucky38i** [comment]
@erm3nda solution seems to have worked
my assets now looks like
```json
"assets": [
  "node_modules/skia-canvas/**/*.*",
  "node_modules/canvas/**/*.*",
]
```
there's some other packages like `pdfjs` and `node-hide-window-console` that doesn't seem to be bundled, regardless of adding it to the assets. For that case those packages need to be packaged with the generated executable. Bit of a nuisance but I suppouse that's an issue with the packages themselves and not `pkg`
![Screenshot 2022-05-24 at 18 37 20](https://user-images.githubusercontent.com/26572019/170097923-b4867241-a6b3-4015-b519-18ca0b6af826.png)
