### ISSUE TITLE
Error: Cannot mkdir in a snapshot. Try mountpoints instead.

### ISSUE THREAD

**Issue by amiralam0** [vercel/pkg#1639]
### What version of pkg are you using?

5.6.0

### What version of Node.js are you using?

v16.15.0

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

default

### Describe the Bug

i am compiling "macaca-cli" repository, and it is compiling successfully into exe.
but when i run the application it gives me this error

```
pkg/prelude/bootstrap.js:1833
      throw error;
      ^

Error: Cannot mkdir in a snapshot. Try mountpoints instead.
    at mkdirFailInSnapshot (pkg/prelude/bootstrap.js:1593:7)
    at Object.mkdirSync (pkg/prelude/bootstrap.js:1605:12)
    at Object.sync [as mkdir] (C:\snapshot\macaca-cli-master\node_modules\mkdirp\index.js:74:13)
    at Logger._init (C:\snapshot\macaca-cli-master\node_modules\xlogger\lib\xlogger.js:44:5)
    at new Logger (C:\snapshot\macaca-cli-master\node_modules\xlogger\lib\xlogger.js:40:8)
    at Object.<anonymous> (C:\snapshot\macaca-cli-master\node_modules\xlogger\lib\xlogger.js:172:18)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

### Expected Behavior

It should run the compiled app

### To Reproduce

just compile "macaca-cli" repository and run it.

**Comment by robertsLando** [comment]
The path where it tries to write is inside the snapshot filesystem, just provide a different path. Read https://github.com/vercel/pkg#snapshot-filesystem

**Comment by amiralam0** [comment]
so do I need to edit all required paths of the repository which I am trying to make into the executable?

**Comment by robertsLando** [comment]
I suggest to create a central method getPath in utils and based on if the path is inside or outside snapshot it returns the correct one

```js
function getPath(write) {
	if (write && process.pkg) return process.cwd()
	return projectPath
}
```

**Comment by amiralam0** [comment]
> I suggest to create a central method getPath in utils and based on if the path is inside or outside snapshot it returns the correct one
> 
> ```js
> function getPath(write) {
> 	if (write && process.pkg) return process.cwd()
> 	return projectPath
> }
> ```

var update = require('npm-update');

this is causing this error,
when I comment out this line, everything working!

can anybody tell me how to fix the snapshot error? which is caused by this line of code

**Comment by robertsLando** [comment]
you should write a patch for npm-update

See example [here](https://github.com/vercel/pkg/issues/1419#issuecomment-997982346)

**Comment by amiralam0** [comment]
is this correct?

`"pkg": {
    "scripts": [
      "./node_modules/npm-update/lib/npm-update.js",
    ],
    "patches": {
			 "./node_modules/npm-update/lib/npm-update.js": ["fn = (await realImport(workerData.filename)).default", "fn = realRequire(workerData.filename.replace('file://', ''))"]
		}
  },`

**Comment by robertsLando** [comment]
@amiralam0 I dunno if it is correct, what I suggest before creating the patch is to manually edit the source code inside `node_modules` folder of `npm-update` package, pack it using pkg, if the change is working create a patch to  match the changes

**Comment by robertsLando** [comment]
BTW the error IMO is here:

```
\node_modules\xlogger\lib\xlogger.js:44:5
```

I think this `xlogger` module by default stores the log or else in a directory inside node_modules folder
