### ISSUE TITLE
appendFileSync has a very slow performance against original nodejs

### ISSUE THREAD

**Issue by AHgPuK** [vercel/pkg#165]
It is very remarkable dropdown in writing speed (Almost x10).
Checked in versions pkg@4.x.x
Not checked prior version 4.

The original nodejs writes very fast and takes up to 25% of CPU time.
pkg is up to 5% and all the application is stuck sometimes.

**Comment by igorklopov** [comment]
Can you provide the code that made you think so?

**Comment by AHgPuK** [comment]
[pkg-test.zip](https://github.com/zeit/pkg/files/1151102/pkg-test.zip)
Sure. The issue is easy to reproduce.
Run with node - 18 seconds
Run built executable >200 seconds

**Comment by igorklopov** [comment]
Well, my times are almost equal. Tested on node4/node6/node8, pkg@4.0.0, MacOS EC, SSD. What OS and disk type do you use to test (SSD/rotational) ?

**Comment by AHgPuK** [comment]
Hi, Igor!
I tested under Windows 8.1 64-bit and rotational HDD 7200rpm
