### ISSUE TITLE
 Warning Failed to make bytecode node14-arm64

### ISSUE THREAD

**Issue by patsonkaushik** [vercel/pkg#1654]
### What version of pkg are you using?

5.7.0

### What version of Node.js are you using?

12.12.12

### What operating system are you using?

Ubuntu 

### What CPU architecture are you using?

armv7l

### What Node versions, OSs and CPU architectures are you building for?

node14-win-arm64

### Describe the Bug
![rest_1](https://user-images.githubusercontent.com/77775964/173551449-2c05a69d-7477-4d1d-a07d-9382f04dc63c.png)

### Expected Behavior
Raspberry Configuration
![Screenshot_2](https://user-images.githubusercontent.com/77775964/173566439-ac770e42-cc4d-4933-9316-d27ca62439b7.png)

I expected that i can put the file at anywhere and run it from anywhere, not depend on origin source code.

Please help me about that.

### To Reproduce

Here is build command:
pkg . 

Here is my build script in package.json file:
"bin": {
    "myapp": "main.js"
  },
  "pkg": {
    "scripts": "build/**/*.js",
    "assets": [
      "node_modules/**/*"
    ],
     "targets": [ "node12-linux-arm64" ],
    "outputPath": "dist"
  }

,

**Comment by jesec** [comment]
See https://github.com/vercel/pkg#targets.
