### ISSUE TITLE
Not found in remote cache: node16-win-x86 

### ISSUE THREAD

**Issue by paulsmithkc** [vercel/pkg#1685]
### What version of pkg are you using?

5.7.0

### What version of Node.js are you using?

16.16.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

Apple M1

### What Node versions, OSs and CPU architectures are you building for?

node16-win-x86

### Describe the Bug

When I try to make a build for target: `node16-win-x86`

I am seeing the following error message:

```
> pkg@5.7.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v16.15.0-win-x86            [                    ] 0%
> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.4","name":"node-v16.15.0-win-x86"}
```

### Expected Behavior

Build succeeds without error.

### To Reproduce

1. nvm install 16
2. Create a project
3. Configure a target of node16-win-x86 in package.json
4. pkg .

**Comment by JamesAngier** [comment]
This is what i get when running the above, if i use node14 i get stuck with 
Could not find NASM, install it or build with openssl-no-asm. See BUILDING.md.

> pkg@5.7.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v16.15.0-win-x86            [                    ] 0%
> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.4","name":"node-v16.15.0-win-x86"}
> Building base binary from source:
  built-v16.15.0-win-x86
> Error! Not able to build for 'win' here, only for 'macos'

**Comment by maksgithub** [comment]
https://github.com/vercel/pkg/issues/1685#issue-1298240056
I have same problem

**Comment by maksgithub** [comment]
> BUILDING.md.

1. Install https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/
2. Add System Environment Variable Path -> C:\Program Files\NASM

**Comment by paulsmithkc** [comment]
Not resolved.

**Comment by ThinhVu** [comment]
> Not resolved.

Do you know where the cache is stored?
