### ISSUE TITLE
 Error: Cannot find module './pdf.js/v1.10.100/build/pdf.js'

### ISSUE THREAD

**Issue by simaybocu** [vercel/pkg#1687]
### What version of pkg are you using?

5.7.0

### What version of Node.js are you using?

14.16.1

### What operating system are you using?

Windows

### What CPU architecture are you using?

Intel(R) Core(TM) i7-7500U

### What Node versions, OSs and CPU architectures are you building for?

node14-win-arm64

### Describe the Bug

Although the pdf-parse package is in node_modules, it gives this error when I run the exe. Can you please help?

### Expected Behavior

what can I do

### To Reproduce

![2022-07-08](https://user-images.githubusercontent.com/33957028/177926750-2fc766a4-3509-4869-b83f-bb2bbcae4593.png)

**Comment by robertsLando** [comment]
Add it to assets in package.json

**Comment by roydbt** [comment]
Mind sharing how you added it?
I tried putting
```json
"pkg": {
  "scripts": "index.js",
  "assets": [
    "./pdf.js/v1.10.100/build/pdf.js",
    "credentials.json"
  ],
  "targets": [
    "latest-win-x64"
  ]
}
```
inside `package.json`, ut both the `pdf-parser` module and `credentials.json` didn't get bundled into the exe file.

**Comment by Apollinaire** [comment]
It's a js file, so add it to scripts instead of assets. I used the full glob for the `lib` folder, and referenced directly the node_modules folder like so:
```json
  "pkg": {
    "scripts": [
      "node_modules/pdf-parse/lib/**/*.js"
    ],
  }
```
