### ISSUE TITLE
ffmpeg executable file failed to run properly after being bundled with pkg

### ISSUE THREAD

**Issue by hnguyen48206** [vercel/pkg#1696]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

14.16.0

### What operating system are you using?

Windows 10 x64

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-win-x64

### Describe the Bug

Hi,

I'm making an a nodejs app (being bundled as an executable) that does a simple job as converting video stream to images and deliver them to web frontend using socket.io. I have used ffmpeg-static to include the ffmpeg.exe (for example in windows) within the node-modules folder. The problem is ffmpeg fails immediately after being called through a sub process (spawn) in the final executable but this is not the case when simply run my project as "node app.js". Any suggestion would be much appriciated.

Best Regards.

### Expected Behavior

Being able to run ffmpeg standalone file within the bundled app.

### To Reproduce

Here is where i host the example app: https://bitbucket.org/hn162/pkgtest/src/master/ 

You guys can just clone it and then run to see the error. The index.html file has been included in views folder too for the testing purpose (simply replace the streamURL with any working stream of your choice).

**Comment by JP-tech-sh** [comment]
As with native addons you need to include your static binary on pkg assets in your package.json or in the  pkg cli options

**Comment by hnguyen48206** [comment]
> As with native addons you need to include your static binary on pkg assets in your package.json or in the pkg cli options

Thank you sir for your timely response. I did try to move and include the ffmpeg.exe file to the root folder and declare it in package.json. Both ways either works just fine. However, I do not think that the problem is about the file path since the app in runtime actually can reach to the file and run ffmpeg command, it just fails shortly right after that which is not the case when not being bundled.

**Comment by Sacha-Bombard** [comment]
Same issue. By using `node ./main.js` there is no problem but, by using the application after packing it ,I've got this error ...
```shell
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn /snapshot/Application/node_modules/ffmpeg-static/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /snapshot/Application/node_modules/ffmpeg-static/ffmpeg',
  path: '/snapshot/Application/node_modules/ffmpeg-static/ffmpeg',
  spawnargs: [
    '-loglevel',
    '8',
    '-hide_banner',
    '-i',
    'pipe:4',
    '-i',
    'pipe:5',
    '-map',
    '0:a',
    '-map',
    '1:v',
    '-c:v',
    'copy',
    '../Moby - Porcelain.mkv'
  ]
}

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by hnguyen48206** [comment]
For now, I have to switch back to use the external ffmpeg installed on client's machine which is not really desirable and portable in term of distribution and deployment. Hope there might be some progress in this matter.

**Comment by reekoz** [comment]
I manage to work adding `./node_modules/@ffmpeg-installer/**` on pkg `assets` in `package.json`

**Comment by deepak-ttpl** [comment]
How to do the same with windows?
