### ISSUE TITLE
[Feature request] Possibility to disable auto assets detection

### ISSUE THREAD

**Issue by Avaray** [vercel/pkg#170]
Like in title. Simple option to disable auto packing assets.
https://github.com/zeit/pkg#detecting-assets-in-source-code

**Comment by igorklopov** [comment]
What particular case you need it for? Please give code example.

**Comment by paul-sanchez** [comment]
Hi.
In my case, I need my code work with dynamic JS files. I want distribute my core and let another users create addons in JS for my program.

`let userAddon = require(path.resolve(__dirname, 'addons','example.js'))`

I would also need that "__dirname" have its natural behavior.

Thanks.

**Comment by tmende** [comment]
Something like  `let userAddon = require(path.join(process.cwd(), 'addons', 'example.js'))` works fine for me in a similar use case.

**Comment by paul-sanchez** [comment]
Oh. Thanks... that help... I don understand that point in the documentation. Sorry.
