### ISSUE TITLE
Fail to run an app containing "canvas" as a dependency

### ISSUE THREAD

**Issue by valerachuk** [vercel/pkg#1714]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

v16.15.0

### What operating system are you using?

Microsoft Windows 10 Pro Version 10.0.19044 Build 19044

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-win

### Describe the Bug

An app with [`canvas`](https://www.npmjs.com/package/canvas) dependency fails in run-time with the following error:

```
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: The specified module could not be found.
C:\Users\XXXX\AppData\Local\Temp\pkg\434b320e8c34135806be5b94815f72cead7762c58c36bd8786b11a443d1ed074\canvas\build\Release\canvas.node
    at process.dlopen (pkg/prelude/bootstrap.js:2255:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\pkgcanvastest\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

The error message is a little confusing because the folder `C:\Users\XXXX\AppData\Local\Temp\pkg\434b320e8c34135806be5b94815f72cead7762c58c36bd8786b11a443d1ed074\canvas\build\Release\` contains `canvas.node` - only `canvas.node`.

But `node_modules\canvas\build\Release\` contains  `canvas.node` + DLLs

I copied `node_modules\canvas\build\Release\` to `C:\Users\XXXX\AppData\Local\Temp\pkg\434b320e8c34135806be5b94815f72cead7762c58c36bd8786b11a443d1ed074\canvas\build\Release\`.

The app has started working, but copying DLLs into the temp folder is not the solution 🤣

### Expected Behavior

Running `index.exe` should output "hello" instead of failing

### To Reproduce

1. Create an empty folder
2. Create `package.json` with the following content:
```
{
  "scripts": {
    "build": "pkg -t node16-win index.js"
  },
  "dependencies": {
    "canvas": "2.9.3",
    "pkg": "5.8.0"
  }
}
```

3. Create `index.js` with the following content:
```
require("canvas");
console.log("hello");
```

4. Run `npm i`
5. Run `npm run build`
6. Run `index.exe`

**Comment by marttinnotta** [comment]
Have you read and followed through [this "Native addons" part](https://github.com/vercel/pkg#native-addons) in readme file? From your package.json it seems not - try it out first.

**Comment by valerachuk** [comment]
Yeah, I tried different configurations but still no luck
```json
{
  "scripts": {
    "build": "pkg -t node16-win index.js"
  },
  "dependencies": {
    "canvas": "2.9.3",
    "pkg": "5.8.0"
  },
  "pkg": {
    "assets": "node_modules/canvas/**/*"
  }
}
```

`canvas.node` is copied as the documentation says
![image](https://user-images.githubusercontent.com/38440869/182964407-cd116976-9583-40ec-b4c5-3a598d7d04c4.png)
But DLLs are missing

**Comment by valerachuk** [comment]
I thought `package.json` is the default value for the `--config` option. I've fixed this by specifying the option explicitly. 

Project with the following `package.json`  works
```json
{
  "scripts": {
    "build": "pkg -c package.json -t node16-win index.js"
  },
  "dependencies": {
    "canvas": "2.9.3",
    "pkg": "5.8.0"
  },
  "pkg": {
    "assets": "node_modules/canvas/**/*"
  }
}
```

**Comment by flyweights** [comment]
🎉🎉🎉

**Comment by y0unjin0h** [comment]
당신은 나의 은인입니다. 너무 감사합니다.
