### ISSUE TITLE
Can't bundle ncc output.

### ISSUE THREAD

**Issue by FrontMage** [vercel/pkg#1729]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

17.9.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

Apple M1

### What Node versions, OSs and CPU architectures are you building for?

node14-linux-x64

### Describe the Bug

Can't bundle the output of `ncc`, I was trying to bundle everything with ncc first then pkg them together.
```bash
> Error! Invalid left-hand side in assignment expression (6717:19)
```

### Expected Behavior

That ncc output can be bundled by pkg.

### To Reproduce

Any node js application will do, just try ncc first then try to bundle the output.

**Comment by robertsLando** [comment]
ncc outputs esm modules AFAIK, you should use an older ncc version or a boundler that converts them to commonjs as esm are not supported by pkg yet

**Comment by FrontMage** [comment]
@robertsLando Thx! I'll try install the older version
