### ISSUE TITLE
Linux result says permission denied when running it.

### ISSUE THREAD

**Issue by Grayseon** [vercel/pkg#1739]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

18.7.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

arm64

### What Node versions, OSs and CPU architectures are you building for?

node18-linux-x64

### Describe the Bug

When running the result of a Linux build, it gives the error: "Permission denied"
I am running this on a virtual machine.

### Expected Behavior

It should say "Hello World" when run

### To Reproduce

Create a new nodejs project and a file named "index.js" with
``console.log('Hello World!')``
in it. Then run 
``pkg index.js``
and run the result in a Linux environment.

**Comment by 0xARK** [comment]
Hey ! Did you manage to solve it ? I have the same problem but generating from linux and running on macos.

**Comment by Grayseon** [comment]
Hi, I did fix this. I think all you have to do is package it natively (from the OS you want to build it from) sadly, but you can use a VM.

**Comment by 0xARK** [comment]
I finally manage to make it works, after further investigation customer was trying to execute the directory instead of the binary x)

**Comment by xuakson** [comment]
> I finally manage to make it works, after further investigation customer was trying to execute the directory instead of the binary x)

How did you do this boss?

**Comment by 0xARK** [comment]
I'm just running `pkg index.js -t lin,win,mac` on my Ubuntu 18.04 vm, and then distribute exe, mac or linux binary in function of customer machine. Then you can execute it on linux + max using ./index and by double-clicking on windows (or using ./index too).

**Comment by xuakson** [comment]
Ait, Sir let me try it now and give a feed back , i'm using vps ubuntu 20

**Comment by xuakson** [comment]
@0xARK , i have compiled the linux file but seems its run but stacked , not running the file.

**Comment by xuakson** [comment]
@0xARK I got this error, when i run it , using an ini file 
```
: Connection timeout
    at SMTPConnection._formatError
```

**Comment by Grayseon** [comment]
Hi, SMTPConnection means something with email, right? Are you sending emails with your app? (Keep in mind that the exe can be read with a hex reader and all the passwords would be visible.) Thanks!
