### ISSUE TITLE
Script runs perfectly, but exe returns error

### ISSUE THREAD

**Issue by eAlexandrohin** [vercel/pkg#1748]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

v18.7.0

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

fetched-v18.5.0-win-x64

### Describe the Bug

Simple checking in switch if property of error equals needed one. 
```javascript
switch (true) {
  case (err.code === 'EEXIST'):
  // code
  break;
}
```
And while it runs as script normally, through `node ds`, the same code packed in exe returns error:
```
node:fs:201
  return (...args) => ReflectApply(cb, this, args);       
                      ^

TypeError: Cannot read properties of null (reading 'code')
    at C:\snapshot\ds\ds.js
    at FSReqCallback.oncomplete (node:fs:201:23)

Node.js v18.5.0
```

### Expected Behavior

Do not return error.

### To Reproduce

Make a async directory via fs and on callback try to get property of error or check its value without `if (err) {/*stuff*/}` block. 
```javascript
fs.mkdir(path, null, (err) => {
  switch (true) {
    case (err.code === 'EEXIST'): someFunc(); break;
    case (err): console.error(err); break;
    default: someFunc();
  };
});
```

**Comment by mehiatt** [comment]
I am also seeing something similiar with 
`TypeError: zmq.zmqVersion is not a function`
in a JS file in node_modules. While my main project is in ts - I have converted them to js files for this project. 
There is no typescript at this point, so I have no idea why TS errors are showing.
