### ISSUE TITLE
ascii encoding not supported exception in Package exe

### ISSUE THREAD

**Issue by anwarjaved** [vercel/pkg#1783]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

14.17.5

### What operating system are you using?

Windows 2012 Server

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

node14-win-x64

### Describe the Bug

throwing ascii encoding not supported exception but it works file if I run it directly fron nodejs

### Expected Behavior

It Should run file like its running locally in nodejs

### To Reproduce

![image_2022_10_14T17_15_33_798Z](https://user-images.githubusercontent.com/99399/195912116-f018c7c7-afba-47ca-95da-5de03c35b97c.png)

**Comment by TransparentLC** [comment]
Fontkit uses a `new TextDecoder('ascii')` to [parse file headers in font files](https://github.com/foliojs/fontkit/search?q=asciiDecoder).

Pkg's pre-built Node.js is built with small-icu but not the full icu data, so the packaged executable can't use [encodings](https://nodejs.org/api/util.html#whatwg-supported-encodings) other than `utf-8`, `utf-16`, `utf-16be` in `TextDecoder`.

**Comment by TransparentLC** [comment]
I write a naive polyfill of the `new TextDecoder('ascii')`. Use it before importing fontkit:

```js
try {
    new TextDecoder('ascii');
} catch {
    const TD = globalThis.TextDecoder;
    globalThis.TextDecoder = class {
        constructor(encoding, options) {
            this.td = encoding === 'ascii' ? null : new TD(encoding, options);
        }

        decode(input, options) {
            if (this.td) return this.td.decode(input, options);
            let r = '';
            for (let i = 0; i < input.length; i++) r += String.fromCharCode(input[i]);
            return r;
        }
    };
}
```

**Comment by TBG-FR** [comment]
If you want to get full-icu into pkg, here you go : https://github.com/vercel/pkg/issues/1731#issuecomment-1317191357
That fixes locales issues, so I think that should also fix ASCII/encoding issues
