### ISSUE TITLE
Can't chdir to /snapshot dir (or subdirectories)

### ISSUE THREAD

**Issue by Malabarba** [vercel/pkg#1791]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

18.5.0

### What operating system are you using?

Ubuntu 22.04.1 LTS

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

18.5.0

### Describe the Bug

The `/snapshot`  filesystem, although it can be read by `fs` operations, looks like it can't be chdir'd to with `process.chdir()`.

### Expected Behavior

I wold expect code containing `process.chdir("/snapshot")` to compile and run without errors

### To Reproduce

Save the following code as `index.js` 
```js
const fs = require("fs");
console.log(fs.readdirSync("/snapshot"));
process.chdir("/snapshot");
```

then do `pkg ./index.js --targets node18-linux-x64 && ./index`.

Line 2 will correctly print the list of files in the `/snapshot` directory, but line 3 will error out with the following error:
```
node:internal/bootstrap/switches/does_own_process_state:112
  rawMethods.chdir(directory);
             ^

Error: ENOENT: no such file or directory, chdir '/PROJECT' -> '/snapshot'
    at wrappedChdir (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at process.chdir (node:internal/worker:99:5)
    at Object.<anonymous> (/snapshot/test-pkg/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chdir',
  path: '/PROJECT',
  dest: '/snapshot'
}
```

**Comment by Malabarba** [comment]
(Also tested with node 16 and 14, for what it's worth)

**Comment by Malabarba** [comment]
(Also, looks like it was brought up in discussions back in April: https://github.com/vercel/pkg/discussions/1576 )

**Comment by drewbitt** [comment]
I can confirm this in node 16.18.1, ubuntu 22, x86_64 as well. It came up with a pkg of a simple `nextjs` app.

**Comment by leeahoward** [comment]
I am having the same issue using node 16.18.1 and next.js 12.2.5. Are there any workarounds for this?

**Comment by drewbitt** [comment]
I am still experiencing this.

**Comment by drewbitt** [comment]
I don't believe Vercel is much interested in maintaining this now that node 18.16 supports single executable applications itself. https://nodejs.org/api/single-executable-applications.html

**Comment by wdelgenio** [comment]
I'm also experiencing this issue, and if vercel isn't going to fix it then `pkg` might just be untenable.

**Comment by robertsLando** [comment]
For anyone that is interested in this project, giving that I don't receive any feedback from Vercel anymore, I created my own forks of both pkg and pkg-fetch:

[yao-pkg/pkg-fetch](https://github.com/yao-pkg/pkg-fetch)
[yao-pkg/pkg](https://github.com/yao-pkg/pkg)

If someone is interested in helping me create a PR or move your active PR to those repositories.

Thanks 🙏🏼
