### ISSUE TITLE
pkg/prelude/bootstrap.js:1876  Throw error; Error: Invalid filename

### ISSUE THREAD

**Issue by AndresQuiVal** [vercel/pkg#1793]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

16.17.0

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

Windows 10 only

### Describe the Bug

When building the `.exe` with this command:

`pkg index.js --targets node16-win-x64`

It succesfully creates the .exe for windows, then when executing it via cmd, it appears the following log:

```
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Invalid filename
```

I tried debugging the .exe creation process, yet no error seems to appear, not warning.

here the `package.json`

```
{
  "name": "cf-solver",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.27.1"
  },
  "dependencies": {
    "@zennolab_com/capmonstercloud-client": "^0.0.14",
    "body-parser": "^1.20.1",
    "express": "^4.18.2",
    "got-scraping": "^3.2.11",
    "pkg": "^5.4.1",
    "playwright": "^1.27.1"
  }
}

```

### Expected Behavior

The program is supposed to run a local server under port 3000, but nothing happens when executing the .exe

### To Reproduce

1. Create the .exe with `pkg index.js --targets node16-win-x64`
2. Execute the `.exe` in cmd to see logs
3. The following appears:
  ```
.pkg/prelude/bootstrap.js:1876
        throw error;
        ^
  
  Error: Invalid filename
```

**Comment by pravinba9495** [comment]
Same issue happens with Ubuntu 22.04 
<img width="640" alt="Screenshot 2023-10-09 at 2 42 27 AM" src="https://github.com/vercel/pkg/assets/25143158/cab0f06b-78af-4367-b70c-61c569bb9f2b">

**Comment by pravinba9495** [comment]
Binary was compiled using `pkg -C -t node18-x64 -o binaries/api dist/server/src/index.js`

**Comment by omarabdula** [comment]
Hello any help????

D:\nc\api-faturacao\build>index.exe
pkg/prelude/bootstrap.js:1872
throw error;
^

Error: File 'C:**\api-faturacao\node_modules@foliojs-fork\linebreak\src\classes.trie' was not included into executable at compilation stage. Please recompile adding it as asset or script.
at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
at Object. (C:\snapshot\api-faturacao\node_moduleshttps://github.com/foliojs-fork\linebreak\src\linebreaker.js:7:36)
at Module._compile (pkg/prelude/bootstrap.js:1926:22)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at Module.require (pkg/prelude/bootstrap.js:1851:31) {
errno: -4058,
code: 'ENOENT',
path: 'C:\snapshot\api-faturacao\node_modules\@foliojs-fork\linebreak\src/classes.trie',
pkg: true
}
