### ISSUE TITLE
> vars in ".env" file not take in external folder 

### ISSUE THREAD

**Issue by Icammarano** [vercel/pkg#1797]
> Here's an [example](https://github.com/shaunwarman/baked-pkg/blob/master/package.json#L14-L16) of what I am currently doing.
> 
> I just add the token (`cat $TOKEN >> .env` or similar) in at CI and use this CI to `pkg` the tool.

Hello, I downloaded your code, I did the npm install, then I ran the "npm run pack". Once the package is created, copy the contents to a folder external to the project (which you should be able to). 
And when executed "./bake", it still does not take the environment variables defined in the .env, in this case TOKEN, since it returns "undefined". 
But if I run it inside the project folder "baked-pkg-master" it works, and get TOKEN=123. 
I don't understand why there is no way to take the environment variables outside the folder project. 
I appreciate help please!
Thx

_Originally posted by @Icammarano in https://github.com/vercel/pkg/issues/358#issuecomment-1310354854_

**Comment by Icammarano** [comment]
I found the solution replacing the path to env file in dotenv config.

`const path = require('path');

require('dotenv').config({
  path: path.join(__dirname, '.env')
});`

**Comment by appasaheb4** [comment]
> 

not working 😞

**Comment by robertsLando** [comment]
This is explained in readme, the path to files need to be set based on if them are shipped with binary (so use snapshot path) or if them are in the root folder where the binary is

**Comment by vorian77** [comment]
My environment is a node.js app that runs as a service on a windows server requiring distinct .env files for development and production. 

1. The entry file is named: app.js
2. The development .env file is located in the same directory as app.js.
3. The pkg'd file is named: app.exe
4. The production .env file is located in the same directory as app.exe on the windows server.

```
// app.js
const path = require('path');
require('dotenv').config({ path: path.join(process.cwd(), '.env')});
const httpsKey = process.env.API_KEY;  // API_KEY is specified in the .env files
```
