### ISSUE TITLE
[Feature suggestion] Make bundler optional

### ISSUE THREAD

**Issue by nuxlli** [vercel/pkg#181]
It would be interesting to have an option to disable the internal pkg bundler. This would allow the coupling of an external tool for that purpose, in my case I am using http://fuse-box.org

I made a few attempts to change the code, but it was a bit more complex than expected. If it is in the interest of anyone else I can work on a patch, what do you think?

**Comment by igorklopov** [comment]
You can bundle your project with fuse-box, get output bundle file and compile the file with pkg. What do you think of it?

**Comment by vweevers** [comment]
+1. Currently one has to rename `require` statements to bypass pkg's bundling. For example, if you want to use browserify instead (I'm not familiar with fuse-box but expect it's similar):

```
browserify --node --no-dg cli.js | derequire > bundle.js
pkg bundle.js
```

If would be great if:

1) pkg would accept stdin input
2) indeed had an option to disable bundling

So you could do something like:

```
browserify --node --no-dg cli.js | pkg --no-bundle --output my-app
```

I realize there's more to it: pkg also does asset detection, transforms `__filename` etc. So you might want options for those too. I'm just spitballing here. Say you want browserify to inline assets:

```
browserify --node --no-dg -t brfs cli.js | pkg --no-bundle --no-assets --output my-app
```

Or disable all these pkg features (avoiding an explosion of options):

```
browserify --node -t brfs cli.js | pkg --bare --output my-app
```

Alternatively, would it be possible to decouple the pkg bundler? I.e. write a lower-level tool that takes input code as a snapshot as-is?

**Comment by igorklopov** [comment]
Well, ok, i understand your points. But why do you need to place everything in one file? Is there a tradeoff when you keep all transformations of your tool, but output the same directory structure to `build` directory (instead of one file)? This is how `pkg` was intended to be used with transpilers like `babel` and `flow`.

**Comment by vweevers** [comment]
> But why do you need to place everything in one file?

That's how browserify works. I admit, it's somewhat a case of "using what I know and love". Generally speaking though, I'm a fan of the unix philosophy. The benefit of a single file - or rather, a standard stream - is you can pipe it into whatever. For example: `browserify [..] | derequire | uglifyjs | pkg`.

As for transpilers, if I needed it (kind of beats the point of pkg, at least when targeting latest node), I'd probably do `browserify -t babelify`.

**Comment by xblox** [comment]
same here, need to exclude quite some stuff from the bundler.
