### ISSUE TITLE
VFS format documentation

### ISSUE THREAD

**Issue by 3niol4** [vercel/pkg#1818]
I'm trying to understand the format of the VFS included in the final files. Is it documented somewhere?

**Comment by robertsLando** [comment]
What you mean with format?

Anyway the only docs available right now are: https://github.com/vercel/pkg/wiki/Developers

**Comment by 3niol4** [comment]
I did, but it doesn't make everything super clear, guess I'll go through the code. The packing code is in the `packer.ts` file, right?

**Comment by robertsLando** [comment]
Yeah
