### ISSUE TITLE
"latest" target causes building. Need a way to be sure to download

### ISSUE THREAD

**Issue by yamalight** [vercel/pkg#182]
I'm not sure if that's intentional, but I expected `latest-*` targets to always fetch _something_.
Currently if you try using `latest-alpine`, it tries to fetch alpine node v8.2.1 which isn't there, so it fails.
I'd suggest either clarifying in docs that `latest-*` targets can fail, or to change the behaviour to always fetch latest existing version (in this case - fall back to 8.0.0).

Here's the log:
```
$ pkg -t latest-alpine -o exoframe-server .
> pkg@4.1.4
> Fetching base Node.js binaries to: ~/.pkg-cache
  fetched-v8.2.1-alpine-x64    [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.3/uploaded-v2.3-node-v8.2.1-alpine-x64
> Asset not found by direct link:
  {"tag":"v2.3","name":"uploaded-v2.3-node-v8.2.1-alpine-x64"}
> Not found in GitHub releases:
  {"tag":"v2.3","name":"uploaded-v2.3-node-v8.2.1-alpine-x64"}
> Building base binary from source:
  built-v8.2.1-alpine-x64
> Error! Not able to build for 'alpine' here, only for 'macos'
error Command failed with exit code 2.
```

**Comment by igorklopov** [comment]
I discourage you using `latest`. Please specify node version explicitly. Still keeping this issue open to solve eventually.
