### ISSUE TITLE
Warning Failed to make bytecode node16-x64

### ISSUE THREAD

**Issue by wlc015f** [vercel/pkg#1822]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

16.16.0

### What operating system are you using?

macOS 12.2

### What CPU architecture are you using?

Intel Core i5

### What Node versions, OSs and CPU architectures are you building for?

node16-macos-intel

### Describe the Bug

i got warning when using pkg building

16:47:04  - Pkb building...
16:47:04  > pkg@5.8.0
16:47:04  > Warning Cannot stat, ENOENT
16:47:04    /home/jenkins/agent/workspace/CD-job/built/demo/.tmp/on-premises-verify.js
16:47:04    The file was required from '/home/jenkins/agent/workspace/CD-job/built/demo/.tmp/start3305.js'
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/chalk/source/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/inquirer.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/chalk/source/utilities.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/objects/choice.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/objects/choices.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/objects/separator.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/base.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/checkbox.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/confirm.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/editor.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/expand.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/input.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/list.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/number.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/password.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/prompts/rawlist.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/ui/baseUI.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/ui/bottom-bar.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/ui/prompt.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/utils/events.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/utils/incrementListIndex.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/utils/paginator.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/utils/readline.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/utils/screen-manager.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/inquirer/lib/utils/utils.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/ansi-escapes/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/cli-cursor/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/figures/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/ora/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/string-width/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/strip-ansi/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/wrap-ansi/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/axios.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/restore-cursor/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/escape-string-regexp/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/is-unicode-supported/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/ora/utilities.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/is-interactive/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/log-symbols/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/ansi-regex/index.js
16:47:43  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/phoebe/node_modules/ansi-styles/index.js
16:47:45  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/utils.js
16:47:45  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/bind.js
16:47:45  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/Axios.js
16:47:45  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/mergeConfig.js
16:47:45  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/defaults/index.js
16:47:45  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/formDataToJSON.js
16:47:45  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/cancel/CanceledError.js
16:47:45  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/cancel/CancelToken.js
16:47:46  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/cancel/isCancel.js
16:47:46  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/env/data.js
16:47:46  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/toFormData.js
16:47:46  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/AxiosError.js
16:47:46  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/spread.js
16:47:46  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/isAxiosError.js
16:47:48  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/buildURL.js
16:47:48  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/InterceptorManager.js
16:47:48  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/dispatchRequest.js
16:47:48  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/buildFullPath.js
16:47:48  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/validator.js
16:47:48  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/AxiosHeaders.js
16:47:49  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/defaults/transitional.js
16:47:49  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/toURLEncodedForm.js
16:47:49  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/platform/index.js
16:47:49  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/adapters/index.js
16:47:49  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/env/classes/FormData.js
16:47:50  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/AxiosURLSearchParams.js
16:47:50  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/transformData.js
16:47:50  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/isAbsoluteURL.js
16:47:50  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/combineURLs.js
16:47:50  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/parseHeaders.js
16:47:50  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/platform/node/index.js
16:47:51  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/adapters/http.js
16:47:51  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/adapters/xhr.js
16:47:52  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/platform/node/classes/URLSearchParams.js
16:47:52  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/platform/node/classes/FormData.js
16:47:52  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/core/settle.js
16:47:52  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/fromDataURI.js
16:47:52  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/AxiosTransformStream.js
16:47:52  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/cookies.js
16:47:52  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/isURLSameOrigin.js
16:47:52  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/parseProtocol.js
16:47:53  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/speedometer.js
16:47:53  > Warning Failed to make bytecode node16-x64 for file /snapshot/.tmp/node_modules/@demo/package-demo/node_modules/axios/lib/helpers/throttle.js
16:47:54  ✔ Pkg build completed
16:47:54  - Sync *.node files...
16:48:06  ✔ Sync *.node files completed
16:48:06  ✔ Successfully

### Expected Behavior

build success

### To Reproduce

private project

**Comment by giviz** [comment]
Going back to using axios 0.27.2 instead of 1.x fixed the issue for me.
So I guess they've changed something in the 1.x that breaks the compatibility with pkg :(

**Comment by demelvin** [comment]
Ran into the same issue with the latest version of axios `1.2.1` downgrading fixed this for me as well.

**Comment by shakedo** [comment]
+1

**Comment by wlc015f** [comment]
> Ran into the same issue with the latest version of axios `1.2.1` downgrading fixed this for me as well.

great, it works !

**Comment by bkrunic** [comment]
> Going back to using axios 0.27.2 instead of 1.x fixed the issue for me. So I guess they've changed something in the 1.x that breaks the compatibility with pkg :(

This is a real life safer. Thank you

**Comment by Dee4kin** [comment]
> Going back to using axios 0.27.2 instead of 1.x fixed the issue for me. So I guess they've changed something in the 1.x that breaks the compatibility with pkg :(

Ty so much! Thats working 4 me

**Comment by robertsLando** [comment]
Couild be because those files are esm modules and pkg doesn't support them, BTW it could be you can just ignore the warning as axios should also have cjs files

**Comment by johandalabacka** [comment]
> Couild be because those files are esm modules and pkg doesn't support them, BTW it could be you can just ignore the warning as axios should also have cjs files

No, it doesn't work. If you run the packaged application will you get an error

Error: Cannot find module '/snapshot/helpdeskproxyjs/node_modules/axios/dist/node/axios.cjs'\n1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.

**Comment by zyf0330** [comment]
@robertsLando As @johandalabacka said, actually it doesn't work.
I think too that pkg should include cjs part of Axios into built binary, but it doesn't, it just ignores the whole Axios package.

**Comment by SunDawning** [comment]
```
pkg package.json
```
```
./dist/foo.exe
```
```
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Cannot find module 'C:\snapshot\foo\node_modules\axios\dist\node\axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\snapshot\\foo\\node_modules\\axios\\package.json',
  pkg: true
}
```

`Error: Cannot find module 'C:\snapshot\foo\node_modules\axios\dist\node\axios.cjs'`

So change your package.json with `assets` like:
```
{
  "dependencies": {
    "axios": "^1.3.3"
  },
  "devDependencies": {
    "pkg": "^5.8.0"
  },
  "pkg": {
    "outputPath": "dist",
    "targets": [
      "win"
    ],
    "assets": [
      "./node_modules/axios/dist/node/axios.cjs"
    ]
  }
}
```

**Comment by zyf0330** [comment]
> @robertsLando As @johandalabacka said, actually it doesn't work. I think too that pkg should include cjs part of Axios into built binary, but it doesn't, it just ignores the whole Axios package.

Now I know why, because `resolve` depending by `pkg` doesn't support `exports` feature of package.json of the axios.

**Comment by johandalabacka** [comment]
I have been experimenting with esbuild to construct only one file which then can be packaged with pgk. Se an example here https://github.com/johandalabacka/esbuild-package-axios

The only thing I can't use (as far as I have noticed) is top-level-awaits  so I have to put them inside a function

**Comment by Zhang81n** [comment]
> Going back to using axios 0.27.2 instead of 1.x fixed the issue for me. So I guess they've changed something in the 1.x that breaks the compatibility with pkg :(

It works, thank you very much !

**Comment by xreyc** [comment]
compile the javascript first using ncc before using pkg.

"scripts": {
    "test": "jest",
    "start": "node src/index.js",
    "dev": "nodemon src/index.js",
    "build": "ncc build  -o build/lib index.js && pkg --target node18-win-x64 -o build/server-interface.exe ./build/lib/index.js"
  },

**Comment by RanjiniAithal** [comment]
Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\sharp\build\Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\sharp\vendor\lib
  %2: path-to-executable/sharp/vendor/lib
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\sharp\build\Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\sharp\vendor\lib
  %2: path-to-executable/sharp/vendor/lib
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\ipx\node_modules\sharp\build\Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\ipx\node_modules\sharp\vendor\lib
  %2: path-to-executable/sharp/vendor/lib
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\ipx\node_modules\sharp\build\Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\ipx\node_modules\sharp\vendor\lib
  %2: path-to-executable/sharp/vendor/lib
> Warning Babel parse has failed: import.meta may appear only with 'sourceType: "module"' (5:45)
> Warning Babel parse has failed: import.meta may appear only with 'sourceType: "module"' (6:45)      
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\proplinks-bk-service\node_modules\clipboardy\index.js
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\proplinks-bk-service\node_modules\clipboardy\lib\linux.js
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\proplinks-bk-service\node_modules\clipboardy\lib\macos.js
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\proplinks-bk-service\node_modules\clipboardy\lib\termux.js
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\proplinks-bk-service\node_modules\clipboardy\lib\windows.js
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\proplinks-bk-service\node_modules\listhen\dist\index.mjs



I'm getting this warnings on running pkg, can someone help me solving this.

**Comment by Keivan-sf** [comment]
For me using `@vercel/ncc` to generate a single cjs from all the files, and then using pkg solved the problem
