### ISSUE TITLE
pkg requires /tmp to be exec enabled

### ISSUE THREAD

**Issue by Megabyte516** [vercel/pkg#1845]
### What version of pkg are you using?

5.8

### What version of Node.js are you using?

16.16

### What operating system are you using?

CentOS 7

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

Node 16

### Describe the Bug

when our application starts, pkg creates a directory under /tmp and if /tmp is not mounted as exec enabled, it fails to start, with error "failed to map segment from shared object: Operation not permitted".

### Expected Behavior

Should not depend on /tmp being exec enabled, as it is considered a security risk.

### To Reproduce

Not sure how

**Comment by robertsLando** [comment]
I suggest to create a PR with an env var to change the `/tmp` folder. Check `prelude/boostrap.js`
