### ISSUE TITLE
Cannot use execSync to run command on shell file in snapshot filesystem at runtime

### ISSUE THREAD

**Issue by samjcombs** [vercel/pkg#1851]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

14.15.1

### What operating system are you using?

macOS

### What CPU architecture are you using?

M1

### What Node versions, OSs and CPU architectures are you building for?

node14 linux mac win

### Describe the Bug

```javascript
execSync(`sh ${path.join(__dirname, '../scripts/script.sh')}`)
```
returns file not found even though i have verified it gets included in the snapshot filesystem

Although `fs` works fine:
```javascript
fs.readFileSync(`${path.join(__dirname, '../scripts/latest-nix.sh')}`);
```

So for now Ill use fs to get the script and then run it from memory.  But it would be cool if docs revealed this limitation as it took much time... thanks though for a great library! 

### Expected Behavior

execSync works and finds the file

### To Reproduce

code in bug description

### Workaround
```javascript
    const someScript = fs.readFileSync(
      `${path.join(__dirname, '../scripts/some-script.sh')}`
    );
    const filepath = path.join(os.tmpdir(), 'some-script.sh');
    fs.writeFileSync(filepath, someScript);
    try {
      execSync(`sh ${filepath}`, {stdio: 'inherit'});
    } catch {
      global.process.exit(1);
    }
    fs.unlinkSync(filepath);
```

**Comment by DeepBhat** [comment]
Can confirm, I am facing the same issue. 
```javascript
function runChromium() {
    const chromiumPath = path.join(__filename, "../node_modules/chromium/lib/chromium/chrome-win/chrome.exe")

    // the chrome-win folder will contain the chrome.exe file
    // assert that the chrome.exe file exists
    console.log("Does the chrome.exe file exist?");
    console.log(fs.existsSync(chromiumPath));

    // run chromiun with the url as an argument
    execSync(chromiumPath + " " + url);
}
```
Even though the assertion is `true`, running `execSync` to invoke the executable always results in a file not found error.
