### ISSUE TITLE
Dynamic library doesn't work at all

### ISSUE THREAD

**Issue by g-k-m** [vercel/pkg#1856]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

Latest

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

latest-win-x64

### Describe the Bug

I did the trick with require.js to add the dynamic libraries which pkg cannot include into the executable, but it just doesn't work

### Expected Behavior

It works

### To Reproduce

I tried the solution with require.js, and it did not work. When i run pkg package.json --debug, i get

```
> [debug] Stat info of C:\Games\Gladiatus farming simulator\node_modules\selenium-webdriver\lib\http.js is added to queue.
> [debug] Cannot resolve ''./atoms/' + module'
  C:\Games\Gladiatus farming simulator\node_modules\selenium-webdriver\lib\http.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> [debug] Cannot resolve 'path.resolve(`../../../bazel-bin/${file}`)'
  C:\Games\Gladiatus farming simulator\node_modules\selenium-webdriver\lib\http.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```

This is my package.json file

`{
  "dependencies": {
    "selenium-webdriver": "^4.5.0"
  },
  "name": "farmer_v109",
  "bin": "farm.js",
  "pkg": {
    "scripts": "require.js",
    "assets": "assets/**/*",
    "targets": [
      "latest-win-x64"
    ],
    "outputPath": "dist"
  }
}`

and this is my require.js file
`require('./node_modules/selenium-webdriver/lib/http.js');`

**Comment by robertsLando** [comment]
Just include those scripts to `scripts` array in json, as you see them are dinamyc so pkg in those line is just telling you he couldn't know what them could be, it's not an error as long as you are sure you added them manually using `scripts`
