### ISSUE TITLE
Security: prebuild-install dependency with high security issue

### ISSUE THREAD

**Issue by matias-hc** [vercel/pkg#1859]
Dependency Check alerts that the dependency `prebuild-install` uses an old version of `simple-get` that creates a high vulnerability, similarly to #1544. Can you please update `prebuild-install` to a newer version?
![image](https://user-images.githubusercontent.com/51689026/216137325-885b1aa6-ac67-4d29-8f19-7bb0e500b9ea.png)

**Comment by robertsLando** [comment]
PR?
