### ISSUE TITLE
MODULE_NOT_FOUND error but module exists

### ISSUE THREAD

**Issue by MasumNishat** [vercel/pkg#1861]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

16.13.0

### What operating system are you using?

Windows 11

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

default

### Describe the Bug

```cmd
pkg/prelude/bootstrap.js:1949
      if (error.code !== 'MODULE_NOT_FOUND') throw error;
                                             ^

TypeError: String.prototype.startsWith called on null or undefined
    at startsWith (<anonymous>)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:849:7)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1947:44)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47
```

### Expected Behavior

Should execute `app.exe`

### To Reproduce

1.    Create `app.js`
2.    Add:
```js
const child_process = require('child_process');
child_process.spawn('cmd.exe', ['/k', 'start cmd'], {
    detached: true,
    stdio: ['ignore', 'ignore', 'ignore']
}).unref();
(async () => {
    await new Promise(r => setTimeout(r, 10000))
    process.exit()
})()
```

3.    Compile with `pkg app.js --targets node16-win-x64`
4. Double-click on `app.exe`
5. Wait for the child window to appear
6. Type `app.exe` and press `Enter`

**Comment by ryanrubleycoates** [comment]
We see this randomly across a fleet of 50K devices now and then, but restarting the process works eventually...

**Comment by MasumNishat** [comment]
Is there any other process to restart self, I need it to add auto-update feature in my app. this code works fine before compiling.

**Comment by lucasvieceli** [comment]
npm install string.prototype.startswith

**Comment by MasumNishat** [comment]
I don't understand what you are telling @lucasvieceli . I'm trying to restart the program, not check some string starts with. You should first understand the problem. 

@ryanrubleycoates I don't know how you have tried. My code not working. Is there any mistake I have done here?
If not then You should mark it as an issue and fix it. else, you tell me that I'm wrong and instruct me on the system.
You are telling the restart method works but not telling exactly how it works. I think I'm very much clear about my problem.

**Comment by lucasvieceli** [comment]
I'm having the same problem, my project internally uses PM2 to create several subprocesses of this binary and when it goes to start in pm2 this error is happening, I had seen on the internet someone saying that if you install the module "string.prototype. startswith" would solve it, but for me it didn't =/

I also have the same error in production, the same linux x64 with the same version works, in another it does not work

**Comment by ryanrubleycoates** [comment]
Our situation also uses pm2 to launch binaries made with pkg. It's very random, but just pm2 kill, pm2 start will usually resolve it. When it's happening, pm2 will keep trying to restart the same binary in a loop, getting this same error: 
```
pkg/prelude/bootstrap.js:1949
      if (error.code !== 'MODULE_NOT_FOUND') throw error;
                                             ^
TypeError: String.prototype.startsWith called on null or undefined
``` 
We could have 3 different apps all built with the same version on pkg and node, and only 1 of them will be stuck in a loop with pm2 restarting it every second because of this.  No idea why a total kill and re-start of the processes makes it suddenly start working either.

**Comment by lucasvieceli** [comment]
I'm also trying to find the solution, I saw that if you try to run pm2 start ./binary the problem will already occur =/

**Comment by hofnarwillie** [comment]
Ran into the same issue (also trying to build a self-updating / evergreen executable that downloads and replaces itself). Got it working when I execute the child_process with a different name as the current process.

1. Download the new executable and store it using a temp name
2. Spawn child process for new temp file
3. When the child process is finished, delete the current executable and rename the temp file

**Comment by lucasvieceli** [comment]
I had a server that was working, I restarted the machine, it stopped working =/

**Comment by iwillwen** [comment]
@hofnarwillie Same issue with same purpose. could you share your solution in detail?

**Comment by hofnarwillie** [comment]
Sorry, my initial solution didn't work once the app was compiled into a single file. Many iterations later though this is the (very hacky) working solution (only works in Windows, but could easily be adapted):

```
  await downloadVersion(version, tempDownloadedFilePath);
  // The currently executing file cannot be removed or renamed, so we spawn a new process to do it
  // We then close the current process so that the new process can take over.
  // To ensure the current process stops in time we add a 6 second delay to the new process
  // using a hacky ping command (since Windows shells do not have a reliable sleep command).
  const moveShellCommand = spawn(
    `ping 127.0.0.1 -n 6 > nul && move "${tempDownloadedFilePath}" "${executablePath}"`,
    [],
    {
      detached: true,
      stdio: ['ignore', 'ignore', 'ignore'],
      shell: true,
    },
  );
  moveShellCommand.unref();
  process.exit(0);
```

**Comment by Luzzifus** [comment]
I just opened a pull request to fix this. It's just a single line.
If you need it urgently, you can apply it yourself locally or via `patch-package`.

**Comment by viceice** [comment]
@Luzzifus This sadly doesn't fix my usecase.

I'm building an executable `containerbase-cli` which is symlinked as `install-tool` and others.
The `install-tool` command is calling some legacy bash scripts which is calling `containerbase-cli` again to download some files.
My workaround is to delete `PKG_EXECPATH` from bash script, so it's not passed to the executable again.
https://github.com/containerbase/base/pull/1210/files#diff-1b11df83c5b75b73fc1fe984fd80195d2880af67db335cc77a79df260d3bd565R4

This help to not go to this code path which would fail on the `path.resolve`.
https://github.com/vercel/pkg/blob/73a03d1c27d879ff82a6d7b58c5f08c1da8a6a6b/prelude/bootstrap.js#L77-L84

**Comment by MasumNishat** [comment]
Is there any update??

**Comment by introspection3** [comment]
this bug exist

**Comment by introspection3** [comment]
-----------------------er.exe

using System.Diagnostics;

namespace er
{
    internal class Program
    {
        static void Main(string[] args)
        {
            ExecuteCmd(Directory.GetCurrentDirectory(), "s.exe");
        }

       static void ExecuteCmd(string dir, string cmd)
        {
            Process process = new Process();
            process.StartInfo.FileName = "cmd.exe";  
            process.StartInfo.Arguments = "/k s.exe"; 
            process.StartInfo.UseShellExecute = false;
            
            process.StartInfo.WorkingDirectory = dir;
            process.Start();
          
        }
    }
}

---------------------------------s.js

console.log(process.argv);
const path = require('path');
const { spawn, execFile } = require('child_process');
setInterval(() => {
    console.log(process.argv);
}, 10000);


setTimeout(() => {
    console.log('s.exe', 'start er.exe');
    let argv0 = process.argv[0];
    let rootPath = require('path').dirname(argv0);

    let exePath = require('path').join(rootPath, 'er.exe');
    console.log('s.exe', 'er exePath=' + exePath);
    startAsync(exePath, rootPath);
}, 5000);


var exec = require('child_process').exec;


function startAsync(cmd) {
    let cwd = path.dirname(cmd);
    const ls = spawn(cmd, [], { cwd: cwd, detached: true, shell: true,env:{} });


    ls.stdout.on('data', (data) => {
        console.log(`s er stdout: ${data}`);
    });

    ls.stderr.on('data', (data) => {
        console.error(`s er stderr: ${data}`);
    });

    ls.on('close', (code) => {
        console.log(`s er close ${code}`);
    });
    setTimeout(() => {
        ls.unref();
    }, 1000);
    
}


//   pkg  -t node18-win32-x64 s.js
