### ISSUE TITLE
 process.argv is null and  __dirname is null and process.cwd() is null  when call exe  (which is created by pkg)  from other program

### ISSUE THREAD

**Issue by introspection3** [vercel/pkg#1866]
### What version of pkg are you using?

5.8

### What version of Node.js are you using?

18

### What operating system are you using?

windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

18

### Describe the Bug

golang 
cmd = exec.Command("cmd.exe", "/C", "start", appPath)
appPath is the exe file path  (which is created by pkg)
 exe file    (which is created by pkg) process.argv is null and  __dirname is null process.cwd() is null

### Expected Behavior

other program can call create a pkgexe process 

### To Reproduce

cmd = exec.Command("cmd.exe", "/C", "start", appPath) or
cmd = exec.Command(ppPath)
cmd.Start()

**Comment by introspection3** [comment]
same as https://github.com/vercel/pkg/issues/1356

**Comment by robertsLando** [comment]
Could it be fixed by this: https://github.com/vercel/pkg/pull/1462?

**Comment by introspection3** [comment]
> Could it be fixed by this: #1462?

i don't know how to test with this fix.but i don't think so,I am using 5.8 version
