### ISSUE TITLE
pkg was pack success, but crash in use pack file, error for 'etcd3 rpc.proto' file path 

### ISSUE THREAD

**Issue by HseYang** [vercel/pkg#1871]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

v16.16.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-macos-x64

### Describe the Bug

pkg was pack success, but crash in use pack file, error for 'etcd3 rpc.proto' file path 

![image](https://user-images.githubusercontent.com/33883616/220283001-a47b94a2-17de-476c-848a-accec2d9f633.png)

pkg code:

    pkg ./bin/www --target=node16-macos-x64 --out-path=./dist/

I can try adding the package to my assets in the pkg config in package.json,

    "assets": [
        ...,
      "node_modules/etcd3/**/*",
      "node_modules/etcd3/**/*.proto",
      "node_modules/etcd3/proto/rpc.proto"
    ]

but same error.

### Expected Behavior

Do not crash when using packaged files

### To Reproduce

[https://github.com/microsoft/etcd3](https://github.com/microsoft/etcd3)

**Comment by robertsLando** [comment]
are you using npm/yarn workspaces? If so the modules could be in the root directory and not in package directory so the assets paths are wrong

**Comment by HseYang** [comment]
> are you using npm/yarn workspaces? If so the modules could be in the root directory and not in package directory so the assets paths are wrong

Thx, Bro.

Yes, npm. 

etcd3 original code like this:

![image](https://user-images.githubusercontent.com/33883616/220295206-dfcc75c0-1e06-4402-83a9-5d9a9044159e.png)


I put 'rpc.proto' in my root directory './proto/', 
and load './proto/rpc.proto' in './node_modules/**/connection-pool.js' file,  
also crash,
but the crash was due to etcd3's grpc can not load proto file

![73b06736-5521-42a0-82ce-0cf99f502542](https://user-images.githubusercontent.com/33883616/220300196-261c31b8-f911-480f-b176-0270800ca85b.jpeg)


Used etcd3 code:

    const { Etcd3 } = require('etcd3');

Simple use normal code will crash, like the first picture of the above 'Describe the Bug',

Now I don't know what to do .....

......

**Comment by HseYang** [comment]
I solved this issues with [`patch-package`](https://github.com/ds300/patch-package) :

## Detail

open `node_modules/etcd3/package.json`, add code:

    "files": [
    	"lib/*",
    	"proto/*.proto"
    ]

then: 

    npx patch-package etcd3 --exclude
    
    npm install


Done ~ !
