### ISSUE TITLE
Support more file extensions when detecting Javascript files

### ISSUE THREAD

**Issue by piranna** [vercel/pkg#1872]
At https://github.com/vercel/pkg/blob/46b3aa5831d5d788cd7f1c9b245d0d4b05cd6d92/lib/common.ts#L91-L93, the `isDotJS()` function only detect the `.js` extension, so when using `.cjs` (CommonJS) extension, files are added as disclosed at https://github.com/vercel/pkg/blob/46b3aa5831d5d788cd7f1c9b245d0d4b05cd6d92/lib/packer.ts#L142. The checks to be added as blob or content are at https://github.com/vercel/pkg/blob/56135b583b901d552e3780e749e79e70e71fd3ea/lib/walker.ts#L480-L492 and https://github.com/vercel/pkg/blob/56135b583b901d552e3780e749e79e70e71fd3ea/lib/walker.ts#L531-L536, so maybe just by modifying `isDotJS()` function is enough? Or is it needed anything else?

**Comment by robertsLando** [comment]
I think modifying that function should be enough, PR?

**Comment by piranna** [comment]
I've done the next change in the transpiled code

```js
function isDotJS(file) {
    return path_1.default.extname(file) === '.js'
    || path_1.default.extname(file) === '.cjs'
    || path_1.default.extname(file) === '.mjs';
}
```

but for some reason I'm getting more `DISCLOSE` than before... :-(

**Comment by robertsLando** [comment]
🤷🏼‍♂️

**Comment by piranna** [comment]
> 🤷🏼‍♂️

Any clue how to test / debug this? It doesn't makes any sense that by adding more files that should be transpiled, I get in return less than before...

**Comment by robertsLando** [comment]
I suggest to clone pkg and write a test with a simple cjs/js file to see if you can make it work

**Comment by piranna** [comment]
no-stale
