### ISSUE TITLE
pkg does not respect `exports` entrypoints defined in `package.json`

### ISSUE THREAD

**Issue by mikeseese** [vercel/pkg#1873]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

18.13.0

### What operating system are you using?

Windows 11

### What CPU architecture are you using?

x86_x64

### What Node versions, OSs and CPU architectures are you building for?

node18-linux-x64

### Describe the Bug

If you are using a CJS project that has `require("axios")` where you're using `axios@1.x` (`1.3.4` at the time of reporting this is latest), the [axios `package.json`](https://github.com/axios/axios/blob/v1.x/package.json#L6-L22) defines `exports` that would resolve to `./dist/node/axios.cjs`. Note, per the [NodeJS docs](https://nodejs.dev/en/api/v18/packages/#package-entry-points), `exports` is used when both `exports` and `main` are defined.

To explain how the `require("axios") => require("axios/dist/node/axios.cjs")` works further, `require("axios")` has a relative path of `.`, so it then looks at [the "." section](https://github.com/axios/axios/blob/v1.x/package.json#L7-L20), then it's not a types lookup or a browser environment, so it then goes to [the "default" section](https://github.com/axios/axios/blob/v1.x/package.json#L16-L19), and since we're using require, it goes to [the "require" section](https://github.com/axios/axios/blob/v1.x/package.json#L17) which is defined as `./dist/node/axios.cjs`.

When I look at my `pkg --debug` output, it shows it's just resolving to `axios/index.js`:

```
> [debug] Content of D:\project\node_modules\@open-match\api\node_modules\axios\package.json is added to queue. It was required from D:\project\node_modules\@open-match\api\lib\models\serviceOptions.js
> [debug] Bytecode of D:\project\node_modules\@open-match\api\node_modules\axios\index.js is added to queue. It was required from D:\project\node_modules\@open-match\api\lib\models\serviceOptions.js
```

The above is using `@open-match/api@1.0.6` where [`import axiosStatic from "axios"`](https://github.com/RedwoodMMO/node-open-match/blob/f34bd08f7c028e8f5f036113c363d34fb07d7351/packages/api/src/models/serviceOptions.ts#L4) gets compiled by `tsc` to `const axios_1 = __importDefault(require("axios"));`

### Expected Behavior

pkg should respect the rules defined by `"exports"` in `package.json` as defined in the [NodeJS docs](https://nodejs.dev/en/api/v18/packages) since that's how require statements are interpreted.

### To Reproduce

1. Install axios: `npm install axios`
1. Require axios: `const axios = requie("axios");`
1. Run `pkg --debug`
1. See that the `axios.cjs` file is never added to the queue

**Comment by robertsLando** [comment]
PR?

**Comment by seesemichaelj** [comment]
I'm currently deciphering to figure out how to implement a fix; I'll update if I end up not having time to make a PR.

**Comment by seesemichaelj** [comment]
If I'm understanding how the walker/follower works, believe the issue is because the `resolve` dependency to follow resolutions [doesn't support exports yet](https://github.com/browserify/resolve/issues/222). It seems like this is going to become more of an issue as some maintainers are apparently dropping `"main"` altogether (since NodeJS essentially says it's been deprecated for awhile). Apparently the issue is affecting `jest` users as well.

**Comment by robertsLando** [comment]
https://github.com/vercel/pkg/issues/1291

**Comment by seesemichaelj** [comment]
I'm aware of #1291. This is unrelated to ESMs; as I stated in my issue description, this for a CJS project with a CJS dependency. While https://github.com/browserify/resolve/issues/222 has `Support ESM resolution` as the title, the issue is 2.5 years old that also includes `Support exports field in package.json`. Per the [NodeJS docs](https://nodejs.dev/en/api/v18/packages/#package-entry-points) (also linked above in my description), the `"exports"` field is not limited to ESM projects and CJS projects can, and do, use it.

**Comment by seesemichaelj** [comment]
Regardless, until `resolve` supports `"exports"`, this issue cannot be fixed unless pkg wants to implement their own solution [like rollup did](https://github.com/rollup/plugins/pull/693#issuecomment-744742615). I definitely don't have the time to implement something like that.

In the meantime, a hacky `pkg.scripts` to include the dependency's file will work

**Comment by piranna** [comment]
I'm facing the same issue.

**Comment by andreasdamm** [comment]
Would switching to https://www.npmjs.com/package/enhanced-resolve be viable?

**Comment by lifegit** [comment]
yes, I'm facing the same issue.

**Comment by luoxzhg** [comment]
refresh

**Comment by mikeseese** [comment]
This issue is still relevant.

**Comment by MaxMusing** [comment]
This is causing issues for us with `openai@4` which relies on `exports`.
