### ISSUE TITLE
the binary .exe immediately exits.

### ISSUE THREAD

**Issue by AyubTouba** [vercel/pkg#1874]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

14.21.1

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-win-x64

### Describe the Bug

I have nestjs app and after launching the pkg command to build `pkg . -t node14-win-x64 -o apptest --debug` and finish with no errors I tried to open to .exe but the cmd immediately closed. I tried to add `--options max_old_space_size=5096` but nothing change

The config: 
`"bin": "dist/main.js",
  "pkg": {
    "scripts": "dist/**/*.js",
    "assets": ["front/**/*","backup/**/*","logs/**/*","files/**/*"]
  }`
the size of the .exe is around 350Mo and I'm using windows to build

Ps: I tried with a small demo and it works (the .exe is around 60mo)

Thanks in advanced 

### Expected Behavior

the binary should at least show the starting of the app

### To Reproduce

.

**Comment by vasilieva-sasha** [comment]
Hi! I Have the same problem, did you manage to solve it?

**Comment by AyubTouba** [comment]
> Hi! I Have the same problem, did you manage to solve it?

I found the problem in MailerModule configuration 
` MailerModule.forRoot({
      transport: {
        ....
      },
      defaults: {
      ...
      },
      template: {
        dir: __dirname + "/templates", // when I remove this line it works, env if I set the folder path as string it doesn't work 
        adapter: new HandlebarsAdapter(),
        options: {
          strict: true,
        },
      },
    }),`
