### ISSUE TITLE
Cannot generate anything (arm64/x64) on macOS M1 ("Failed to make bytecode")

### ISSUE THREAD

**Issue by evil-shrike** [vercel/pkg#1876]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

19.4

### What operating system are you using?

macOS Ventura 13.2.1

### What CPU architecture are you using?

Apple M1

### What Node versions, OSs and CPU architectures are you building for?

default, node16-macos-arm64, node16-macos-x64

### Describe the Bug

It doesn't matter what I'm building, can be just a simple script.
First of all, pkg failed to use my system Node:
```
/Users/segy/work/samples/node-exec$ pkg ./index.mjs
> pkg@5.8.0
> Targets not specified. Assuming:
  node19-linux-arm64, node19-macos-arm64, node19-win-arm64
> Error! No available node version satisfies 'node19'

/Users/segy/work/samples/node-exec$ node -v
v19.4.0
/Users/segy/work/samples/node-exec$ which node
/opt/homebrew/bin/node
```

Then I tried specifying a target explicitly, first tried node16:
```
/Users/segy/work/samples/node-exec$ pkg ./index.mjs --target node16-macos-arm64
> pkg@5.8.0
> Warning Failed to make bytecode node16-arm64 for file /snapshot/node-exec/index.mjs

/Users/segy/work/samples/node-exec$ pkg ./index.mjs --target node16-macos-x64
> pkg@5.8.0
> Warning Failed to make bytecode node16-x64 for file /snapshot/node-exec/index.mjs
```

same for other node versions (18):
```
/Users/segy/work/samples/node-exec$ pkg ./index.mjs --target node18-macos
> pkg@5.8.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v18.5.0-macos-arm64         [====================] 100%

> Warning Failed to make bytecode node18-arm64 for file /snapshot/node-exec/index.mjs
```

### Expected Behavior

generate an executable

### To Reproduce

I guess its macOS  arm64 specific, doesn't seem to depend on actual input code

**Comment by sauhaardac** [comment]
Am also having this issue...

**Comment by robertsLando** [comment]
#1291
