### ISSUE TITLE
Try nightmarejs, cannot package a node app?

### ISSUE THREAD

**Issue by gabeo8** [vercel/pkg#188]
Hello,
I see in dictionary have support Nightmare and Electron. But I try, it not working.
Error:
`> pkg@4.2.0
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  C:\Users\Administrator\Desktop\PROJECTS\night\node_modules\nightmare\lib\runner.js
  path-to-executable/nightmare/runner.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  C:\Users\Administrator\Desktop\PROJECTS\night\node_modules\nightmare\lib\frame-manager.js
  path-to-executable/nightmare/frame-manager.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  C:\Users\Administrator\Desktop\PROJECTS\night\node_modules\nightmare\lib\ipc.js
  path-to-executable/nightmare/ipc.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  C:\Users\Administrator\Desktop\PROJECTS\night\node_modules\nightmare\lib\preload.js
  path-to-executable/nightmare/preload.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  C:\Users\Administrator\Desktop\PROJECTS\night\node_modules\electron\dist
  path-to-executable/electron/dist
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  C:\Users\Administrator\Desktop\PROJECTS\night\node_modules\sliced\index.js
  path-to-executable/node_modules/sliced/index.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  C:\Users\Administrator\Desktop\PROJECTS\night\node_modules\deep-defaults\lib\index.js
  path-to-executable/node_modules/deep-defaults/index.js`

**Comment by igorklopov** [comment]
Did you do everything that is written in warnings? Please give the list of directory with compiled executable. It must contain subdirectories like `nightmare` and `electron`, etc.

**Comment by gabeo8** [comment]
@igorklopov 
Thanks reply.
I have include scripts to package.json. But,  It don't work.

**Comment by igorklopov** [comment]
Please give the list of directory with compiled executable.

**Comment by gabeo8** [comment]
I have do it.
It ok, not show error. But don't work, **it not show electron windows.**
![pkg](https://user-images.githubusercontent.com/9195197/29004757-6aa99afa-7af7-11e7-9273-39fcfef4b361.png)

**Comment by pablohenriq** [comment]
I am having the same error.
I tried to follow what all the warning messages ask for, but the error persists.
In my case, I'm using `electron`.

**Comment by raczak** [comment]
Hello, same as you bro, I'm working on it since 2 days now....
I'm using nighmarejs

**Comment by gumpjt** [comment]
Same issue. Any update on this?

**Comment by Zer0ne83** [comment]
Same issue. I've tried every combination of dir paths alterations known to man.

**Comment by relixj** [comment]
My bad I was pointing at the wrong start file. I changed it as below and it started working,

Pkg **bin/www** -t node8-win-x64 -o "App Name"

**Comment by z1988hf** [comment]
I have the same problem. Seems pkg have packed electron to the output exe. But the exe cannot run except its original path. I guess the reason is it cannot find electron.exe. What is the path of electron.exe after packed into putput exe?

const { exec } = require('child_process');
exec('"./node_modules/electron/dist/electron.exe" .', (err, stdout, stderr) => {
   //exec('dir', (err, stdout, stderr) => {
  if (err) {
    console.error(err)
  } else {
   // the *entire* stdout and stderr (buffered)
   console.log(`stdout: ${stdout}`);
   console.log(`stderr: ${stderr}`);
  }
});
