### ISSUE TITLE
Cannot find snapshot path after packaging file

### ISSUE THREAD

**Issue by dagrooms52** [vercel/pkg#1883]
### What version of pkg are you using?

latest

### What version of Node.js are you using?

latest

### What operating system are you using?

win

### What CPU architecture are you using?

x64

### What Node versions, OSs and CPU architectures are you building for?

something

### Describe the Bug

After using pkg on index.js, I call `./index-win.exe` and get:

> Error: Cannot find module 'C:\snapshot\Program Files\nodejs\node_modules\@gltf-transform\cli\src\cli.ts'

C:\snapshot doesn't exist on my machine. This is borked.

### Expected Behavior

Works.

### To Reproduce

Use pkg on a file

**Comment by dagrooms52** [comment]
Here's a minimal repro of the issue:
- git clone https://github.com/donmccurdy/glTF-Transform
- cd glTF-Transform/tree/main/packages/cli
- pkg .

This dumps a bunch of warnings about not finding any of the modules listed in dependencies.

**Comment by bentacos** [comment]
Seems to be related with my issue #1931
