### ISSUE TITLE
Drop support of Node 12 as it is EOL

### ISSUE THREAD

**Issue by Mikescops** [vercel/pkg#1886]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

18

### What operating system are you using?

all

### What CPU architecture are you using?

all

### What Node versions, OSs and CPU architectures are you building for?

all

### Describe the Bug

Drop support of Node 12 as it is EOL.

pkg is currently supporting Node 12 in the CI tests, as this version of node is EOL we could remove it.

Side note: Node 14 will be EOL on 30 Apr 2023.

### Expected Behavior

N/A

### To Reproduce

N/A

**Comment by baparham** [comment]
@leerob @robertsLando I'm all for this, I think we could probably just make the call and bump major versions to `6.0.0` and only support 16, 18, and 19 with it.

14 is EOL in about a month, so why keep it around if we are dropping old support in `6.0.0` unless we want to match the node.js timeline exactly (https://github.com/nodejs/release#release-schedule)

**Comment by baparham** [comment]
the last few node 14 fixes maybe can be patch released into the 5.x stream if they release in the next month.

**Comment by robertsLando** [comment]
I would keep node 14 for a while, AFAIK when we discussed about this we planned to keep LTS and latest EOL release (in this case node 14 until 16 reaches EOL)

**Comment by robertsLando** [comment]
> BUT the version has been EOL by that time, so why support it if node.js is not supporting it???

I agree with you but last time we discussed this with the team the decision was that, maybe just to give a little time to users to move on, also because if we remove it it means users need to stick with a specific pkg version otherwise they cannot use an old nodejs version anymore (whatever is the reason they want to do so)
