### ISSUE TITLE
thread worker exited

### ISSUE THREAD

**Issue by erpadmin** [vercel/pkg#1893]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

v16.18.0

### What operating system are you using?

arch

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux

### Describe the Bug

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: The worker thread exited
    at Worker.onWorkerExit (/snapshot/api/node_modules/thread-stream/index.js:180:32)
    at Worker.emit (node:events:527:28)
    at Worker.[kOnExit] (node:internal/worker:278:10)
    at Worker.<computed>.onexit (node:internal/worker:198:20)
Emitted 'error' event on ThreadStream instance at:
    at destroy (/snapshot/api/node_modules/thread-stream/index.js:349:12)
    at Worker.onWorkerExit (/snapshot/api/node_modules/thread-stream/index.js:180:3)
    at Worker.emit (node:events:527:28)
    at Worker.[kOnExit] (node:internal/worker:278:10)
    at Worker.<computed>.onexit (node:internal/worker:198:20)

### Expected Behavior

to run same as when app run directly with node

### To Reproduce

.

**Comment by erpadmin** [comment]
seems to happen during postgres database connection, normally the app would print the following instead of erroring
Successfully connected to DB
[1679410954383] INFO (ga-api/140449 on archops): up and running in development @: archops on port: 5000}

**Comment by erpadmin** [comment]
comparison strace for working connection (`node src/index.js`)
```
read(16, "\1\0\0\0\0\0\0\0", 1024)      = 8
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 24
connect(24, {sa_family=AF_INET, sin_port=htons(5432), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(13, EPOLL_CTL_ADD, 24, {events=EPOLLOUT, data={u32=24, u64=24}}) = 0
epoll_wait(13, [{events=EPOLLOUT, data={u32=24, u64=24}}], 1024, 0) = 1
getsockopt(24, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
setsockopt(24, SOL_TCP, TCP_NODELAY, [1], 4) = 0
write(24, "\0\0\0@\0\3\0\0user\0postgres\0database\0c"..., 64) = 64
epoll_ctl(13, EPOLL_CTL_ADD, 24, {events=EPOLLIN, data={u32=24, u64=24}}) = -1 EEXIST (File exists)
epoll_ctl(13, EPOLL_CTL_MOD, 24, {events=EPOLLIN, data={u32=24, u64=24}}) = 0
epoll_wait(13, [], 1024, 0)             = 0
epoll_wait(13, [{events=EPOLLIN, data={u32=24, u64=24}}], 1024, 7607) = 1
read(24, "R\0\0\0\27\0\0\0\nSCRAM-SHA-256\0\0", 65536) = 24
getpid()                                = 142623
getpid()                                = 142623
mprotect(0x7f9078383000, 245760, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mprotect(0x7f9078383000, 245760, PROT_READ|PROT_EXEC) = 0
write(24, "p\0\0\0007SCRAM-SHA-256\0\0\0\0!n,,n=*,r="..., 56) = 56
mprotect(0x7f9078383000, 245760, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mprotect(0x7f9078383000, 245760, PROT_READ|PROT_EXEC) = 0
epoll_wait(13, [{events=EPOLLIN, data={u32=24, u64=24}}], 1024, 0) = 1
read(24, "R\0\0\0\\\0\0\0\vr=YqSvTgYu6UPVWDRBK5yIJ"..., 65536) = 93
mprotect(0x7f9078383000, 245760, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mprotect(0x7f9078383000, 245760, PROT_READ|PROT_EXEC) = 0
write(24, "p\0\0\0lc=biws,r=YqSvTgYu6UPVWDRBK5"..., 109) = 109
epoll_wait(13, [], 1024, 0)             = 0
epoll_wait(13, [{events=EPOLLIN, data={u32=24, u64=24}}], 1024, 7601) = 1
read(24, "R\0\0\0006\0\0\0\fv=6xfKddnYCxE7rEXB8db3K"..., 65536) = 465
mprotect(0x7f9078383000, 245760, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mprotect(0x7f9078383000, 245760, PROT_READ|PROT_EXEC) = 0
write(24, "Q\0\0\0WSET client_min_messages TO "..., 88) = 88
epoll_wait(13, [], 1024, 0)             = 0
epoll_wait(13, [{events=EPOLLIN, data={u32=24, u64=24}}], 1024, 7599) = 1
read(24, "C\0\0\0\10SET\0C\0\0\0\10SET\0S\0\0\0\26TimeZone\0"..., 65536) = 47
getpid()                                = 142623
getpid()                                = 142623
write(24, "Q\0\0\0\31SELECT 1+1 AS result\0", 26) = 26
epoll_wait(13, [{events=EPOLLIN, data={u32=24, u64=24}}], 1024, 0) = 1
read(24, "T\0\0\0\37\0\1result\0\0\0\0\0\0\0\0\0\0\27\0\4\377\377\377\377\0\0"..., 65536) = 64
write(19, "Successfully connected to DB\n", 29Successfully connected to DB
) = 29
```

**Comment by erpadmin** [comment]
any way to get more detail on the node:events?

**Comment by baparham** [comment]
I suspect this is the same or similar issue as https://github.com/vercel/pkg-fetch/issues/282 Have you been able to try using a newer version of pkg-fetch and node.js to see if that resolves the issue?
