### ISSUE TITLE
Trojan.Agent.Win32.2853154

### ISSUE THREAD

**Issue by NotFubukIl** [vercel/pkg#1899]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

16.16.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-win

### Describe the Bug

So, When I put the exe on virustotal it says Trojan.Agent.Win32.2853154 
But My Code is only a console.log

### Expected Behavior

I expected 0 detects or smthg

### To Reproduce

index.js - console.log("something")
Build it 
Put it on virustotal

**Comment by makors** [comment]
Most likely just a general detection based off of the file info it was able to gather. Nothing to worry about.
