### ISSUE TITLE
Reopen ENOENT when executing bundled binary asset #1516

### ISSUE THREAD

**Issue by boblund** [vercel/pkg#1904]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

18.15.0

### What operating system are you using?

MaxOS 13.2.1

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

v18.5.0-macos-x64

### Describe the Bug

Executing ```./dist/cli-macos``` results in:
```
Error: spawn /snapshot/testwebview/bin/darwin-amd64/webview ENOENT
```

Pkg property of package.json:
```
"pkg": {
   "assets": ["./public/*", "./bin/darwin-amd64/webview"],
   "outputPath": "dist"
}
```

Source line for spawn:
```
child_process.spawn(join(__dirname, 'bin/darwin-amd64/webview'), args)
```

Partial output of ```DEBUG_PKG=1 pkg . --debug```:

```
> [debug] The file was included as asset content
  /Users/blund/Documents/swdev/testwebview/bin/darwin-amd64/webview
```

### Expected Behavior

Webview is successfully launched by the pkg executable

### To Reproduce

Execute steps in bug description.

**Comment by boblund** [comment]
Here is virtual file system from executing ```./dist/cli-macos```:

```
------------------------------- virtual file system
/snapshot
  testwebview                              8478341 
    cli.js                                     531 
    package.json                               312 
    public                                    2149 
      index.html                              1306 
    bin                                    8478341 
      darwin-amd64                         8476192 
        webview                            8476192 
Total size =  8478341
```

**Comment by sunknudsen** [comment]
@si458 Would you happen to know why one cannot spawn included asset?

**Comment by si458** [comment]
> @si458 Would you happen to know why one cannot spawn included asset?

Sadly I'm not sure

The only thing I no is as my other comment says

I have to include the asset (exe in my case) then copy it to a temp folder somewhere, then run it from there

It has something to do with pkg/node not nowhere where it exe is because of its like virtual folder structure (if that makes sense?)
