### ISSUE TITLE
Failed to make bytecode for multiple files

### ISSUE THREAD

**Issue by Default-01** [vercel/pkg#1905]
### What version of pkg are you using?

latest

### What version of Node.js are you using?

18.7

### What operating system are you using?

Windows 11

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

any

### Describe the Bug

When i run `pkg -t node16 index.js` i get the following warnings:

```
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\DBD-Advanced-Ticket-Bot\node_modules\file-type\index.js
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\DBD-Advanced-Ticket-Bot\node_modules\file-type\core.js
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\DBD-Advanced-Ticket-Bot\node_modules\file-type\supported.js
> Warning Failed to make bytecode node16-x64 for file C:\snapshot\DBD-Advanced-Ticket-Bot\node_modules\file-type\util.js
```

### Expected Behavior

Should compile properly

### To Reproduce

run `pkg -t node16 index.js` with the latest version of Discord.j@14.9.0 and you get this error.

**Comment by fcastilloec** [comment]
I'm experiencing the same on Ubuntu 22.04 and node 16.

**Comment by nadeemahmad** [comment]
@fcastilloec I am running into a similar issue as above. Do you have any recommendations on how to fix the import issue?

**Comment by kuema** [comment]
As a workaround, you can include the files in question as _assets_.
The warnings will still be present at build time, but at least you have the files included. They load properly at runtime, just tested it with the axios package.

```
   "assets": [
      "node_modules/axios/**"
    ]
```

**Comment by Sidewinder1138** [comment]
I'm having the same issue, running on Windows 11, Node 18. I think the paths are wrong, in your example there is:
```C:\snapshot\DBD-Advanced-Ticket-Bot...```

That **C:\snapshot** doesn't seem right, and it's doing that for me as well.
