### ISSUE TITLE
Node 18.15 as Error

### ISSUE THREAD

**Issue by longyanjiang** [vercel/pkg#1924]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

node 18.15.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

Intel

### What Node versions, OSs and CPU architectures are you building for?

node18-mac-x64

### Describe the Bug

Node.js v18.5.0
/snapshot/chatgpt-cooper/node_modules/.pnpm/registry.npmmirror.com+axios@1.3.4/node_modules/axios/lib/helpers/speedometer.js:55
export default speedometer;
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (node:vm:102:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

![image](https://user-images.githubusercontent.com/49814706/235365077-e496d8a7-71f2-44f2-85bc-03c2cedb4d43.png)

### Expected Behavior

I used to package my Nestjs project, and my node version is 18.15.0. This error occurs: Unexpected token 'export'

### To Reproduce

![image](https://user-images.githubusercontent.com/49814706/235365159-49d24445-3ca9-4fe2-9b84-f6a2c2952fd2.png)

**Comment by adminqe** [comment]
+1

**Comment by adminqe** [comment]
> ### 您使用的是什么版本的 pkg？
> 5.8.1
> 
> ### 您使用的是哪个版本的 Node.js？
> 节点 18.15.0
> 
> ### 您使用什么操作系统？
> 苹果系统
> 
> ### 您使用的是什么 CPU 架构？
> 英特尔
> 
> ### 您正在构建哪些 Node 版本、操作系统和 CPU 架构？
> node18-mac-x64
> 
> ### 描述错误
> Node.js v18.5.0 /snapshot/chatgpt-cooper/node_modules/.pnpm/registry.npmmirror.com+axios@1.3.4/node_modules/axios/lib/helpers/speedometer.js:55 导出默认速度计； ^^^^^^
> 
> SyntaxError：套接字 上的新脚本 (node:vm:102:7)出现意外的令牌“导出” 。([eval]:18:19) 在 Socket.emit (node:events:537:28) 在 addChunk (node:internal/streams/readable:324:12) 在 readableAddChunk (node:internal/streams/readable:297: 9) 在 Readable.push (node:internal/streams/readable:234:10) 在 Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
> 
> ![图像](https://user-images.githubusercontent.com/49814706/235365077-e496d8a7-71f2-44f2-85bc-03c2cedb4d43.png)
> 
> ### 预期行为
> 我以前打包过我的Nestjs项目，我的node版本是18.15.0。发生此错误：意外的令牌“导出”
> 
> ### 重现
> ![图像](https://user-images.githubusercontent.com/49814706/235365159-49d24445-3ca9-4fe2-9b84-f6a2c2952fd2.png)

+1

**Comment by baparham** [comment]
I'm pretty sure this relates to using ESM instead of commonjs. From what I remember, pkg doesn't support ecmascript, but I don't have the time to verify that claim, so it's just an idea for you to pursue to see if using commonjs instead works for you

**Comment by baparham** [comment]
found the reference in the pinned issue: https://github.com/vercel/pkg/issues/1291
