### ISSUE TITLE
Reading the root of a drive on windows results extra 'snapshot' directory

### ISSUE THREAD

**Issue by vicapow** [vercel/pkg#1929]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

v10.23.1

### What operating system are you using?

windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node18-win-x64

### Describe the Bug

The binary exists on the `C:\`. The binary then attempts to read a drive on say `E:\` using `readdir()`

ie., 

````
let dirents = await readdir(dir, { withFileTypes: true });
````

but this inaccurately returns an extra folder called `snapshot` on the `E:\` drive. I understand there is this [snapshot filesystem](https://github.com/vercel/pkg/tree/main#snapshot-filesystem) but I would not have expected this it override file system calls from another drive. With the current behavior, we cannot have a cli binary that can read the entire drive contents without either explicitly ignoring all drives with a root folder names `snapshot` that happens to actually be on that drive, or explicitly not allow reading drive contents with a `snapshot` directory.

### Expected Behavior

Allow having readdir work for an entire drive other than the one that contains the binary.

### To Reproduce

Create a binary, setup a new drive, E:\, run on windows, attempt to read the drive using readdir giving it E:\ as the readdir argument path. see that it returns a `snapshot` directory on `E:\` which was not expected

**Comment by Renari** [comment]
I think this may be the same issue I was having here: https://github.com/vercel/pkg/discussions/1928

**Comment by Renari** [comment]
.

**Comment by Renari** [comment]
still relevant
