### ISSUE TITLE
Cannot find worker js file included as an asset on Windows

### ISSUE THREAD

**Issue by bentacos** [vercel/pkg#1931]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

16.0.0

### What operating system are you using?

WSL on Windows 11

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux-x64, node16-win-x64

### Describe the Bug

I have been pondering this issue for several days, yet it continues to elude my understanding.

I have this in my package.json:
```
"pkg": {
    "assets": [
      "./worker1.cjs",
      "./worker2.cjs",
      "./worker3.cjs"
    ]
  },
```

I have this code that starts a new worker when called:
```
const createWorker = async (type, workerId, unique, extra = {}) => {
    const isPkg = typeof process.pkg !== "undefined";

    console.log(join(__dirname, `${type}.cjs`));
    
    const newWorker = new Worker(isPkg ? join(__dirname, `${type}.cjs`) : join(process.cwd(), "src", "workers", `${type}.js`), {
        workerData: {
            unique,
            unique: workerId,
            extra: extra
        }
    });

    if(type == "worker1") {
        workers.set(`${unique}.${workerId}`, newWorker);
    }

    return newWorker;
};
```

The worker encounters an issue when attempting to initiate a new thread, as it consistently displays an error indicating the inability to locate the worker file within the Windows binary. In contrast, this problem does not arise on Linux, where the functionality operates flawlessly.

I'm getting this worker path on Windows which includes an error:
```
C:\snapshot\project-directory\worker1.cjs

Error: Cannot find module 'C:\snapshot\project-directory\worker1.cjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:191:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

While on Linux I'm getting this path and it works fine:
`/snapshot/project-directory/worker1.cjs`

### Expected Behavior

It is imperative for the built Windows binary to exhibit the same capability as its Linux counterpart, namely locating the worker files without any issues. However, the current situation demonstrates that the Windows binary fails to perform this crucial function.

### To Reproduce

Start a new worker thread using a worker file included as an asset on a Windows binary.

**Comment by bentacos** [comment]
I tried to list the files and folder in the root of the binary snapshot, this is what I got:

Windows:
```
main.cjs
node_modules
```

Linux:
```
main.cjs
worker1.cjs
worker2.cjs
worker3.cjs
node_modules
```

Does Windows and Linux has different build approach?

**Comment by bentacos** [comment]
I manage to find the cause of the problem. I forgot that I was using a custom script using @angablue/exe when building the binary for Windows. Sorry, my bad 💯

**Comment by marcosknudsen** [comment]
How can i solve this?
