### ISSUE TITLE
pkg@5.8.1 "No available node version satisfies node16.14.2"

### ISSUE THREAD

**Issue by SpacewormSera** [vercel/pkg#1932]
PKG version: pkg@5.8.1
Node version: 16.14.2
OS: Windows10

package.json: 

```
"bin": "app2.js",
  "pkg": {
    "assets": "./ADDONS/...pathToAddon/myAddon.node",
    "outputPath": "dist"
  },
  
  "scripts": {
    "build": "pkg . --target node16.14.2-win-x64 --out-path dist/"
  }
```

I have only Node 16.14.2 installed. When in "build" section the node version is set like "node16.14.2-win-x64",  it shows the error: 
```
"No available node version satisfies node16.14.2"
```

 I used #1623 issue answer -
"add console.log in the pkg module's lib-es5/producer.js, find a function called "nativePrebuildInstall", add console.log(nativeFile)"

But if I set target like this "node16-win-x64"  I get this:

```>>>nativeFile:  C:\somePath\ADDONS\Logger\bin\x64\Release\Logger.node.win.v16.16.0```

So the question is how to explicitly set the version to 16.14.2 ?

_Originally posted by @SpacewormSera in https://github.com/vercel/pkg/discussions/1930_

**Comment by baparham** [comment]
there is not a requirement that the binary pkg creates and your environment node version have to match. Is there a specific reason you need 16.14.2 instead of using 16.16.0 as pkg wants to?

**Comment by SpacewormSera** [comment]
Yes, there was specific reason for it - I have native addon module, which runs only on that version. So, after some digging out I found out that specific version of pkg works with specific version of Nodejs. In my case the pkg version should've been 5.6.0.
