### ISSUE TITLE
how to run linux compiled node.js script in linux? i dont know the commands

### ISSUE THREAD

**Issue by TERRYKOLBEN** [vercel/pkg#1935]
### What version of pkg are you using?

5.4.1

### What version of Node.js are you using?

18

### What operating system are you using?

ubuntu , centos

### What CPU architecture are you using?

-

### What Node versions, OSs and CPU architectures are you building for?

node18-linux

### Describe the Bug

whats the command to run this file without any extension under linux / centos?

### Expected Behavior

whats the command to run this file without any extension under linux / centos?

### To Reproduce

whats the command to run this file without any extension under linux / centos?

**Comment by OneCricketeer** [comment]
From README

> Command line call to packaged app `./app a b` is equivalent to `node app.js a b`
