### ISSUE TITLE
Better error message than "AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value"

### ISSUE THREAD

**Issue by samuelko123** [vercel/pkg#1938]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

16.13.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node14-win-x64

### Describe the Bug

Basically, it is a re-open of #1631.

If I'm on VPN and trying to fetch Node.js source, it will give error message like this:
![image](https://github.com/vercel/pkg/assets/91960206/97cd735d-c21c-4723-9b4e-9a410fc682cb)

If I comment out this line:
![image](https://github.com/vercel/pkg/assets/91960206/6f6e720c-6ee5-4f85-855c-2e17a7691785)

Then I will get this error, which is more comprehensible:
![image](https://github.com/vercel/pkg/assets/91960206/9a9adffe-1bf4-4a4b-9de9-9a5cf2791ae7)

I understand it's an upstream issue (`pkg-fetch`), but I'll leave it here for you to coordinate with `pkg-fetch`.
After all, I'm using `pkg`.

### Expected Behavior

Display this error:
`Error! FetchError: request to https://nodejs.org/dist/v14.20.0/SHASUMS256.txt failled, reason: unable to get local issuer certificate`

Instead of this error:
`Error! AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:`

### To Reproduce

1. Make sure you're on VPN
2. Delete the `PKG_CACHE_PATH` folder (For me, it's `C:\Users\<user>\.pkg-cache`)
3. Run `npx pkg --targets node14-win-x64 --output ./bin/test index.js` (or something like that)
4. It'll give the error message

**Comment by ninjaboy** [comment]
Still reproduces for me on windows despite environment variable being set, how can I reopen this?
