### ISSUE TITLE
Files packaged with code containing pupeteer-core 20.4.0 or higher cannot be executed

### ISSUE THREAD

**Issue by MCHK0306** [vercel/pkg#1947]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

18.16.0

### What operating system are you using?

macOS

### What CPU architecture are you using?

Apple M1

### What Node versions, OSs and CPU architectures are you building for?

node18-macos-arm64, node18-win-arm64

### Describe the Bug

When I package puppeteer-core 20.4.0 or higher and launch the executable, the following error message occurs.
(The error does not occur with puppeteer-core 20.3.0 or lower, but there is a bug in 20.3.0 or lower, so we want to use 20.4.0 or higher)

To begin with, I don't know if the error is caused by pkg or by puppeteer-core.

----------------
pkg/prelude/bootstrap.js:657
    const error = new Error(
                  ^

Error: File '/**/InventoryTool_v4/node_modules/vm2/lib/setup-sandbox.js' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
    at Object.<anonymous> (/snapshot/InventoryTool_v4/node_modules/vm2/lib/vm.js:148:57)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31) {
  errno: -2,
  code: 'ENOENT',
  path: '/snapshot/InventoryTool_v4/node_modules/vm2/lib/setup-sandbox.js',
  pkg: true
}

Node.js v18.5.0

### Expected Behavior

I need solution.

### To Reproduce

Sorry, but my code is under development and we would like to avoid sharing it as much as possible.

**Comment by AYS08** [comment]
There are two solutions for this

FYI: My Puppeteer version is 20.7.4 and these solutions works fine.

1. Adding node_modules as assets

You will have to add these lines to your package.json file
```javascript
"bin": {
    "index": "./index.js"  //Path to your entry file (Delete this comment if you are copying this to package.json)
},
"pkg": {
    "assets": [
        "node_modules/**/*"
    ],
    "targets": [
        "node18-macos-arm64",
        "node18-win-arm64"
    ]
}
```

 and execute `pkg .` or `pkg package.json` to compile the executables else it won't work

Or If you don't like to edit your package.json then there is another solution

2. Using path.join() to your entry file

This dosen't include fiddling with package.json just add this code in your entry file 

```javascript
const path = require('path');
path.join(__dirname, "node_modules/vm2/lib/setup-sandbox.js");
```

Note: Make sure that you are pointing towards node_modules folder. If your file structure is like this
├── node_modules
├─┬ src
│ └── index.js
├── package-lock.json
└── package.json
then add `../` before node_modules to go to parent folder i.e
```javascript
const path = require('path');
path.join(__dirname, "../node_modules/vm2/lib/setup-sandbox.js");
```


and compile as usual using `pkg index.js` or `pkg ./src/index.js`

**Comment by robertsLando** [comment]
@AYS08 You should avoid adding all node_modules to assets, you should just add the modules needed by pupeteer

**Comment by AYS08** [comment]
@robertsLando Oh! Thank you for correcting me. I only used puppeteer and didn't think about DevDependency modules or modules that wouldn't be needed otherwise. I will update the assets.

**Comment by AYS08** [comment]
@robertsLando Also I found out that `pkg index.js` is being compiled differently than `pkg package.json`or `pkg .` which is the reason why I was getting `Error: Passed function cannot be serialized!` in puppeteer when using `pkg index.js`. May I open a new issue regarding this with a code to reproduce or should I dicuss it here?

**Comment by MCHK0306** [comment]
Thank you for all the information you have given me. But in the end, I didn't know the best solution, so I hope you can help me.

**Comment by AYS08** [comment]
@MCHK0306 You can use any solution you like, both work. If you are already using bin then go with the first solution. If you are not using bin and don't mind adding two extra lines in your code then you may go with the second solution.

**Comment by MCHK0306** [comment]
@AYS08 Thanks,  Thank you so much !!!  it worked!!!  I tried second solution since it seemed to be simple.

**Comment by AYS08** [comment]
@MCHK0306 You're Welcome (^‿^)
