### ISSUE TITLE
"config" package cannot access the directory

### ISSUE THREAD

**Issue by paveldhq** [vercel/pkg#1959]
### What version of pkg are you using?

5.8.0

### What version of Node.js are you using?

18.13.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

default

### Describe the Bug

the [config](https://www.npmjs.com/package/config) package requires a directory with yml files for configs. After packing with `pkg .` the build-in directory is not accessible.

### Expected Behavior

`config` directory with contents is found

### To Reproduce

1. Create a sample application using TypeScript
2. Add config as dependency
3. Add

```
... 
"pkg": {
  "targets": [
    "node18-linux-x64",
    "node18-win-x64",
    "node18-macos-arm64"
  ],
  "scripts": "dist/**/*.js",
  "outputPath": "release",
  "assets": [
    "config/*.yml"
  ]
}
...
```
to package.json

**Comment by ParseDark** [comment]
same issue.  This not work. We can't debug snapshot? Just want to double check the file has been copy into snapshot

```
  "assets": [
      "node_modules/.prisma/client/*",
      "build/**/*",
      "public/**/*",
      "dist/**/*"
    ],

```
