### ISSUE TITLE
Failed to compile node v18.5.0-win-x86

### ISSUE THREAD

**Issue by kerwenzhang** [vercel/pkg#1989]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

18.14.0

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node 18.5.0-win-x86

### Describe the Bug

I compiled pkg\examples\express using node.js v18.14.0 x86. The `package.json` was modified to: 
```
{
  "name": "express-example",
  "license": "ISC",
  "bin": "index.js",
  "dependencies": {
    "express": "4.15.2"
  },
  "pkg": {
    "assets": [
      "views/**/*"
    ],
    "targets": [
      "node18-win-x86"
    ]
  }
}
```

When run `pkg .` it started to download and compile `node 18.5.0-win-x86`
![image](https://github.com/vercel/pkg/assets/11705075/a412c1f4-11b5-42d0-a334-7f160caaf79b)

But it stopped during compile
![image](https://github.com/vercel/pkg/assets/11705075/ad6797fd-a18b-43f1-a73d-85b837b621d6)

Going to the node folder, I could run `.\vcbuild.bat` successfully.

### Expected Behavior

Should compile sucessfully.

### To Reproduce

Download pkg 5.8.1
Goto examples\express, run npm install
modify package.json 
run pkg .

**Comment by matevy** [comment]
This probably happens because you are building node 18.5.0 with gcc 13.
