### ISSUE TITLE
Error: ENOSPC: no space left on device, mkdtemp '/tmp/pkg-XXXXXX'

### ISSUE THREAD

**Issue by charbelMat** [vercel/pkg#1990]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

16.20.1

### What operating system are you using?

Ubuntu 22.04.1 LTS

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node16-linux-x64

### Describe the Bug

When we run the binary on different Threads, 12 in our case on a 16 CPU machine, the /tmp folder is filled with pkg-XXXXX files and getting this memory error:

Error: ENOSPC: no space left on device, mkdtemp '/tmp/pkg-XXXXXX'

Our tmp storage is small (20 M approx) and we can't increase so is there's any way to change where pkg saves those files ? 

Thank you 

### Expected Behavior

Use a different Directory than /tmp

### To Reproduce

Run the built binary on different threads with a small tmp storage folder.

**Comment by robertsLando** [comment]
You should try opening a PR to set a different tmp folder using an env var. Remember to update docs too

**Comment by charbelMat** [comment]
thank you @robertsLando for your advice. but the ISP won't let use modify the moutings.

**Comment by robertsLando** [comment]
What I mean is to create the PR on this project to add that funcitonality

**Comment by charbelMat** [comment]
It would be a pleasure to contribute. But first you have to explain to me what do u mean by PR :) And is there's any git standards to follow for contribution here ? Thank you

**Comment by robertsLando** [comment]
PR stays for pull request. It's a way to contribute to a git project. You essentially need to fork this project and start making the changes needed on that fork then you create a pull request once you are done, I will review your changes and if everything is ok merge them in master.
