### ISSUE TITLE
pkg 5.8.1 somehow lists pkg-fetch 3.4.2 as required dependency in package-lock.json. How to update it so 3.5 is leveraged?

### ISSUE THREAD

**Issue by RCALEAD** [vercel/pkg#1998]
### Discussed in https://github.com/vercel/pkg/discussions/1997

<div type='discussions-op-text'>

<sup>Originally posted by **RCALEAD** September 26, 2023</sup>
Working towards updating node.js to version 18.15, but somehow it still shows nodejs 18.5. Looks like issue is that pkg 5.8.1 is still listing pkg-fetch 3.4.2 as dependency in package-lock.json , which will only allow nodejs version 18.5. For nodejs version 18.15, it needs pkg-fetch 3.5 in dependency in package-lock.json - how this can be updated?</div>

**Comment by ryanrubleycoates** [comment]
I just added this to my package.json:
```
  "overrides": {
    "pkg": {
      "pkg-fetch": "^3.5.2"
    }
  }
```

**Comment by ryanrubleycoates** [comment]
Unfortunately, we have a bunch of stuff that seems to be moving to requiring 18.17.0+ or 20+ and it looks like pkg might be coming to a dead-end from some other threads here.

**Comment by robertsLando** [comment]
Use: https://github.com/yao-pkg/pkg
