### ISSUE TITLE
Error! No available node version satisfies 'node20'

### ISSUE THREAD

**Issue by filefi** [vercel/pkg#2014]
### What version of pkg are you using?

5.8.1

### What version of Node.js are you using?

v20.9.0

### What operating system are you using?

Windows

### What CPU architecture are you using?

x86_64

### What Node versions, OSs and CPU architectures are you building for?

node-v20.9.0-win-x64

### Describe the Bug

node-v20.9.0 is already LTS. but still get this error:
```
Error! No available node version satisfies 'node20'
```

### Expected Behavior

output single .exe file

### To Reproduce

![image](https://github.com/vercel/pkg/assets/16501603/d7b6a5f2-fb49-4b4e-a0f0-9a4825b8a3dd)

**Comment by chstappert** [comment]
Have a look here: https://github.com/vercel/pkg/discussions/1972#discussioncomment-7113223

**Comment by damartripamungkas** [comment]
try with this fork repo : https://github.com/yao-pkg/pkg-fetch

**Comment by milkcoke** [comment]
bump..

**Comment by ronak1009** [comment]
I am too facing the similar issue with node 20 on Ubuntu 20.04. Max I could try to pkg is with node18-linux-x64. Is this still under development?
```
> pkg index.js
> pkg@5.8.1
> Targets not specified. Assuming:
  node20-linux-x64, node20-macos-x64, node20-win-x64
> Error! No available node version satisfies 'node20'
```
