### ISSUE TITLE
Dynamic file reading and serving (images, videos)

### ISSUE THREAD

**Issue by nwaxiomatic** [vercel/pkg#210]
I'm having issues packaging my app which takes webcam photos, saves the photos, converts them to a video, and then hands the video and image back to the frontend as relative file locations.

Before packaging this was lazily done by just returning the frontend http calls with the directory name of the image and file to be loaded, however because pkg requires all static files to be linked during the packaging process this seems to hard break the architecture of the code.

Do I need to change the app over to an http stream system or can pkg dynamically serve the newly created files?

Thanks in advance.

**Comment by i-khan** [comment]
+1
