### ISSUE TITLE
PKG is not compiling referenced modules when babel-register is in use.

### ISSUE THREAD

**Issue by winneon** [vercel/pkg#211]
Hello,

I am trying to use `babel-register` with my current project, and when I reference an ES6-compliant module that should be transpiled by `babel-register`, instead PKG cannot generate the bytecode for said file and the resulting binary cannot find the referenced module.

`index.js`

```javascript
'use strict'

require('babel-register')
new (require('./main.js').default)
```

`main.js`

```javascript
'use strict'

class Main {
  constructor(){
    console.log("Hello, world!")
  }
}

export default Main
```

The output for the PKG command is as follows:

```
dankisk-arch ~/dev/seekrit % ./node_modules/.bin/pkg --targets latest-linux-x64 app/index.js
> pkg@4.2.4
> Warning Failed to make bytecode latest-x64 for file /snapshot/seekrit/app/main.js
dankisk-arch ~/dev/seekrit % 
```

What am I doing wrong here? My node version is the latest and so is PKG.

**Comment by boshido** [comment]
I'm using babel-register too.
For me I faced problem of "..." syntax, it caused pkg throw an error when it found "..." command
```
> pkg@4.2.4
> Error! Unexpected token (25:84)
  /home/boshido/Sendit/sendit-2stage-api/app/apis/admin/admin-driver.flow.js
```

**Comment by konsumer** [comment]
I have a similar issue. [Here](https://github.com/konsumer/shadertoy) is the project I am trying to compile. It uses node-webgl to make the window. Runs fine locally, but I get this when I try to build:

```
> shadertoy@0.0.0 build /Users/konsumer/Desktop/shadertoy
> rimraf shadertoy && pkg src/index.js --public -o shadertoy

> pkg@4.2.4
> Targets not specified. Assuming:
  node8-macos-x64
> Warning Failed to make bytecode node8-x64 for file /snapshot/shadertoy/src/main.js
> Warning Failed to make bytecode node8-x64 for file /snapshot/shadertoy/src/ui.js
> Warning Failed to make bytecode node8-x64 for file /snapshot/shadertoy/src/Effect.js
```

**Comment by bipinacellere** [comment]
I m facing similar issue?
Any updates on this?

I m trying with "pkg --target latest-linux-x64 app.js"

> Warning Failed to make bytecode latest-x64 for file /snapshot/test/node_modules/safefs/es6/lib/safefs.js

**Comment by cancerberoSgx** [comment]
Did you try to bundle all first with browserify like this ? 

```
browserify myappindex.js --no-bundle-external  --no-builtins  -o bundle.js
pkg -t node8-linux -c pkg.json -o execfile bundle.js
```

**Comment by coderfox** [comment]
I solved this by removing `~/.pkg-cache`.

It seems some of the prebuilt binary are broken for some time.

**Comment by PiotrAleksander** [comment]
Have you actually tried to build your app first?
If using Babel better transpile using `babel app -d dist` and then indicate entrypoint at /dist to the pkg, like `pkg ./dist/index.js`.
