### ISSUE TITLE
How to modify properties of the .exe

### ISSUE THREAD

**Issue by Heronbeluci** [vercel/pkg#212]
I need to add icon and force administrator in my distribuition, how i do this?

sorry about this, but i cant find in the documentation.

**Comment by dsole** [comment]
I think you need to do this by modifying the EXE after pkg has run.
See #149 for a similar issue

**Comment by mmamedel** [comment]
I had a similar need to change the EXE's resources.
As you will see in the code below a lot can be done in different ways, but the spirit behind this solution is:

Download cache with pkg-fetch
Edit cache with rcedit
Use cache in pkg
Here is my typescript code:

import rcedit from 'rcedit'
import glob from 'glob'
import path from 'path'

process.env.PKG_CACHE_PATH = path.resolve('./.pkg-cache')
build()

async function build() {
  const pkgTarget = 'node14-win-x64'
  const cacheExe = await downloadCache(pkgTarget)

  await rcedit(cacheExe, {
    'product-version': '1,0.0.0',
    'file-version': '1,0.0.0',
    icon: path.resolve('./src/assets/icon.ico'),
    'version-string': {
      FileDescription: 'File description',
      ProductName: 'Program Name',
      LegalCopyright: `© ${new Date().getFullYear()} My Copyright.`,
      OriginalFilename: 'program.exe',
    },
  })

  const pkg = await import('pkg')
  const outputExe = path.resolve('./dist/output.exe')
  await pkg.exec([path.resolve('./dist/app.js'), ...['--target', pkgTarget], ...['--output', outputExe]])
}

async function downloadCache(pkgTarget: string): Promise<string> {
  const [nodeRange, platform, arch] = pkgTarget.split('-')
  const pkgFetch = await import('pkg-fetch')
  await pkgFetch.need({ nodeRange, platform, arch })
  const cacheExe = glob.sync(`${PKG_CACHE_PATH}/**/fetched*`)
  if (cacheExe.length < 1) throw new Error('Error downloading PKG cache')

  return cacheExe[0]
}

**Comment by robertsLando** [comment]
@mmamedel Are you interested on integrating that in pkg? I think it would be easy to do, it just needs a new option maybe pointing to a file that specify the configuration to use in rcedit, when that option is specify simply run that code after the node binary download

**Comment by mmamedel** [comment]
Yes, I’ll be glad to help. Your idea is an additional argument in the pkg.exec() function? Something like —resources or -rc? And you said this would point to a file with confit for rcedit, you envision a json file? 
Another option is adding these options to the package.json under the pkg session. What sounds a better implementation?

**Comment by robertsLando** [comment]
yeah you could place this in package.json `pkg` settings, maybe under `rcOptions`. I think this only works with windows exe right?

**Comment by eborned** [comment]
I tried the above solution, but it does not seem to work. The cache file is changed (although I cannot seem to change the ICO, but that could be a rcedit issue). But the main problem is that the `pkg` does not use the modified cache file, because the hash does not match. So it redownloads the file, reverting all rcedit changes:

```
> pkg@5.2.1
compression:  Brotli
> Binary hash does NOT match. Re-fetching...
  fetched-v14.17.0-win-x64            [====================] 100%
```

Did you not run into this or is the binary hash check new?

**Comment by mmamedel** [comment]
@TheCelebrimbor As you can see in the example I posted previously, I’m not changing the final pkg output with rcedit, instead I edited Node.js cache executable downloaded by pkg-fetch and used it with pkg to create the executable.
