### ISSUE TITLE
Add Node 8.4.0

### ISSUE THREAD

**Issue by garthk** [vercel/pkg#215]
Same shape as #191.

**Comment by jgoux** [comment]
v8.5.0 is out too. 😃

**Comment by mika-fischer** [comment]
And 8.6.0...

**Comment by cancerberoSgx** [comment]
I think this issue should be closed since support for node 8.6.0 is done:
https://github.com/zeit/pkg/releases/tag/4.2.5

I tested it successfully with : 
`
pkg -t node8.6.0-linux -c pkg.json -o myexec bundle.js
`
