### ISSUE TITLE
pkg and upx compression.

### ISSUE THREAD

**Issue by antoniomuso** [vercel/pkg#228]
Any executable  packed with pkg and compressed with upx seems to be broken. You just see the Node prompt but the app is not executed.

**Comment by cayuu** [comment]
Dupe: https://github.com/zeit/pkg/issues/121
Related: https://github.com/zeit/pkg/issues/50

**Comment by nd0164** [comment]
you may try a new toy [pkgx](https://github.com/irelance/node-pkgx)

**Comment by ArkadiuszMichalski** [comment]
For anyone UPX+pkg works even for simple console.log("hellow world") on Windows? If yes please share what version Node/UPX/pkg and system you used and what args you used. I always get Pkg: Error reading from file.
