### ISSUE TITLE
warning : cannot include addon %1 into executable

### ISSUE THREAD

**Issue by hnlinzhi19** [vercel/pkg#229]
warning question: 
> pkg@4.2.4
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  G:\gitbook\pkg-test\node_modules\node-sass\vendor\win32-x64-57\binding.node
  path-to-executab

Environmen ：  win10 
code: `
var sass = require('node-sass');
var data = '#hello {\n  color: #08c; }\n';
const result = sass.renderSync({ data: data }).css.toString();
if (result === data) {
  console.log('ok');
}`

I only copy node-sass test,but in my pc ,i cannot pkg node-sass; At the same time, I copy binding.node to root , but the same warning .

**Comment by wuyuanyi135** [comment]
I have the same issue

**Comment by santorkclows** [comment]
Hi,
I have a similar problem with Sharp, also on Windows 10

package.json
`{
"name": "test", "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "author": "",
  "license": "ISC",
  "dependencies": {
    "sharp": "^0.18.3"
  }
}`

index.js
`var sharp = require('sharp');

sharp('test.jpg')
    .resize(200)
    .toFile(new Date().getTime() + '.jpg')
    .then((info) => { console.log(info) })
    .catch((err) => { console.error(err) });`

**Comment by santorkclows** [comment]
Hi,
I have a similar problem with Sharp, also on Windows 10.
I have created a small example with this issue

**package.json**
```
{
  "name": "test", 
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "author": "",
  "license": "ISC",
  "dependencies": {
    "sharp": "^0.18.3"
  }
}
```

**index.js**
```
var sharp = require('sharp');

sharp('test.jpg')
    .resize(200)
    .toFile(new Date().getTime() + '.jpg')
    .then((info) => { console.log(info) })
    .catch((err) => { console.error(err) });
```

**After running pkg the output is:**
 

> pkg -o .\exe\test.exe -c .\package.json .\index.js
> > pkg@4.2.4
> > Targets not specified. Assuming:
>   node8-win-x64
> > Warning Cannot include file %1 into executable.
>   The file must be distributed with executable as %2.
>   C:\Node-js\TSWorkspace\sandbox\test\node_modules\sharp\build\Release
>   path-to-executable/sharp/build/Release
> > Warning Cannot include file %1 into executable.
>   The file must be distributed with executable as %2.
>   C:\Node-js\TSWorkspace\sandbox\test\node_modules\sharp\vendor\lib
>   path-to-executable/sharp/vendor/lib

Any help would be appreciated!

**Comment by patrickhulce** [comment]
I'm also experiencing this with sharp for a folder that doesn't seem to exist, so I'm not sure what, if anything, needs to be copied to root. Executable seems to work fine on my machine though 🤷‍♂️ 

`node_modules/sharp/` has no vendor or vendor/lib subdirectories.

**Comment by Charrondev** [comment]
@hnlinzhi19 I ran into this issue today and have resolved it:

- You need to move your compiled node-sass `binding.node` file into a mirror of the file structure in built directory. For example in my case I was packaging a file `/git/vanilla-cli/src/buildtool.js` into 

-`/git/vanilla-cli/bin/buildtool-macos`

The macOS version of the node binding was in `/git/vanilla-cli/src/node_modules/node-sass/vendor/darwin-x64-57/binding.node`. I needed to copy this binding to the location `/git/vanilla-cli/bin/node-sass/vendor/darwin-x64-57/binding.node`, and now it works.

This will only work on this particular OS that I'm running though. I intend to also build this to run on Windows and that will require packaging my tool on a windows machine and copying a second `binding.node` to a slightly different folder.

**Comment by Charrondev** [comment]
@patrickhulce There should be a file `C:\Node-js\TSWorkspace\sandbox\test\node_modules\sharp\build\Release\sharp.node` and ~30 files in `C:\Node-js\TSWorkspace\sandbox\test\node_modules\sharp\vendor\lib`. 

You will need to copy the `sharp.node` to `C:\Node-js\TSWorkspace\sandbox\test\exe\sharp\build\Release\sharp.node`. You will probably also need to copy the ~30 .dylib files to `C:\Node-js\TSWorkspace\sandbox\test\exe\sharp\vendor\lib`.

I can't see your whole project structure but I would imagine it needs to look like this:
`C:\Node-js\TSWorkspace\sandbox\test`
|-- `node_modules`
|-- `index.js`
|-- `exe`
|---|-- `test.exe`
|---|-- `sharp`
|---|---|-- `build\Release`
|---|---|---|-- `sharp.node`
|---|---|-- `vendor\lib`
|---|---|---|-- A bunch of `.dylib files`

I'm not 100% sure about the `.dylibs` and how they differ from the `.node` files, but I can definitely see them in my `node_modules` folder.

The error messages for this type of thing should be much clearer.

**Comment by santorkclows** [comment]
@Charrondev Thx for info. I will copy these files manually. Shame that, PKG doesn't integrate those files to the exe file or copies them in a right directory.

**Comment by patrickhulce** [comment]
Thanks for the response @Charrondev, but the problem is specifically that there is no vendor subdirectory in the `node_modules/sharp` folder. `build/Release` is there, I've copied it, and all seems well, but the vendor directory pkg tells me to copy simply doesn't exist. 

```sh
$ pkg
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules/sharp/vendor/lib
  path-to-executable/sharp/vendor/lib
$ ls node_modules/sharp/vendor/lib
ls: node_modules/sharp/vendor/lib: No such file or directory
$ ls -1 node_modules/sharp
CONTRIBUTING.md
LICENSE
README.md
binding.gyp
binding.js
build
docs
lib
node_modules
package.json
src
```

**Comment by mrvik** [comment]
C addons cannot be included no matter if you put them in `pkg.assets` on `package.json` , any update on this?

**Comment by lauborges** [comment]
I have the same issue

**Comment by ifree92** [comment]
I also have this problem when I'm trying to build the small application with the `node-pty` module inside.

Would be great to have an ability just to mark files which will be just copied inside of binary keeping original path.

Any thoughts on it?

**Comment by scientistnik** [comment]
Build package with `sqlite3`. Same issue....

**Comment by dogeFu** [comment]
pack with oniguruma,Same issue.
still get a xx.exe  thought.
I create a folder to put the file was warning, under the same folder with xx.exe. Then the exe works well.
This tool is really good~~~
 It will be better if this issue is fixed.

**Comment by simnovus** [comment]
You can use nexe package for now. It performs the same thing and equally effficient.

**Comment by vermadev95** [comment]
You can use nexe package for now. It does the same work.

**Comment by fcastilloec** [comment]
@vermadev95 `nexe` seems to have the same problem as this module when trying to include `*.node` files as resources

**Comment by FengBryan** [comment]
Is this issue has any process？ I have same problem with use `node-canvas`.

**Comment by lemoncalamitous** [comment]
Same issue on my end when packaging my app with `bcrypt`. I'll wait if a fix is in progress on this.

**Comment by zhushenhang** [comment]
> Same issue on my end when packaging my app with `bcrypt`:
> ![image](https://user-images.githubusercontent.com/24726531/92121135-8248c400-ee2c-11ea-9f6d-0f8dc6230aa4.png)
> 
> node_modules were added as asset using
> `"pkg": { "assets": [ "node_modules/**/*", ] }`
> 
> I'll wait if a fix is in progress on this.

yes,I encountered the same problem as you while using bcrypt, how did you solve it?
thank you.

**Comment by shyser** [comment]
This is my solution: 

```typescript
const BEFORE = 'before';
const AFTER = 'after';

handleModuleSharp(BEFORE, cwd);
await runCmd(cwd, `pkg . --targets node12-linux-x64 `);
handleModuleSharp(AFTER, cwd);

function handleModuleSharp(arg: string, cwd: string) {
  const pkgName = path.join(cwd, 'package.json');
  const pkgInfo = fse.readJSONSync(pkgName);
  if (!pkgInfo.dependencies.sharp) return;

  const moduleSharpDir = path.join(cwd, 'node_modules/sharp');
  const keyStr = {
    raw: "require('../build/Release/sharp.node')",
    replaced: "require(require('path').join(process.cwd(), 'sharp/build/Release/sharp.node'))",
  };
  const targetDir = path.join(moduleSharpDir, 'lib');
  fse.readdirSync(targetDir).forEach(filename => {
    if (!filename.endsWith('.js')) return;
    const filepath = path.join(targetDir, filename);
    let content = fse.readFileSync(filepath, {encoding: 'utf8'});
    if (arg === BEFORE) content = content.replace(keyStr.raw, keyStr.replaced);
    else if (arg === AFTER) content = content.replace(keyStr.replaced, keyStr.raw);
    fse.writeFileSync(filepath, content);
  });
  if (arg === AFTER) {
    fse.copySync(path.join(moduleSharpDir, 'build'), path.join(cwd, 'sharp/build'), {recursive: true});
    fse.copySync(path.join(moduleSharpDir, 'vendor'), path.join(cwd, 'sharp/vendor'), {recursive: true});
  };
};
```

**Comment by winie-hy** [comment]
So is there a proper solution? This problem has been bothering me for a long time, and I have been unable to package the Node. js file

**Comment by winie-hy** [comment]
Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\puppeteer\.local-chromium
  %2: path-to-executable/puppetee

Hope to get help

**Comment by winie-hy** [comment]
and my index.js was  this:
const puppeteer = require('puppeteer');
var fs = require("fs");
																											
puppeteer.launch({headless:false}).then(async browser => {
    const page = await browser.newPage();
    await page.goto('https:www.baidu.com');

    let html = await page.content()
    // other actions...
    // fs.writeFileSync(path.join(__dirname, 'm.txt'), html.toString(),'utf-8')

});

**Comment by max-programming** [comment]
These are the warnings I get when I package my app. I even tried to copy the files. 
But I would admit that `node_modules\sharp\vendor\lib` does not exist. Instead I have `node_modules\sharp\vendor\8.10.0\lib`

```sh
PS D:\Nodejs\whatsapp-api-js> npm run build

> whatsapp-api-js@1.0.0 build
> pkg index.js -t node14-win-x64 --config package.json

> pkg@4.4.9
> Warning Cannot resolve '`./session.json`'
  D:\Nodejs\whatsapp-api-js\index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve '`./session.json`'
  D:\Nodejs\whatsapp-api-js\index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: D:\Nodejs\whatsapp-api-js\node_modules\fsevents\fsevents.node
  %2: path-to-executable/fsevents.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: D:\Nodejs\whatsapp-api-js\node_modules\sharp\build\Release\sharp.node
  %2: path-to-executable/sharp.node
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\puppeteer\.local-chromium
  %2: path-to-executable/puppeteer
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\puppeteer\.local-chromium
  %2: path-to-executable/puppeteer
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\sharp\build\Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\sharp\vendor\lib
  %2: path-to-executable/sharp/vendor/lib
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\sharp\build\Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules\sharp\vendor\lib
  %2: path-to-executable/sharp/vendor/lib
```

**Comment by femski** [comment]
This is really shameful. Just spent a day dealing with this (upgrading downgrading versions of npm modules and node versions)

You have to tar/package your executables generated by pkg along with add.node type artifacts  in your node_modules directory  (left behind by pkg)  and place them together in exact same structure at your target location. "pkg" strangely does not copy/include .node artifacts. 

So do something like this (from root of your project):

tar -cvf  mypackage.tar `find node_modules -name '*.node'` ./myexecutable

now take mypackag.tar to your destination and do a

tar -xvf mypackage.tar

This will extract the addon.node etc files in node_modules directory and along with executabls generated by pkg.

now you can run: ./myexecutable

In my case missing artifacts were:

/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node
./node_modules/node-expat/build/Release/node_expat.node
./node_modules/node-expat/build/Release/obj.target/node_expat.node
./node_modules/libpq/build/Release/addon.node
./node_modules/libpq/build/Release/obj.target/addon.node
./node_modules/node-sass/vendor/linux-x64-64/binding.node

**Comment by akrapacs** [comment]
I'm having the same problem with sharp. I see 4 warnings when I run the `pkg` command:

```
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/sharp/build/Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/sharp/vendor/lib
  %2: path-to-executable/sharp/vendor/lib
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/sharp/build/Release
  %2: path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  %1: node_modules/sharp/vendor/lib
  %2: path-to-executable/sharp/vendor/lib
```

**package.json:**
```
"bin": "dist/index.js",
"pkg": {
        "scripts": "dist/**/*.js",
        "targets": [
            "node14-macos-x64"
        ],
        "outputPath": "pkg"
}
```

**build script:**
```
rm -fr pkg
npm run-script build
pkg .

mkdir -p pkg/sharp/build
cp -r node_modules/sharp/build/Release pkg/sharp/build/Release

mkdir -p pkg/sharp/vendor
cp -r node_modules/sharp/vendor/8.10.5/lib pkg/sharp/vendor/lib
```

Note: The warning specifies `path-to-executable/sharp/vendor/lib` but that doesn't exist for me

**When I run the executable I get:**

```
pkg/prelude/bootstrap.js:1359
      throw error;
      ^

Error: 
Something went wrong installing the "sharp" module

dlopen(/var/folders/fb/x390_95n0756wbj8hvxp76pw0000gn/T/979222841668bc8ce0c0515e4d11b523098b453ef9c9bb8e143159c56e157456_sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: /var/folders/fb/x390_95n0756wbj8hvxp76pw0000gn/T/979222841668bc8ce0c0515e4d11b523098b453ef9c9bb8e143159c56e157456_sharp.node
  Reason: image not found
```

I get the same error message if I try to execute without the `sharp` directory which seems to indicate it's not finding it at all.
