### ISSUE TITLE
How attach .exe files?

### ISSUE THREAD

**Issue by zentala** [vercel/pkg#235]
I would like to attach MongoDB files to generated by pkg .exe file. I planning to run it using `exec`. I added mongo path to `package.json`:
```
  "pkg": {
    "assets": "client/**/*",
    **"scripts": "mongo/**/*"**
  }
```

Unfortunately, after running `pkg` I got an error:
```
> Error! Unexpected character '�' (1:2)
  C:\htdocs\[project_name]\dist\mongo\bsondump.exe
```

So I have questions:
1) Is it even possible to attach some exe files to my package? 
2) If yes how can I do it? 
3) Is there any different possibility to pack MongoDB app files and generated by pkg exec to one exe file?

**Comment by megastef** [comment]
Did you try to add the .exe to "assets"?
