### ISSUE TITLE
Issue with pkg

### ISSUE THREAD

**Issue by arijit158** [vercel/pkg#242]
I have created a nodejs app with express-generator.Now when I run this pkg it creates the binary file for me.But unable to run the file.I could not find any error to debug.
Attach the folder structure.Can you please guide me little bit briefly.
From the ReadMe I am unable to understand and get no clue in some where else.
![screenshot from 2017-09-22 17-36-53](https://user-images.githubusercontent.com/1275171/30743795-cbed2bbc-9fbc-11e7-9ec4-2eb4d4b1bcc2.png)
Attach the pakage json file.

![packagejson](https://user-images.githubusercontent.com/1275171/30743903-37c33444-9fbd-11e7-9076-8380cd9e2b75.png)

Please let me know what to change in package json or any change required in the folder structure

**Comment by cancerberoSgx** [comment]
are you in windows or unix ? in windows just execute the generated .exe. Use the terminal. In unix - linux or mac - probably you need to give execution permissions before executing it, like this: 
`
chmod a+x ./yourexec
./yourexec
`

**Comment by KalaiselvanMahendran** [comment]
you no need to add node_modules in package.json
