### ISSUE TITLE
[Doc] add doc for show how to manual fetch the base binaries.

### ISSUE THREAD

**Issue by Cologler** [vercel/pkg#243]
By some reason, some area cannot fetch them on cli:

![picpick-20170924-161548-001](https://user-images.githubusercontent.com/10906962/30780770-592c9d6c-a145-11e7-8c04-2ad747bde86a.png)

I am already read the source code and download base binaries from https://github.com/zeit/pkg-fetch/releases and rename them.

However, if this can add into doc, it may helpful.

**Comment by stevobm** [comment]
I also meet with the same problem, and I can't even download the releases!

**Comment by Cologler** [comment]
@stevobm try use proxy.
