### ISSUE TITLE
Support for native modules required through 'bindings' module

### ISSUE THREAD

**Issue by mika-fischer** [vercel/pkg#250]
It would be great if pkg would have special handling for the bindings module, since it's quite popular. See here for inspiration:

https://github.com/nexe/nexe/blob/79bcb753b462d5d87580f773c8024bcf89888076/src/bundling/bindings-rewrite.ts#L125-L138

**Comment by sam-lex** [comment]
My .exe worked inside my app folder, but got bindings error once it was out. But if node_modules folder is together, it executes with no problems. this might be a temporary work-around.

**Comment by mika-fischer** [comment]
@igorklopov Could you give a pointer as to how these could be supported?

**Comment by RobLoach** [comment]
Related: https://github.com/zeit/pkg/issues/250

**Comment by meetmangukiya** [comment]
Why is this issue linking itself? @RobLoach did you mean to link something else?

**Comment by RobLoach** [comment]
Probably a wrong clipboard. I forget which issue I was originally attempting to link.

**Comment by meetmangukiya** [comment]
Okay thanks, I was hoping someone solved this problem

**Comment by RobLoach** [comment]
The best I could come up with was having the binary in the same directory. Seemed satisfactory for my use case.
