### ISSUE TITLE
Cannot require with a substitution-free template string

### ISSUE THREAD

**Issue by jaubourg** [vercel/pkg#252]
In the project I'm trying to compile, I have files with require statements like this:

```js
const program = require( `commander` );
```

Which give me the following kind of warnings:

```
> Warning Cannot resolve '`commander`'
```

At runtime, I get the following error message:

```
Error: Cannot find module 'commander'
```

Of course, the following works:

```js
const program = require( "commander" );
```

It's even worse when such requires are within a dependency. In that case, no warning is issued at all during compilation and we're left with the runtime error alone.

Sadly, the project is pretty big with lots of dependencies and the style guide covering them all requires the usage of backtick strings wherever possible... which includes require statements.

I've also tried nexe and it suffers from the same problem (I will open an issue there too).

Any chance to have substitution-free strings considered as string litterals so that such require statements are recognized ?

**Comment by cancerberoSgx** [comment]
I'm using browserify like this which supports it: 

```
browserify myappindex.js --no-bundle-external  --no-builtins  -o bundle.js
pkg -t node8-linux -c pkg.json -o execfile bundle.js
```
