### ISSUE TITLE
API rate limit exceeded for pkg on travis

### ISSUE THREAD

**Issue by 0i0** [vercel/pkg#266]
hope i'm in the right place.
I'm getting  API rate limit exceeded error I think its when travis is trying to pkg my node

doesn't anyone have a work around?

https://travis-ci.org/0i0/nonky/builds/290889917

> > pkg@4.2.5
> > Fetching base Node.js binaries to PKG_CACHE_PATH
> > Error! ESOCKETTIMEDOUT
> > Asset not found by direct link:
>  {"tag":"v2.3","name":"uploaded-v2.3-node-v6.10.3-macos-x64"}
> > Error! API rate limit exceeded for 208.78.110.199. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by wilmardo** [comment]
Has anyone resolved this issue? It is possible to pass authentication to the requests?
