### ISSUE TITLE
Make some kind of self-extracting archive or installer(How to do that)?

### ISSUE THREAD

**Issue by saiteja2464** [vercel/pkg#268]
Hi,

Can anyone help me with this, I could see on npm page it is mentioned that an installer can be built using pkg. But I couldn't find a way to do that. I was able to build executables.  Any help will be greatly appreciated.

Thanks,

**Comment by sam0x17** [comment]
@saiteja2464 what they mean is you could build an installer yourself and use pkg to deploy it, that said there might be an example floating around somewhere

**Comment by maxwellllll** [comment]
For Windows, you can check out [Inno Setup](http://www.jrsoftware.org/ishelp/). It has a wizard you can use to get a simple installer out in a few minutes, but it also offers lot of flexibility.
