### ISSUE TITLE
%1 %2 in output

### ISSUE THREAD

**Issue by reitmaster** [vercel/pkg#271]
Running a debug command like `pkg . --debug` shows:

```
> [debug] File %1 added to queue
```

Should the %1 be replaced with a file name?

**Comment by cancerberoSgx** [comment]
I can't reproduce this issue. I just tried npm init -y then adding "bin" in my package.json to point to my index and then pkg . --debug will build my exec just fine... Also execs works ok. Also pkg debug information is shown correctly

**Comment by franck34** [comment]
I'm on windows, using latest version. Same thing %1 %2 ...

Seem's it's normal ?
https://github.com/zeit/pkg-fetch/blob/master/lib/log.js

**Comment by wyattjoh** [comment]
Experiencing the same.

**Comment by Tmarty** [comment]
I created a repository that reproduces this issue: https://github.com/Tmarty/pkg-271
