### ISSUE TITLE
pkg 4.3.0-beta.1  could not fetch node 8.9.0 on armv7 

### ISSUE THREAD

**Issue by serkanp** [vercel/pkg#285]
when install pkg latest, it installes 4.3.0-beta.1
when using on armv7:
pkg -t node8-linux-armv7 app.js
it tries to fetch 8.9.0 but could not find the binary file.. 
it tries to build it from base binary from source.. 
its been more then 10 hours :)) still on make process.. 
when will you update armv7 8.9.0 ? 
or , is it possible to specify the latest compiled binary for 8.x.x
and what is the latest compiled armv7 node 8.x.x version?

**Comment by reejinbouk** [comment]
try to install 4.2.5, there is still no pkg for armv7
sudo npm install -g pkg@4.2.5

**Comment by IannothSlurgh** [comment]
I have a similar problem for node6-armv6. An earlier version of pkg could get node6-armv6 binaries, but the most recent can't. I believe that it is being caused by the pkg-fetch dependency that pkg relies on.

See my original issue:

[https://github.com/zeit/pkg-fetch/issues/31](url)

**Comment by Root-Core** [comment]
I have the same problem with `node6-linux-armv7`, an older version worked some time ago.
I will look into use an old version until this is fixed.

**Comment by KingRial** [comment]
@Root-Core could you share the correct working version with armv7 ?
