### ISSUE TITLE
Possibility to prefetch Node.js binaries

### ISSUE THREAD

**Issue by kernle32dll** [vercel/pkg#292]
Hi,

this is more of a feature request than an issue, but I hope its okay to put here nevertheless.

It would be nice, to have an cmd option to let pkg load the required Node.js binaries. The reason for this is, that I use pkg in a docker build. Right now, pkg loads the binaries on its first call, which leads to my build-server literally fetching the binaries on each build, as the cache of the previous build run is lost trough dockers layer system.

So, ideally there would be an command like e.g. `pk --binaries`, which would allow pkg to **just** load the required binaries. This would allow to cache the loaded binary leveraging dockers layer system.

**Comment by bigbenz8** [comment]
I have a nodejs binary file which could run on android , how to use it when I use pkg to compile my project ?

**Comment by roccomuso** [comment]
Right now you can achieve this result playing with `pkg-fetch` and `pkg`:

```javascript
process.env.PKG_CACHE_PATH = path.join(__dirname, '.pkg-cache-upx') // inject

const {exec} = require('pkg')
const {need} = require('pkg-fetch')
...
```

**Comment by jthegedus** [comment]
similar to https://github.com/zeit/pkg/issues/429

**Comment by MartinJohns** [comment]
@lucbelliveau Great idea! Adopted the approach for Windows using PowerShell:

```powershell
$null | Out-File -Encoding ASCII noop.js; npx pkg@5.7.0 --targets=node14-win-x64 --out=noop.exe noop.js; Remove-Item noop.exe; Remove-Item noop.js
```

**Comment by devthejo** [comment]
here is how I do in Dockerfile
```Dockerfile
RUN pkg-fetch -- -n node18
```
