### ISSUE TITLE
Warning Failed to make bytecode node6-x86

### ISSUE THREAD

**Issue by priyath** [vercel/pkg#294]
I converted my node project into an executable using zeit/pkg for x64 without any issues. However, the x86 conversion fails with the following errors
```
pkg@4.3.0-beta.1
Warning Failed to make bytecode node6-x86 for file /snapshot/myTool_x86/index.js error (spawn /home/user/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86 ENOENT)
Warning Failed to make bytecode node6-x86 for file /snapshot/myTool_x86/node_modules/lodash/lodash.js error (spawn /home/user/.pkg-cache/v2.5/fetched-v6.11.5-linux-x86 ENOENT)
.... this warning is repeated for multiple files
```
The command used for the x64 and x86 builds:

x64: pkg -t node6-linux-x64 --output myTool_x64 index.js
x86: pkg -t node6-linux-x86 --output myTool_x86 index.js

**Comment by simonhochrein** [comment]
You could try deleting the ~/.pkg-cache folder.

**Comment by malixsys** [comment]
same here: 
```
> Warning Failed to make bytecode latest-x64 for file /snapshot/Assets/node_modules/lodash-es/lodash.js
> Warning Failed to make bytecode latest-x64 for file C:\snapshot\Assets\node_modules\lodash-es\lodash.js
```

**Comment by dimitarnestorov** [comment]
This is what caused it for me:
```javascript
const path = require('path')

const { path } = require('yargs').argv
```

**Comment by kauffmanes** [comment]
@dimitarnestorov can you explain what the issue is and why it caused the failure? I also have this issue.

**Comment by dimitarnestorov** [comment]
Looking at it now I see that I'm defining `path` twice. Not sure if that is the actual issue though. I guess I wasn't using ESLint.

**Comment by kauffmanes** [comment]
@dimitarnestorov Mine is failing on something similar and I'm wondering if it's the syntax of just using { path }.

`export { default as add } from './add.js';` is failing in a Lodash package for me.

**Comment by dimitarnestorov** [comment]
I wouldn't use ECMAScript modules with pkg.

**Comment by kwisatz** [comment]
Seeing the same with `pkg 4.3.8` (the last one supporting 32-bit Windows binaries) and trying to use the `openpgp` module:

```bash
~$ npx pkg@4.3.8 .
> pkg@4.3.8
> Warning Failed to make bytecode latest-x64 for file /snapshot/application/node_modules/openpgp/dist/node/openpgp.min.js
> Warning Failed to make bytecode latest-x64 for file C:\snapshot\application\node_modules\openpgp\dist\node\openpgp.min.js
> Warning Failed to make bytecode latest-x86 for file C:\snapshot\application\node_modules\openpgp\dist\node\openpgp.min.js
```
