### ISSUE TITLE
pkg errors with "No available node version satisfies 'node7.x'"

### ISSUE THREAD

**Issue by franklinwesley** [vercel/pkg#296]
I try update to pkg version v4.3.0-beta.x but retur "No available node version satisfies 'node7.10.0'". I try with node6 and node8 and works, but my project require node7. What to do?

**Comment by boughtonp** [comment]
I had same problem - our solution was to stop using pkg.

**Comment by hipstersmoothie** [comment]
This is a super old version of node we will not be supporting
