### ISSUE TITLE
the procedure entry point GetLocaleInfoEx could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by serkanp** [vercel/pkg#312]
hi ,
when compiling for windows x86 , it works in win7+
but on windows xp, i got this error.. 

test code:
var moment=require('moment')
console.log('time is:',moment().toJSON())

compiled with :
pkg -t node8-win-x86 app.js -o test.exe

when i use:
pkg -t node7-win-x86 app.js -o test1.exe
i got:
the procedure entry point QueryThreadCycleTime could not be located in the dynamic library Kernel32.dll

it was working well before with enclosejs

**Comment by DrewMurr2** [comment]
I am having the same issue.

**Comment by Omar1123** [comment]
I have the same issue with GetLocaleInfoEx

**Comment by DonovanBoddy** [comment]
Anyone have any solution to this?

**Comment by andytuch** [comment]
I am having this same issue as well. Any help would be appreciated.

**Comment by kingmatusevich** [comment]
same issue
