### ISSUE TITLE
[Question] How to exclude unnecessary files

### ISSUE THREAD

**Issue by Kikobeats** [vercel/pkg#313]
I'm trying to generate a lightweight bundle, excluding non-production `dependencies` and more not useful files like `README.md`, `.eslint`, etc.

I generated a tooling for doing that called [untracked](https://github.com/Kikobeats/untracked), it will create an array of git ignore pattern matching.

The point is, how I can connect this with `pkg`?

I suppose that you are not exposing something like `.pkgignore` because actually, you don't follow this approach; I think you are trying to follow require AST, is this correct?

and, in this case, are these files being excluded from the output?

**Comment by Kikobeats** [comment]
I think it's still a legit question

**Comment by maxymoo22** [comment]
So do I. I would greatly appreciate the ability to ignore files from being packaged.
