### ISSUE TITLE
Can i package electron app?

### ISSUE THREAD

**Issue by Nisthar** [vercel/pkg#325]
Can i package electron app? Is it possible to decompile the app and get the code?

**Comment by BenGermany** [comment]
Packing electron would be the next great thing - I am hoping for the future, too ;-)

But, by the way, with professional tools, every code can be decompiled, often as relative cryptic code, but hidden things can be unhidden. But - that's more for very professionals than standard users ;-)

**Comment by jingsam** [comment]
Use electron-packager

**Comment by lgoudriaan** [comment]
this is a duplicate of #52

**Comment by yakirzana** [comment]
> Use electron-packager

Not enough. In electron-packager the source files are visible.
