### ISSUE TITLE
Debug packed exe app

### ISSUE THREAD

**Issue by nsknet** [vercel/pkg#328]
Hi all,
Can I attach a debugger to a running application that packed by pkg?
My new company has a packed console app without source code. It's worked fine in last year but it has some small exception in this year.
Seems some exceptions mentioned c:\snapshot\xxx.js. I guess we have a solution to recover their file and debug to it.
Anyone help me to find a debugger, or recover the source code?

Thanks

**Comment by BenGermany** [comment]
Can you post images or text from complete error info?

**Comment by theWebalyst** [comment]
@nsknet I just found this which shows how to use the chrome debugger with a pakaged app. Haven't tried it yet https://github.com/zeit/pkg/issues/93

There's a comment that it works on Linux but not Windows.

Note also it is an old issue so things may have changed!
