### ISSUE TITLE
GitLab CI

### ISSUE THREAD

**Issue by imkarma** [vercel/pkg#332]
Hi everyone some one can help me and give example of `.gitlab-ci.yml`?
And where file will be placed after `pkg` finish work etc.
Thx

**Comment by Clement-TS** [comment]
Hi,
I assume this is out of pkg scope.

**Comment by derdiggn** [comment]
Hi, 

i use gitlab for building, here is my config. 

`image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build

build_windows:
  stage: build
  script:
    - npm install typescript -g
    - npm install pkg -g
    - npm install
    - npm run ci:build:exec:win
  tags:
    - dev
  artifacts:
    paths:
      - /builds/GITLAB_TEAM/GITLAB_PROJECT/bin/mms.exe
    expire_in: 1 week`


in my package.json i use the following command 

`"ci:build:exec:linux": "./node_modules/.bin/tsc && pkg . -t latest-win-x64 --out-path /builds/GITLAB_TEAM/GITLAB_PROJECT/bin",`

**Comment by jokesterfr** [comment]
I would recommend you not using -g for installing nom packages.
Use devDependencies instead :

npm i --save-dev typescript pkg

Then you only need to perform "npm i" in your CI file script.
