### ISSUE TITLE
Cross Compiling (WIN->ARM)

### ISSUE THREAD

**Issue by ByeongYeon** [vercel/pkg#333]
Hello~!

I am trying to automate the building and deploying process from WINDOWS to a ARMv7.

Currently I am developing on Windows, deploying the source code to ARMv7 and compiling there, since CPU cross compilation is not available.

I find the **pkg\lib-es5\index.js** and print __target3_

>pkg test.js -t node8-linux-armv7

{ nodeRange: 'node8',
  platform: 'linux',
  arch: 'armv7',
  output: 'C:\\Users\\bro\\test',
  forceBuild: false,
  fabricator:
   { nodeRange: 'node8',
     **platform: 'win',**
     arch: 'armv7',
     forceBuild: false } }
 
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.3/uploaded-v2.3-node-v8.0.0-win-armv7

Can I compiling this in windows ?

**Comment by ByeongYeon** [comment]
I can cross compiling 'test.js' in linux. but There is some error like 
Error: Cannot find module '/snapshot/workspace/test.js'
when runtime in armv7.

**Comment by Kaesebrot84** [comment]
Same here.
```
pkg ./.tmp/server/app.js -c package.json -t node8-linux-armv7
```
prints
```
> pkg@4.3.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v8.9.0-win-armv7     [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v8.9.0-win-armv7
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v8.9.0-win-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v8.9.0-win-armv7"}
> Building base binary from source:
  built-v8.9.0-win-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'
```

**Comment by DonovanBoddy** [comment]
Same issue, anyone have a solution?

**Comment by uds214125** [comment]
using system architecture x64, x86, etc.

When  I changed : **armv7** to **x64** , it working and creating.

pkg . --target=node8-linux-x64 --debug

But the problem is,  it is just a simple file without any extension.

How to install on linux platform ?
