### ISSUE TITLE
Notice: Packaging compiled binaries to debian packages

### ISSUE THREAD

**Issue by jeppech** [vercel/pkg#347]
**This is just an FYI.** 
If you want to package you binary, as a Debian package, you have to leave out the `dh_strip` build step. Apparently this, strips out debug information, that `pkg` relies on, and renders the binary in an unwanted state.

**Comment by harisvsulaiman** [comment]
@jeppech This is how I solve the problem in my app.
https://github.com/harisvsulaiman/pushy
