### ISSUE TITLE
Ability to use compilers

### ISSUE THREAD

**Issue by darky** [vercel/pkg#349]
For example, **ts-node**
It register **.ts** extensions for properly run in node.js

**Comment by patrickpissurno** [comment]
Have you tried setting up ```gulp``` to automatically transpile your .ts files and then use ```pkg``` with the normal .js files?

**Comment by lucasyvas** [comment]
This would be a nice addition

**Comment by hipstersmoothie** [comment]
pkg requires you to transpile code first, this is outside the scope of pkg
