### ISSUE TITLE
Is there a better way to import env variables?

### ISSUE THREAD

**Issue by orion110217** [vercel/pkg#354]
All I saw is appending it in the command myEnv='sample' ./myapp, will there be a better way for example passing it in the config? 

`{
"pkg": {
"env": ['this', 'that']
}
}
`

**Comment by Clement-TS** [comment]
I did a suggestion there: https://github.com/zeit/pkg/issues/358#issuecomment-367707499

**Comment by jflayhart** [comment]
Personally, I use [webpack's DefinePlugin](https://webpack.js.org/plugins/define-plugin/).
