### ISSUE TITLE
project with mplayer

### ISSUE THREAD

**Issue by Suprincesu** [vercel/pkg#355]
i just used mplayerjs to play sound from nodejs but while i pkg my project i couldnt hear any sound. it acts like the assets folder was missing but i clearly mentioned in my package.json. mplayerjs uses os mplayer. SO is it possible to package this project??

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
