### ISSUE TITLE
Cannot use process.stdout.ANYTHING (like clearLine, cursorTo, write, etc)

### ISSUE THREAD

**Issue by atljoseph** [vercel/pkg#356]
This happens if I use process,stdout.ANYTHING:
Error: TypeError: process.stdout.clearLine is not a function

**Comment by atljoseph** [comment]
This is a no brainer...should ALWAYS be able to use stdout ...

**Comment by Clement-TS** [comment]
`process.stdout.write` is working

**Comment by atljoseph** [comment]
Not here

**Comment by santanuthepro** [comment]
```js
process.stdout.clearLine();
process.stdout.write();
process.stdout.cursorTo();
```

**Comment by Zappo-II** [comment]
Does anybody care to work on this one...???
Does anybody else face this issue...???
It's kind of annoying, since it's working when running with `node myScriptThatDoesIt.js` but not in binary...
At least in my environment, which is archlinux...

**Comment by tripulse** [comment]
'-'

**Comment by atljoseph** [comment]
To be honest, just use golang if you can. Lots of experience behind that. Way better than node.

**Comment by tripulse** [comment]
To replace Node.JS with Go is a *very retarded* idea, it’s rather more better to learn pure C than that. Aleast, builds your experience of **true sytems programming.**

**Comment by atljoseph** [comment]
Showing your true colors calling something retarded. Glad I don’t know you

**Comment by atljoseph** [comment]
More better. Lol

**Comment by tripulse** [comment]
i'ht ya do be doin' dat ashley shi' bu' it do ain' ya' shi'ass survah'y imma balin' ya lmaoo

**Comment by telugu-boy** [comment]
> Showing your true colors calling something retarded. Glad I don’t know you
why would you care about someone's true colors if you don't know them '''''''''''-'''''''''''''
