### ISSUE TITLE
How to bake NODE_ENV=production into executable?

### ISSUE THREAD

**Issue by Deilan** [vercel/pkg#358]
How to bake `NODE_ENV=production` into executable?

There's a `--options` CLI flag used to bake v8 options into executable, but I can't see if it could be used for that or not.

**Comment by Clement-TS** [comment]
You may consider create a *bundle.js* file:

```js
process.env.NODE_ENV = "production"
const app = require('./app.js')
app.run()
```

And run pkg on it.

**Comment by ksmithut** [comment]
When you run the packaged app `./packaged-app` or whatever, just run it with `NODE_ENV=production ./packaged-app`

**Comment by Deilan** [comment]
@Clement-TS @ksmithut Thanks, but neither is relevant to me. I can't hardcode `NODE_ENV` value, nor force a client to pass this arg manually. Just need to start `my-app.exe` with a `NODE_ENV=production` already embedded there at package-time.

**Comment by jjhesk** [comment]
are there any ways to read local env or config file?

**Comment by ksmithut** [comment]
I also use the `dotenv` package which was able to read a .env file that exists next to the binary produced by pkg

**Comment by ksmithut** [comment]
But I guess if you can’t have a client change their environment variable, then forcing them to create an env file probably won’t be better.

**Comment by tomgao365** [comment]
in windows, you can run cmd.exe like this:
```bat
SET NODE_ENV=production && app.exe
```

**Comment by PranayAgarwal** [comment]
I'd say production should be the default mode unless dev or something else is explicitly specified. So something like:

```
if (!process.env.NODE_ENV) {
    process.env.NODE_ENV = "production"
}
```

at application start should work.

**Comment by Deilan** [comment]
@PranayAgarwal Well, ssually it's exactly opposite. See [Express.js](https://github.com/expressjs/express/blob/master/lib/application.js#L71) or [Koa.js](https://github.com/koajs/koa/blob/master/lib/application.js#L45) as an example.

**Comment by shaunwarman** [comment]
I'd love to bake an auth token into the executable. We have some build scripts we've compiled into an executable using `pkg`. It's all internal, but I still don't want an auth token in text. Just want our locked down CI to add that auth token for the code to pull in at compile time.

**Comment by tw0517tw** [comment]
Agree with lock down access tokens at build time.

**Comment by beac0n** [comment]
@Deilan : Why don't you just set `NODE_ENV` to production as default and overwrite it with `NODE_ENV=development` if you are in development?

You control the development environment, so that should be an easy thing to do.
You could do something like this in a global config.ts file:
```typescript
const PRODUCTION = 'production';
export const NODE_ENV = process.env.NODE_ENV || PRODUCTION;
```

**Comment by jamesdixon** [comment]
@beac0n this actually worked great. Nice solution

**Comment by panpansh** [comment]
Thank you for your reply dear @beac0n ! So I was able to solve my headache !
Even if the environment variable is set to "development", it allows the package to be read in "production" mode.
However the code remains present in the package.
If there is a simple method to make everything cleaner, I am interested otherwise it is not a big deal ... Thank you again :)

```js
let working_dir;
if (process.env.NODE_ENV == 'development' && !process.pkg) {
    working_dir = __dirname;
} else {
    working_dir = process.cwd();
}

const fs = require('fs');
const path = require('path');
if (!fs.existsSync(path.join(working_dir, 'db'))) {
    fs.mkdirSync(path.join(working_dir, 'db'));
}
```

**Comment by udgeetPanamax** [comment]
> are there any ways to read local env or config file?

I have the same question.  I have dotenv file in project. I want to change the variables without repack. How can I achieve this? 

Is there any way to use the whole dotenv file outside the package?

**Comment by udgeetPanamax** [comment]
> I also use the `dotenv` package which was able to read a .env file that exists next to the binary produced by pkg

How to use it?

**Comment by Icammarano** [comment]
Same error, packaging outside the project where it was packaged does not take the environment variables defined in the .env file.
`./ap-api
--> process.env.DB_HOSTNAME undefined`

**Comment by Icammarano** [comment]
> Here's an [example](https://github.com/shaunwarman/baked-pkg/blob/master/package.json#L14-L16) of what I am currently doing.
> 
> I just add the token (`cat $TOKEN >> .env` or similar) in at CI and use this CI to `pkg` the tool.

Hello, I downloaded your code, I did the npm install, then I ran the "npm run pack". Once the package is created, copy the contents to a folder external to the project (which you should be able to). 
And when executed "./bake", it still does not take the environment variables defined in the .env, in this case TOKEN, since it returns "undefined". 
But if I run it inside the project folder "baked-pkg-master" it works, and get TOKEN=123. 
I don't understand why there is no way to take the environment variables outside the folder project. 
I appreciate help please!
Thx

**Comment by pustekuchen91** [comment]
> > Here's an [example](https://github.com/shaunwarman/baked-pkg/blob/master/package.json#L14-L16) of what I am currently doing.
> > I just add the token (`cat $TOKEN >> .env` or similar) in at CI and use this CI to `pkg` the tool.
> 
> Hello, I downloaded your code, I did the npm install, then I ran the "npm run pack". Once the package is created, copy the contents to a folder external to the project (which you should be able to). And when executed "./bake", it still does not take the environment variables defined in the .env, in this case TOKEN, since it returns "undefined". But if I run it inside the project folder "baked-pkg-master" it works, and get TOKEN=123. I don't understand why there is no way to take the environment variables outside the folder project. I appreciate help please! Thx
> 
> Edit: I found the solution replacing the path to env file in dotenv config.
> 
> `require('dotenv').config({ path: path.join(__dirname, '.env') });`
> 
> Thx

Dont forget to add `const path = require('node:path');`
