### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by ataft** [vercel/pkg#360]
Is there a way to auto-update the package similar to https://electronjs.org/docs/api/auto-updater?

**Comment by donlucacorleone** [comment]
_Just to subscribe to any replies because I'm interested in auto-updates too._

**Comment by lizhil** [comment]
the same problem

**Comment by yi-ge** [comment]
the same problem

**Comment by hipstersmoothie** [comment]
this is outside the scope of pkg

**Comment by fractaal** [comment]
How might one implement auto-update functionality, though?
