### ISSUE TITLE
ARM64v8 support?

### ISSUE THREAD

**Issue by kerberjg** [vercel/pkg#361]
Targets like RaspberryPi 3 or Scaleway's ARM64 servers make this an enticing request.

Is there any chance of this target being supported in the near future?

**Comment by ryanaltair** [comment]
https://github.com/zeit/pkg/issues/146

**Comment by ryanaltair** [comment]
https://github.com/robertsLando/pkg-binaries try armv8 prebuild, due to https://github.com/zeit/pkg-fetch/issues/35

**Comment by jesec** [comment]
Bump and ping @igorklopov. 

Native support would be better. While third party build can serve as a workaround, it is not the ideal solution.

Nowadays, arm64 is more important than ever. It is unfortunate that this great project supports armv6/v7 but not arm64. Many modern distributions have plans to remove multilib (armv7 compat on arm64), which will make the pkg executable unusable as the package depends on the C standard library of the proper arch/distro. Additionally, some modern processors (Apple M1, upcoming ARM reference designs) no longer support 32-bit compatibility mode. 

Currently, it fails with:

```
> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-linux-arm64  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.4.0-linux-arm64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-arm64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-arm64"}
> Building base binary from source:
  built-v14.4.0-linux-arm64
> Error! Not able to build for 'arm64' here, only for 'x64'
```

**Comment by robertsLando** [comment]
Now it's supported

**Comment by kerberjg** [comment]
Awesome work, thank you 🙌✨
