### ISSUE TITLE
[Error] Unexpected token

### ISSUE THREAD

**Issue by arguiot** [vercel/pkg#372]
Hello 👋.  
I'm trying to build a CLI tool, and it works perfectly when I use it with Node.js on my computer.

But with `pkg`, it's another story. When I'm trying to compile the CLI, I'm getting a weird issue:
```
> Error! Unexpected token (36:74)
  /Users/travis/build/Trowler/Trowler/node_modules/prompts/lib/index.js
```
_This is the Travis build, but I get the same error on my computer_

If you need more information (such as debug output) on the build, you can check the [Travis-Ci build](https://travis-ci.org/Trowler/Trowler/builds/351342083)

**Comment by ngankt2** [comment]
i have same bug!
```
 pkg -t latest-linux-x64 -o ./app.dev ./app.js

> pkg@4.3.0
> Error! Unexpected token 
```
error with:
` markup = renderToString(
                    <Provider store={store}>
                        <RouterContext {...renderProps} />
                    </Provider>
                );`
And fix with: https://stackoverflow.com/questions/44961697/react-express-unexpected-token-in-call-to-rendertostring
but still bug with: {...{},new_key:'new_value'} and fix with Object.assign
.........
