### ISSUE TITLE
error from compiling ts

### ISSUE THREAD

**Issue by jjhesk** [vercel/pkg#373]
this error is throw when 

1) using ts to compile to js

2) using node-9 packing

pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: File '/**/xxx/node_modules/vm2/lib/sandbox.js' was not included into executable at compilation stage. Please recompile adding it as asset or script.

**Comment by victornikitin** [comment]
jjhesk, have you found a solution?
We have the same problem with sandbox in vm2 and package.

**Comment by GustavoKatel** [comment]
I have added the package to the assets list. It's working here.

```json
"pkg": {
    "assets": [
        "node_modules/vm2/**/*"
    ]
}
```
