### ISSUE TITLE
how to use pkg for egg.js

### ISSUE THREAD

**Issue by bigbenz8** [vercel/pkg#382]
I have a project used by egg.js (https://eggjs.org/) . How to use pkg for my project. Waitting for help.... thanks.

**Comment by xinjingfen** [comment]
fixed it.
add "bin": "node_modules/egg-bin/bin/egg-bin.js" into package.json

**Comment by VincentWuShiChao** [comment]
> fixed it out.
> add "bin": "node_modules/egg-bin/bin/egg-bin.js" into package.json

If it is egg-scripts, is it similarly configured from the node_modules path？
