### ISSUE TITLE
PKG inspect

### ISSUE THREAD

**Issue by dobraMorda** [vercel/pkg#384]
Hello!

Anyone knows how to enable inspect in pkg? I tried to use a sample but it not works.

Best regards!
Dobra morda

**Comment by azryelryvel** [comment]
#93 is closed so i write here.
I mostly did what's written in #93 but so far it's not working for me.
I ran a node:12.16.1 container and installed pkg locally in it. In `node_modules/pkg-fetch/patches/node.v12.16.1.cpp.patch` , I removed the node_options.cc block which seems to be the one blocking the use of inspect.
Then i used the local pkg to build the application :
`node node_modules/pkg/lib-es5/bin.js path/to/server.js --debug -b -t host --options inspect`
But I still get `/root/.pkg-cache/v2.6/built-v12.16.1-linux-x64: bad option: --inspect`
