### ISSUE TITLE
Issue when packaging binaries with makepkg

### ISSUE THREAD

**Issue by inverse** [vercel/pkg#389]
When packaging binaries with `makepkg` on arch that goes through a strip step to remove unneeded symbols the output yields binaries that are unable to be executed.

Producing the following error:

`Pkg: Error reading from file.`

Any suggestions?

pkg: 4.3.1
node: 8.10.0

**Comment by brandon-leapyear** [comment]
+1 also related to #347

**Comment by maniolias** [comment]
Old issue but if it can help people, for makepkg just add :
`options=("!strip")`
In PKGBUILD file
