### ISSUE TITLE
How to make a ".exe" for both 32-bits and 64bits?

### ISSUE THREAD

**Issue by ndrantotiana** [vercel/pkg#392]
Hello,
Anyone could help me on how to create a single Windows binary for a Node.js application that will both work on 32-bts System and on x64 one too please?
Thank you in advance.

**Comment by woodlandhunter** [comment]
A 32-bit binary will run on either Windows 32-bit or 64-bit. This is the simplest solution. Specify x86 for the arch: https://github.com/zeit/pkg#targets

**Comment by ndrantotiana** [comment]
Thank you.
The fact is that even if a 32-bit app will run on a x64 platform, it is not optimized to do so :(. Is there any tool available in pkg to create an installer that will bundle both 2 versions of the app (x86 and x64) that will install the right version?

**Comment by woodlandhunter** [comment]
I don't believe that pkg has any tools to create any installer itself. You can create both binaries using pkg and then use an installer creator, like [NSIS](http://nsis.sourceforge.net/Main_Page), to create an installer that can [choose which arch to install at runtime](https://github.com/tonytheodore/nsis/blob/master/Include/x64.nsh).

[Other hacks](https://stackoverflow.com/questions/802192/roll-64-bit-and-32-bit-versions-of-an-app-into-the-same-binary) to achieve a fat binary would likely be outside pkg's intended use.

**Comment by chiragpurohit71085** [comment]
In my  package.json I have kept following configuration and it created build for both 32 and 64 bit Windows machine

"pkg": {
    "assets": [
      "xxx/**/*",
      "xxx/**/*"
    ],
    "scripts": "xxx/**/*.js",
    "targets": [
      "node8",
	  "x86"
    ]
  },
