### ISSUE TITLE
PKG + sequelize-typescript

### ISSUE THREAD

**Issue by Maximvdw** [vercel/pkg#400]
It seems to have problems to include the sequelize-typescript module
due to it using a dynamic require for their "Model" objects.
https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/models/Model.js#L6

I fixed it by adding "node_modules/sequelize-typescript/lib/models/v4/*", is there a cleaner way of detecting this?

**Comment by tiagojlara** [comment]
+1

**Comment by zuohuadong** [comment]
+1

**Comment by olaferlandsen** [comment]
@Maximvdw you was adding it on assets???

**Comment by karimEch** [comment]
I found out. Your workaround works for me.
