### ISSUE TITLE
termux support

### ISSUE THREAD

**Issue by tondy67** [vercel/pkg#405]
There is no precompiled binaries for Termux (https://termux.com/) and it not compile at all :(
Termux itself has a latest nodejs & npm packages.
I'm very satisfied of "pkg" and it even work under Alpine (my desktop) but Termux support is critical for what I have in mind!
Please, please, please ... :)

**Comment by HardlyMirage** [comment]
Can you show me what you tried and what kind of errors you're seeing?

**Comment by HardlyMirage** [comment]
Keep in mind that you'll need to set a linux armv6 target.

**Comment by tondy67** [comment]
https://wiki.termux.com/wiki/Package_Management#Compiling_packages_on_device
