### ISSUE TITLE
fs.copyFile and snapshot filesystem

### ISSUE THREAD

**Issue by jsonmaur** [vercel/pkg#420]
Trying to copy a file from the snapshot filesystem to the real filesystem results in the following error:
`ENOENT: no such file or directory`. Seems to happen in all versions after 4.2.4.

Example code that should work:
```javascript
fs.copyFile(
  path.resolve(__dirname, 'some_file.json'),
  path.resolve(process.cwd(), 'some_new_file.json')
)
```

**Comment by jsonmaur** [comment]
Using [ncp](https://github.com/AvianFlu/ncp) as a temporary workaround since it doesn't rely on the `fs.copyFile` function.

**Comment by AxelTerizaki** [comment]
I can confirm your little trick worked out for me o/

**Comment by sqliang** [comment]
> Trying to copy a file from the snapshot filesystem to the real filesystem results in the following error:
> `ENOENT: no such file or directory`. Seems to happen in all versions after 4.2.4.
> 
> Example code that should work:
> 
> ```js
> fs.copyFile(
>   path.resolve(__dirname, 'some_file.json'),
>   path.resolve(process.cwd(), 'some_new_file.json')
> )
> ```

Maybe pkg does not kidnap function `fs.copyFile`. I meet the same issue, and I resolve it by replace copyFile with readFile & writeFile:

```js
// previously:
function copyFile(sourcePath, targetPath) {
    generatedFilePaths.push(targetPath);
    fs.copyFileSync(sourcePath, targetPath);
}
// now:
function copyFile(sourcePath, targetPath) {
            generatedFilePaths.push(targetPath);
            const sourceData = fs.readFileSync(sourcePath, ENCODING);
            fs.writeFileSync(targetPath, sourceData, ENCODING);
        }

```

**Comment by paulocoghi** [comment]
What can we do when using [**`fs-extra`**](https://github.com/jprichardson/node-fs-extra)?

I get the same error when calling a [**`fs.copy`**](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md), but I would not like to manually rewrite it (to be able to apply those workarounds), since there is a lot of things made on fs-extra.

**Comment by jdziat** [comment]
You need to not use the copy method from the fs-extra package. It must do something with path that pkg intercepts/changes.

**Comment by paulocoghi** [comment]
It seems to be a regression bug, since [it worked fine](https://github.com/zeit/pkg/issues/366) until `4.2.6`.

**Comment by jingsam** [comment]
This issue is still not solved. Any progress on this issue? @igorklopov

**Comment by jingsam** [comment]
Hi, @igorklopov thanks for your great work. However, this issue is indeed a pain in our application and still not fixed for two years. Do you have any plans to get this issue to be solved, or suggest some work rounds. Many thanks and wish you a good day.

**Comment by medikoo** [comment]
We workaround this issue by loading following patch at begin of main module: https://github.com/serverless/serverless/blob/94ff3b22ab13afc60fb4e672520b4db527ee0432/lib/utils/standalone-patch.js

**Comment by ryanaltair** [comment]
> Another option that works is to use:
> 
> ```js
> const fileBuffer = fs.readFileSync(path.resolve(__dirname, 'some_file.json'))
>  
> fs.writeFileSync(self.dynLibraryPath, fileBuffer)
> ```

this work with pkg 4.4.9
with node14

**Comment by medikoo** [comment]
.

**Comment by fbmiranda7** [comment]
bump, cant copy file from snapshot

**Comment by dukei** [comment]
It is really annoying bug. Why is not it getting fixed?

**Comment by jingsam** [comment]
bump

**Comment by paulocoghi** [comment]
.

**Comment by robertsLando** [comment]
Hi everyone, I use pkg like you for my projects and when I find a bug I try to fix it my self, fixing this is not so difficult as it just require to add a patch like the one specified by @medikoo in `prelude/bootstrap.js`. 

Please if you use this project help to keep it maintained by contributing to it.

Thanks

**Comment by robertsLando** [comment]
PR ready to fix this

**Comment by jdziat** [comment]
@robertsLando I like it, i think the only thing is that it may lead people to not understand context when working with this package. If they inadvertently forget to include a file in the snapshot and it loads a file from the filesystem instead it could cause some issues or in a worst case scenario a vulnerability. I think that's why this hasn't been patched/implemented.

**Comment by jdziat** [comment]
@robertsLando Not disagreeing but you may want to make it possible to turn this off via a flag.

**Comment by chaeyan** [comment]
bump
