### ISSUE TITLE
npm install failure using git+ssh://github.com/zeit/pkg.git on node 6.14.1

### ISSUE THREAD

**Issue by tingshao** [vercel/pkg#422]
Hi, pkg is a wonderful tool that we used it in our project. I was trying to use the latest code which has resolved a security issue #409 , so I use the URL dependency in my package.json. However, I found after I switched my node version to 6.14.1 using `nvm use 6`, the installation of pkg failed, and I attached the error below, is node 6 losing support? thanks.
```
npm WARN deprecated simple-bufferstream@1.0.0: no longer maintained
npm WARN enoent ENOENT: no such file or directory, open '/home/tshao/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/tshao/.nvm/versions/node/v6.14.1/bin/node" "/home/tshao/.nvm/versions/node/v6.14.1/bin/npm" "i" "git+ssh://git@github.com/zeit/pkg.git"
npm ERR! node v6.14.1
npm ERR! npm  v3.10.10
npm ERR! path /home/tshao/tmp/node_modules/pkg/lib-es5/bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/tshao/tmp/node_modules/pkg/lib-es5/bin.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/tshao/tmp/node_modules/pkg/lib-es5/bin.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tshao/tmp/npm-debug.log

```

**Comment by onny** [comment]
Encounter this issue too using pkg 4.8.8 and npm 6.14.5, nodejs 14.3.0

**Comment by Reda1000** [comment]
I just used some container with
- arm32v7
- ubuntu:18.04
- npm@6.14.6
- node@v12.18.3
 - pkg of version 4.4.9 
and got an ENOENT error like above as well. As workaround I had to downgrade to 4.4.8 to get it work. Maybe helping others - but I think the original reason for this ticket two years ago might have been another root-cause.

Btw. another container with x64 seems to work with 4.4.9.

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
