### ISSUE TITLE
Writing to files inside Snapshot

### ISSUE THREAD

**Issue by hadiayoub97** [vercel/pkg#435]
The pkg description describes how to access files from the snapshot file system created when running the executable file, but when I try to write to them (using fs.writeFile), I get an error. 

Does the library support writing to snapshot files?
And if not are there any suggested workarounds?

**Comment by onegiga** [comment]
No, you can not write into the snapshot file system as its a readonly fs instead use current directory or any other directory of your choice to write data to it.

**Comment by kailashyogeshwar85** [comment]
How to overcome people using os.tempdir which will return the snapshots tempdir. Many clients use tempdir to store some kind of logs on system and package user files as well.
