### ISSUE TITLE
Possible to compile as modules

### ISSUE THREAD

**Issue by SridharRamasami** [vercel/pkg#436]
Hi,

We have an application that may need patching after release.  The compiled binary from pkg for us is about 80MB.  So, if we have a patch, we have to push 80MB to the client, even thought the modified files may only be a few MBs.

Is is possible to comile into modules or parts, so that only the affected part gets pushed to the client, thus decreasing the time needed for download?

Or is it possible to exclude some directories or files from the compilation process?

Thanks,

**Comment by SridharRamasami** [comment]
I looked at some comments from other users.  

Looks like if I require a file with an absolute path, it wont be included in the executable.  eg:
require(process.cwd() + '/config.js');

So lets there are 20 files I want to keep as is, then I could just do the above for the 20 files and my goal would be acheived?

Someone, with experience please confirm or correct.

Currenly, I am not able to try this, as its not able to finish compiling and gives an error
I am not able to try it myself right now, because its giving me other errors such as:

**Comment by hipstersmoothie** [comment]
pkg is meant for compiling your entire app into a binary. Making it into modules won't work, there is another issue for excluding files #313
