### ISSUE TITLE
Failed to make bytecode error

### ISSUE THREAD

**Issue by SridharRamasami** [vercel/pkg#437]
When Im running the pkg, I get the following warning:

Warning Failed to make bytecode node8-x64 for file /snapshot/captivePortal/node_modules/safefs/es6/lib/safefs.js

However, the executable is created and when I try to run it, it crashes with the error:
Error: ENOENT: no such file or directory, mkdir '/snapshot/captivePortal/logs/'

Whats the problem and how would I correct it?

**Comment by sharathbaddam** [comment]
i have same problem, any inputs ?

**Comment by soptimizer** [comment]
is there any solution?

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
