### ISSUE TITLE
Generated exe is not working , independently 

### ISSUE THREAD

**Issue by deveshsinghal22** [vercel/pkg#440]
I am trying make a exe of protractor project. everything works well if I run the exe in the same folder.
But when I copy and paste this exe somewhere else, then it doesn't work. 

I was going through doc and intro, its saying that no need to install npm packages.
 Am I missing anything. 

its a help request rather than bug.  :)

**Comment by igorklopov** [comment]
Please provide as much information as possible. Output of pkg, output of working app, output of non-working app.

**Comment by deveshsinghal22** [comment]
hello,

output of pkg means the --debug log?
also when I move exe from the folder, then it just popup once and close it.

I am running tests using npm script, is it possible to give npm script rather than entry file name

**Comment by deveshsinghal22** [comment]
Hi @igorklopov ,

when I generate build package , i can see its binding node_modules.
but if I remove the src folder and node_modules it doesnt work. 

my folder structure is as below
app / 
 -----src /
 -----node_modules
 -----package.json
 -----app.js


below is the code for app.js
`exec('npm test')`

and npm test is `protractor src/protractor.config.js`

what can be the best way to generate build using this structure.
