### ISSUE TITLE
`pkg` snapshot prefix creation dependent upon drive `pkg` being called from on Windows

### ISSUE THREAD

**Issue by gsroberts** [vercel/pkg#443]
When using `pkg` to create an executable containing my node project locally on a Windows VM that only has one drive (c:), the prefix for the snapshot file system contains `c:\snapshot\` as expected.  However, when the package is built by our Jenkins build server (Windows), the prefix gets created as `s:\snapshot` instead of the expected `c:\snapshot`.  

I believe this to be due to how `pkg` assembles the prefix and appears to be dependent upon the drive letter that `pkg` is being executed from (perhaps the `process.pwd()` for `pkg`?), at least on a Windows machine.

A suggested potential resolution is to either use `c:\snapshot\` exclusively for the prefix or allow the prefix to be configurable when packaging using `pkg` via a parameter.

**Comment by igorklopov** [comment]
Does it lead to any malfunction?

**Comment by gsroberts** [comment]
When you are using absolute paths in the JS code, using `c:\snapshot`  as the first part of the path is expected to succeed, at least as I understand The documentation, but in the instances I've described the actual absolute path would be `s:\snapshot` and thus using the absolute path of `c:\snapshot\modules\mymodule\`, for example, would fail, causing a null reference exception during import.

**Comment by gtaranas** [comment]
I can confirm that, if your project is under D:\  and you package your app from within this drive, executable won't run on pc without a driver D: 

is there any workaround for this?

**Comment by perrywang** [comment]
I can confirm this. The simplest workaround is always pkg project on C: driver.
