### ISSUE TITLE
How to lock the MD5 is value by use pkg?

### ISSUE THREAD

**Issue by LTGKeithYang** [vercel/pkg#445]
How to lock the MD5 is value by use pkg?When I create two windows is .exe files from one source code.The MD5  is value are different.And the problem is't a time problem.How can i fixed?

**Comment by Hypfer** [comment]
https://github.com/vercel/pkg#bytecode-reproducibility

> Why would you want to do this?
>
>If you need a reproducible build process where your executable hashes (e.g. md5, sha1, sha256, etc.) are the same value between builds. Because compiling bytecode is not deterministic (see here or here) it results in executables with differing hashed values.
