### ISSUE TITLE
Is there any way to encrypt a pkg compiled execute? 

### ISSUE THREAD

**Issue by zhzehong** [vercel/pkg#468]
When I open the executable file with vim, I can see my source code. Is there any way to encrypt it or obfuscate it?

**Comment by jhabdas** [comment]
wut? didn say dat in teh readme :p

**Comment by terapackets** [comment]
I tried it but can't see source code in the output executable.

Note that some symbols may be there. For example,  in my script, I have 
```
readStream.on('data', function(chunk) {  
    console.log(chunk.length)
}).on('end', function() {
    console.log(total);
});
```
The executable contains `readStream` but not the above code snippet

**Comment by sstativa** [comment]
According to this [#190](https://github.com/zeit/pkg/issues/190), you have to remove `license` property from `package.json`.
It did work for me very well in the past, but does not work for latest version 4.3.4, and I have no clue why.
