### ISSUE TITLE
pkg .exe file execute on win10

### ISSUE THREAD

**Issue by dashng** [vercel/pkg#469]
I package the .exe file and try to execute on win10.

The system prevent the file from running, and i click button run anyway, then the system quit right way.

Anyone have any suggestions will be appreciated.

Thanks.

**Comment by DanielRuf** [comment]
Can you check if this is caused by Windows Defender or any other antivirus solution?

**Comment by dashng** [comment]
@DanielRuf caused by sqllite3-promise lib, shows error when loading this lib.

Finally I use docker as work around.
