### ISSUE TITLE
Multiple entry points

### ISSUE THREAD

**Issue by ZLJasonG** [vercel/pkg#481]
If package.json contains and object with multiple elements, only the first gets built, there doesn't appear to be any way to specify which to build.

eg
```
{
    "bin": {
        "entry1": "src/entry1",
        "entry2": "src/entry2"
    }
}
```

Ideally there would be a command line option to specify which entry point to use. As a work around, I tried creating multiple package.json format files with different names and passed the paths to pkg but that seemed to create exe's that used no entry point.

**Comment by Altantur** [comment]
Also it would fantastic to have option to run them parallel.

**Comment by cinderblock** [comment]
I'm finding I'd like to be able to have two entry points. In my use case, they share a substantial amount of code. It would be nice to have them automatically share a 3rd common source file to reduce code duplication. However, I imagine many would like to also have the option to not use a shared source to keep it truly single file. If only this were possible with native modules as well...

**Comment by ZLJasonG** [comment]
Still a desired feature

**Comment by cinderblock** [comment]
`no-stale`

**Comment by cinderblock** [comment]
`never-stale`?
