### ISSUE TITLE
Why? -> Warning Cannot include file %1 into executable.

### ISSUE THREAD

**Issue by axe312ger** [vercel/pkg#487]
```
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/opn/xdg-open
  path-to-executable/xdg-open
```

1. I guess the placeholder %1 should be replaced with the actual string.
2. Why can it not be included? I want to understand the reason behind it. Packaging my application to a single executable and then be forced to supply additional files kind of destroys the single executable claim.

Is there a way to fix this? On pkg or user level?

Thanks a lot :)

Related:
* https://github.com/zeit/pkg/issues/207
* https://github.com/sindresorhus/opn/pull/100

**Comment by robertsLando** [comment]
For this I have create a script in `package.json` to copy each file that cannot be included in the exec in the executable dir (in my case the exec dir is `dist` specified in the option `--out-path dist`): 

```javascript
"scripts": {
    "package": "sudo pkg package.json -t node10-linux-x64 --out-path dist && cp ./node_modules/opn/xdg-open ./dist/xdg-open && cp <add here all others file you need to import>",
  },
```

**Comment by robertsLando** [comment]
@axe312ger I'm not a developer/contributor of this package and I think that is not so easy to include this files in the executable file as anyone has make this feature even if this package is used from many users. Readme.md says that this files must be included within the executable folder so I have just provided a simple script to make things work until developers find an easier way to make this work :smile:

**Comment by pcnate** [comment]
I wonder why this is even an issue when building for Windows. Maybe I don't fully understand the use-case for opn.

I experience this when manually running pkg with `pkg server.js --target node10-win-x64 --output dist/app.exe'. 
My goal was to run it as `await exec([ 'server.js', '--target', 'node10-win-x64', '--output', 'app.exe' ])` but that results in the following

```
[nodemon] starting `node .\bin\build-app.js`
> pkg@4.3.5
(node:17416) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at getPath (D:\github\test\node_modules\dir-glob\index.js:6:41)
    at globs.concat.map.x (D:\github\test\node_modules\dir-glob\index.js:47:59)
    at Array.map (<anonymous>)
    at module.exports.sync (D:\github\test\node_modules\dir-glob\index.js:47:33)
    at globDirs (D:\github\test\node_modules\globby\index.js:58:9)
    at getPattern (D:\github\test\node_modules\globby\index.js:61:64)
    at globTasks.reduce (D:\github\test\node_modules\globby\index.js:107:19)
    at Array.reduce (<anonymous>)
```

Any ideas if this is related or a separate issue? I'll open another issue anyways

**Comment by stuartellis** [comment]
I am seeing the same message when building on macOS Mojave, for macOS and Windows targets. Since this is not an error, and outside of the control of the pkg project, perhaps the best option is to add a note to the documentation.

Would the maintainers accept a docs PR for this?

**Comment by pcnate** [comment]
I would expect so as it is common practice in OSS

**Comment by sowmenappd** [comment]
Has anyone been able to solve this yet? Apart from the solution suggested by @robertsLando, I mean.

**Comment by axe312ger** [comment]
Nope, sadly we just display the path to open to the CLI and linux users have to open the path on their own. All other OS will open browser and direct the user to the page we want them to look at.
