### ISSUE TITLE
work perfect on windows but not on mac

### ISSUE THREAD

**Issue by elmissouri16** [vercel/pkg#489]
**pkg version : 4.3.3
node version : 8.11.2**
this is my package.json 
`{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "bin": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "inquirer": "^6.0.0",
    "instagram-private-api": "^0.6.8",
    "line-read": "^1.0.1",
    "lodash": "^4.17.10",
    "prompt-list": "^3.2.0"
  },
  "pkg": {
    "assets": [
      "list/*.*", "cookies/*.*"
    ]
  }
}`

this my project tree
├───cookies
          ├── username.json
├───list
           ├── list.txt
└───node_modules
 |----app.js
 |----vars.js
 and I'm calling files this way  `path.join(__dirname,'list/list.txt')`
 its work on windows fine when i run pkg app.js or pkg . but on mac dosnt read the files  from cookies folder

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
