### ISSUE TITLE
Error! Unexpected character '@' (1:0)

### ISSUE THREAD

**Issue by bipinacellere** [vercel/pkg#493]
Error! Unexpected character '@' (1:0)
  /var/www/html/myproject/dist/node_modules/compass-mixins/lib/_compass.scss

I am getting an error while running pkg using command
`$ pkg -c package.json --target=node8-linux-x64 server/app.js`

**Comment by zocheyado** [comment]
@bipinacellere Did you ever figure this out? I am getting the same issue on another package.

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
