### ISSUE TITLE
Error at doCallback...

### ISSUE THREAD

**Issue by Araknos** [vercel/pkg#494]
After using pkg main.js to generate my .exe, when I launch it I got this error:
{ Error
    at doCallback (C:\snapshot\pharmony_csv\node_modules\node-firebird\lib\index.js:1234:18)
    at C:\snapshot\pharmony_csv\node_modules\node-firebird\lib\index.js:2929:21
    at C:\snapshot\pharmony_csv\node_modules\node-firebird\lib\messages.js:126:13
    at pkg/prelude/bootstrap.js:253:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
  cause:
   Error
       at doCallback (C:\snapshot\pharmony_csv\node_modules\node-firebird\lib\index.js:1234:18)
       at C:\snapshot\pharmony_csv\node_modules\node-firebird\lib\index.js:2929:21
       at C:\snapshot\pharmony_csv\node_modules\node-firebird\lib\messages.js:126:13
       at pkg/prelude/bootstrap.js:253:12
       at process._tickCallback (internal/process/next_tick.js:61:11),
  isOperational: true }

My code:

```
const path = require('path');
const fs = require('fs');
const Firebird = require('node-firebird');
const Promise = require('bluebird');
Promise.promisifyAll(Firebird);

const options = {
    host: 'localhost',
    port: 3050,
    database: path.resolve(__dirname, './PHA.FDB'),
    user: 'SYSDBA',
    password: 'masterkey',
    lowercase_keys: false,
    role: null,
    pageSize: 4096,
};

const connect = async () => {
    try {
        const db = await Firebird.attachAsync(options);
        
        Promise.promisifyAll(db);
        
        return db;
    } catch (e) {
        console.log(e);
        process.exit(1);
    }
};
```

package.json:
```
{
  "name": "pharmo",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "async": "^2.6.1",
    "bluebird": "^3.5.1",
    "fast-csv": "^2.4.1",
    "node-firebird": "^0.8.6",
    "pkg": "^4.3.1",
    "winston": "^3.0.0"
  }
}

```
Any idea ?

**Comment by igorklopov** [comment]
https://github.com/hgourvest/node-firebird/blob/master/lib/firebird.msg must be included as pkg assert. Otherwise you don't get proper error messages. Feel free to add a dictionary and a test :) https://github.com/zeit/pkg/tree/master/dictionary

**Comment by Araknos** [comment]
Thank's for your answer; How to include it ? I saw on others issues something like that:
```
  "pkg":{
    "scripts":"connection.js"
  }
```
(not working)

**Comment by vinicioslc** [comment]
Some notice ? Im getting the same issue with a project

**Comment by vinicioslc** [comment]
I added these lines 
```
    'use strict';

    module.exports = {
        pkg: {
            scripts: [
                'lib/**/*.js'
            ],
            assets: "lib/**"
        }
    };

```
at file called ``node-firebird.js`` in ``dictionary`` folder of pkg now im getting following error

```
C:\snapshot\experimentos_firebird\node_modules\node-firebird\lib\index.js:1234
        callback(new Error(obj.message));
                 ^
Error: I/O error during "CreateFile (open)" operation for file "C:\SNAPSHOT\EXPERIMENTOS_FIREBIRD\DATA1.FDB", Error while trying to open file
    at doCallback (C:\snapshot\experimentos_firebird\node_modules\node-firebird\lib\index.js:1234:18)
    at C:\snapshot\experimentos_firebird\node_modules\node-firebird\lib\index.js:2929:21
    at C:\snapshot\experimentos_firebird\node_modules\node-firebird\lib\messages.js:151:25
    at search (C:\snapshot\experimentos_firebird\node_modules\node-firebird\lib\messages.js:117:13)
    at C:\snapshot\experimentos_firebird\node_modules\node-firebird\lib\messages.js:54:21
    at zalgoSafe (pkg/prelude/bootstrap.js:256:10)
    at pkg/prelude/bootstrap.js:519:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:603:17)
PS C:\Users\vinic\Desktop\experimentos_firebird>
```

Apparently it is compiling all files from the library now because of the new error I have no idea.
