### ISSUE TITLE
Using pkg with Webpack

### ISSUE THREAD

**Issue by brandon-leapyear** [vercel/pkg#496]
Hi, thanks for this package. It does what it needs to do well, and seems to work for our use-case of bundling an Express server + React staticfiles into an installer to run on a customer's system.

We've run into a couple problems, and figured out some ways to get around them. I just wanted to make an issue here to document what we did and see if there are any upstream solutions that can be made from this experience.

## Webpack/package.json

The main problems stem from our code needing to be compiled by Webpack first, since our code is written in Typescript. As a result, we couldn't take advantage of the features in `package.json`, since we would need to specify a Javascript file as the `bin` entrypoint.

## __dirname

The first, as documented elsewhere in this repo, when setting `target: "node"` in the Webpack configuration, Webpack does [weird things](https://github.com/webpack/webpack/issues/1599) with `__dirname`. Basically, the outputted file is something like
```
(function(__dirname, __filename) {
    ...
    path.join(__dirname, ...)
    ...
}).call(this, '/', '/index.js')
```
Hence, `__dirname` is not overwritten with `/snapshot` when bundled with `pkg`.

### Directories

In our code, we have `app.set('views', path.join(__dirname, 'views'))`. It would be nice if `pkg` can detect this and bundle the entire `views` directory. We currently get around this by just specifying the file directly: `res.render(path.join(__dirname, 'views/index.pug'))`, which isn't a big deal for us, since we only have one template we care about.

### path.join

The biggest problem we had is getting `pkg` to bundle `index.pug`. The documentation says that it detects all uses of `path.join` and adds the relevant file to assets. Webpack mangles the call to `path.join` into
```
var path_1 = __defaultImports(__webpack_require(71));
...
path_1.default.join(__dirname, 'index.pug')
```
which `pkg` fails to automatically detect as `path.join(__dirname, 'index.pug')`.

## path.resolve

Tangentially, as specified in #301, we use `path.resolve` in a couple places, and it would be nice to detect those uses in addition to `path.join`. This wasn't a direct issue, but it's a nice-to-have.

# Conclusion

Overall, this is a great package, and we want to thank you for contributing on `pkg` and giving us a huge boost in our system. We hope that our experience may help out others using your package and even improve the package. If we have any spare time, maybe we'll try to get around working on these fixes upstream. Again, thanks for all of your work!

**Comment by brandon-leapyear** [comment]
Also, more customizing of options would be great. For example,

* Specifying base directory for assets (instead of just dirname of config file)
* Specifying `assets` on the command line

Fore more details, here is the webpack plugin we wrote:

```
class WebpackPkgPlugin {
  constructor() {
    this.targets = ['host']
    this.input = 'INPUT.js'
    this.output = 'OUTPUT'
  }

  apply(compiler) {
    compiler.hooks.afterEmit.tapAsync('WebpackPkgPlugin', async (compilation, callback) => {
      const { outputPath } = compilation.compiler

      const entry = path.resolve(outputPath, this.input)
      const output = path.resolve(outputPath, this.output)

      const cwd = process.cwd()
      const config = path.resolve(cwd, 'pkg_config.json')
      fs.writeFileSync(config, JSON.stringify({
        assets: ['dist/**/*.js', 'dist/**/*.pug']
      }))

      console.log(`Packaging: ${path.relative(cwd, entry)} => ${path.relative(cwd, output)}`)

      try {
        await exec([
          entry,
          '--config', config,
          '--targets', this.targets.join(','),
          '--output', output
        ])
      } catch (e) {
        return callback(e)
      }

      // remove original .js file
      fs.unlinkSync(entry)

      callback()
    })
  }
}
```

**Comment by Coriou** [comment]
Thank you very much for posting your feedback. I'm trying to achieve something, I believe, very similar : bundling an Express app that would serve a static React site.

I'm also stuck on this `path.join` issue. 

Have you found a way around it without rewriting your own cross-platform method to join paths ?

**Comment by brandonchinn178** [comment]
What do you mean by cross platform? path.join should be cross platform

**Comment by Coriou** [comment]
Yeah I know it is and that’s why I’d like to use it. Never mind my question, I’ll keep poking around this and eventually figure it out. Thanks

**Comment by Darkle** [comment]
Just to add my own approach here - what I usually do is set all the [webpack node polyfills](https://webpack.js.org/configuration/node/) to false:

```
  node: {
    console: false,
    global: false,
    process: false,
    Buffer: false,
    __filename: false,
    __dirname: false,
    setImmediate: false
  },

```
And then I use https://github.com/liady/webpack-node-externals to tell webpack not to transpile the node_modules folder.

**Comment by tobiasmuecksch** [comment]
This same problem occurs with the `tsc` compiler. Does anyone have a solution for that?
