### ISSUE TITLE
Don't silently use Node executables of a different version

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [vercel/pkg#498]
I just debugged for hours why on earth my .exe keeps crashing when created with `pkg` but not `nexe` and then I found the very simple reason:

I'm using a feature that was introduced in node v10.6.0 (and am currently using v10.8.0) but `pkg` simply used v10.4.1 - no error, warning, nothing.

**Comment by pdhar-tibco** [comment]
Is it possible to specify a locally build node executable for pkg to use instead of the downloaded one ?

**Comment by theWebalyst** [comment]
> I found the very simple solution

@s-h-a-d-o-w what was the *solution*, it isn't obvious to me. Also, is there a way to find out which version it has packaged? Thanks.

**Comment by s-h-a-d-o-w** [comment]
Apologies, I misspoke. I meant "reason".

You could try passing `--build` to pkg, so that it builds from source. I assume (!) that it would fetch the sources for the node version you are currently using. Note that building may take 1 hour depending on your machine and the last time I did it with nexe (maybe pkg's build pipeline works differently), it made my machine unusable - very aggressive CPU usage.

(Edited my original post)

**Comment by theWebalyst** [comment]
Thanks, and for the tips. I wasn't aware of `nexe `. How do they compare - any notable pros and cons of one or the other?

**Comment by s-h-a-d-o-w** [comment]
You're welcome.
Not really, what I like and dislike about either one is quite balanced.
I'd recommend to try them both and see which works best for you.
