### ISSUE TITLE
Could this be combined with Electron?

### ISSUE THREAD

**Issue by hmbrg** [vercel/pkg#52]
Practically, the only time you want to distribute a commercial app and use some sort of code protection is with desktop apps. So it would make a lot of sense to combine this with Electron. Are there any plans for that?

**Comment by ganeshkbhat** [comment]
Alternatively, you  an specify an option to open the default browser on start of .exe and run the .exe in quiet/silent mode

**Comment by alexluoli** [comment]
It's perfect that pack electron projects for protect js source code!

**Comment by Penagwin** [comment]
Any word on this? Can we use pkg with electron?

**Comment by francois06** [comment]
bump

**Comment by igorklopov** [comment]
Pkg's own issues are of higher priority. Once things like code sign are solved, i will have a look at how electron works internally and how to combine them.

**Comment by rwatts3** [comment]
@ganeshkbhat  how would you specify this option? Could you give an example ?

**Comment by makerGeek** [comment]
isn't electron-builder like pkg for electron apps?
https://github.com/electron-userland/electron-builder

**Comment by taha** [comment]
@makerGeek no, electron-builder just follows the [Electron's guide](https://electron.atom.io/docs/tutorial/application-distribution/) on packing

**Comment by Kazako** [comment]
bump :+1:

**Comment by cameronb23** [comment]
Still looking very much for this. Must have!

**Comment by antonioaltamura** [comment]
so there is no way to bundle an electron app in ONE executable?

**Comment by Penagwin** [comment]
Antonio I think you can (Checkout EXE Packers). A lot of us are concerned about trying to keep IP out of plaintext. Currently you just run a command and have all the source code in from of you.

**Comment by luki06** [comment]
Hi,
So... 2019 is it possible yet if not is there any alternative packaging without source code thanks.

**Comment by d0peCode** [comment]
Any updates?

**Comment by leodelgadodev** [comment]
bump

**Comment by bc238dev** [comment]
I am also interested and looking for any updates on this.

**Comment by aperkaz** [comment]
Any updates on this? :question:

**Comment by aperkaz** [comment]
As an obfuscating alternative, you can try: https://github.com/OsamaAbbas/bytenode
Works pretty well with Electron.

**Comment by Nisthar** [comment]
bump
