### ISSUE TITLE
Access Denied when using PKG on MacOS and Linux

### ISSUE THREAD

**Issue by fisch3r** [vercel/pkg#524]
Hi there,
I installed the latest pkg (4.3.4): 
`npm install pkg -g`
Then I execute pkg:
`pkg ./bin/backend.js --target node6-win-x86 -o ./dist/backend.exe`

Error Message:
`> pkg@4.3.4
> Error! Error: EACCES: permission denied, scandir '/.DocumentRevisions-V100'`

My node version: 7.5.0

I tried the following so far:
- reinstalling pkg
- setting PKG_CACHE_PATH to the current working directory like:
`PKG_CACHE_PATH=/Users/someuser/mypkgcache`

It also occurs on my build server (Linux), only the folder is different: /.cache
Any ideas here?

**Comment by fisch3r** [comment]
It is indeed the same error. I found a module which contains filepaths to "/.js" etc. I fixed the problem locally by checking for leading slashes and removing them. Also added a pull request for the fix.

**Comment by chartinger** [comment]
Can confirm. Had the same error from a third party dependency to a array-from polyfill. Watch the debug output and check the last package.json for things like https://github.com/studio-b12/array-from/blob/24de20f9f765a3ba18400fda43b2e4e1b70a0541/package.json#L28

**Comment by motin** [comment]
@fisch3r Thanks. I can confirm that this bug is no longer apparent when using your version of pkg (`npm install --save-dev fisch3r/pkg#bug/524`).
