### ISSUE TITLE
change location of .pkg-cache

### ISSUE THREAD

**Issue by klymsoftware** [vercel/pkg#537]
how can i tell pkg to look somewhere else for fetched-v8.11.3-win-x64 in the C:\Users\%user%\.pkg-cache\v2.5 directory? Im trying to user pkg on a jenkins job with no internet and no access to user directories.

**Comment by fisch3r** [comment]
Use the environment variable PKG_CACHE_PATH when calling pkg. For Windows:
`set PKG_CACHE_PATH=C:\myPkgCachePath`
or mac/linux:
`PKG_CACHE_PATH=/myPkgPath pkg ...`
