### ISSUE TITLE
Providing ICU data at runtime

### ISSUE THREAD

**Issue by rldcampbell** [vercel/pkg#539]
I would like to be able to [provide full ICU data at node runtime](https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime), but am unsure how to achieve this with pkg. I have tried adding the data as assets and also just bundling with the packaged artifacts, but have not met with any success. I'm trying something along these lines:

`pkg -t node8-win-x64 --options icu-data-dir=/node_modules/full-icu -o build/bin/app.exe index.js`

I'm not clear on exactly how everything is working, I hope it's a simple solution that I am simply missing!

Many thanks for your help

**Comment by eug48** [comment]
I think you might be missing a "." in the icu-data-dir, try:

`pkg -t node8-win-x64 --options icu-data-dir=./node_modules/full-icu -o build/bin/app.exe index.js`

you can also try ensuring that you're using the assets key from package.json:

`pkg -t node8-win-x64 --options icu-data-dir=./node_modules/full-icu -o build/bin/app.exe .`

**Comment by tomjohnburton** [comment]
Also having this issue. Any ideas?

**Comment by tomjohnburton** [comment]
@rldcampbell did you ever get this to work?

**Comment by KevinRohn** [comment]
any news on this? I also tried to export NODE_ICU_DATA=node_modules/full-icu
but it doesn`t work. it always use small-icu :/

**Comment by TBG-FR** [comment]
Same issue here... see #1731 for reference (and links to other similar issues too)

**Comment by TBG-FR** [comment]
Here's a working example/solution to get correctly formatted dates with `pkg` : https://github.com/vercel/pkg/issues/1731#issuecomment-1317191357
