### ISSUE TITLE
Support for additional targets from nodejs.org or additional build documentation?

### ISSUE THREAD

**Issue by ElleshaHackett** [vercel/pkg#541]
Hi,
Is there an easy way (or future support) for other distributions. Node.js does seem to have binaries for that already https://nodejs.org/dist/latest/. Like:

- SunOS-x64
- aix-ppc-64
- linux-arm64
- linux-ppc641e
- linux-s390x

This would benefit the project overall since more platforms and architectures widen the usage scope and so value of the project. It would be great to add one of the listed strings to the target argument but if more customs steps are needed additional documentation would help.

**Comment by KerimG** [comment]
I would like to add support for aix-ppc-64 but I don't have an idea where to start.
