### ISSUE TITLE
Unable to build freebsd-x86, freebsd-x64, linux-armv6, linux-armv7 on Windows 10

### ISSUE THREAD

**Issue by ElleshaHackett** [vercel/pkg#542]
I'm able to compile into a ton of platforms and architectures and am very enthusiastic about the use of pkg. Unfortunately I am not able to build for the following platforms on my Windows 10 machine:

- freebsd-x86
- freebsd-x64
- linux-armv6
- **linux-armv7**

_It seems that freebsd and armv6 are no longer supported in pkg version 2.5 is that correct? If so, are there any instructions how to compile node8 with pkg v2.4 on armv6 and freebsd-(86/64) instead? And what are the pros and cons of doing so._ 

I've searched for the corresponding versions here https://github.com/zeit/pkg-fetch/releases/ and found that the binaries are actually available in 2.4. And that the armv7 version for linux is also available for v2.5 (which I'm currently using). I've tried different prefixes such as `latest-`, `node8-`, `node7-` but nothing seems to work. The node version for my application should be minimal v8 or higher. 

Anyway, here some debug info:
> pkg test.js --targets node8-**linux**-armv7

results in

> pkg@4.3.4
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v8.11.3-win-armv7    [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v8.11.3-win-armv7
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v8.11.3-win-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v8.11.3-win-armv7"}
> Building base binary from source:
  built-v8.11.3-win-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'

Which is strange. It seems that it replaces the `-linux-` part for `-win-`. Which of course doesn't have a binary for `arm` available. Any thoughts on how to fix this?

**Comment by MichaelLeeHobbs** [comment]
The same issue was not able to build BSD. 

> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v8.11.3-freebsd-x64
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v8.11.3-freebsd-x64"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v8.11.3-freebsd-x64"}
> Building base binary from source:
  built-v8.11.3-freebsd-x64
> Error! Not able to build for 'freebsd' here, only for 'win'
> pkg@4.3.4
> Fetching base Node.js binaries to PKG_CACHE_PATH

**Comment by ElleshaHackett** [comment]
@evilrabbit any chance we could do something with this?

**Comment by theone3nu** [comment]
Any update on this please. I am also facing the same issue.

**Comment by tomachinz** [comment]
I'm able to build a win32 image on my mac for my app AminoSee but on linux I get this error. With the same command:

`pkg . --targets win-x86 --output ./dist/AminoSee_win/aminosee-win32.exe`

I think perhaps I'd need to download some stub image but not sure where to start.

Oddly this works on the CLI on my machine, **but not** when I do `npm run win32` which is a script line exactly like above. Perhaps this means I have something in my path that allows me to compile win32 binary on my mac with pkg but that thing is not installed on my linux box. The location of pkg on each machine is:

/usr/local/bin/pkg (mac)
/home/tom/.nvm/versions/node/v12.1.0/bin/pkg (linux)

The mac says this:
```
➜  src_aminosee git:(master) ✗ pkg . --targets win-x86 --output ./dist/AminoSee_win/aminosee-win32.exe
> pkg@4.3.4
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  /Users/tom/Dropbox/Sites/funk.co.nz/aminosee_src/dist/root/pos.node
  path-to-executable/pos.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  /Users/tom/Dropbox/Sites/funk.co.nz/aminosee_src/node_modules/get-cursor-position/build/Release/pos.node
  path-to-executable/pos.node
➜  src_aminosee git:(master) ✗
```

But the linux box says:

```
tom@cheese:~/AminoSee$ pkg . --targets win-x86 --output ./dist/AminoSee_win/aminosee-win32.exe
> pkg@4.4.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.2.0-linux-x86    [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-linux-x86
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-linux-x86"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-linux-x86"}
> Building base binary from source:
  built-v12.2.0-linux-x86
> Error! Not able to build for 'x86' here, only for 'x64'
tom@cheese:~/AminoSee$

```

**Comment by JanMalch** [comment]
I got the same issue. I specified the target as `node12.2-linux-armv7` but then it tries to fetch the Windows binary `fetched-v12.2.0-win-armv7`.

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
