### ISSUE TITLE
Android (Termux) support seems fairly easy

### ISSUE THREAD

**Issue by ElleshaHackett** [vercel/pkg#543]
Android (Termux) support was mentioned https://github.com/zeit/pkg/issues/405, https://github.com/zeit/pkg/issues/288 and https://github.com/zeit/pkg/issues/292#issuecomment-363623299. I noticed that my nodejs script can be installed and works 100% when I use Termux on Android. I can just go use `npm install` and within Termux my script works fine with node v8 and node v10. 

What is needed to get support for this in pkg so I compile a binary that can be used in Termux instead? I read (https://github.com/zeit/pkg/issues/405#issuecomment-384111854) that armv6 is needed for that? And I assume that support was dropped in pkg v2.5, right? It would be great to know the possibilities here.

**Comment by RangerMauve** [comment]
This would be nice to have still. 😁
