### ISSUE TITLE
Error when using bigint even when targeting Node 10.x

### ISSUE THREAD

**Issue by johnmave126** [vercel/pkg#545]
Starting from Node 10.5.0, support of bigint was officially added
https://v8.dev/blog/bigint
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2018-06-20-version-1050-current-targos

However pkg doesn't seem to recognize the syntax even if it is supported by node without any command line switch.

For example, pkg will refuse to pack
```javascript
//index.js
const a_big_int = 0n;
```

My current workaround is to wrap everything related to bigint by `eval`. But since `eval` is evil, it will be much appreciated if it can be supported somehow.

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
