### ISSUE TITLE
Warning Malformed requirement for 'o'

### ISSUE THREAD

**Issue by csbenjamin** [vercel/pkg#548]
I am receiving this warning. Everything works fine in the compiled code, but I want to solve what is causing this warning. Where should I start to search? It do not tell me the line or anything else. What "Malformed requirement" means?

**Comment by csbenjamin** [comment]
I am compiling code processed by webpack

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
