### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by nianik5098** [vercel/pkg#549]
The following error occurs when i try to run the executable built from the command:

> ./node_modules/.bin/pkg package.json --out-path ./out -t node10-linux-x64

Error:

`pkg/prelude/bootstrap.js:1252`
`      return wrapper.apply(this.exports, args);`
`                     ^`

`TypeError: Cannot read property 'on' of undefined`
`    at Object.<anonymous> (/snapshot/contact-app2/main.js:0:0)`
`    at Module._compile (pkg/prelude/bootstrap.js:1252:22)`
`    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)`
`    at Module.load (internal/modules/cjs/loader.js:610:32)`
`    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)`
`    at Function.Module._load (internal/modules/cjs/loader.js:541:3)`
`    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)`
`    at startup (internal/bootstrap/node.js:274:19)`
`    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)`

There were some warnings when the packaging command successfully ran:
> pkg@4.3.4
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules/electron/dist
  path-to-executable/electron/dist
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/sliced/index.js
  path-to-executable/node_modules/sliced/index.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  node_modules/deep-defaults/lib/index.js
  path-to-executable/node_modules/deep-defaults/index.js

Couldn't find any **sliced** or **deep-defaults** folder in **node_modules**. Any guess what's happening here??

**Comment by nkonk** [comment]
@nianik5098 Were you able to get this to work ? running into the same issue

**Comment by HeadlessTech** [comment]
@nkonk sorry bro. it was a long time ago and i don't remember a thing about this. sorry can't help. :(

**Comment by nianik5098** [comment]
@nkonk sorry bro. it was a long time ago and i don't remember a thing about this. sorry can't help. :(

**Comment by bhavints** [comment]
Same issue. Can't find these folders?

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
