### ISSUE TITLE
specify node version

### ISSUE THREAD

**Issue by bsparacino** [vercel/pkg#551]
Is there a way to specify the node version.
Right now when I compile, pkg is fetching v10.4.1-win-x64
I need at minimum v10.5.0, is there anywhere I can update this value?

**Comment by hipstersmoothie** [comment]
PKG only support a subset of node versions. We currently support 10.15.3

**Comment by rs-siemens** [comment]
@Daniel-Olivier "Other than specifying the base version you cannot influence the Node JS version used without hacking the cached binaries."

How can we hack the cached binaries. I have the required binaries in the cache but pkg still pulls an earlier version. I have the binary for 14.21.1 but pkg is pulling 14.20.0.

**Comment by Daniel-Olivier** [comment]
@rs-siemens First download the binary for the version you want to use and put it in a known location, then run the following script after replacing values as-needed
```JavaScript
const fs       = require('fs');
const path     = require('path');
const pkg      = require('pkg');
const pkgFetch = require('pkg-fetch');

// Replace this with the full path to the binary you downloaded
const CACHE_OVERRIDE_BINARY_PATH = '';

// Replace with the path to the folder containing your package.json file
const PACKAGE_PATH = __dirname;

// Replace with the path where the built application binary should be created
const OUTPUT_BINARY_PATH = path.resolve(__dirname, 'bin', 'my-app.exe');

/// Replace anything in here with the build target you need
const target = {
  nodeRange : 'node14',
  platform  : 'win',
  arch      : 'x86',
};
target.string = `${target.nodeRange}-${target.platform}-${target.arch}`;

const buildApp = async () => {
  const nodeBinaryCachePath = await pkgFetch.need(target);
  const nodeBinaryBuiltPath = path.join(
    path.dirname(nodeBinaryCachePath),
    path.basename(nodeBinaryCachePath).replace(/^fetched\-/i, 'built-'),
  );
  const nodeBinaryBackupPath = path.join(
    path.dirname(nodeBinaryCachePath),
    path.basename(nodeBinaryCachePath).replace(/^fetched\-/i, 'backup-'),
  );
  
  await fs.promises.copyFile(nodeBinaryBuiltPath, nodeBinaryBackupPath);
  try {
    await fs.promises.copyFile(CACHE_OVERRIDE_BINARY_PATH, nodeBinaryBuiltPath);
    
    await pkg.exec([
      PACKAGE_PATH,
      ...[ '--target', target.string   ],
      ...[ '--output', OUTPUT_BINARY_PATH ],
      // Add any other command-line arguments here
    ]);
  } finally {
    await fs.promises.copyFile(nodeBinaryBackupPath, nodeBinaryBuiltPath);
  }
};

buildApp()
  .then(() => {
    console.log('Application build process completed');
    process.exit(0);
  })
  .catch((err) => {
    console.log('Application build process failed');
    console.error(err);
    process.exit(1);
  });
```
Keep in mind that this will replace the binary pkg intends to use for that node version and if interrupted it will not put the original pkg binary back into the cache

You can also modify metadata of the Node JS binary you downloaded such as the file version to change the file version of the output application. Attempting to modify the metadata of built applications will corrupt them on certain Node JS versions
