### ISSUE TITLE
Static link libstdc++

### ISSUE THREAD

**Issue by aslafy-z** [vercel/pkg#555]
I'd like to ask `pkg` to statically link `libstdc++` into the binary file. I currently need to add libstdc++ into my alpine container before running my binary file and I would like not having to.
 
```dockerfile
FROM alpine:3.8
RUN apk add --no-cache libstdc++
COPY ./bin /bin
ENTRYPOINT ["/bin"]
```

Any thoughts?
Is this possible?

**Comment by danawoodman** [comment]
I'd love to know this too!

**Comment by nickgrealy** [comment]
I presume this is the reason I'm getting the following error, when trying to run my binary in a `scratch` dockerfile:

**_Script_**
`pkg --debug --targets node10-linux-x64 --output runme index.js`

**_Dockerfile_**
```
FROM scratch
COPY runme /
CMD ["/runme"]
```

_**Error**_
> standard_init_linux.go:211: exec user process caused "no such file or directory"

**Comment by nickgrealy** [comment]
Related: https://spectrum.chat/zeit/pkg/static-linking~3cf4ae80-c6e6-4694-9328-21f4cf35cdd7

**Comment by nickgrealy** [comment]
@igorklopov - first of all, thanks for an awesome tool!

Just reading [your comments here](https://spectrum.chat/zeit/pkg/static-linking~3cf4ae80-c6e6-4694-9328-21f4cf35cdd7?m=MTUzMzg3ODA0NzE2Ng==)...

> Right. Try running args.push('--fully-static') here https://github.com/zeit/pkg-fetch/blob/master/lib/build.js#L72 and then passing -b option to your pkg call.

Is there any chance we can have this added to the `pkg` library (maybe as a CLI option)?

**Comment by hsablonniere** [comment]
Hey wonderful team of pkg :wink: thanks for this awesome tool!

We're also interested in this issue at Clever Cloud for our CLI and we're available to test any alpha/beta if needed.

**Comment by robertsLando** [comment]
cc @jesec ?

**Comment by jesec** [comment]
That would increase the binary size unnecessarily for majority of users, as it is simply improbable for a functional system to NOT have the standard C++ library. Additionally, static linking has certain security implications, and some distributions  (such as EL) simply don’t provide static libraries (`*.a`). 

Instead, make it Alpine only.

**Comment by robertsLando** [comment]
> Instead, make it Alpine only.

Yeah I think they means to add this just for alpine binaries, btw I think that add an apk install command isn't that hard to do... Maybe we could add some docs about this

**Comment by jesec** [comment]
This issue has been resolved. Please let me know if it is still relevant.
