### ISSUE TITLE
How to pass environment variables when compiling?

### ISSUE THREAD

**Issue by udithv** [vercel/pkg#558]
Is there a way to pass environment variables during compilation like

`NODE_ENV=build pkg index..js`

**Comment by saikoux12** [comment]
1、 pkg index.js
2、 NODE_ENV=build ./index

**Comment by robertsLando** [comment]
you can define env vars the same way you define them when you run a nodejs app.

MY_ENV=xxx node index.js
MY_ENV=xxx ./app
