### ISSUE TITLE
Dealing with .node files for embedded databases.?

### ISSUE THREAD

**Issue by udithv** [vercel/pkg#560]

**Comment by sharathbaddam** [comment]
??

**Comment by udithv** [comment]
@sharathbaddam 
I am using level db for one of my projects. After compiling it requires leveldown.node file to be in the root directory of the executable. Is there a way to compile that as well ?

**Comment by sharathbaddam** [comment]
With pkg, you cannot compile native node modules inside executable currently. I use level db in one of the projects and you would need leveldown.node file along with executable.

**Comment by udithv** [comment]
@sharathbaddam I know that's what I am trying to solve.

**Comment by robertsLando** [comment]
> With pkg, you cannot compile native node modules inside executable currently. I use level db in one of the projects and you would need leveldown.node file along with executable.

Now you can
