### ISSUE TITLE
Hide sources from binary

### ISSUE THREAD

**Issue by magres** [vercel/pkg#563]
All the js sources are to be read from binary even with a notepad. Any recommended way to hide them?

**Comment by ciukstar** [comment]
Hi! 
May I ask you how did you "read" them?

**Comment by danielgindi** [comment]
From the README:

> scripts is a glob or list of globs. Files specified as scripts will be compiled using v8::ScriptCompiler and placed into executable without sources. They must conform JS standards of those Node.js versions you target (see Targets), i.e. be already transpiled.

So you have to configure your pkg correctly. Classic RTFM.
