### ISSUE TITLE
pkg generated a huge executable on Linux?

### ISSUE THREAD

**Issue by hyifeng** [vercel/pkg#565]
Hi,

I was trying to build an executable for Linux, by running this command
```
npx pkg  . --out-dir ./build/out -t linux
```
Finally I got a huge huge executable file, about 1GB size! 
And the executable's node-sass doesn't work too, it shows some error about node-sass binding doesn't found for Linux/musl.
But my system is Ubuntu 14.04.

Could you help?

**Comment by hipstersmoothie** [comment]
If you include a lot of code, pkg will create big binaries 🤷
