### ISSUE TITLE
node 10 LTS support?

### ISSUE THREAD

**Issue by j-brown** [vercel/pkg#569]
With node 10.13.0, v10 is now LTS.

Are there any plans up update pkg to support this?

Currently, if I build with node10-*, it uses 10.3.0/10.4.0

**Comment by j-brown** [comment]
@ALangguth I believe you could remove those with the --no-warnings v8 flag.

**Comment by chemzqm** [comment]
I want to use work thread, but current node 10 used by pkg is node 10.4.1, it was added in 10.5.0 😞

**Comment by soumyakantiroychowdhury** [comment]
> That would also remove the nasty `(node:15274) ExperimentalWarning: The http2 module is an experimental API.` warning, as this was removed with 10.10

Exactly.

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
