### ISSUE TITLE
Was the package abandoned by the developer?

### ISSUE THREAD

**Issue by thiagoanselmo** [vercel/pkg#571]
We have not had any updates for some time.

**Comment by igorklopov** [comment]
Pkg is maintained 👌  We use pkg to pack now-cli.

**Comment by j-brown** [comment]
Ty for the confirmation @igorklopov 

Would you be able to comment on LTS support (#575  and #569)?

**Comment by leerob** [comment]
Hello! I'm picking things back up here and helping clean up what's open. We are looking for help from the community to update things 😄 Feel free to comment back here if you'd like to assist.

**Comment by leerob** [comment]
https://github.com/vercel/pkg/issues/1065
