### ISSUE TITLE
LTS Support

### ISSUE THREAD

**Issue by alexgreenland** [vercel/pkg#575]
Great package here, really appreciate the work. However, we're blocked on the Node version and we need a way forward.

We'd like to use the latest Node LTS (`v10.13.0`) in pkg, most importantly because it has new `crypto` methods, released in `10.12`.

If you're too busy to pick this up, I'm happy to pair or go forward creating a release for this, but I need to know how to go about it. I experimentally tried diffing `10.13.0` with `10.4.1` and modifying the patch file, but this got too difficult as Node has refactored a number of files, namely debug tooling becoming inspector.

How do you go about patching Node to work with `pkg`? Is there a set of steps to be followed or a rationale to what you're doing to make it compatible? I hope there's a more robust approach than  applying the 10.4.1 patch case by case in context of 10.13, but if that's the case, let me know.

Thanks!

**Comment by j-brown** [comment]
I'm very interested in this, see #569

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
