### ISSUE TITLE
Is there any way to reduce binary size?

### ISSUE THREAD

**Issue by nombrekeff** [vercel/pkg#578]
Thing is when I add a new script instead of just increasing by that file size it increases quite a bit.
Is this behaviour expected? Or is there a way to reduce the size in some way?

PD: I can provide more information if needed!

**Comment by Daniel-Olivier** [comment]
Please share your package.json file as the "pkg" config there has a large effect on binary size

try running `npm ddp` before running pkg as it tries to ensure that you have not installed the same dependencies multiple times and tries to flatten your node_modules

Which script did you add?

**Comment by nombrekeff** [comment]
Hi, thanks for the reply!
 
> try running npm ddp before running pkg    

**I will try this tonight and will let you know if it helps!**

Here is my package.json file, I have quite a bit of dependencies, but the problem was adding a new file in my src wich increased size exponentially.

```jsonc
{
  "main": "index.js",
  "scripts": {
    "test": "jest",
    "test:w": "jest --watchAll",
    "start": "node scripts/start.js",
    "server": "node www/server.js",
    "rallf-runner": "rallf-runner",

    /* Explained below */
    "pkg": "node scripts/build.js -t all" 
  },
  "dependencies": {
    "adm-zip": "^0.4.11",
    "autobahn": "^18.10.2",
    "body-parser": "^1.18.3",
    "chalk": "^2.4.1",
    "cli-spinner": "^0.2.8",
    "cors": "^2.8.5",
    "express": "^4.16.4",
    "fs-extra": "^7.0.0",
    "inquirer": "^6.2.0",
    "json-rpiecy": "^0.2.0",
    "loggin-js": "^0.2.13",
    "lowdb": "^1.0.0",
    "npm": "^6.4.1",
    "npm-run": "^5.0.1",
    "rallf-js-sdk": "^0.4.11",
    "request": "^2.88.0",
    "selenium-webdriver": "^4.0.0-alpha.1",
    "semver": "^5.5.1",
    "uuid": "^3.3.2",
    "vue-material": "^1.0.0-beta-10.2",
    "vuew": "^1.0.0-security",
    "webdriverio": "^4.14.0",
    "ws": "^6.0.0",
    "yargs": "^12.0.2"
  },
  "devDependencies": {
    "babel-preset-vue": "^2.0.2",
    "husky": "^1.2.0",
    "jest": "^23.6.0",
    "pkg": "^4.3.4"
  },
 "pkg": {
    "scripts": [
      "./bin/trainer.js",
      "./bin/trainer-manager.js",
      "./bin/daemon.js",
      "./bin/spawn.js",
      "./methods/work.js",
      "./methods/health.js",
      "./methods/system-status.js"
    ],
    "assets": [
      "./lib/**/*.js",
      "./bin/trainer.js",
      "./bin/trainer-manager.js",
      "./bin/spawn.js",
      "./bin/daemon.js",
      "./methods/work.js",
      "./methods/health.js",
      "./methods/system-status.js",
      "./config/default_config.json"
    ]
  },
  "bin": "bin/incubator.js"
}
```
> * I just realized I have added my scripts both on **scripts** and **assets**... maybe that is causing an issue

Where `scripts/build.js` does:
```js
    pkg.exec(['package.json', '--target', target, '--output', output + '/' + target]);
```

**Comment by Daniel-Olivier** [comment]
Is there a particular reason your "bin" is different to your main file?

Please avoid including JavaScript files under assets unless you specifically want to avoid including what they require or want to make sure they are not turned into bytecode

The paths you are including are in the wrong format. They are supposed to be glob paths. Glob paths should not start with "."

`package.json`
```json
{
  "main": "index.js",
  "scripts": {
    "test": "jest",
    "test:w": "jest --watchAll",
    "start": "node scripts/start.js",
    "server": "node www/server.js",
    "rallf-runner": "rallf-runner",
    "pkg": "node scripts/build.js -t all" 
  },
  "dependencies": {
    "adm-zip": "^0.4.11",
    "autobahn": "^18.10.2",
    "body-parser": "^1.18.3",
    "chalk": "^2.4.1",
    "cli-spinner": "^0.2.8",
    "cors": "^2.8.5",
    "express": "^4.16.4",
    "fs-extra": "^7.0.0",
    "inquirer": "^6.2.0",
    "json-rpiecy": "^0.2.0",
    "loggin-js": "^0.2.13",
    "lowdb": "^1.0.0",
    "npm": "^6.4.1",
    "npm-run": "^5.0.1",
    "rallf-js-sdk": "^0.4.11",
    "request": "^2.88.0",
    "selenium-webdriver": "^4.0.0-alpha.1",
    "semver": "^5.5.1",
    "uuid": "^3.3.2",
    "vue-material": "^1.0.0-beta-10.2",
    "vuew": "^1.0.0-security",
    "webdriverio": "^4.14.0",
    "ws": "^6.0.0",
    "yargs": "^12.0.2"
  },
  "devDependencies": {
    "babel-preset-vue": "^2.0.2",
    "husky": "^1.2.0",
    "jest": "^23.6.0",
    "pkg": "^4.3.4"
  },
 "pkg": {
    "scripts": [
      "/lib/**/*.js",
      "/bin/**/*.js",
      "/methods/**/*.js"
    ],
    "assets": [
      "/config/default_config.json"
    ]
  },
  "bin": "bin/incubator.js"
}
```

**Comment by Daniel-Olivier** [comment]
Any chance of getting the script file you added to src?

**Comment by nombrekeff** [comment]
> Is there a particular reason your "bin" is different to your main file?

No, its the one `npm init` generates by default and I forgot to change it ^^'.

> Please avoid including JavaScript files under assets

Oh, okay, I added them while trying to get it to compile... then when I got it woking I forgot to remove them.

> The paths you are including are in the wrong format

I see, I will change them!

**Comment by nombrekeff** [comment]
I think this is the file I added:
```
const path = require('path');
const os = require('os');
const fs = require('fs-extra');
const AdmZip = require('adm-zip');

class Files {
  constructor() {

  }

  static validPath(path) {
    let validation = {
      valid: true,
      error: null
    };

    if (typeof path !== 'string') {
      validation.valid = false;
      validation.error = 'Path must be a string';
    }
    else if (!fs.existsSync(path)) {
      validation.valid = false;
      validation.error = `Path ${path} does not exists`;
    }

    return validation;
  }

  static extract(inpath, outpath, { autoremove = false } = {}) {
    let valid = Files.validPath(inpath);
    if (valid.error) throw new Error(valid.error);

    if (!outpath) {
      outpath = inpath.replace('.zip', '');
    }

    const zip = new AdmZip(inpath);
    zip.extractAllTo(outpath);

    if (autoremove) fs.removeSync(zipPath);
  }
}

Files.os = os;
Files.path = path;
Files.fs = fs;

Files.paths = {
  get DATA_DIR() {

  }
};

module.exports = Files;
```

**Comment by nombrekeff** [comment]
Is it posible that `require` are imported more than once? That the feeling it gave me... because of how much it increased... just a thought!

**Comment by nombrekeff** [comment]
I will do some more tests tonight on an empty project _(as this one is quite the big project already)_ and test a bit more, and see if I can find what is causing the issue!

**Comment by MarcMagnin** [comment]
hey! Any update on the matter?

**Comment by nombrekeff** [comment]
Hi there! We ended up setting back from the project in which we used `pkg`, so I didn't spend much more time on this. 

If this still feels like an issue, I could look for the project and try gathering more information.

**Comment by KaoSDlanor** [comment]
@nombrekeff Did you require adm-zip anywhere else?

**Comment by nombrekeff** [comment]
I ended up using another library for this purpose, but I only imported there!

**Comment by liudonghua123** [comment]
I write a none dependence hello world example which only print hello. It almost produce a 40M+ program.

```
D:\test\hello>cat index.js
console.info('hello');

D:\test\hello>dir
 Volume in drive D is Data
 Volume Serial Number is 08F2-7D08

 Directory of D:\test\hello

2020-02-18  11:44    <DIR>          .
2020-02-18  11:44    <DIR>          ..
2020-02-18  11:44                24 index.js
               1 File(s)             24 bytes
               2 Dir(s)  19,053,830,144 bytes free

D:\test\hello>pkg index.js
> pkg@4.4.3
> Targets not specified. Assuming:
  node12-linux-x64, node12-macos-x64, node12-win-x64

D:\test\hello>dir
 Volume in drive D is Data
 Volume Serial Number is 08F2-7D08

 Directory of D:\test\hello

2020-02-18  11:45    <DIR>          .
2020-02-18  11:45    <DIR>          ..
2020-02-18  11:45        43,900,934 index-linux
2020-02-18  11:45        42,098,994 index-macos
2020-02-18  11:45        40,708,943 index-win.exe
2020-02-18  11:44                24 index.js
               4 File(s)    126,708,895 bytes
               2 Dir(s)  18,827,542,528 bytes free

D:\test\hello>
```

The installer of nodejs on Windows is no more than 20M.

```
D:\test\hello>curl -I https://nodejs.org/dist/v12.16.0/node-v12.16.0-x64.msi
HTTP/1.1 200 OK
Date: Tue, 18 Feb 2020 03:32:34 GMT
Content-Type: application/octet-stream
Content-Length: 19673088
Connection: keep-alive
Set-Cookie: __cfduid=da0bb3ef627085c017856a7755e74cd8e1581996754; expires=Thu, 19-Mar-20 03:32:34 GMT; path=/; domain=.nodejs.org; HttpOnly; SameSite=Lax
Last-Modified: Tue, 11 Feb 2020 15:36:41 GMT
ETag: "5e42ca09-12c3000"
Cache-Control: max-age=14400
CF-Cache-Status: HIT
Age: 67
Accept-Ranges: bytes
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 566cef456c60d1cf-HKG


D:\test\hello>
```

Can we reduce, shrink or compress it.

**Comment by DigitalMarc** [comment]
> I ended up using another library for this purpose, but I only imported there!

@nombrekeff may I ask what library you've been using instead?

**Comment by nombrekeff** [comment]
@DigitalMarc 
I can't find it right now, but it was an alternative to pkg. I think it was [nexe](https://github.com/nexe/nexe) but I'm not 100% certain.

**Comment by KaoSDlanor** [comment]
@liudonghua123 the Node JS install .msi file is basically a .zip archive with some additional functionality. You can even open .msi files with most archive programs like 7zip. That is why the installer is smaller than your packaged binary. You are welcome to zip it after packaging to reduce its size. I build many packaged binaries into Debian installers and they shrink there too

@nombrekeff I suspect that your packaged binary grew so much when you added that script due to the dependencies it needs. A simple way to illustrate this is to uninstall the adm-zip dependency and use git to view the changes in your package-lock.json file (package.json only includes your direct dependencies, package-lock.json includes all dependencies - even those that were added by your dependencies). You will probably find that adm-zip has a bunch of code and even more dependencies. In order to include that script file into your binary the pkg module must also include adm-zip package

When building packages I tend to use some other bundling step like WebPack / Browserify which generates a copy of all of the code needed and merges it into a single file in a separate folder (and has many more benefits as well) - If you bundle the code and the output folder grows much larger then you know that pkg is not at fault for increasing the binary size

**Comment by liudonghua123** [comment]
@KaoSDlanor Thanks, I tried to compress it using zip or 7z, it reduced almost 2/3 in size.

**Comment by erossignon** [comment]
see also #885
