### ISSUE TITLE
set options issue

### ISSUE THREAD

**Issue by saikoux12** [vercel/pkg#583]
when i use pkg package.json -t node10-linux-x64 . it is ok.
but when i use pkg package.json -t node10-linux-x64 --options max-old-space-size=8192 . 
when i run my project. it said 

Error: Cannot find module '--max-old-space-size=8192'....

**Comment by saikoux12** [comment]
also , i use cluster to fork process..

**Comment by saikoux12** [comment]
master.js
`
const cluster = require('cluster');
if(cluster.isMaster){
    cluster.fork({name:1});
    cluster.fork({name:2});
    cluster.fork({name:3});
}
`
index.js
`require('./src/master');
`
package.json
`
{
  "name": "test",
  "version": "0.0.1",
  "bin": "index.js",
  "pkg": {
    "script": [
      "src/**/*"
    ]
  }
}
`

**Comment by saikoux12** [comment]
@igorklopov @leo please help....

**Comment by poseidonCore** [comment]
Related to #459
