### ISSUE TITLE
Warning Failed to make bytecode node10-x64 for file /snapshot/app/node_modules/@babel/runtime/helpers/esm/AsyncGenerator.js

### ISSUE THREAD

**Issue by ViableClanMember** [vercel/pkg#586]
hi i have @babel/core in my deps, but i see;

> Warning Failed to make bytecode node10-x64 for file /snapshot/app/node_modules/@babel/runtime/helpers/esm/AsyncGenerator.js
> Warning Failed to make bytecode node10-x64 for file /snapshot/app/node_modules/@babel/runtime/helpers/esm/AwaitValue.js
> Warning Failed to make bytecode node10-x64 for file /snapshot/app/node_modules/@babel/runtime/helpers/esm/applyDecoratedDescriptor.js
> Warning Failed to make bytecode node10-x64 for file /snapshot/app/node_modules/@babel/runtime/helpers/esm/arrayWithHoles.js
> Warning Failed to make bytecode node10-x64 for file /snapshot/app/node_modules/@babel/runtime/helpers/esm/arrayWithoutHoles.js
> Warning Failed to make bytecode node10-x64 for file /snapshot/app/node_modules/@babel/runtime/helpers/esm/assertThisInitialized.js
> Warning Failed to make bytecode node10-x64 for file /snapshot/app/node_modules/@babel/runtime/helpers/esm/asyncGeneratorDelegate.js

any ideas folks/ many thanks

**Comment by grapewheel** [comment]
may the promise error, I got this too

**Comment by hipstersmoothie** [comment]
This issue is pretty old with no reproduction repo. If this issue still persists feel free to open a new issue with a reproduction repo!
