### ISSUE TITLE
uglify the js code and then pack it

### ISSUE THREAD

**Issue by leex90** [vercel/pkg#594]
Hi,

I have tried to pack a single executable file and all works like a charm. but when I open it with notepad++, I can still see the pretty js codes. is it possible to uglify(compress) the js codes and then pack them? which would also reduce the binary file size

Thank you :)

**Comment by Daniel-Olivier** [comment]
Please remove the "ISC" license from your package.json file. pkg does not bother to hide source code that is licensed as public

**Comment by iba-jsykes** [comment]
I do uglification in my build before it ever gets to pkg, and I'm not even that smart.

**Comment by JaLe29** [comment]
@mrleex I am using obfuscator for "uglify" and protect code before package using pkg.

Check this:

https://github.com/javascript-obfuscator/javascript-obfuscator

**Comment by LubomirGeorgiev** [comment]
@JaLe29 

How do you combine it with pkg?
What should I do to obfuscate the binaries generated by pkg?

**Comment by JaLe29** [comment]
@LubomirGeorgiev 

1) Create code - `normal.js` file
2) Obfuscate this code - `normal.js` -> `obfuscated.js`
3) Bundle `obfuscated.js` using pkg.

**Comment by JaLe29** [comment]
Ok, I digged in deep using this obfuscator and it really not working for multiple file project.

There is a problem with the obfuscated required file.

PKG can't package obfuscated require like this. 

Did you found some solution?

**Comment by bisubus** [comment]
Removing `license` and setting `private: true` in package.json doesn't seem to affect anything with latest release. Am I missing something? Where does the rumour about `license` originate from?

**Comment by vincentmorneau** [comment]
Doesn't work for me either. Any update?

**Comment by bisubus** [comment]
It's not stale, bot.

**Comment by robertsLando** [comment]
In order to make it not visible simple set the repository to private in package.json and the code will be compiled to bytecode, no need to use obfuscator

**Comment by jesec** [comment]
`pkg` will try to precompile the code into bytecode, which is arguably more effective than any "JS uglify". 

This is out of scope for `pkg`. You can use https://github.com/vercel/ncc or configure Webpack to do that.
