### ISSUE TITLE
Include .key, .pem, .sh extension file ?

### ISSUE THREAD

**Issue by uds214125** [vercel/pkg#599]
How to add file like extension with .pem or .key or .crt etc. into binary ?

Is it possible to add private/public key content into binary ?

Actually, .pem file start with content with 
 ----------BEGIN PRIVATE KEY-----
and it breaks. 

Error: 

### Parsing error: Invalid left-hand side in prefix operation

{
  "name": "server",
  "version": "0.0.0",
  "private": true,
  "bin": "./output/main.bundle.js",
  "main": "./app.js",
  "engines": {
    "node": ">=6"
  },
  "scripts": {
    "build-prod": "pkg -t latest-linux-x64 -o ./app ./server.js",
    "build": "webpack --config build/webpack.config.js --progress true --display-error-details true"
  },
  "dependencies": {
    "@babel/runtime": "^7.2.0",
    ...
  },
  "devDependencies": {
    "webpack": "^4.20.2",
    ...
  },
  "pkg": {
    "scripts": [
      "node_modules/*",
      "node_modules/sharp/build/Release/sharp.node",
      "output/main.bundle.js"
    ],
    "assets": [
      "views/**/*",
      "public/**/*",
      "private_key.pem"
    ],
    "targets": [
      "node8"
    ]
  }
}

How to avoid checking/parsing content of one file but include it ?

Please somebody help.

**Comment by Daniel-Olivier** [comment]
Please include your package.json file

I have included a basic template below that might solve your problem but it is hard to be sure if I don't know the specifics of your package

package.json
```javascript
{
  "name": "myapp",
  "version": "1.0.0",
  "description": "This is your app description",
  ...
  "pkg": {
    "scripts": [] // JavaScript files you want to package into your app. Will be parsed and checked and all required files will also be parsed and checked
    "assets": [ // Misc files you want to package into your app. Will not be parsed. Certain file extensions will not be allowed (like .node)
      "/my_keys/private_key.pem"
    ]
  },
  "licence": "" // If you leave license as "ISC" as is default then your packaged files might be readable
}
```

If you want to copy the example into your code please take out the "..." and the comments as they are not valid JSON

**Comment by uds214125** [comment]
I have added on more .env file to read environment data. while build is ok, no error.

but it is giving error while execution, my evn file.
.env
--------
PORT=8080
HOST=localhost
CRYPTO_KEY=asdaadsa
JWT_TTL=1d

Error : Uncaught Error Caught: ReferenceError: Invalid left-hand side in assignment
