### ISSUE TITLE
emoji support

### ISSUE THREAD

**Issue by leovafme** [vercel/pkg#600]
Hi. 
Does anyone have any idea how emoji is supported in pkg?

in develop not pkg
![image](https://user-images.githubusercontent.com/17578723/50724891-b81b2f80-10c2-11e9-8501-791bcf379dba.png)

in production on pkg
![image](https://user-images.githubusercontent.com/17578723/50724883-84d8a080-10c2-11e9-8f85-2081017b62eb.png)

**Comment by igorklopov** [comment]
Can you please post a simple code snippet to reproduce?

**Comment by leovafme** [comment]
Of course, just do a pkg with these console log

`console.log('example 🐢');
console.log('example ☁️');
`
