### ISSUE TITLE
Does pkg tailor node_modules content? for example omit devDependencies?

### ISSUE THREAD

**Issue by towertop** [vercel/pkg#601]
I have a project containing many scripts and dependencies just for developing phase. And I hope the executables built by pkg can be as small as possible.

I just wonder if i need to extract  those modules in devDependencies and my scripts to another project.  Does pkg just put the full node_modules folder into the exported executable? I dont know how to decompile the binary file to check this.

**Comment by sharathbaddam** [comment]
Try "pkg ." to build from package.json. It will omit devDependencies and build an executable using just dependencies.

**Comment by rucciva** [comment]
@sharathbaddam , a bit confused here

from the doc:
> - Path to package.json. Pkg will follow bin property of the specified package.json and use it as entry file.
> - Path to directory. Pkg will look for package.json in the specified directory. See above.

does it means now pkg does not only travers the bin property but also entry in dependencies if using package.json?
