### ISSUE TITLE
[Request] Support static TemplateLiteral in require

### ISSUE THREAD

**Issue by Jakst** [vercel/pkg#602]
Many libraries do things like 
```javascript
require(`fileNameWithNoDynamicParts`)
```
with TemplateLiterals. Could pkg support following these types of requires?

**Comment by Jakst** [comment]
Closing this as I do not use pkg any more. Although, I don't believe the underlying issue is fixed yet.

**Comment by robertsLando** [comment]
There is a PR #981

**Comment by Jakst** [comment]
Good to hear!
