### ISSUE TITLE
Unable to cross-compile (OSX->ARM)

### ISSUE THREAD

**Issue by OutsourcedGuru** [vercel/pkg#605]
I'm on macOS Mojave 10.14.2 with node v10.0.0, pkg 4.3.5 in a typical "Hello, World!" `index.js` file, as simple as can be. No `package.json` is present. I've created a `dist` folder under the project folder itself.

My intended target is a Raspberry Pi 3B (armv7).

```
pkg -o dist/testpkg-raspi -t node6-linux-armv7 index.js

> pkg@4.3.5
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v6.11.5-linux-armv7  [====================] 100%
  fetched-v6.11.5-macos-armv7  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v6.11.5-macos-armv7
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v6.11.5-macos-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v6.11.5-macos-armv7"}
> Building base binary from source:
  built-v6.11.5-macos-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'
```

Note that I did not ask for a `macos` version of this. Yet it attempts to download a permutation of `node6-macos-armv7` nonetheless and then seems to fail as a result.

**Comment by esanai** [comment]
You can make the package on your Raspberry Pi but you can't make it on your macOS. Refer to the link https://github.com/zeit/pkg/issues/39#issuecomment-298698020
> To explain a bit: at this time `pkg` can do cross-platform-compilation (build for Windows on Linux), but not cross-CPU-compilation (build for ARM on x64). `pkg` _does_ work for ARM, but needs to be run on ARM hardware (Raspberry Pi, etc.).
> 
> As of [zeit/pkg-fetch@67c4a7b](https://github.com/zeit/pkg-fetch/commit/67c4a7b0823497704351638eb4216fb553006757) `pkg` will now throw an error when attempting to do this.

**Comment by OutsourcedGuru** [comment]
That's a shame. I guess I might request that this information somehow bubble up into the documentation so that others don't spend time trying to do this. Thanks.
