### ISSUE TITLE
executable doesn't run when node_modules folder removed

### ISSUE THREAD

**Issue by joseph-lum** [vercel/pkg#607]
I generated an executable using the command:

`pkg index.js -t node8-win-x64 --output test.exe
`

The test.exe does run like expected (giving same output as if I had done ` node index.js `), but when I moved test.exe out of the folder, or deleted/renamed node_modules folder, it breaks.

text.exe size is around 50-60Mb so I would have expected the node_modules files to be included in the package. Any idea whether it could be due to any dependencies failing or etc.?

**Comment by sharathbaddam** [comment]
error stack ?

**Comment by joseph-lum** [comment]
The thing is that the command runs without errors in the terminal. It shows `> pkg@4.3.5` for a while when running, but once its done it returns.

Not sure whether this is helpful but here are the dependencies on my pkg (v4.3.5) package.json:
`"dependencies": {
    "@babel/parser": "7.1.6",
    "babel-runtime": "6.26.0",
    "chalk": "2.4.1",
    "escodegen": "1.11.0",
    "fs-extra": "7.0.1",
    "globby":  #"8.0.1",
    "into-stream": "4.0.0",
    "minimist": "1.2.0",
    "multistream": "2.1.1",
    "pkg-fetch": "2.5.6",
    "progress": "2.0.1",
    "resolve": "1.6.0",
    "stream-meter": "1.0.4"
  } `
OS: Windows 10

I tried updating globby to 8.0.2 based on #604, and also tried updating to the latest pkg@4.3.6 but the same problem happens.

**Comment by kentarouh** [comment]
I also experience this issue. I just created a new issue on the same topic #795.
