### ISSUE TITLE
does not register as a tty?

### ISSUE THREAD

**Issue by seiyria** [vercel/pkg#628]
I'm trying to read keypresses from my packaged exe with this, but it doesn't seem to work. This is what I'm doing:

```
  require('readline').emitKeypressEvents(process.stdin);

  process.stdin.setRawMode(true);

  process.stdin.on('keypress', (chunk, key) => {
    replkeyhelper(key, noxInstances);
  });
```

But I get an error `process.stdin.setRawMode is not a function`. I looked around and it seems this happens when node isn't in TTY mode. Is it possible to make this work with pkg?

**Comment by guyisra** [comment]
Was this resolved? I have a similar issue @seiyria
