### ISSUE TITLE
PKG not using current sources?

### ISSUE THREAD

**Issue by JoshMcCullough** [vercel/pkg#631]
Running `pkg .` in my project's root dir builds the package fine. Running the binary, however, blows up. While trying to track this down, I edited the content of the file which was causing the failure, which is in node_modules. I re-run `pkg .`, and the same error occurs, at the same exact line, but the line _still looks like it did before my edits_.

Is pkg using old / cached sources? If so, how can I clear this cache so I can build my package with my edited node module and continue debugging?

**Comment by JoshMcCullough** [comment]
This might not be an issue any more but I haven't tested it recently.

**Comment by robertsLando** [comment]
@JoshMcCullough Could you try again and report back the result?

**Comment by jesec** [comment]
Are you using a bundler like `webpack`, or processor like `babel`? 

If you do, you have to run those commands before you run pkg. 

pkg does not have cache, so it is improbable for it to have this kind of issue.
