### ISSUE TITLE
Cannot include a dll into assets.

### ISSUE THREAD

**Issue by navkirat-singh** [vercel/pkg#632]
I am creating an executable which loads my custom DLLat runtime.

In my index.js, I am able to load the my DLL using node-ffi. 
`
var myLib= ffi.Library('./mylib.dll', {
    "foo": ["int", ["pointer"] ]
  });
`

I am compiled the application using "pkg ./index.js". The executable works and needs the DLL in the directory at runtime.

It would be great if I could include the DLL into assets just like images. I tried using the "assets" in "pkg" config in package.json but the executable does not loads the DLL at runtime.
`
"pkg": {
    "assets": ["mylib.dll"]
}
`

The debug logs show the following:
`
  D:\bundlenodeapp\mylib.dll
> [debug] The file was included as DISCLOSED code (with sources)
`

- Is my DLL getting included in the executable?
- If the executable is included, then what path should I use in my application to load that DLL?
- What exactly does it means that the file was included as DISCLOSED code?

**Comment by ldstein** [comment]
I bumped into this recently while packaging some windows executables.

In my case, I had to copy the files from pkg's virtual filesystem to the physical file system. Then the OS could handle the file as normal:

```
const fs = require('fs');
const path = require('path');

function writeToStorage(virtualFilePath)
{    
    const filename        = path.basename(virtualFilePath);
    const realInstallPath = path.join(realInstallDir, filename);

    if (!fs.existsSync(realInstallPath))
    {
        const data = fs.readFileSync(virtualFilePath);        
        fs.writeFileSync(realInstallPath, data);
    }

    return realInstallPath;
}

const realInstallDir = path.join(process.cwd(), 'exes');

if (!fs.existsSync(realInstallDir))
{
    fs.mkdirSync(realInstallDir);
}

const elevate        = writeToStorage(path.join(__dirname, 'bin/elevate-x64.exe'));
const serviceManager = writeToStorage(path.join(__dirname, 'bin/service-manager.exe'));
const service        = writeToStorage(path.join(__dirname, 'bin/service.exe'));

module.exports = {elevate, serviceManager, service};
```
