### ISSUE TITLE
Unable to create armv6 build

### ISSUE THREAD

**Issue by theone3nu** [vercel/pkg#637]
My pkg version is 4.3.7
I am using this command to build armv6 version.
 pkg server.js --targets node10-linux-armv6
It says  Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v10.4.1-linux-armv6"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v10.4.1-linux-armv6"}
> Building base binary from source:
  built-v10.4.1-linux-armv6
> Error! Not able to build for 'armv6' here, only for 'x64'

Please help.

**Comment by Agusnez** [comment]
I also get this error. Same version of pkg running on macOS Mojave 10.14.4

**Comment by Agusnez** [comment]
I believe you have to build that executable from an ARM computer. Cross-compilation doesn't work straight out the box.

**Comment by lefuturiste** [comment]
@Agusnez So, how we can make Cross-compilation working with this lib ?
