### ISSUE TITLE
Failed to run when node module folder contain dot

### ISSUE THREAD

**Issue by ronkorland** [vercel/pkg#640]
I created a sample application with ```threads``` package.

**test.js**
```
const spawn = require('threads').spawn;

const thread = spawn(function(input, done) {
  done({ string : input.string, integer : parseInt(input.string) });
});

thread
  .send({ string : '123' })
  .on('message', function(response) {
    console.log('123 * 2 = ', response.integer * 2);
    thread.kill();
  })
  .on('error', function(error) {
    console.error('Worker errored:', error);
  })
  .on('exit', function() {
    console.log('Worker has been terminated.');
  });
```

How to reproduce
1. ```npm install threads```
2. ```pkg test.js```
3. Run pkg binary file

**ERROR**
```
module.js:547
    throw err;
    ^

Error: Cannot find module '/snapshot/threads-pkg/node_modules/threads/lib/worker.node/slave.js'
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (bootstrap_node.js:227:16)
    at bootstrap_node.js:648:3
Worker has been terminated.
```

**Comment by Daniel-Olivier** [comment]
Try explicitly adding the folder as a script folder in the pkg config of your package.json file

Pkg is clearly including the threads module into your compiled app because you can require it without error and your on exit handler is being called

You will probably find that the threads module is doing a require statement from a variable or something

If you have the following code
```
const module_name = 'threads';
const threads = require(module_name);
```
Then pkg will fail to work out what you are requiring

**Comment by ronkorland** [comment]
I added scripts section to package.json it's solved the issue but created another one 
```
Error: Error: Cannot find module '../config'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
```

**Comment by Daniel-Olivier** [comment]
Please include the contents of your package.json file so I can take a look

**Comment by ronkorland** [comment]
```
  "pkg": {
    "scripts": [
      "node_modules/threads/dist/slave.js",
      "node_modules/threads/lib/workerNode/slave.js"
    ]
  },
```

**Comment by Daniel-Olivier** [comment]
try the much simpler
```
"pkg": {
  "scripts": "node_modules/**/*"
},
```
and see if that works. If it does then once again threads or one of its dependencies is doing unsupported require calls. Including your entire node_modules folder as a script isn't exactly ideal but it can be a workaround if you have dependencies that refuse to play nice

If including the entire folder as a script doesn't wok you could try including it as an asset although that will result in a fairly large binary

**Comment by Daniel-Olivier** [comment]
Also you could just try to run the compiled binary despite the message regarding the config file. It is entirely possible that it is an optional extra that threads uses if it is available and ignores if it is not

**Comment by ronkorland** [comment]
I tried to add ```"node_modules/**/*"``` but I get too many errors.

**Comment by Daniel-Olivier** [comment]
Can you show us some of the errors?

Also please try to run the compiled binary despite the errors

**Comment by ronkorland** [comment]
```
  /Users/rkorland/git/runner-pkg/node_modules/.bin/ncp
> Error! Unexpected character '�' (1:0)
  /Users/rkorland/git/runner-pkg/node_modules/.bin/ngrok
```

What do you mean to run "binary despite the errors"?

**Comment by Daniel-Olivier** [comment]
Oh that is my mistake. Please replace "node_modules/**/*" with "node_modules/**/*.js"

We told it to include non JavaScript files as scripts

**Comment by ronkorland** [comment]
New error

```
  /Users/rkorland/git/runner-pkg/node_modules/is-function/browser-test.js
> Error! TypeError: alias.match is not a function
    at shortFromAlias (/usr/local/lib/node_modules/pkg/lib-es5/walker.js:70:18)
    at Walker._callee5$ (/usr/local/lib/node_modules/pkg/lib-es5/walker.js:891:25)
    at tryCatch (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at <anonymous>
```

**Comment by Daniel-Olivier** [comment]
I'm afraid I can't help you with that one. Hopefully someone else if familiar with it
