### ISSUE TITLE
Warning Failed to make bytecode

### ISSUE THREAD

**Issue by vivekp2018** [vercel/pkg#641]
Hi,
Getting a warning while creating executeable 
Warning Failed to make bytecode node8-x64 for file /snapshot/node_modules/brotli/build/encode.js

**Comment by im-sven** [comment]
Try to run pkg with the `--debug` flag, for more information.

**Comment by vivekp2018** [comment]
Hi sven,

Got this error when run with --debug flag.brotli npm package is using emscripten c++ compiler to compile  c++ code to javascript directly.the encode.js file is generated by emscripten c++ compiler  and this file is minified one.Many well known packages like fontkit is using brotli package internally for compression.this pkg is having more than 2 lakh downloads mainly as dependency of other packages.
Will get same error if try to generate binary for fontkit.

**Comment by alexluoli** [comment]
> Warning Failed to make bytecode node8-x64 for file C:\snapshot\SI-Server\node_modules\brotli\build\encode.js

same

**Comment by benfletcher** [comment]
I'm running into this with Yoga, the Facebook Flexbox cross-environment implementation.

**Comment by Jozsan** [comment]
I have the same error, has anybody got a workaround ? 

``` 
Warning Failed to make bytecode node12-x64 for file C:\snapshot\<projectName>\node_modules\brotli\build\encode.js
```

**Comment by emaxedon** [comment]
I'm getting this issue as well
```
> Warning Failed to make bytecode node12-x64 for file /snapshot/shuttlecontrol-api/node_modules/brotli/build/encode.js
```

**Comment by gigouni** [comment]
Hi @emaxedon @Jozsan  @benfletcher @alexluoli 

How did you fix it? Did you find a workaround?

Thanks

**Comment by Jozsan** [comment]
Personally, I removed the dependencies that used brotli

**Comment by gigouni** [comment]
Thanks @Jozsan for your answer

Won't be possible for me. Need to find another solution..

`brotli`was the only one failing? Did you know (even after) the difference with the other modules justifying all this mess up?

**Comment by flisboac** [comment]
For me, the same is happening with a dependency called [ky](https://www.npmjs.com/package/ky). Not depending on it directly. It seems like it requires either transpilation or [Node's experimental module support](https://nodejs.org/api/esm.html), because it seems to depend on ES2015's module syntax/system.

I bundle a single `index.js` file from TypeScript sources using Parcel (with `parcel build src/index.ts --target node --out-dir dist/main --out-file index.js --experimental-scope-hoisting`).

Targets: 

- node12-linux-x64
- node12-win-x64

It seems like running `pkg` using `package.json`-based settings as e.g. `pkg . --out-dir dist/exe/` causes this error, somehow.

My `pkg` config in `package.json` is as follows:

```json
{
  "pkg": {
    "targets": [
      "node12-linux-x64",
      "node12-win-x64"
    ]
  }
}
```

Here are the last lines of output from the second command (i.e. `pkg . --debug`):

```
  [
  {
    "nodeRange": "node12",
    "platform": "linux",
    "arch": "x64",
    "output": "~/<REDACTED>/docker-registry-clean/dist/exe-linux",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node12",
      "platform": "linux",
      "arch": "x64",
      "forceBuild": false,
      "binaryPath": "~/.pkg-cache/v2.6/fetched-v12.13.1-linux-x64"
    },
    "binaryPath": "~/.pkg-cache/v2.6/fetched-v12.13.1-linux-x64"
  },
  {
    "nodeRange": "node12",
    "platform": "win",
    "arch": "x64",
    "output": "~/<REDACTED>/dist/exe-win.exe",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node12",
      "platform": "linux",
      "arch": "x64",
      "forceBuild": false,
      "binaryPath": "~/.pkg-cache/v2.6/fetched-v12.13.1-linux-x64"
    },
    "binaryPath": "~/.pkg-cache/v2.6/fetched-v12.13.1-win-x64"
  }
]
/snapshot/docker-registry-clean/node_modules/ky/index.js:460
export default createInstance();
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:85:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
/snapshot/docker-registry-clean/node_modules/ky/index.js:460
export default createInstance();
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:85:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
> Warning Failed to make bytecode node12-x64 for file /snapshot/docker-registry-clean/node_modules/ky/index.js
C:\snapshot\docker-registry-clean\node_modules\ky\index.js:460
export default createInstance();
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:85:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
C:\snapshot\docker-registry-clean\node_modules\ky\index.js:460
export default createInstance();
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:85:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
> Warning Failed to make bytecode node12-x64 for file C:\snapshot\docker-registry-clean\node_modules\ky\index.js
```

Surprisingly, if I run `pkg dist/main/index.js --output dist/exe/docker-registry-clean --targets node12-linux-x64,node12-win-x64` instead, this bytecode generation failure does not occur.

**Comment by paulgalow** [comment]
I have run into the same problem:
`> Warning Failed to make bytecode node12-x64 for file /snapshot/<project-name>/node_modules/brotli/build/encode.js`

However, I was able to compile the same project using [nexe](https://github.com/nexe/nexe). Not much of help for solving the issue at hand, I know. But I thought I'd let you know.

**Comment by SLOBYYYY** [comment]
What I'm going to write is very weird. I was able to find the part that was causing this by very ugly reverse engineering:

In `node_modules/brotli/build/encode.js`, go to line 40 and search for `function Cb`. It should be the last one. It ends with the following part: `return g|0`. When I replaced this with a simple assignment & return, it stopped the error happening (e.g.: `const abcd = g|0; return abcd`).

I just hopped on this problem so bear in mind the following:
- AFAIK the `encode.js` is platform dependent so this solution might be completely bad for you (I use debian linux with node `v10.16.0`)
- This might not solve anything, just make the error message disappear
- I know it doesn't make any sense

**Comment by igorklopov** [comment]
Does you application work after `Failed to make bytecode`? Because it is intended as `Warning` - it still lets the application execute well in most cases.

**Comment by gillez** [comment]
> What I'm going to write is very weird. I was able to find the part that was causing this by very ugly reverse engineering:
> 
> In `node_modules/brotli/build/encode.js`, go to line 40 and search for `function Cb`. It should be the last one. It ends with the following part: `return g|0`. When I replaced this with a simple assignment & return, it stopped the error happening (e.g.: `const abcd = g|0; return abcd`).
> 
> I just hopped on this problem so bear in mind the following:
> 
>     * AFAIK the `encode.js` is platform dependent so this solution might be completely bad for you (I use debian linux with node `v10.16.0`)
> 
>     * This might not solve anything, just make the error message disappear
> 
>     * I know it doesn't make any sense

I've no idea how you found that, but I just tried the same thing and the warning has disappeared for me too. No idea why and I agree that it might be just hiding the message rather than solving anything.

In answer to the question from @igorklopov, my application seems to work fine after the warning occurs. Does this mean it's not a problem?

**Comment by benfletcher** [comment]
Does wrapping in parens `return (g|0)` also resolve the problem?

Is there a strategy you can recommend to resolve these issues with other culprit files @SLOBYYYY ? Thanks!

**Comment by SLOBYYYY** [comment]
> Does you application work after Failed to make bytecode? Because it is intended as Warning - it still lets the application execute well in most cases.

You won't like my answer: I don't know. I just jumped deep into this problem when other team members were busy with shipping new features, while trying to solve packaging and integrate this into the CI and also to make it deployable.

I found this "solution" but I didn't do a follow-up whether or not it actually made any difference.

> Is there a strategy you can recommend to resolve these issues with other culprit files @SLOBYYYY ? Thanks!

If you read my previous paragraph, this heavily depends on whether or not it matters at all. If it does, an ugly-but-working method would be `sed`-ing this part in your CI script. Calling this a "strategy" would be an overstatement though :)

In any case, I'm very interested finding the "why" of this problem too.

**Comment by artemcarabash** [comment]
Faced the same issue after upgrading pkg to version 4.4.9. 
Downgrated to 4.3.7 back and issue dissapeared. The only problem is that the 4.3.7 does not supports node12 but for me it doesnt matter.

**Comment by pompep** [comment]
In my case direct dependency caused this issue so I was able to fix it with following steps:
1. skip pkg auto include for this module - just use non-literal argument in requiring (e.g.  require("pg-query-emscripten" + "/pg_query"))
2. list this file in pkg assets, so it will be no more compiled

(pkg v. 4.4.9.)

**Comment by azerpas** [comment]
For those using Typescript, try setting
```json
    "target": "ES2020",                               
    "module": "commonjs",
```
 inside your `tsconfig.json`

**Comment by StiliyanKushev** [comment]
I can confirm the issue still remains. Without an immediate fix, the tool is unfortunately useless. I am facing the exact same issue as @appurist does.

**Comment by martnjf** [comment]
@appurist I can't delete the imports because I need all of them, have you find the way to make it work?

**Comment by appurist** [comment]
@martnjf I just switched back to require and CommonJS modules for now on that project. But I'm also effectively avoiding Pkg now because I want to be using ES modules everywhere. Even in the browser.

**Comment by martnjf** [comment]
@appurist thanks for the reply, what other things have you used instead of Pkg?

**Comment by ve3** [comment]
This seems to be not working with new JS export/import file.

**Comment by fhirfly** [comment]
confirmed problem with an es6 module setup

**Comment by JohannesBeiser** [comment]
Still no fix? In my case its axios that internally uses export/import syntax. Request to reopen this issue

**Comment by Hareis** [comment]
> 仍然没有修复？在我的例子中，它在内部使用导出/导入语法的公理。请求重新打开此问题。恢复到2年的旧版本axios@0.21.1修复了这个问题

good job

**Comment by TerryJoo** [comment]
Who can help me? This is my failed case when build with prisma client.
```
> [debug] prebuild-install failed[C:\Users\NvirLabs_2022-0923\Projects\nestjs-template\node_modules\.prisma\client\query_engine-windows.dll.node]:
  spawnSync C:\Users\NvirLabs_2022-0923\Projects\nestjs-template\node_modules\pkg\node_modules\.bin\prebuild-install ENOENT
/snapshot/nestjs-template/node_modules/.prisma/client/runtime/edge-esm.js:98
`)}return await y,this._fetcher.request({document:B,clientMethod:o,typeName:T,dataPath:s,rejectOnNotFound:O,isList:S,rootField:h,callsite:a,args:n,engineHook:this._middlewares.engine.get(0),headers:f,transaction:g,unpacker:b,otelParentCtx:x,otelChildCtx:bt.active()})}get $metrics(){if(!this._hasPreviewFlag("metrics"))throw new we("`metrics` preview feature must be enabled in order to access metrics API");return this._metrics}_hasPreviewFlag(n){var o;return!!((o=this._engineConfig.previewFeatures)!=null&&o.includes(n))}}return u(t,"PrismaClient"),t}u(Fg,"getPrismaClient");var Dg=["$connect","$disconnect","$on","$transaction","$use","$extends"];function is(e,t){return typeof e!="object"?e:new Proxy(e,{get:(r,n)=>{if(!Dg.includes(n))return n===Rg?t==null?void 0:t.id:typeof r[n]=="function"?(...o)=>n==="then"?r[n](o[0],o[1],t):n==="catch"||n==="finally"?r[n](o[0],t):is(r[n](...o),t):is(r[n],t)}})}u(is,"transactionProxy");var Ng={findUnique:"findUniqueOrThrow",findFirst:"findFirstOrThrow"};function kg(e,t,r){if(e){let n=Ng[r],o=t?`prisma.${t}.${n}`:`prisma.${n}`,i=`rejectOnNotFound.${t!=null?t:""}.${r}`;ki(i,`\`rejectOnNotFound\` option is deprecated and will be removed in Prisma 5. Please use \`${o}\` method instead`)}}u(kg,"warnAboutRejectOnNotFound");d();p();m();var jg=new Set(["toJSON","asymmetricMatch",Symbol.iterator,Symbol.toStringTag,Symbol.isConcatSpreadable,Symbol.toPrimitive]);function $g(e){return new Proxy(e,{get(t,r){if(r in t)return t[r];if(!jg.has(r))throw new TypeError(`Invalid enum value: ${String(r)}`)}})}u($g,"makeStrictEnum");d();p();m();d();p();m();var TD=fl.decompressFromBase64;var export_findSync=void 0;var export_warnEnvConflicts=void 0;export{pt as DMMF,ft as DMMFClass,Ka as Debug,Ge as Decimal,_t as Engine,Fs as Extensions,$t as MetricsClient,et as NotFoundError,_e as PrismaClientInitializationError,je as PrismaClientKnownRequestError,Qe as PrismaClientRustPanicError,Ce as PrismaClientUnknownRequestError,we as PrismaClientValidationError,pe as Sql,tf as Types,TD as decompressFromBase64,dd as empty,export_findSync as findSync,Fg as getPrismaClient,md as join,Qi as makeDocument,$g as makeStrictEnum,Ko as objectEnumValues,tc as raw,rc as sqltag,Ic as transformDocument,Yi as unpack,export_warnEnvConflicts as warnEnvConflicts};
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         


SyntaxError: Unexpected token 'export'
    at new Script (node:vm:102:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.5.0
/snapshot/nestjs-template/node_modules/.prisma/client/runtime/edge-esm.js:98
`)}return await y,this._fetcher.request({document:B,clientMethod:o,typeName:T,dataPath:s,rejectOnNotFound:O,isList:S,rootField:h,callsite:a,args:n,engineHook:this._middlewares.engine.get(0),headers:f,transaction:g,unpacker:b,otelParentCtx:x,otelChildCtx:bt.active()})}get $metrics(){if(!this._hasPreviewFlag("metrics"))throw new we("`metrics` preview feature must be enabled in order to access metrics API");return this._metrics}_hasPreviewFlag(n){var o;return!!((o=this._engineConfig.previewFeatures)!=null&&o.includes(n))}}return u(t,"PrismaClient"),t}u(Fg,"getPrismaClient");var Dg=["$connect","$disconnect","$on","$transaction","$use","$extends"];function is(e,t){return typeof e!="object"?e:new Proxy(e,{get:(r,n)=>{if(!Dg.includes(n))return n===Rg?t==null?void 0:t.id:typeof r[n]=="function"?(...o)=>n==="then"?r[n](o[0],o[1],t):n==="catch"||n==="finally"?r[n](o[0],t):is(r[n](...o),t):is(r[n],t)}})}u(is,"transactionProxy");var Ng={findUnique:"findUniqueOrThrow",findFirst:"findFirstOrThrow"};function kg(e,t,r){if(e){let n=Ng[r],o=t?`prisma.${t}.${n}`:`prisma.${n}`,i=`rejectOnNotFound.${t!=null?t:""}.${r}`;ki(i,`\`rejectOnNotFound\` option is deprecated and will be removed in Prisma 5. Please use \`${o}\` method instead`)}}u(kg,"warnAboutRejectOnNotFound");d();p();m();var jg=new Set(["toJSON","asymmetricMatch",Symbol.iterator,Symbol.toStringTag,Symbol.isConcatSpreadable,Symbol.toPrimitive]);function $g(e){return new Proxy(e,{get(t,r){if(r in t)return t[r];if(!jg.has(r))throw new TypeError(`Invalid enum value: ${String(r)}`)}})}u($g,"makeStrictEnum");d();p();m();d();p();m();var TD=fl.decompressFromBase64;var export_findSync=void 0;var export_warnEnvConflicts=void 0;export{pt as DMMF,ft as DMMFClass,Ka as Debug,Ge as Decimal,_t as Engine,Fs as Extensions,$t as MetricsClient,et as NotFoundError,_e as PrismaClientInitializationError,je as PrismaClientKnownRequestError,Qe as PrismaClientRustPanicError,Ce as PrismaClientUnknownRequestError,we as PrismaClientValidationError,pe as Sql,tf as Types,TD as decompressFromBase64,dd as empty,export_findSync as findSync,Fg as getPrismaClient,md as join,Qi as makeDocument,$g as makeStrictEnum,Ko as objectEnumValues,tc as raw,rc as sqltag,Ic as transformDocument,Yi as unpack,export_warnEnvConflicts as warnEnvConflicts};
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         


SyntaxError: Unexpected token 'export'
    at new Script (node:vm:102:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by robertsLando** [comment]
export is only valid with esm

**Comment by hitech95** [comment]
I'm facing similar issues with Axios and yup.
We updated an old codebase to newer dependencies and now pkg dosnt want to work.

And I have no idea where to start.

**Comment by robertsLando** [comment]
You need to convert your esm code to cjs and then package it

**Comment by robertsLando** [comment]
Try using ncc but you need an old version

**Comment by hitech95** [comment]
We use glob array to import some stuff, how does ncc handle this?

**Comment by robertsLando** [comment]
I sincerly have no clue as I never used it my own and that's a really specific use case, you should give that a try but there should be a fix to that too someway

**Comment by or185014** [comment]
I had the same issue as a few others with using latest axios version >= 1.x . I solved it by using [ncc](https://github.com/vercel/ncc) (It doesn't look like you need to use an older version I am using 0.36.0 just fine). Here is what my build and pkg scripts look like in my package.json
```
...
  "main": "dist-temp/index.js",
  "bin": "dist-temp/index.js",
  "scripts": {
    "build": "tsc && ncc build -o dist",
    "pkg": "pkg ./pkg.config.json -o dist/my.exe",
    ...
  }
...
```
The pkg.config.json used above is essentially a package.json with just the configuration values for the pkg tool needs.
```
{
   "main": "dist/index.js",
   "bin": "dist/index.js",
   "pkg": {
      "targets": [
        "node16-win-x64"
      ],
      "assets": [
        "src/images/*"
      ]
    }
}
```
I also modified my tsconfig.json to output to a temp folder to separate the transpiled files from the single file ncc produces
```
...
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "strict": true,
    "outDir": "dist-temp",
    "esModuleInterop": true,
  },
...
```

**Comment by rsgilbert** [comment]
Thanks everyone, I used @vercel/ncc . My build script is like this:
```
"scripts": {
    "test": "jest",
    "start": "node src/index.js",
    "dev": "nodemon src/index.js",
    "build": "ncc build  -o build/lib ./src/index.js && pkg --target node16-win-x64 -o build/NDAMIS-API.exe ./build/lib/index.js"
  },
```

**Comment by crhistianramirez** [comment]
@rsgilbert  small correction `--target` should be `--targets`

**Comment by appurist** [comment]
FYI, based on the very helpful comments above, I was finally able to combine this to produce a pkg deliverable based on ESM code earlier today. I used:
`esbuild ./main.mjs --bundle --platform=node --outfile=dist/main.cjs --define:import.meta.url=__dirname`
followed by:
`pkg -t node18-win dist\main.cjs`
and that produced a `main.exe` file in the current directory.

I had one top-level `await` that I then needed to replace with a Promise+then, but that was easy enough.

**Comment by calebeaires** [comment]
The solution @rsgilbert bring to us helped me, but my pkg failover in another problem. Lua files used by an lib called bull

**Comment by ThePicYazan** [comment]
Warning Failed to make bytecode node18-x64 for file C:\snapshot\Best Store\node_modules\discord.js-selfbot-v13\node_modules\axios\lib\axios.js
> Warning Failed to make bytecode node18-x64 for file C:\snapshot\Best Store\node_modules\discord.js-selfbot-v13\node_modules\axios\lib\utils.js
> Warning Failed to make bytecode node18-x64 for file C:\snapshot\Best Store\node_modules\discord.js-selfbot-v13\node_modules\axios\lib\helpers\bind.js

**Comment by shirser121** [comment]
> Warning Failed to make bytecode node18-x64 for file C:\snapshot\Best Store\node_modules\discord.js-selfbot-v13\node_modules\axios\lib\axios.js
> 
> > Warning Failed to make bytecode node18-x64 for file C:\snapshot\Best Store\node_modules\discord.js-selfbot-v13\node_modules\axios\lib\utils.js
> > Warning Failed to make bytecode node18-x64 for file C:\snapshot\Best Store\node_modules\discord.js-selfbot-v13\node_modules\axios\lib\helpers\bind.js

Same here

**Comment by rsgilbert** [comment]
@shirser121 hi, make sure your package.json is specifying the project as commonjs. If you're using es modules, then you need to first convert the code into commonjs using babel. 

Something like:
`
"scripts" { 
    ...,
    "build": "babel src -d build/babel/lib && ncc build -o build/ncc/lib build/babel/lib/index.js && pkg --compress GZip --target node16-win-x64 -o build/CORPS-API.exe ./build/ncc/lib/index.js"
}
`
I can share more if we are on the same page.

**Comment by shirser121** [comment]
> @shirser121 hi, make sure your package.json is specifying the project as commonjs. If you're using es modules, then you need to first convert the code into commonjs using babel.
> 
> Something like: `"scripts": { ..., "build": "babel src -d build/babel/lib && ncc build -o build/ncc/lib build/babel/lib/index.js && pkg --compress GZip --target node16-win-x64 -o build/CORPS-API.exe ./build/ncc/lib/index.js" }` I can share more if we are on the same page.

I not using typescrip.
I success to do it with ncc.
not i get this error:
``` 
Warning Cannot resolve 'filePath'
  C:\Users\shir ser\Desktop\Cyber\DEV\Node.js\Battabo Data Extractor\build\lib\index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```
