### ISSUE TITLE
provide option to install/pack specific version of nodejs

### ISSUE THREAD

**Issue by kumarrishav** [vercel/pkg#643]
Currently we can give only the major version name like node8. So, instead of downloading the latest or specified version, it installs 8.11.3 which i think comes from https://github.com/zeit/pkg-fetch/releases. 
pkg-fetch doesn't has latest binary and lastly it was updated in 2017. After that, there were bunch of security fixes in these versions. 

Why don't we switch to public nodejs download source?

**Comment by DaneTheory** [comment]
I've been curious about this as well. Many issues posted reference the need/want to DL a specific version of Node. What's the reasoning for Node builds called via `pkg-fetch`?

**Comment by mvillaizan** [comment]
Certain dependencies require Node 8.13+ for example but pkg-fetch pulls 8.11, It would be nice to get to chose a specific version.
