### ISSUE TITLE
error packing with json-ometajs dependency

### ISSUE THREAD

**Issue by jimudall** [vercel/pkg#645]
I'm using pkg@4.3.7 and trying to package my app - which of course has a bunch of node modules.  One of these is json-ometajs.  In that package there is a file: index.ometajs.

When I try to create my package, pkg complains with the following error:
Unexpected token, expected ";" (3:6)
  ./node_modules/jsonic-ometajs/index.ometajs

I'm quite stumped and have no idea how to get past this problem.  I'd appreciate any suggestions

Jim

**Comment by aufabdulnafea** [comment]
I am facing the same problem, have you found any solution?
