### ISSUE TITLE
Views folder not added to pkg

### ISSUE THREAD

**Issue by som0027** [vercel/pkg#646]
I have a problem in my node project when i make executable with pkg my Views folder not added to them.I got error when i run executable (Failed to lookup View in Views directory).
I discussed with Npm support and these people raise hands and suggest me to put my problem here.please help me.If you want to any further information about my real project please feel free to ask me 
![Screenshot from 2019-03-14 11-08-16](https://user-images.githubusercontent.com/48580842/55052651-b9377980-507f-11e9-80a4-76f59e904af3.png)

**Comment by informvisu** [comment]
MyNode
./logs
./node_modules
./public - contains css, images, js folders
./src - contains .js files
./views - contains .ejs files
./env.properties
./favicon.ico
./package.json
./server.js

package.json
{
  ...,
  "main": "server.js",
  "bin": "server.js",
  ...,
  "pkg": {
    "assets": ["views/**/*", "public/**/*"]
  }
}

C:\Users\vis\Documents\MyNode>pkg -t node8-win package.json
> pkg@4.3.8

C:\Users\vis\Documents\MyNode>

Copied mynode.exe,env.properties to C:\Users\vis\Desktop\node-exe-test

C:\Users\vis\Desktop\node-exe-test>mynode.exe
2019-05-04T12:50:31.146Z info [server.js      ]: application is running at: https://L010230:443
Error: Failed to lookup view "home" in views directory "C:\Users\vis\Desktop\node-exe-test\views"

**Comment by mehdi-sh-hm** [comment]
Same issue

**Comment by Benbinbin** [comment]
Maybe the `__dirname` cannot parse correctly.

I use express-generator set up a node app, and use [multer](https://github.com/expressjs/multer) middleware to handle the file (images) upload. After `pkg` pack the code, it cannot access the static folder, refer to @jesec [answer](https://github.com/vercel/pkg/issues/1187#issuecomment-846840942). 

I replace the static folder path from `app.use(express.static(path.join(__dirname, 'public')));` to `app.use(express.static(path.join(process.cwd(), 'public')));` and it work.

**Comment by anmolthedeveloper** [comment]
Above mentioned solutions are not working
