### ISSUE TITLE
Process env gives error while running exe

### ISSUE THREAD

**Issue by psaxena** [vercel/pkg#648]
I want to pkg node express app using pkg. My pkg json looks like:
`"scripts": {
    "start": "SET NODE_ENV=development&node ./bin/www",
    "start-prod": "SET NODE_ENV=production& node ./bin/www"
  },
  "dependencies": {
    "better-queue": "^3.8.10",
    "cookie-parser": "~1.4.3",
    "data-store": "^3.1.0",
    "debug": "~2.6.9",
    "express": "~4.16.0",
    "http-errors": "~1.6.2",
    "morgan": "~1.9.0",
    "pug": "2.0.0-beta11",
    "winston": "^3.2.1",
    "winston-daily-rotate-file": "^3.8.0",
    "ws": "^6.2.0"
  },
  "pkg": {
    "assets": [
      "views/**/*",
      "public/javascripts/*.js"
    ]
  },
  "bin": "./bin/www"`

I am using running node env to load config files for dev and production env using "process.env.NODE_ENV". This gives me error while compiling "Warning Cannot resolve '`${ process.cwd() }/config/${ process.env.NODE_ENV }.json`'" and fails while calling the exe.

Please suggest how to load diff env files while using pkg

**Comment by isaelblais** [comment]
You need to put relative path everywhere inside you project. Also include node_modules inside the assets from the config file.

Also execute the exe via command line so we can see the full error log and please paste it here.

**Comment by ybzjsxh** [comment]
> You need to put relative path everywhere inside you project. Also include node_modules inside the assets from the config file.
> 
> Also execute the exe via command line so we can see the full error log and please paste it here.

I have the same issue, and here's what command line says, please help, thx
![image](https://user-images.githubusercontent.com/18141198/66727580-d04e8500-ee72-11e9-8298-afc34fbbe238.png)
