### ISSUE TITLE
Compiled nodejs for armv7 armv6 and arm64 alpine/linux

### ISSUE THREAD

**Issue by robertsLando** [vercel/pkg#658]
Hi, I have created a dockerfile to cross compile nodejs for different architecture.

I have also provided some prebuilt binaries too if you want to add them to `pkg-fetch` releases binaries: 

https://github.com/robertsLando/pkg-binaries

**Comment by lefuturiste** [comment]
I'm trying to build a binary of my Node.js app on a classic x86_64 computer but for a armv6 target (raspbian raspberry pi zero). How I can use your tool to do that. I can't find anything on your README for that

**Comment by robertsLando** [comment]
My tool is used to get pre-compiled nodejs binaries to use with pkg, you should be able to do what you are looking for by checking the code I use to compile it with different archs (using qemu).
