### ISSUE TITLE
is it possible to pack a project with childprocess calling external python script?

### ISSUE THREAD

**Issue by ctlkkc** [vercel/pkg#661]
As subject, especially if the python script also has dependencies:
e.g.:
```
const spawn = require("child_process").spawn;

		const pyProg = spawn(config.python_path, [config.gsauth, token[1]]);
		pyProg.stdout.on('data', function (data) {
                    //do something here
		});
```

**Comment by mursang** [comment]
did you solve this?

**Comment by FilipParyz** [comment]
Hi,
I've come across the same issue and would love to know if anyone knows how to deal with it?

Node.js app that executes a python script with `pythonApp = spawn('python', 'pathToScript.py');` and checks for `pythonApp.stdout.on, pythonApp.stderr.on and pythonApp.on('exit')`.
I want to package it with PKG, but then the python can't open the `pathToScript.py` file.
