### ISSUE TITLE
node v10.4.1 have a timer bug

### ISSUE THREAD

**Issue by homerzhou** [vercel/pkg#666]
HI:
   node v10.4.1 have a timer bug [#22149](https://github.com/nodejs/node/issues/22149)
   this bug will cause setInterval and setTimeout will not trigger after about 25 days.
   I am worry there may be more bug from v10.4.1 to v10.15.3.
   Is PKG can support lastest node10 version to node10.15.3 ?

**Comment by Benno007** [comment]
This would be very beneficial for us too if we could get a more recent version of node 10 👍

**Comment by fredericosilva** [comment]
Sharing the same pain here. Getting always this warning (http2 became stable on v10.10.0 )

```
(node:371) ExperimentalWarning: The http2 module is an experimental API.
```

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
