### ISSUE TITLE
Support Node 12

### ISSUE THREAD

**Issue by guyisra** [vercel/pkg#673]
I'm getting 
  node12-linux-x64, node12-macos-x64, node12-win-x64
> Error! No available node version satisfies 'node12'

**Comment by Luke265** [comment]
I've created a pull request https://github.com/zeit/pkg-fetch/pull/65

**Comment by hipstersmoothie** [comment]
Node 12 is now supported

**Comment by mdhornet90** [comment]
I'm seeing this issue today with `v4.3.8`
