### ISSUE TITLE
Cannot Find .wsf Script

### ISSUE THREAD

**Issue by ofthedove** [vercel/pkg#679]
I'm attempting to package a program that uses regedit into an exe. I can package it up, but when I run it I get the error:

```
Input Error: Can not find script file "C:\snapshot\<project name>\node_modules\<sub-project name>\node_modules\regedit\vbs\regList.wsf".
```

I updated my package.json to include:
```
  "pkg": {
    "scripts": "**/regedit/**/*.wsf"
  }
```
and ran pkg with the command:
```
pkg .\package.json --target node10-win-x64
```
but I still see the same error.

I ran `pkg` with the `-d` option and reviewed the resulting log and I see these relevant entries:
```
> [debug] Content of %1 is added to queue. It was required from %2
  C:\b\node_modules\super-bean\node_modules\regedit\vbs\regList.wsf
  C:\b\package.json
```
```
> [debug] Stat info of %1 is added to queue
  C:\b\node_modules\super-bean\node_modules\regedit\vbs\regList.wsf
```
```
> [debug] The file was included as asset content
  C:\b\node_modules\super-bean\node_modules\regedit\vbs\regList.wsf
```

So it seems the script is being included. Why can't the executable find the script?

**Comment by smnth90** [comment]
Is it working for you? What is the solution?
I tried in the same way as you did. But it is throwing error saying "Pkg cannot compile other than .js extension"

**Comment by robertsLando** [comment]
Did you try to add it as an asset instead of scripts?
