### ISSUE TITLE
App closes silently when cross-pakging from MacOs to Win and logging with pino

### ISSUE THREAD

**Issue by boristian** [vercel/pkg#688]
Hello,

i would like to cross-pkg an app from MacOS for Windows. In the app i'm using [pino](https://github.com/pinojs/pino) as logging module.  When i start the app on CMD, the app opens up and closes silently with no log output at all.

I've made a sandbox script:

```js
const pino = require()'pino'

console.log('Setting up  pino ...')

const log = pino({ level: 'debug', name: 'main' })

log.info('Initializing...')

process.on('error', err => console.error(err))
```

This command i use to pkg:

```sh
pkg -t node10-win-x64 -o ./pkg_test_win package.json
```

Pkging the same script on windows, it works fine.

Am i doing something wrong?

Greetz and thanks in advance,
Christian

**Comment by petrbroz** [comment]
I have the same problem when trying to use [commander.js](https://github.com/tj/commander.js). When cross-packaging a simple commander.js app from macOS to Windows binaries, I get no output. When packaging from Windows to Windows binaries, everything works.

**Comment by AxelTerizaki** [comment]
Coincidentally I just noticed today that my issue #686 also applies on macOS, so the two are duplicate/related :)

My issue is cross-packaging from Linux to macOS/Windows

For now I've reverted to pkg 4.3.8 which seems to work fine.

**Comment by petrbroz** [comment]
Thank you for the tip @AxelTerizaki! Reverting to 4.3.8 helped me as well.

**Comment by AntonioCunha** [comment]
We were having issues building from Windows to Linux and Reverting to 4.3.8 solved our issues too.

**Comment by AxelTerizaki** [comment]
Is it still happening here too with 4.4.2 ? This version solved my similar issue.

**Comment by n1ru4l** [comment]
Can we setup github actions for testing this behavior? It is possible to run OS X, Unix and Windows actions 🤔

Afaik this issue is still present in 4.4.x

**Comment by robertsLando** [comment]
Now github actions are setted up
