### ISSUE TITLE
sqlite3 packaging error - Cannot find module

### ISSUE THREAD

**Issue by chriszilla1123** [vercel/pkg#690]
I am trying to bundle sqlite3 into my program, which was installed in the usual way using `npm install sqlite3`.

I run the following command to package, which runs without errors or warnings.:

```
chris@chris-server:~/Storage/Programming/tempoServer$ pkg package.json && mv tempo-server-* ./dist/
> pkg@4.4.0
> Targets not specified. Assuming:
  node8-linux-x64, node8-macos-x64, node8-win-x64
```

After distributing the executable to another machine and executing it, I get the following output:

```
chris@chris-remote:~/Storage/tempoServer$ ./tempo-server-linux
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: Cannot find module '/snapshot/tempoServer/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:546:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/tempoServer/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
```

The dependincy is included using `const sqlite = require('sqlite3');`, and works perfectly when starting the program through NPM. 

Any suggestions? I have tried including the entire `node_modules` folder in my `package.json` `pkg` config, as well as just including the `sqlite3` folder, both with the same error. Running pkg through `pkg server.js` also has the same results.

**Comment by jfhenon** [comment]
Do you have node_sqlite3.node and your package in the same folder ? (.node files can’t be included in the package) 
See https://github.com/zeit/pkg/blob/master/README.md#native-addons

**Comment by sharathbaddam** [comment]
Sqlite3 has a native addon (.node) file which cannot be packaged into exe, you would need to have .node files along with exe. 
You can edit the way sqlite3 is requiring the .node file to not have that same folder structure as shown in the error. I edited it in a way that it will expect the .node file to be in same folder as exe.

**Comment by FabianTe** [comment]
@sharathbaddam

> You can edit the way sqlite3 is requiring the .node file to not have that same folder structure as shown in the error. I edited it in a way that it will expect the .node file to be in same folder as exe.

Could you please show how?

**Comment by sharathbaddam** [comment]
@FabianTe i have a gulp script as following that replaces the code in sqlite3.js file before building an exe 

`function sqlite(done) {`
     ` gulp.src(['node_modules/sqlite3/lib/sqlite3.js'])`
    `    .pipe(replace("require(binding_path)", "require('./node_sqlite3.node)"))`
    `.pipe(gulp.dest('node_modules/sqlite3/lib/'))`
    `.once("error", function () { this.once("finish", () => process.exit(1));})`
    `.once("end", function() { done()});`
`}`

**Comment by robertsLando** [comment]
This should be fixed here: https://github.com/vercel/pkg/blob/master/dictionary/sqlite3.js

**Comment by H31t0rGamer** [comment]
> This should be fixed here: https://github.com/vercel/pkg/blob/master/dictionary/sqlite3.js also now .node files should automatically be added to the executable, if not you just have to specify them in [assets](https://github.com/vercel/pkg#native-addons)

How am i suposed to do that?

**Comment by xencodes** [comment]
@robertsLando how we are supposed to add `.sqlite.node` in the assets object ?

**Comment by xencodes** [comment]
i was using `pnpm`, but by using `yarn` it worked
