### ISSUE TITLE
 Can't resolve '@babel/runtime-corejs2/core-js/json/stringify' 

### ISSUE THREAD

**Issue by ShintaroNippon** [vercel/pkg#694]
ran

 pkg app.js -t node10-linux-x64 --output boxit

./boxit

> Using "webpackDevMiddleware" config function defined in next.config.js.
> Using external babel configuration
> Location: "/home/shintaro/Desktop/projects/github/frontend/app/.babelrc"

Failed to compile.

/snapshot/frontend/node_modules/next/dist/client/event-source-polyfill.js
Module not found: Can't resolve '@babel/runtime-corejs2/core-js/json/stringify' in '/snapshot/frontend/node_modules/next/dist/client'

**Comment by ShintaroNippon** [comment]
I already removed the babelrc, its not required i think..

I'm using this boilerplate
https://github.com/MustansirZia/next-express-bootstrap-boilerplate

thanks in advance

**Comment by ShintaroNippon** [comment]
I have installed this
"@babel/runtime": "^7.3.4",
"@babel/runtime-corejs2": "^7.4.5",

but now fires this error

./app-linux 
```
[ error ] /snapshot/frontend/node_modules/next-server/dist/lib/loadable.js
Module not found: Can't resolve '@babel/runtime-corejs2/core-js/array/is-array' in '/snapshot/frontend/node_modules/next-server/dist/lib'

```
can someone help

thanks

**Comment by ShintaroNippon** [comment]
please check this:

https://github.com/babel/babel/issues/10030

many thanks

**Comment by MAGICSCIENTIST** [comment]
i found the same error in my project when i use an npm-link module. 
but the module work fine if the module is published and install by the project.
so it's there any solutions?...

**Comment by benpetsch** [comment]
Solved the issue for me:
`npm install --save-dev @babel/runtime-corejs2 `

**Comment by oste** [comment]
I am seeing a similar issue. Unfortunately the solution @benpetsch mentioned does not work. It did change the error slightly and now I am seeing this

```
 web  Failed to compile.
/usr/local/lib/node_modules/expo-cli/node_modules/react-error-overlay/lib/index.js
Module not found: Can't resolve '@babel/runtime-corejs2/core-js/array/from' in '/usr/local/lib/node_modules/expo-cli/node_modules/react-error-overlay/lib'
```

I am using expo with nextjs for web

**Comment by MatteoGioioso** [comment]
Same issue here, however after installing `npm install --save-dev @babel/runtime-corejs2` and successfully started nextjs development, I just realized that there the server was not reloading at any changes and time to time was getting stuck.

**Comment by pedromagalhaes** [comment]
yarn @babel/runtime-corejs2 --dev

**Comment by Lwdthe1** [comment]
@benpetsch's fix worked for me
