### ISSUE TITLE
How to Compile puppeteer package file?

### ISSUE THREAD

**Issue by rebootcode** [vercel/pkg#696]
I am getting an error while compiling a puppeteer package file. It's not compiling.

How to compile nodejs file that it compiles and binds chromium too or anything related to have compiled and packaged app.

Thanks

**Comment by rebootcode** [comment]
I just found this issue here - https://github.com/zeit/pkg/issues/204  but can't find any solution there. Has anyone tried and successfully achieved?

**Comment by jchook** [comment]
@rebootcode I figured out a [workaround](https://github.com/zeit/pkg/issues/204#issuecomment-536323464).

Unfortunately zeit cannot bundle Chromium, so you have to distribute it alongside your binary. You could also look into other tools like [warp](https://github.com/dgiagio/warp).

**Comment by hipstersmoothie** [comment]
closing as this issue is a dupe
