### ISSUE TITLE
How to handle update of application with migration using pkg

### ISSUE THREAD

**Issue by psaxena** [vercel/pkg#697]
Hi,

I am using pkg module to create an exe of my application. Till now, updating application was only update exe.

with introduction of database, Application uses sqlite db and sequelize for creating migrations. I wan to know how can we run migrations as part of updating packaged application apart from copying updated exe?

Thanks,
Pooja

**Comment by shanmukhateja** [comment]
@psaxena did you figure out how to do this?

**Comment by hipstersmoothie** [comment]
This is outside the scope of `pkg`
