### ISSUE TITLE
App Name with "." truncated

### ISSUE THREAD

**Issue by DamienGagniere** [vercel/pkg#698]
My application's name has "." like a.b.c
But there is a problem with the option out-path, the last part is removed:
so for **a.b.c** i got an exe named **_a.b.exe_** instead of **a.b.c.exe**.
i found the probleme in the code of **index.js** at the line **268**:
```
const ext = path.extname(name);
output = name.slice(0, -ext.length || undefined);
```
Why do you take into account that the name of application has an extension?
May is it possible to avoid it?

**Comment by robertsLando** [comment]
@DamienGagniere This can be avoided yes. Would you like to submit a fix?
