### ISSUE TITLE
Compiling out of a string

### ISSUE THREAD

**Issue by oonqt** [vercel/pkg#706]
Hey, so say for example I have my code to compile as a string in my code, and I want to compile it without referencing a file: `let code = "console.log";`. Basically what I want to do is compile my code that is stored as a string, not as an individual JS file. Is this possible? If so, how can it be achieved?

**Comment by OneBitAhead** [comment]
Hi, if I get you right: you want to be able to load javascript code from strings (or even database entries ;)).

This will work. *index.js*
```javascript
/** Needed to load modules from string (or even a database) */
function requireFromString(src, filename) {
   var Module = module.constructor;
   var m = new Module();
   m._compile(src, filename);
   return m.exports;
}
/** Your "string" code **/
let code = `exports.hello = function(a){
   console.log("Hello ", a);
}`;

var helloWorld = requireFromString(code,"");
//console.log(helloWorld);
helloWorld.hello("World");
```

*package.json* (here for linux)
```json
{
  "name": "test",
  "bin": "index.js",
  "pkg":{
   "targets": ["latest-linux-x64"]
  }
}
```

Run 
```shell
pkg .
```

... and have fun with
```shell
./test
# output will be 
Hello World
```
