### ISSUE TITLE
--options max_old_space_size can not run in cluster mode

### ISSUE THREAD

**Issue by tianxhgithub** [vercel/pkg#707]
such as : 
file FCSAppCluster376.js include :
const cluster = require('cluster'); 
    if (cluster.isMaster) {
        console.log(`Master ${process.pid} is running`);
        var prc=cluster.fork();
        .....
    } else { 
        require('./FCSApp.js');
        console.log(`Worker ${process.pid} started`);
    }

pkg -t win -c ./config.json  ./FCSAppCluster376.js --options max_old_space_size=4096

when run FCSAppCluster376.exe report err:
Error: Cannot find module 'E:\Code\nodejs\EDC376\FCSNode376\--max_old_space_size=4096'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)
worker 7048 died.

**Comment by tianxhgithub** [comment]
C:\Users\Administrator>pkg -v
4.4.0
C:\Users\Administrator>node -v
v10.16.0

**Comment by tianxhgithub** [comment]
how to avoid this problem?

**Comment by hellower** [comment]
I have same issue.

**Comment by PascalPuchtler** [comment]
+1

**Comment by PascalPuchtler** [comment]
I have a smal work around.
With this it is not possible to configurate the max_old_space_size from a worker, but the max_old_space_size from the master.

I used:

```
const cluster = require('cluster');
cluster.setupMaster({
      exec: __dirname + '/Worker.js',
      execArgv: []
    });
let worker = cluster.fork();
```

**Comment by SnakeDrak** [comment]
Same issue here, I have used the @PascalPuchtler workaround meanwhile.

**Comment by lamualfa** [comment]
Temporary solution:

https://github.com/vercel/pkg/issues/1047#issuecomment-1293431841
