### ISSUE TITLE
'sequelize' is not recognized as an internal or external command, operable program or batch file. Error: Error: Command failed: sequelize db:migrate

### ISSUE THREAD

**Issue by psaxena** [vercel/pkg#708]
Hi,

I am trying to package my application which uses sqlite and sequelize. My package json is like:
`"dependencies": {
    "@types/bluebird": "^3.5.26",
    "@types/libxmljs": "^0.18.3",
    "@types/node": "^11.12.1",
    "@types/restify": "^7.2.9",
    "@types/restify-errors": "^4.3.3",
    "@types/uuid": "^3.4.4",
    "@types/validator": "^10.11.0",
    "@types/ws": "^6.0.1",
    "better-queue": "^3.8.10",
    "data-store": "^3.1.0",
    "libxmljs": "^0.19.5",
    "pkg": "^4.3.7",
    "restify": "^8.2.0",
    "sequelize": "^5.8.7",
    "sequelize-cli": "^5.4.0",
    "sqlite3": "^4.0.8",
    "typescript": "^3.3.4000",
    "uuid": "^3.3.2",
    "winston": "^3.2.1",
    "ws": "^6.2.1",
    "yamljs": "^0.3.0"
  },
  "pkg": {
    "assets": [],
    "scripts": [
      "build/*.js",
      "build/routes/*.js",
      "build/**/*.js",
      "node_modules/sequelize/*.js",
      "node_modules/sequelize/**/*.js",
      "node_modules/sqlite3/lib/*.js",
      "node_modules/sqlite3/*.js*",
      "node_modules/node-pre-gyp/lib/*.js",
      "node_modules/node-pre-gyp/lib/util/*.js*"
    ]
  },
  "bin": "build/main.js",`

And my Main.js is :

function initializeDB() {
    // Return new promise 
    return new Promise(function (resolve, reject) {
        // Do async job
        console.log("returning promise");
        resolve(1);
    })

}
initializeDB()
    // Perform DB migrations and seeders
    .then(() => {
        console.log("sequelize db:migrate");
        // Require dbconfig so that the correct .env file is picked up before we try and update any databases and cached.
        return exec.execSync("echo 'pooja' && sequelize db:migrate", { stdio: 'inherit' })
    })
    // Start Server
    .then(() => {
        console.log("Staring server");
        require('./server.js')
    })
    .catch((err) => {
        console.log('Error: ' + err)
        process.exit(1)
    })

Also, Command i am using to package application is 
`pkg . --targets latest-win-x64`

This is generatin my app.exe in same folder and I am able to run. When I copy my  exe to different  folder, I get the error saying:
`E:\Analyzer Complete\AnalyzerDeploy\AnalyzerService>analyzer.exe
returning promise
sequelize db:migrate
'sequelize' is not recognized as an internal or external command,
operable program or batch file.
Error: Error: Command failed: sequelize db:migrate`

Please let me know how to make app.exe work  with sqlite and sequelize. I've tried copying "node_sqlite3.node" to other folder as well.

**Comment by sam0x17** [comment]
You should call sequelize from your node_modules folder as you can't expect it to be installed on the target system. So instead of `sequelize db:migrate` something like `./node_modules/sequelize/whatever_the_binary_path_is db:migrate`
