### ISSUE TITLE
produced executable exits with return code 4

### ISSUE THREAD

**Issue by gautaz** [vercel/pkg#709]
Hello,

One of our bundled services fails to start correctly once bundled with `pkg`.
It exits directly with return code 4.

Looking at [pkg sources](https://github.com/zeit/pkg/blob/master/prelude/bootstrap.js#L1257), this can possibly be related to a `VERSION_MISMATCH` but this is quite obscure to me.

Maybe someone can shed some light on what causes such an exit code?

**Comment by gurisko** [comment]
Hi @gautaz . I bumped into this too. It is a mismatch between your `NODE_OPTIONS` variable and the built executable. I managed to work around this by unsetting the variable before building.

**Comment by gautaz** [comment]
Thanks @gurisko, since then we have moved to nexe but perhaps we'll go back to pkg later on :-).
