### ISSUE TITLE
using C++ addon in pkg script result in "node version mismatch"

### ISSUE THREAD

**Issue by Firlfire** [vercel/pkg#715]
Hi!

I'm using node 10.15.1 and npm 6.4.1

I have asked this to [nodeJS](https://github.com/nodejs/help/issues/1980) and I'm waiting an answer from them, but maybe you can help me ?

When I launch the .exe that pkg generated I getting this error :

> The module '[...]/addon.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 64.
> This version of Node.js requires NODE_MODULE_VERSION 72.
> Please try re-compiling or re-installing the module (for instance, using npm rebuild or npm install).

My problem is that I have created this 'addon.node' so I can not rebuild it (I tried but I have the same issue).
Maybe I can "force" pkg to compile with NODE_MODULE_VERSION 64 instead of 72 ?

Thanks in advance

**Comment by lselden** [comment]
The node version vs. NODE_MODULE_VERSION is listed [here](https://nodejs.org/en/download/releases/). Your addon got compiled using your current version of node (10.15.1). You can fix this by:
* set env variable `npm_config_target` to your target version of node - to use latest 12 do `npm_config_target="12.4.0"`. Then run [`npm rebuild`](https://docs.npmjs.com/cli/rebuild) to recompile.
* Target `node10` when running pkg using the [`--targets` option](https://github.com/zeit/pkg#targets)
