### ISSUE TITLE
string concatenation whitespaces replaced with "String.prototype.matchAll"

### ISSUE THREAD

**Issue by NiclasThobaben** [vercel/pkg#717]
Hello there,
i got this weird issue, which took me quite a while to discover.
When i packaged my project for node10-linux-x64 everything was working fine, but the win-x64 version was not working at all. After a while i found that concatenated strings, which include whitespaces were not concatenated properly. Instead of the expected whitespace, "String.prototype.matchAll" is inserted. I'm not sure if this is a node problem (probably not?), pkg or a windows problem. Or am I missing out on something here?

```
var foo = 'foo';
var bar = 'bar';

console.log('A', 'foo bar');
console.log('B', foo + ' ' + bar);
console.log('C', `${foo} ${bar}`);
console.log('D', foo.concat(' ').concat(bar));

//Expected output:
// A foo bar
// B foo bar
// C foo bar
// D foo bar

//Actual output:
// A foo bar
// B fooString.prototype.matchAllbar
// C fooString.prototype.matchAllbar
// D fooString.prototype.matchAllbar
```

**Comment by infloop** [comment]
Faced the same issue a day ago

**Comment by infloop** [comment]
@NiclasThobaben Do you have a workaround?

**Comment by NiclasThobaben** [comment]
unfortunately not...it works just fine with node8 which is ok for me right now,  but it would be desireable to work with node10 aswell
