### ISSUE TITLE
Wrong targets when multiple are specified on command line

### ISSUE THREAD

**Issue by mxmauro** [vercel/pkg#718]
Hi, if I run the following command on Windows, it works as expected.

`pkg -t node10-win-x86,node10-win-x64,node10-linux-x64,node10-macos-x64 ....`

But if I run it under Ubuntu, it tries to download node10-linux-x86 package which does not exist on repository and also it was not specified as a target.

It works fine when running the script several times specifying one target each round.

Regards,
Mauro.

**Comment by gokaybiz** [comment]
Same issue here.
I only set node10-win-x86, but It's trying fetch node10-linux-x86  too. But there is no linux-x86.
Then throwing error...
