### ISSUE TITLE
Cannot Run Mac Executable.

### ISSUE THREAD

**Issue by MB911** [vercel/pkg#722]
I used 
**pkg package.json** 
to create a Mac Executable for my project --example.js. But when I double click on that executable, it executes from the root directory instead of executing from it's own directory.
Therefore, I'm getting module not found error.
Error: Cannot find module '/Users/*******/debug.js'

I have to run it through terminal by moving into that directory. I want it to work by just clicking on the executable.

I'm using 

- MacOS Mojave 10.14.5
- Node version 10.13.0

**Comment by rao123dk** [comment]
is it works on others platform?  

have you mentions this in package.json file?
"pkg": {
    "scripts": "build/**/*.js",
    "assets": "views/**/*"
  }

**Comment by igorklopov** [comment]
You need `path.dirname(process.execPath)'

**Comment by erjanmx** [comment]
Thanks @igorklopov for your reply. Yes I did try that one also, but it creates another issue when running directly with node, then it outputs my current node directory, i.e.

HOME/.nvm/versions/node/v12.16.1/bin.

Any ideas to have a solution or do I need to make extra checks and call the right one?

**Comment by igorklopov** [comment]
@erjanmx  Right. You need to check `process.pkg`. If true then my line above, if false then your line you want from direct node run, like `__dirname` (not sure tho).

**Comment by erjanmx** [comment]
Just tested and everything seems to be working as expected with your proposed solution, @igorklopov, both on macOS and Windows (didn't test on linux tho).
Thanks a lot for your help!
