### ISSUE TITLE
File or directory 'E:\**\DrawMe\public\index.html' was not included into executable at compilation stage. Please recompile adding it as asset or script.

### ISSUE THREAD

**Issue by Wolfleader101** [vercel/pkg#723]
I am getting `File or directory 'E:\**\DrawMe\public\index.html' was not included into executable at compilation stage. Please recompile adding it as asset or script.`

But i have clearly linked them here
`"pkg": {
    "assets": ["public/*","/public/**/*"]
  }`

**Comment by 1imad** [comment]
Did you find any solution for this? I'm facing the same issue.
