### ISSUE TITLE
best practice for publishing pkg binaries to npm

### ISSUE THREAD

**Issue by GiladShoham** [vercel/pkg#725]
Hi,
I'm the maintainer of a [big open source CLI tool named bit](https://github.com/teambit/bit).
I've started playing with pkg a few months ago in order to publish our tool as a binary with node.
Most of our users install bit via npm / yarn.
I wonder if there are best practices on how to publish the pkg file to npm / yarn.
I thought maybe upload the file somewhere and just publish a package with a post install script which fetches the binary. 
Any idea would be great.
Thanks.

**Comment by GiladShoham** [comment]
Also found out that in v0.18.5 of ncc the following is not working:
```sh
npm init -y
npm i requirejs
touch a.js
echo "require('requirejs')" > a.js
ncc build a.js
```
Which makes my windows machine not working since I use this package and newer versions of ncc are not working on windows.

**Comment by adrukh** [comment]
👋 @GiladShoham 

We're @snyk, and we are using `pkg` to publish binaries of our CLI as GH release assets (using `semantic-release`). See https://github.com/snyk/snyk/blob/master/.releaserc for more details, let me know if you have any questions!

**Comment by GiladShoham** [comment]
Thanks @adrukh, it's very helpful.
I look at your npm package, and I didn't saw the binaries there.
How do you handle different node versions between users who install snyk via the binary and always have your configured node version and users who install it via npm and uses their own node version?
I see the control of the node version as one of the biggest advantages of using pkg. But if your users can install it via npm, you must test and support a lot of node versions.
Am I missing something?
Thanks.

**Comment by adrukh** [comment]
> I look at your npm package, and I didn't saw the binaries there.
Indeed, we don't publish them to npmjs. If we did, our package size would grow significantly, and that's not good. See https://packagephobia.now.sh/result?p=snyk, we're now at ~22MB download size, and each binary is over 50MB in size. I'd hate to ask our users to download 150MB they won't need each time they install our CLI.
Instead, we use the GH release page as a download page.

> How do you handle different node versions
We test against the versions we want to support, see https://github.com/snyk/snyk/blob/master/.travis.yml#L3-L7 . It is becoming easier with us converting our codebase to typescript.
