### ISSUE TITLE
Can't spawn from other process - Windows

### ISSUE THREAD

**Issue by atomicus** [vercel/pkg#734]
When I'm trying to spawn my package by calling

`
const worker = spawn(${pathToPkg},{cwd:this.targetDir,detached:true,stdio:'ignore'}
            );
           worker.unref();
`

The pkg opens, but it does not display any output, like it's stdio was /dev/null.
Running directly does not give any issues, any ideas?

**Comment by felladrin** [comment]
That's the expected behavior of spawned programs. Check here: https://nodejs.org/api/child_process.html#child_process_child_process

So to make _worker_ output in your current console, you need to listen to its event `data`, like this:

```
worker.stdout.on('data', (data) => {
  console.log(`worker stdout: ${data}`);
});
```

**Comment by TheTechdoodle** [comment]
Don't forget to reference the script file in the args option. See here: https://github.com/zeit/pkg/issues/591#issuecomment-451390770
