### ISSUE TITLE
Support for node-adodb

### ISSUE THREAD

**Issue by chrissantamaria** [vercel/pkg#736]
I currently use `pkg` in production with [`node-adodb`](https://github.com/nuintun/node-adodb/blob/master/README-EN.md) being one of my main packages used in my application. Due to the way it performs database queries, it relies on one of its lib files `adodb.js` being accessible from a spawned CScript process which `pkg` prevents due to its bundling behavior.

This is a [known issue](https://github.com/nuintun/node-adodb/issues/113) and the current solution is to manually copy the file to the execution directory and point `node-adodb` to it. This works fine for me, but I would prefer for the Node process to be able to either create this file at runtime if it's not present or prevent needing it in the directory altogether.

I see the `dictionary` directory in `pkg` filled with what I suspect to be patches for some packages, though there's no documentation I could find on them. Is there any way a similar patch could be made for `node-adodb` / where could I find resources to create a patch myself?

**Comment by chrissantamaria** [comment]
Found a slightly better solution - I'm now able to copy the file directly from `node_modules` to the execution directory. I was unable to do this previously because of a ENOENT error when running `fs.copyFileSync` but a temporary solution in #420 seems to work for now.

That being said, proper support for `node-adodb` and, more importantly, documentation for package patches would be greatly appreciated.

**Comment by albertodam** [comment]
Hi @chrissantamaria i have same problem, but i dont understand how you resolve. Can you show me the code?

**Comment by chrissantamaria** [comment]
Sure! Here's a demo repo to show how I've handled this situation in the past: https://github.com/chrissantamaria/pkg-node-adodb
