### ISSUE TITLE
Tries to include wrong targets

### ISSUE THREAD

**Issue by DenizBasgoren** [vercel/pkg#743]
when I type
`pkg -t latest-win-x86 index.js`
it first fetches latest-win-x86, then tries to fetch latest-linux-x86. When it tries to fetch latest-linux-x86 it throws an error telling that linux x86 can't be built on x64. I can't get it working.

**Comment by rjconrad** [comment]
Same exact problem. I'm working on a mac and getting this:

```
rick$ yarn pkg . -t win-x86
yarn run v1.16.0
$ /Users/rick/sil/lessons-from-luke/node_modules/.bin/pkg . -t win-x86
> pkg@4.4.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.2.0-win-x86      [====================] 100%
  fetched-v12.2.0-macos-x86    [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-macos-x86
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-x86"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-x86"}
> Building base binary from source:
  built-v12.2.0-macos-x86
> Error! Not able to build for 'x86' here, only for 'x64'
```

**Comment by samiyaakhtar** [comment]
Getting the same error as well.

**Comment by teppeis** [comment]
same: https://github.com/zeit/pkg/issues/735
related: https://github.com/zeit/pkg-fetch/issues/68

**Comment by karlsnyder0** [comment]
Same issue.  When trying to build Win32 inside an alpine docker PK tries downloading the alpine x86.  Wut???
