### ISSUE TITLE
pkg with local node sources

### ISSUE THREAD

**Issue by ctlkkc** [vercel/pkg#744]
How to pkg with local node sources instead of requesting from GitHub (firewall restriction)?
let's say there is the local sources file is "node-v8.9.3-source.tar.gz" downloaded from official nodejs site. 
What would be the command option to pkg the project with above sources (Linux distribution)?

Thanks

**Comment by JoHi21** [comment]
Hello ctlkkc,

I had a similar issue behind corporate Proxy and solved it by manually downloaded the sources from https://github.com/zeit/pkg-fetch/releases

**Comment by sumitcodename47** [comment]
Where can I find this directory in Linux?

**Comment by benjhess** [comment]
> Where can I find this directory in Linux?

In your home directory. E.g: 
```sh
$ cd ~/.pkg-cache/
$ find .
./v2.6
./v2.6/fetched-v10.15.3-linux-x64
```

**Comment by yuchi** [comment]
Please note that there’s a [undocumented `PKG_CACHE_PATH` environment variable](https://github.com/zeit/pkg-fetch/blob/03f551cd538d9cd631c70215c5c7b2f85965411c/lib/places.js#L8-L10) which **defaults** to `~/..pkg-cache`. So in a CI context you can control the position of the cache easily by exportng such variable with your preferred location.

**Comment by PriyaSivaraj1987** [comment]
I am same issue.. would like to have env variable for corporate proxy so that we can avoid manual downloads
