### ISSUE TITLE
Issue with node10-win-x64 binary output from a Mac

### ISSUE THREAD

**Issue by TomYeoman** [vercel/pkg#745]
Hi team,

When building the `node10-win-x64` binary from a mac I get what appears like a broken binary output ( node 8 works fine )

When running the node10 output on a windows machine the executable opens then immediately closes with no logging.

If I build the same binary ( a node 8 or 10 version ) on my windows machine then the same binary opens as expected and prints logs etc.

System specs

**Mac**
- Node 8X / 10X tried running on both
- 10.14.5 Mojave

The size of the windows vs mac binary is identical with both appearing to package node10 into it correctly

Any ideas?

**Comment by cankuscu** [comment]
try running your directly from cmd, it will tell you the error. you can also try compiling on windows using parallels or vm

**Comment by gabrielstuff** [comment]
regarding https://github.com/zeit/pkg/issues/779, using *4.3.8* indeed fixes the issue to build from mac to win with node 10.

**Comment by TomYeoman** [comment]
@cankuscu sorry if I was unclear but this is getting run via terminal - there is zero output in one case whereas another works. 

@gabrielstuff thanks i'll try re-compiling and testing soon :)

**Comment by Nashorn** [comment]
any solution?

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
