### ISSUE TITLE
[bug] Ignore .vue files inside node_modules

### ISSUE THREAD

**Issue by robertsLando** [vercel/pkg#746]
I'm getting this error

```
> Error! Unexpected token (3:0)
  /myApp/node_modules/vue2-google-maps/dist/components/infoWindow.vue
```

Seems that pkg is trying to compile a vue files and this throws the error shown. How can  this be avoided?

**Comment by apozyniuk** [comment]
@robertsLando try to add `/myApp/node_modules/vue2-google-maps/dist` as assets in package.json

**Comment by robertsLando** [comment]
Already tried and still doesn't work @apozyniuk

**Comment by hipstersmoothie** [comment]
@robertsLando Is this still an issue?

**Comment by robertsLando** [comment]
Yeah, I had to fix this by creating a script that moves the files from node modules and put them back after compilation, I think we should skip some files like .vue

**Comment by hacke2** [comment]
you can try catch when pkg use babel parse
