### ISSUE TITLE
Segmentation fault on OSX

### ISSUE THREAD

**Issue by zoell** [vercel/pkg#747]
I am trying to build a small node.js program on Windows 10 64 bit. On Windows the exe it is working fine, however I have an OSX 10.14 running in VMWare and when I run the osx binary it I get a Segmentation Fault: 11 in Terminal.

What can be the problem here or what can I do to see more information?

**Comment by ljbuck** [comment]
I had exactly the same issue, I ran pkg on Win 10 64bit and got the same seg 11 error when I tried to run the generated macos app on a macbook (not VM).  When I tried to run the generated linux app on an Ubuntu VM I got a similar error (segmentation failure - core dump). 

However, when I ran pkg on the same code on Ubuntu I was then able to run the generated files without error on linux, mac and windows too. So it looks like cross-compilation does work.. but as long as you are not packaging up on windows.

Anyway, that is as much investigation as I had time for.

**Comment by migmac99** [comment]
> I had exactly the same issue, I ran pkg on Win 10 64bit and got the same seg 11 error when I tried to run the generated macos app on a macbook (not VM). When I tried to run the generated linux app on an Ubuntu VM I got a similar error (segmentation failure - core dump).
> 
> However, when I ran pkg on the same code on Ubuntu I was then able to run the generated files without error on linux, mac and windows too. So it looks like cross-compilation does work.. but as long as you are not packaging up on windows.
> 
> Anyway, that is as much investigation as I had time for.

this worked for me however, I had to use
´´´
sudo npm install -g pkg
´´´
on the mac I used to package the app
