### ISSUE TITLE
--no-bytecode fails if package.json in subfolder of project without license

### ISSUE THREAD

**Issue by luxferresum** [vercel/pkg#748]
This is true for example for the `rxjs` package. It contains a `operators/package.json` file which breaks `pkg` when `operators/index.js` should be included without bytecode.

**Comment by luxferresum** [comment]
has this been fixed? or is this a wontfix?

**Comment by robertsLando** [comment]
Not fixed yet, PR?

**Comment by Hypfer** [comment]
There's a workaround using the `--public-packages` flag

#1140 added documentation on how to use that
