### ISSUE TITLE
Sharing node pre-complied source across multiple projects

### ISSUE THREAD

**Issue by ctlkkc** [vercel/pkg#755]
Hi this is just a generic functionality question - is it possible to share node pre-complied source across multiple projects? Let us say there are 3 project using the same source to pkg and got 3 executable:
./a1 50M
./a2 60M
./a3 70M

Can we have the functionality that sharing the  ~/.pkg-cache/v2.6/fetched-v8.16.0-linux-x64 source across the 3 above: 

./a1 20M
./a2 30M
./a3 40M

Run as:
./a1 --node-source=~/.pkg-cache/v2.6/fetched-v8.16.0-linux-x64

**Comment by slasktrat** [comment]
+1 for this! :)

**Comment by slasktrat** [comment]
This is still on the wishlist
