### ISSUE TITLE
Windows build crashes when built with 4.4.0 but works fine when built with 4.3.8

### ISSUE THREAD

**Issue by crazyquark** [vercel/pkg#762]
Windows binaries built on Linux with pkg are crashing right away.
Here is what wine says:
wine: Unhandled page fault on read access to 0xffffffffffffffff at address 0x140c436b8 (thread 002a), starting debugger...

I get the same error on windows too, looks like the linker screwed up something?

It works fine if built with pkg 4.3.7 or 4.3.8

**Comment by crazyquark** [comment]
Maybe related to https://github.com/zeit/pkg/issues/686 ?

**Comment by crazyquark** [comment]
Full backtrace: [backtrace.txt](https://github.com/zeit/pkg/files/3566428/backtrace.txt)

**Comment by perrywang** [comment]
I am also experiencing similar problem when I package win on MacOS then run it on windows it directly report segment fault.

**Comment by BitesizedLion** [comment]
I can reproduce and have encountered.
The executable for each OS has to be compiled on the same OS
