### ISSUE TITLE
npm i pkg gives "npm ERR! code CERT_NOT_YET_VALID" error

### ISSUE THREAD

**Issue by nateshmbhat** [vercel/pkg#764]
I am not able to install pkg at all from npm .

```
npm ERR! code CERT_NOT_YET_VALID
npm ERR! errno CERT_NOT_YET_VALID
npm ERR! request to https://registry.npmjs.org/pkg failed, reason: certificate is not yet valid

```

**Comment by DimitrijeManic** [comment]
@nateshmbhat Have you checked your system time?

**Comment by MatanYemini** [comment]
I have the same issue while running it using docker terminal.
My system time is correct, and if I try to execute npm install in my terminal it works.
Seems weird, know how to fix? @DimitrijeManic
