### ISSUE TITLE
next-i18next can't find folder when I run binary

### ISSUE THREAD

**Issue by SkunSHD** [vercel/pkg#767]
> docker run --rm -it -p 3003:3003 -e "PORT=3003" -e "API_URL=https://API_URL.com" app
> pkg/prelude/bootstrap.js:1185
>       throw error;
>       ^
> Error: ENOENT: no such file or directory, scandir '/app/static/locales/en'
> 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
>     at Object.readdirSync (fs.js:785:3)
>     at Object.fs.readdirSync (pkg/prelude/bootstrap.js:787:35)
>     at getAllNamespaces (/snapshot/app/node_modules/next-i18next/dist/commonjs/config/create-config.js:49:19)
>     at _default (/snapshot/app/node_modules/next-i18next/dist/commonjs/config/create-config.js:54:27)
>     at new NextI18Next (/snapshot/app/node_modules/next-i18next/dist/commonjs/index.js:30:43)
>     at Object.<anonymous> (/snapshot/app/src/i18n.js:0:0)
>     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
>     at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

I'm getting an error when I run binary in container.
Although I added static folder in pkg's assets, i18n can't find the static folder.
The static folder has this structure:
https://www.npmjs.com/package/next-i18next#2-translation-content
>     at getAllNamespaces (/snapshot/app/node_modules/next-i18next/dist/commonjs/config/create-config.js:49:19)
The code from that line:
`combinedConfig.ns = getAllNamespaces(path.join(process.cwd(), "".concat(localePath, "/").concat(defaultLanguage)));`
How can I fix this?

**Comment by roberto-slopez** [comment]
You try run command incorrect context, `../snapshot` is package, your resource `./app/static/locales/en` is out package
