### ISSUE TITLE
Failed to make bytecode node10-x64 for file ..  how to fix it ?

### ISSUE THREAD

**Issue by kanso-git** [vercel/pkg#770]
Hello all,

any help to fix this error Failed to make bytecode node10-x64 for file would be appreciated .

![image](https://user-images.githubusercontent.com/2843192/65043052-78e3f480-d95a-11e9-8266-f23a91811d0d.png)

many thanks

**Comment by sgoll** [comment]
I am experiencing the same issue. What is interesting is that the same repository, same version of `pkg` and all other dependencies, was working without problems when I last built a couple months ago.

**Comment by sgoll** [comment]
Ah, `-d` revealed the culprit: lots of `SyntaxError`. The reason was that I was transpiling to ES6 which does not seem to cope well with `pkg`. The `import`/`export` syntax prevents it to make bytecode.

My solution was to target `es5` instead in my `tsconfig.json`.

**Comment by trungutt** [comment]
Same here

**Comment by roberto-slopez** [comment]
Check this issue: [733](https://github.com/zeit/pkg/issues/733)

**Comment by MaQiangWei** [comment]
You can try using .njs packages
