### ISSUE TITLE
Try to run the command this way: `pkg -t node10-win-x64 main.build.js`

### ISSUE THREAD

**Issue by RajanZhan** [vercel/pkg#780]
Try to run the command this way: `pkg -t node10-win-x64 main.build.js`

_Originally posted by @roberto-slopez in https://github.com/zeit/pkg/issues/777#issuecomment-539562443_

**Comment by RajanZhan** [comment]
the same ,like this 
G:\Project\nest.js\nest tester\build>pkg -t node10-win-x64 main.build.js
> pkg@4.4.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.15.3-win-x64     [                    ] 0%
> Error! ESOCKETTIMEDOUT
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-win-x64"}
  fetched-v10.15.3-win-x64     [                    ] 0%
> Error! ESOCKETTIMEDOUT

**Comment by rao123dk** [comment]
What is your pkg version? Please try with pkg@4.3.7 its compatible with node10. otherwise, use 
pkg -t latest-win-x64 main.build.js
