### ISSUE TITLE
Feature request: update feature

### ISSUE THREAD

**Issue by iamisti** [vercel/pkg#789]
Can we have a feature that will make the app update itself when a new version is out?

Use case:
- The app i'm using got a newer version, so it'll automatically update itself without the need to download the executable again from the vendor website

**Comment by philippefutureboy** [comment]
@iamisti Hi Istvan! Since then, did you come up with a solution?

**Comment by iamisti** [comment]
not yet, changed library actually

**Comment by philippefutureboy** [comment]
Interesting, what did you go for?

**Comment by jazozaya** [comment]
@iamisti  - Any update? I'm also looking for a solution.

I'm investigating docker as an alternative, but still in the research phase.

**Comment by hipstersmoothie** [comment]
This is outside the scope of `pkg`
