### ISSUE TITLE
The animate.css module: Error! Unexpected character '@' 

### ISSUE THREAD

**Issue by goforward01** [vercel/pkg#79]
I used the express example of the **pkg** project to test the animate.css module I used in my project, installed by: `npm i animate.css -S`, and when I ran the command: `pkg package.json`, it came out the result:
```
> Error! Unexpected character '@' (1:0)
  /home/test/pkg-master/examples/express/node_modules/animate.css/animate.css
```
Maybe it isn't the place to ask question, but I tried according to the readme of **pkg**， and with no luck. It didn't work, whether I modified the package.json by adding the **assets** part or other way, Does anybody know how to solve this, tell me please, thx.

**Comment by igorklopov** [comment]
Hi! Please post code of minimal example. I need to know how front-end javascript code gets compiled as back-end code into executable. And then i'll try to figure out how to avoid it.

**Comment by goforward01** [comment]
Okay, I made a small example, as issue #79 and issue #81 described.
[vue-demo.zip](https://github.com/zeit/pkg/files/999932/vue-demo.zip)

**Comment by goforward01** [comment]
@igorklopov Okay, I added a simple example of using animate.css, btw, I modified the package.json too to make it work with pkg to produce the same error I met before.
[vue-demo.zip](https://github.com/zeit/pkg/files/999977/vue-demo.zip)

**Comment by ainglese** [comment]
i've had a similar(but i think not the same) problem with a powershell script, it seemed pkg was trying to bundle the css as a script.

in my case the error was that i had specified:
```
"scripts": [
      "libs/**/*"
    ],
```

changing it to:
```
"scripts": [
      "libs/**/*.js"
    ],
```

solved the problem. hope it helps!

**Comment by igorklopov** [comment]
TODO. Warning if someone tries to use a `.css` file in "scripts"

**Comment by SwarmKlaus** [comment]
I ran into the exact same problem. Even using your vue-demo project:
![image](https://user-images.githubusercontent.com/30899845/29170753-490e314a-7dda-11e7-9732-e158220e7e94.png)

**Comment by SwarmKlaus** [comment]
Hi Igor,

could you help me on this issue, please? As mentioned, I get the same error even using your vue-demo project. What could be wrong?

**Comment by vitali-korezki** [comment]
Hey guys,

I have a similar issue with .js.map files, by trying create a package for socket.io app. 

> Error! Unexpected token (1:10)
  /Users/.../Development/projects/app/node_modules/socket.io/node_modules/socket.io-client/dist/socket.io.js.map

Has someone any idea, how to fix this? Will be really great!

Thanks,
VK

**Comment by zachariahtimothy** [comment]
I am running into the same issue using [Typeface Roboto](https://github.com/KyleAMathews/typefaces/tree/master/packages/roboto). I am using Next JS with Material design so maybe we can find a way to ignore some files, then add them as assets?
