### ISSUE TITLE
how do I kill the example app?

### ISSUE THREAD

**Issue by ognjetina** [vercel/pkg#793]
I packed the example started it and now it is running forever on my mac... 8080 port is taken even after restarting... and I can't even list the process that is taking it up...

**Comment by daliborgogic** [comment]
```bash
# Find by port
$ sudo lsof -i tcp:[PORT]
# Kill process
$ kill -9 [PID]
```

**Comment by ognjetina** [comment]
well that's the weird part... its not listed as a process.. I have done so much stuff to find out whats going on... at this point I am not even sure is it from this package or who knows what...

**Comment by Nashorn** [comment]
https://github.com/Nashorn/kill-port
