### ISSUE TITLE
is there any idea to compile to wasm, which may run in browser directly

### ISSUE THREAD

**Issue by blizzardzheng** [vercel/pkg#794]
is there any idea to compile to wasm, which may run in browser directly

**Comment by ncoonrod** [comment]
Now with Docker and Kubernetes supporting WASM deployments, compiling to WASM would be useful.

Here's a bit about Docker + WASM: https://docs.docker.com/desktop/wasm/

**Comment by image72** [comment]
[compile NodeJS to wasm #3774](https://github.com/nodejs/help/issues/3774)

**Comment by premkumarrtech** [comment]
include your wasm file in package.json
sample -- i used imagescript npm ... where it has .wasm file dependencies


"pkg": {  
    "scripts": [],
    "assets": [
      "node_modules/imagescript/wasm/any/font.wasm",
      "node_modules/imagescript/wasm/any/gif.wasm",
      "node_modules/imagescript/wasm/any/jpeg.wasm",
      "node_modules/imagescript/wasm/any/png.wasm",
      "node_modules/imagescript/wasm/any/svg.wasm",
      "node_modules/imagescript/wasm/any/tiff.wasm"
    ],
    "targets": [      
      "node16-win-x64"
    ]
  }
