### ISSUE TITLE
Node 10.17 broken binary

### ISSUE THREAD

**Issue by kybarg** [vercel/pkg#798]
When building `win-x64` application on CircleCI `exe` file won't run. In logs it says that it `node.exe` has wrong `sha` sum
Seems like it dowloads ` fetched-v10.15.3-win-x64 `
**Tested**: pkg@4.4.0, pkg@4.3.4

**Update**
pkg@4.3.6 works

**Comment by Fadoli** [comment]
pkg 4.4.x branch uses a broken node patch for node10, workaround is going back to pkg 4.3.x (you'll have a node 10.4.1 version from pkg-fetch 2.5.x branch)

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
