### ISSUE TITLE
run the target binary in Ubuntu

### ISSUE THREAD

**Issue by hkbluesky** [vercel/pkg#799]
Hi, how do I run the complied linux in Ubuntu? I tried "./complied_binary". This does not work

**Comment by ViniciusFXavier** [comment]
Try `sudo ./complied_binary`!
I don't know why but for me the files that are generated to linux only work when using `sudo`

**Comment by BadmasterY** [comment]
@hkbluesky 
try it
```npm
chmod -x complied_binary
sudo ./complied_binary
```
