### ISSUE TITLE
can not run the  package!!!!

### ISSUE THREAD

**Issue by saikoux12** [vercel/pkg#800]
i found a problem.

when the code has 
a.js
```
const zzz = 'z';
const a = `[${zzz}]`;
console.log(a);
```
package.json 
```
{
  "name": "helloworld",
  "main": "a.js",
  "bin": "a.js",
  "dependencies": {
    
  }
}
```

i can package this .
but when i run the helloworld.
it just quit.
if you change '[' or ']' to anther chat,it can work.
by the way, the problem is cause in windows, in linux ,there is not a problem

**Comment by saikoux12** [comment]
by the way, the problem is cause in windows, in linux ,there is not a problem

**Comment by saikoux12** [comment]
in node js 10

**Comment by kybarg** [comment]
It sounds like issue I have #798

**Comment by Nashorn** [comment]
same issue in 4.4.9
