### ISSUE TITLE
node8-linux-armv7 fails

### ISSUE THREAD

**Issue by isabel-ordas** [vercel/pkg#809]
I am creating my binary by executing: 
pkg -t node8-linux-armv7 

and I get the following error 

> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v8.16.2-linux-armv7

what should I do?

**Comment by wuguzaliang** [comment]
Know-how:
How to fix this issue yourself?
1. find out one existed release for your platform from here https://github.com/zeit/pkg-fetch/releases.
 Eg: for your armv7 version: 
![图片](https://user-images.githubusercontent.com/17598406/70961586-34810580-20bd-11ea-8315-d1dc3fcdd71e.png)
2. you might select the version node8.16.0 or latest verison.
3. Assume you select node 8 , install node 8.16.0
4. run pkg -t node8.16.0-linux-armv7.
It will work.
Hope help you.
