### ISSUE TITLE
vue-quill-editor module: Error! Unexpected token (1:0)

### ISSUE THREAD

**Issue by goforward01** [vercel/pkg#81]
Testing with the vue wrapper of quill editor, while the vue-quill-editor contains a vue component in the require expression, so the **pkg** run out with the result below:
```
> Error! Unexpected token (1:0)
  /home/test/jzver/node_modules/vue-quill-editor/src/editor.vue
```
and the index.js file of the vue-quill-editor just like:
```
/**
 * Vue-Quill-Editor
 * @author Surmon.me
 */

window.Quill = require('quill/dist/quill.js')
var quillEditor = require('./editor.vue')
var VueQuillEditor = {
  Quill: Quill,
  quillEditor: quillEditor,
  install: function(Vue) {
    Vue.component('quill-editor', quillEditor)
  }
}

module.exports = VueQuillEditor
```
Does it just add the editor.vue file to assets of package.json could solve this problem? I tried but failed, maybe I was wrong about the way to use the assets in package.json file. Any suggestion would be appreciated, thx a lot.

**Comment by igorklopov** [comment]
Hi! Please post code of minimal example. I need to know how front-end javascript code gets compiled as back-end code into executable. And then i'll try to figure out how to avoid it.
