### ISSUE TITLE
Windows binary ICO replacement fails

### ISSUE THREAD

**Issue by tarkh** [vercel/pkg#812]
PKG 4.4.1, Node v12.13.1
After updating *.exe file iconset with Resource Hacker, getting error:
`Pkg: Error reading from file.`
I do keep same iconset size as original Node has (16, 32, 48, 64, 128, 256), but can't get it to work. Btw previous version works just fine with iconset swapped by Resource Hacker.
Thanx!

**Comment by tarkh** [comment]
Okay, I found workaround, not so conveniently, but it works: just change iconset of SOURCE file, that located in PKG cache folder (on Mac it is `~/.pkg-cache`). Then build your software.

**Comment by robertsLando** [comment]
@tarkh PR?

**Comment by robertsLando** [comment]
For linux we could create a `.desktop` file for it
