### ISSUE TITLE
Error reading file: [Error: ENOENT: no such file or directory, open './public/scheduledTimes.json'] {

### ISSUE THREAD

**Issue by mattehalen** [vercel/pkg#817]
So im getting this error:
`Error reading file: [Error: ENOENT: no such file or directory, open './public/scheduledTimes.json'] {
`

even when i have this in package.json:
```
"pkg": {
    "scripts": "build/**/*.js",
    "assets": [ "bin/**/*", "lib/**/*" , "public/**/*", "routes/**/*" ,"views/**/*" ]
  },
```
![Skärmavbild 2019-12-23 kl  10 37 59](https://user-images.githubusercontent.com/16779335/71349906-57edf980-2570-11ea-8180-b0447de72cb3.png)

how do i fix this?

**Comment by 313364973** [comment]
tanks too

**Comment by thomasdingemanse** [comment]
I'm having a similar issue. If I execute the packaged binary, I get the following error message:

```
ENOENT: no such file or directory, scandir 'D:\snapshot\my-app\server\plugins'
```

However, in the output generated by running pkg with the `--debug` flag, it seems like the directory was included in the snapshot:

```
> [debug] The directory files list was included (1 item)
  D:\Development\my-app\server\plugins
> [debug] Stat info of %1 is added to queue
  %1: D:\Development\my-app\server\plugins
> [debug] The file was included as bytecode (no sources)
  D:\Development\my-app\server\plugins\db.js
```

There is only a single file in this directory. It is loaded by [fastify-autoload](https://github.com/fastify/fastify-autoload), which takes a dir argument:

```
app.register(fastifyAutoLoad, {
  dir: path.join(__dirname, 'plugins'),
  options: Object.assign({}, options)
})
```

However, I don't think the issue is due to fastify or fastify-autoload, since I've also added the path to my `package.json` explicitly:

```
  "pkg": {
    "scripts": [ "./server/plugins/**/*.js", "./server/routes/**/*.js" ],
    "assets": [ "./client/dist/**/*" ]
  }
```

I'm using node **14.15.1** and pkg **4.4.9**. If I can help with any additional info or debugging steps, let me know!

**Comment by conquera99** [comment]
> I'm having a similar issue. If I execute the packaged binary, I get the following error message:
> 
> ```
> ENOENT: no such file or directory, scandir 'D:\snapshot\my-app\server\plugins'
> ```
> 
> However, in the output generated by running pkg with the `--debug` flag, it seems like the directory was included in the snapshot:
> 
> ```
> > [debug] The directory files list was included (1 item)
>   D:\Development\my-app\server\plugins
> > [debug] Stat info of %1 is added to queue
>   %1: D:\Development\my-app\server\plugins
> > [debug] The file was included as bytecode (no sources)
>   D:\Development\my-app\server\plugins\db.js
> ```
> 
> There is only a single file in this directory. It is loaded by [fastify-autoload](https://github.com/fastify/fastify-autoload), which takes a dir argument:
> 
> ```
> app.register(fastifyAutoLoad, {
>   dir: path.join(__dirname, 'plugins'),
>   options: Object.assign({}, options)
> })
> ```
> 
> However, I don't think the issue is due to fastify or fastify-autoload, since I've also added the path to my `package.json` explicitly:
> 
> ```
>   "pkg": {
>     "scripts": [ "./server/plugins/**/*.js", "./server/routes/**/*.js" ],
>     "assets": [ "./client/dist/**/*" ]
>   }
> ```
> 
> I'm using node **14.15.1** and pkg **4.4.9**. If I can help with any additional info or debugging steps, let me know!

hi, did you solve the issue?
