### ISSUE TITLE
Package for linux-arm7 didn't run on arm7 platform

### ISSUE THREAD

**Issue by j-suhas** [vercel/pkg#818]
I've created a package for a js file with targets set as _-t node8-linux-arm7._  But it gives the following error:-

module.js:487
    throw err;
    ^

Error: Cannot find module '/snapshot/filePath/filename.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1251:46)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1280:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3

**Comment by adonespitogo** [comment]
I am getting a strange behaviour with armv7 on orange pi zero. I can create an executable file successfully without warnings and errors, meaning all packages where successfully snapped shot.

But when I ran the package, it generates error `Cannot find module [some module]`. [Some module] is a dependency of one of my required packages. When I manually require the [some module] package, it will generate another error for other packages being not found.

To conclude, I have to manually require in my codes the sub dependencies of my project's depdencies in order for it to be added in the executable file.

Note that this does not happen in raspberry pi 3 model b and in my ubuntu pc. Only in orange pi zero.

**Comment by j-suhas** [comment]
I want to run the package on WebOS. Any help appreciated. Thank you.
