### ISSUE TITLE
Unable to create package for latest node version and arm7 architecture 

### ISSUE THREAD

**Issue by j-suhas** [vercel/pkg#819]
Trying to create a package for the latest node version for arm7 architecture (_current:_ node-v12.13.1-linux-armv7), throws _Error! 404 Not Found_ while fetching base Node.js binaries

I'm doing this process on a Linux machine: 16.04.1-Ubuntu x86_64

`$ pkg -t latest-linux-armv7 filename.js`

stack trace:
> pkg@4.4.2
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.13.1-linux-armv7 [                    ] 1%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.13.1-linux-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.13.1-linux-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.13.1-linux-armv7"}
> Building base binary from source:
  built-v12.13.1-linux-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'

**Comment by artemis15** [comment]
Well I also faced this issue.. I just reverted back to node v1. This is the latest version pkg supports according to below link:
[https://github.com/zeit/pkg-fetch/blob/master/patches/patches.json](
https://github.com/zeit/pkg-fetch/blob/master/patches/patches.json)

**Comment by rakemen** [comment]
no matter what version I downgrade to, pkg always takes the v12.13.1 and tries to build, am I missing something here?

**Comment by biancode** [comment]
It looks like pkg does not see built assets on ARM and try to fetch via HTTP per pkg call and that has a 404 and then it builds again and again from Git Source of node - pkg should see the built-v12.16.1-linux-armv7 and us it if it has no forceBuild option

https://github.com/zeit/pkg-fetch/issues/87

**Comment by biancode** [comment]
The build option steps over the call via HTTP and the 404, but the same compiling again.
