### ISSUE TITLE
Allow configuring outside of package.json

### ISSUE THREAD

**Issue by kiprasmel** [vercel/pkg#829]
I have a project where I want to create a few different executables. I'm unable to do this currently, because each one request a different "pkg" configuration inside "package.json".

I'd like to be able to either provided it through the CLI and/or through the `exec` module from `pkg` (hopefully both).

Thanks!

**Comment by sergiz** [comment]
You can use the --config option or provide a path to a file named *.config.json that has name, bin and pkg keys (looking like package.json).
You can read the source to find all the details.
