### ISSUE TITLE
javascript-obfuscator with pkg - dynamic require fails

### ISSUE THREAD

**Issue by eduardoewgo** [vercel/pkg#831]
I'm trying to use **javascript-obfuscator** within **pkg** and I'm stuck with a problem when obfuscating string literals.

Normally we have something like `const fs= require('fs');`, however when I obfuscate the code it changes for something like `const c = require(b('0x0'));` which then fails on pkg build for that module.. 

I tried having all my requires inside a `require.js` file, which then I include in the pkg scripts. In the `main.js` (the one being compiled into exec) I simply do a `const m = require('require')`, but it doesn't work very well - I'm probably doing something wrong here.

Anyway, any help is appreciated.

**Comment by cocoonyou** [comment]
@eduardoewgo its quite simple i use it on one of myne ill give u a config
`const fs = require('fs');
const JavaScriptObfuscator = require('javascript-obfuscator');

fs.readFile('./index.js','utf8',function(err,data){
    var obfuscationResult = JavaScriptObfuscator.obfuscate(
        `${data}`,
        {
            compact:true,
            controlFlowFlattening:false,controlFlowFlatteningThreshold:0.75
            ,deadCodeInjection:true,deadCodeInjectionThreshold:1,
            debugProtection:false,debugProtectionInterval:false,disableConsoleOutput:false,
            domainLock:[],
            identifierNamesGenerator:'hexadecimal',identifiersPrefix:'',
            inputFileName:'',
            log:false,
            renameGlobals:true,
            reservedNames:[],reservedStrings:[
                "node-machine-id",
                "fs",
                "request",
                "https",
                "console-title",
                "readline",
                "child_process",
                "readline.createInterface({input:process.stdin,output:process.stdout})","draftlog"
            ],
            rotateStringArray:true,seed:0,
            selfDefending:false,sourceMap:false,
            sourceMapBaseUrl:'',sourceMapFileName:'',sourceMapMode:'separate',
            stringArray:true,stringArrayEncoding:true,stringArrayThreshold:1,
            target:'node',
            transformObjectKeys:false,
            unicodeEscapeSequence:true
        }
    );
    fs.writeFile('obv.js', obfuscationResult.getObfuscatedCode(),(err) => {
        if (err) throw err;
    });
});`

Be sure to define reserved strings

**Comment by eduardoewgo** [comment]
@cocoonyou I used `fs` just as an example, I'm really using it to be honest.

The issue is more about "how can I _hide_ the modules I'm requiring".

Thanks though.

**Comment by cocoonyou** [comment]
simple answer u dont

**Comment by cocoonyou** [comment]
u can turn it into hex like \x55\x55 ect... but they can decode it XD

**Comment by tarkh** [comment]
@eduardoewgo well, actually you can hide your modules, but it's tricky way... Manually copy them from "node_modules" directory to, for example, "modules" directory. Change require paths in your main program.
Set PKG config to
```javascript
  "pkg": {
    "private": "true",
    "scripts": "modules/**/*.js"
  }
```
Keep in mind, that only *.js files in your modules directory will be compiled.

**Comment by BlackHacks** [comment]
I solved this is issue today for a company project. 
It's a bit hacky but gets the job done. 
Steps:
- Run Webpack without obfuscation (turned off via Environmental variable)
- Run a script that parses the JS file as text and extract all requires to an array.
- Write array to file (reserved.txt).
- Run Webpack a second time with Obfuscation while setting reservedStrings to JSON.parse(fs.readFileSync("reserved.txt")).
- Pkg resulting .js

**Comment by Baker68** [comment]
this worked for me (its not pretty): 
```typescript
const dynamicImport = (file: string): any => {
  const _module = eval("mo" + "d" + "ul" + "e");
  const content = _module["requ" + "ire"](file);
  return content.default ? content.default : content;
};
```
