### ISSUE TITLE
Swap file inside executable

### ISSUE THREAD

**Issue by elpaxel** [vercel/pkg#832]
**What would you like to be added**:
Some sort of swap file. When I pack my script, pkg will add 100mb of free space inside executable where I will be able to store "future" created files from my script.

**Why is this needed**:
Cause I want trully single executable without any assets even in the future :)

**Comment by vladiks** [comment]
If I understand correctly, you are asking for something which can not be done by something like pkg. There is no way of hiding newly created files inside your complied script... is that what you mean? This just compiles all your code and nodejs into one executable file, but when you create folders and files, it will be created inside the filesystem, next to your runtime file.
