### ISSUE TITLE
Is there any way that the binary uses the node_modules/ from the local file system instead of the snapshot/ folder?

### ISSUE THREAD

**Issue by csskevin** [vercel/pkg#833]
First of all, great project, it is awesome!

I am trying to dynamically install npm packages, because I am building an application which requires installing npm packages at runtime. For this I have used a npm package called [npmi](https://www.npmjs.com/package/npmi), which allows me to install npm packages programatically.
This library installs this packages for sure into the current directory within the`node_modules/` folder.

Due the pkg library copies the `node_modules/` folder at compiletime to `/snapshot`, installed packages at runtime won't be used by the binary, obviously. 

This furthermore brings to the question, if it is possible to tell the pkg library **not to copy** the `node_modules/` folder to `snapshot/` at **compiletime** and using the `node_modules/` folder from the current directory at **runtime**?

**Comment by tnhh00037** [comment]
Instead of `import { your-thing } from 'module-name'`
You can try `import { your-thing } from ' /absolute-path-to-project/node-modules/module-name'`
It will import directly from that path
