### ISSUE TITLE
Auto asset detection mess

### ISSUE THREAD

**Issue by sergiz** [vercel/pkg#842]
Auto asset detection is definitely a good idea, but currently it's pretty messy.

What I have found out so far:
1) It only works, if your variable name for "path" module is exactly "path" (all lower case letters). If you use "Path" or anything else, it won't work.

2) Whatever path.join refers to, will be included as an asset, even if it's a JS file and even, if you specifically define it as a script in package.json (path.join detection will override your "scripts").

I think it would be nice, if we can gather some ideas how to make this better. Currently, if you want to utilize this auto detection while also protecting your JS source code, you have to use "path.join" (in lowercase) when referring to your actual assets and "Path.join" (or anything except path in lowercase) to refer to your scripts (while also defining them in "scripts" in package.json).

**Comment by sergiz** [comment]
Not stale.

**Comment by robertsLando** [comment]
@sergiz PR?

**Comment by sergiz** [comment]
Honestly, I don't know how to improve this. It looks like that currently it searches for "path.join(..)", but if we wanted to implement my idea then it would need to check if the variable points to "path" module.

Maybe a better solution would be to document that the "path" module has to be referenced in "path" variable (typed exactly like this) and that everything it points to will be regarded as an asset (even if it's a JS file).
