### ISSUE TITLE
Question: where can I find a list of valid targets

### ISSUE THREAD

**Issue by TravelingTechGuy** [vercel/pkg#846]
I can't find pkg's changelog, so it's hard to know which Node versions are supported by pkg. 

Is there a way to either have a definitive list, that gets updated whenever a new version is added, or better yet: an API call that will show all supported targets?

**Comment by gigouni** [comment]
The README seems to answer to your question: https://github.com/zeit/pkg#targets

You'll find the same releases that the existing ones here: https://nodejs.org/en/download/releases/. Just respect the naming pattern `node${release}-${platform}-${arch}`

**Comment by TravelingTechGuy** [comment]
The README only explains how to specify a target. It does not (as far as I've seen) specify WHICH targets are supported. The amount of people who hit issues with Node 3 should be evidence of that.

The list of available releases you pointed to contains many releases that are actually not supported by pkg.

Again, either a changelog specifying which releases are supported, or a CLI command listing supported releases is needed, IMHO.

**Comment by allardy** [comment]
@TravelingTechGuy  I think you can refer to the patches file here to see which version are used: https://github.com/zeit/pkg-fetch/blob/master/patches/patches.json

**Comment by TravelingTechGuy** [comment]
@allardy Thanks, that does clearly show the supported version. Now, is there a way to include those in a changelog, or include a link to this file in the README?

Also, what is the process by which support for a new Node version is added? E.g I'm currently using v13.9.0. When will that be supported? What is required to add support for that? Can I help?

**Comment by allardy** [comment]
In the pkg-fetch repository, you have all the tools required to build the node binary from its source code, so the best I can tell is to clone it yourself and try building one of the existing version. 

It seems that there's only one patch to be executed for a specific version, so I guess you could just see what pkg is changing and try to do the same in the newest version.

I also guess the process is community-driven, so when someone takes the time to do it, it appears :)
