### ISSUE TITLE
Can I pkg without static folder?

### ISSUE THREAD

**Issue by lyw1991** [vercel/pkg#847]
Some uploaded images will be saved in my folder,but the static floder is read only. How can I save my uploaded files?

**Comment by sergiz** [comment]
Just save it normally to your drive. Make sure to not refer your path using __dirname since that points to the snapshot system.

**Comment by lyw1991** [comment]
Got it, thank you

**Comment by leerob** [comment]
Thank you for cleaning up issues @hipstersmoothie 🙏

**Comment by Benbinbin** [comment]
I use express-generator set up a node app, and use [multer](https://github.com/expressjs/multer) middleware to handle the file (images) upload. After `pkg` pack the code, it cannot access the static folder, refer to @jesec [answer](https://github.com/vercel/pkg/issues/1187#issuecomment-846840942). 

I replace the static folder path from `app.use(express.static(path.join(__dirname, 'public')));` to `app.use(express.static(path.join(process.cwd(), 'public')));` and it work. Maybe the `__dirname` cannot parse correctly.
