### ISSUE TITLE
Cannot compile nestjs

### ISSUE THREAD

**Issue by ShareQiu1994** [vercel/pkg#855]
pkg version 4.4.3
nest version 6.13.2 

Reproduce：
nest new pkg-test 
npm install

update packjson ：
```
"bin": "dist/main.js" 
  "scripts": {
   "pkg": "pkg . -t node12-win-x64 -o app --debug",
}
```
npm run build 
npm run pkg 

The compilation process has been in an infinite loop

**Comment by ShareQiu1994** [comment]
Minimum Repositories :
[https://github.com/ShareQiu1994/pkg-test.git](https://github.com/ShareQiu1994/pkg-test.git)

**Comment by zoe-icu** [comment]
hi,  the package.json should like this
  "bin": "dist/main.js",
  "pkg": {
    "scripts": "dist/**/*.js",
    "assets": "logs/**/*"
  }
 then run the command 

pkg . -t node12-win-x64 -o app --debug

**Comment by ricardovigatti** [comment]
Thank you @zoe-icu
