### ISSUE TITLE
Is it there a way to copy the files from Snapshot to local machine

### ISSUE THREAD

**Issue by J1G4RSH4H** [vercel/pkg#857]
Hi,

I am trying to copy the files from the running exe file created using pkg and i want few files from the snapshot of the pkg to be copied to local machine where the exe file is currently running.

Thanks.

**Comment by igorklopov** [comment]
Does `fs.copyFile` work?

**Comment by jigsshah** [comment]
I am using fs.copySync to copy the files and it does throws me the error 
Error: ENOENT: no such file or directory, open 'C:/snapshot/app/dist/config.json'

**Comment by jigsshah** [comment]
Hi,
Any suggestions ion the same ?

I am using fs.copySync to copy the files and it does throws me the error
Error: ENOENT: no such file or directory, open 'C:/snapshot/app/dist/config.json'

**Comment by jigsshah** [comment]
Hi, 
Could please provide me some guidance here ? 
I tried both fs.copySync and fs.copyFile but neither one works.
Thanks

**Comment by fujinxiang** [comment]
try to read from srcpath then write to destpath

**Comment by carlhaman** [comment]
I can confirm that @fujinxiang approach works. I bundled a binary file that my code needed later on, and it couldn't run from the snapshot file system, so it needed to be extracted to the "real" file system:

`let copy = fs.createReadStream(pathInSnapshotFileSystem).pipe(fs.createWriteStream(target), { end: true });
copy.on('close', () => {
//here the file writing is done and the file is avalible
}

`

**Comment by jigsshah** [comment]
Thanks @carlhaman  for the confirmation, I will surely give it a try and update the issue here.

**Comment by FinlayDaG33k** [comment]
Is there a way to do this for entire directories as well?

**Comment by jonathanasquier** [comment]
@carlhaman method works, using ncp works out of the box for coping folders @FinlayDaG33k, probably using the mechanism under the hood.

**Comment by FinlayDaG33k** [comment]
@jonathanasquier Yea, in the end I just used a `glob` and a `for` loop to extract all files (I want to minimize the amount of extra dependencies):
```js
// Get a list of all config files
const files: string[] = await globResources('**/*');

// Extract each of the config files
for(let file of files) {
      // Build our destination path
      let dest = path.resolve(file).replace(Data.getResourceDir(), Data.getProjectPath());

      // Copy the file from our resources to the destination
      await copy(file, dest);
    }
```
