### ISSUE TITLE
Packaged startup much slower than node when large node_modules is bundled?

### ISSUE THREAD

**Issue by cspotcode** [vercel/pkg#859]
I'm seeing that a `pkg`-bundled binary seems to start up much slower than the equivalent binary running from a traditional npm installation with `node_modules` directory on the filesystem.  Is there a reason for this?

My bundled binary is 100MB; I have a lot of `node_modules`.  With a traditional npm installation, this isn't a big deal because it doesn't mean we're loading all of that stuff from disk.  Many of those modules are lazy-loaded.

Does the bundled snapshot filesystem require extra parsing at startup?  Is the number of bundled files linearly related to startup time?

**Comment by seb-mtl** [comment]
@cspotcode Did you ever find a solution? I experience the same behaviour at the moment and I am trying to speed up the startup phase

**Comment by kanjieater** [comment]
I also seem to be experiencing this

**Comment by bruce-bjorklund-sophos** [comment]
Experiencing this on a pretty significant level. Anyone have any insights?
