### ISSUE TITLE
Can I use pkg's bundled executable file as node itself?

### ISSUE THREAD

**Issue by RogerKang** [vercel/pkg#864]
Assume I have a bundled file named as `bundleFile`. It should contains the whole nodejs runtime and other resources including node libraries、glob resources and so on.
And can I use it to run other script files? Like: (the input form is not proper but you know what I mean)
```bundleFile other.js```
Because bundleFile has the whole nodejs runtime, it should be possible technically. And I swear that I have seem this implementation on other tools.

**Comment by cspotcode** [comment]
Pretty sure you would need your .js code to handle this, for example, by parsing the argv array and executing the right `require()` statement.

**Comment by igorklopov** [comment]
You need to set `PKG_EXECPATH` env var to `PKG_INVOKE_NODEJS` when running bundled executable. For example `PKG_EXECPATH=PKG_INVOKE_NODEJS ./yourapp -p 42`

**Comment by RogerKang** [comment]
> PKG_INVOKE_NODEJS

It works, thanks!

**Comment by RogerKang** [comment]
> Pretty sure you would need your .js code to handle this, for example, by parsing the argv array and executing the right `require()` statement.

Thanks! It could be an option.
