### ISSUE TITLE
Pkg wants to fetch binaries for wrong OS

### ISSUE THREAD

**Issue by vladiks** [vercel/pkg#869]
I am trying to do cross-os build. Host pc is windows 10 64bit. Target is linux arm64.

By calling `pkg index.js -t node12.13.1-linux-arm64`
Result is:
> pkg@4.4.4
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.13.1-win-arm64   [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.13.1-win-arm64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.13.1-win-arm64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.13.1-win-arm64"}
> Building base binary from source:
  built-v12.13.1-win-arm64
> Error! Not able to build for 'arm64' here, only for 'x64'

The fact that it tries to fetch and download file with win in its name looks like a bug to me? https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.13.1-win-arm64 
Maybe it should be
https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.13.1-linux-arm64 ?

**Comment by vladiks** [comment]
By digging deeper - it seems that fabricator object needs the same binaries for host OS thus the win it filename., Those binaries are not available for win / arm64 and host platform win x64 can not build arm64 binaries, so it looks like I will need to compile my builds on target arm64 machine?

**Comment by robertsLando** [comment]
@vladiks https://github.com/robertsLando/pkg-binaries
