### ISSUE TITLE
Is there a way to change the process name of the .exe?

### ISSUE THREAD

**Issue by BryanEnid** [vercel/pkg#872]
There are processes in the task manager with the same name and description as the compiled result: "Node.js: Server-side JavaScript". Is there a way to change the description to identify which one is the final program?

**Comment by animaonline** [comment]
Any updates?

**Comment by Alex-Mann** [comment]
Also interested in this. Does anyone know if the name is set in pkg or is it an artifact of using Node?

**Comment by Alex-Mann** [comment]
It seems that this gets set either in this [file](https://github.com/nodejs/node/blob/8b4af64f50c5e41ce0155716f294c24ccdecad03/src/res/node.rc#L55) or this [file](https://github.com/nodejs/node/blob/242bfb6bfc21d571ac5eb14b3c7db1ac9bcb9ee8/doc/node.1#L33) on the NodeJS side.

**Comment by chrisamin** [comment]
I would also be interested to know if there's a way to achieve this. With nexe I could just set process.title to a name of my choice (on Linux), but for some reason the same thing doesn't work with pkg.

**Comment by BryanEnid** [comment]
No luck yet

**Comment by LaurentGoderre** [comment]
I got some success by using `process.title = "My Title"`. It renames the process and it works in the CLI but it still displays in Windows under a NodeJS process group.

**Comment by dotob** [comment]
this would still be a thing to have...

**Comment by dabo248** [comment]
I'm using Resource Hacker as a workaround for Windows to change the process name: http://www.angusj.com/resourcehacker/

`
...
VALUE "FileDescription", "My Process Name"
...
`

**Comment by KvelaGorrrrnio** [comment]
Any updates?

**Comment by Slapbox** [comment]
Is there still no way to do this and no plan?

It's not great in Task Manager to see the NodeJS icon for the process, and even worse to see the description as just, "Node.js: Server-side JavaScript."
