### ISSUE TITLE
promisified exec and execFile should return a promise with ChildProcess instance attached

### ISSUE THREAD

**Issue by onip** [vercel/pkg#881]
as per [documentation](https://nodejs.org/dist/latest-v12.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) `require('child_process').exec` and `require('child_process').execFile` should return a promise with the `require('child_process').ChildProcess` instance attached to the `.child` property.

**Comment by leerob** [comment]
https://github.com/vercel/pkg/pull/880
