### ISSUE TITLE
Unable to run the generated outside of the project root folder

### ISSUE THREAD

**Issue by ssh24** [vercel/pkg#884]
### Description

If I package my node application into an executable and run the executable within the project root folder, it works fine. If I move the executable to another directory, it fails to start with the following error:
```
 sakib@ibm.com  ~/workspace/executables   master ●  ./ad-services 
 sakib@ibm.com  ~/workspace/executables   master ●  npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/sakib@ibm.com/workspace/executables/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/sakib/workspace/executables/package.json'
```
Any idea why this might be happening and how can I run the executable in a different folder?

**Comment by sergiz** [comment]
Your script wants to open package.json at some point, but you didn't explicitly include it i n your pkg config.

**Comment by ssh24** [comment]
How do I explictly include `package.json` in my pkg config? This is what I have so far in my package.json
```
  "bin": "dist/index.js",
  "pkg": {
    "source": ["dist/src/**/*.js"],
    "assets": ["package.json"]
  },
  "scripts": {
    "build": "tsc",
    "pkg": "npm run build && pkg package.json -t host --out-dir executables"
  }
```

**Comment by sergiz** [comment]
Then you do not propertly refer to the snapshot filesystem. Make sure that you path to the package.json is starting with the __dirname in your script.

**Comment by sergiz** [comment]
Then you do not propertly refer to the snapshot filesystem. Make sure that your path to the package.json is starting with the __dirname in your script.

**Comment by sergiz** [comment]
The script that threw an error which is shown in the first post.
