### ISSUE TITLE
Not included into executable at compilation stage. Please recompile adding it as asset or script.

### ISSUE THREAD

**Issue by karl0ss** [vercel/pkg#893]
Not too sure on this one, My package.json includes as shown -

 ```
  "pkg": {
    "scripts": [
    ],
    "assets": [
      "node_modules/figlet/**/*.*",
      "node_modules/figlet/fonts/Standard.flf"
    ]
  }
```
This is displayed when I try to run app-win.exe
```
(node:28040) UnhandledPromiseRejectionWarning: Error: File 'C:\**\MiWatchKleaner2.0\node_modules\figlet\fonts\Standard.flf' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:426:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:654:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:698:18)
    at Function.loadFontSync (C:\snapshot\MiWatchKleaner2.0\node_modules\figlet\lib\node-figlet.js:48:23)
    at Function.textSync (C:\snapshot\MiWatchKleaner2.0\node_modules\figlet\lib\figlet.js:732:43)
    at Object.header (C:\snapshot\MiWatchKleaner2.0\lib\common.js)
    at Object.mainMenu (C:\snapshot\MiWatchKleaner2.0\pages\pages.js)
    at Object.<anonymous> (C:\snapshot\MiWatchKleaner2.0\app.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
(node:28040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by perminoveugenehuawei** [comment]
Almsot the same issue for me. Proto files do not includes in build, but I defined them into assets

**Comment by karl0ss** [comment]
I seemed to fix this by specifying the file explicitly that I neeed...

```
 "pkg": {
    "scripts": [],
    "assets": [
      "node_modules/figlet/fonts/Standard.flf",
      "data/xiaomiPackageRemovalList.json"
    ],
    "targets": [
      "node12-linux-x64",
      "node12-macos-x64",
      "node12-win-x86"
    ]
  }
```

**Comment by lili2311** [comment]
👋 I am also having issues.

I tried every which way to include it:
- full relative path
- with a glob pattern

What else is needed? This seems to work fine in other repos I have that use this but not this time.

## package.json
```
  "pkg": {
    "scripts": [
      "dist/**/*.js"
    ],
    "assets": [
      "src/lib/generate-report/templates/*.hbs"
    ]
  }
```

## Command
After running `pkg .` I get the error 

## Error
```
generate-report/templates/licenses-view.hbs' was not included into executable at compilation stage. Please recompile adding it as asset or script.
```
## Version
pkg@4.4.9

**Comment by JaosnHsieh** [comment]
> I seemed to fix this by specifying the file explicitly that I neeed...
> 
> ```
>  "pkg": {
>     "scripts": [],
>     "assets": [
>       "node_modules/figlet/fonts/Standard.flf",
>       "data/xiaomiPackageRemovalList.json"
>     ],
>     "targets": [
>       "node12-linux-x64",
>       "node12-macos-x64",
>       "node12-win-x86"
>     ]
>   }
> ```

this works after i added to `package.json`

```
"pkg": {
    "scripts": [],
    "assets": [
      "node_modules/figlet/fonts/Ghost.flf"
    ],
    "targets": [
      "node12-macos-x64"
    ]
  }
```

and build with `pkg .`

**Comment by taylorjdawson** [comment]
I get `Not more than one entry file/directory is expected` when I run with `pkg .` but currently my assets are not getting included. Full cmd:
```
pkg . -t node12-alpine-x64 --output app index.js
``` 
@karl0ss what command did you run with?

**Comment by halmos** [comment]
I wasn't able to get any solution involving the config `assets` setting to work on its own. However, I found that using the `path.join()` method, as described at https://github.com/vercel/pkg#detecting-assets-in-source-code, forced pkg to include the asset into the build. 

As a workaround, by insuring that any required assets were included in a `path.join()` call, I was able to resolve the error.

**Comment by omarabdula** [comment]
Hello any help????

D:\nc\api-faturacao\build>index.exe
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: File 'C:\**\api-faturacao\node_modules\@foliojs-fork\linebreak\src\classes.trie' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
    at Object.<anonymous> (C:\snapshot\api-faturacao\node_modules\@foliojs-fork\linebreak\src\linebreaker.js:7:36)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31) {
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\snapshot\\api-faturacao\\node_modules\\@foliojs-fork\\linebreak\\src/classes.trie',
  pkg: true
}

**Comment by JoaoAntonioCarvalho** [comment]
> I wasn't able to get any solution involving the config `assets` setting to work on its own. However, I found that using the `path.join()` method, as described at https://github.com/vercel/pkg#detecting-assets-in-source-code, forced pkg to include the asset into the build.
> 
> As a workaround, by insuring that any required assets were included in a `path.join()` call, I was able to resolve the error.

This work for me as well!
