### ISSUE TITLE
Can PKG support module-alias?

### ISSUE THREAD

**Issue by fengcms** [vercel/pkg#896]
Test project file tree:
```
├── config
│   └── index.js
└── index.js
```
Code of index.js
```js
require('module-alias/register')
const { A, B } = require(':config')
console.log(A, B)
```
Code of config/index.js
```js
module.exports = {
  A: 1,
  B: 2
}
```
Config in package.json
```json
  "_moduleAliases": {
    ":config": "config"
  }
```
-----
It's work in nodejs, print this:
```bash
$ node index.js
1 2
```
but, if I run this `pkg index.js`, print this:
```
$ pkg index.js
> pkg@4.4.8
> Targets not specified. Assuming:
  node10-linux-x64, node10-macos-x64, node10-win-x64
> Warning Cannot find module ':config' from '/Users/fungleo/Sites/Github/npm-test'
  %1: /Users/fungleo/Sites/Github/npm-test/index.js
```
so.... I want cry...some one help me?

**Comment by darrensapalo** [comment]
This issue has been a [feature request since 2017](https://github.com/vercel/pkg/issues/249).

**Comment by uxin603s** [comment]
don't use package.json
use addAlias to setting
https://www.npmjs.com/package/module-alias#advanced-usage
