### ISSUE TITLE
pkg not available for ppc64le

### ISSUE THREAD

**Issue by madscientist159** [vercel/pkg#898]
pkg should support the OpenPOWER (ppc64le) architecture, which is increasingly used in server, desktop and even embedded applications.

**Comment by madscientist159** [comment]
It should be enough to fix pkg-fetch (https://github.com/zeit/pkg-fetch/issues/90) in the short term, but a ppc64le binary would also be nice to have.

**Comment by igorklopov** [comment]
@madscientist159 do you have an advice to setup ppc64le host without having the hardware? qemu?

**Comment by madscientist159** [comment]
@igorklopov Yes, qemu works fine:

`qemu-system-ppc64 -machine pseries -cpu power9 -nodefaults -nographic -serial stdio`

Note this can be painfully slow -- if you need to do any significant work on POWER you can get a small VPS over at https://www.integricloud.com , otherwise if there's a desire to have actual CI / ppc64le builds there is a possibility we could provide free access to a dedicated VM for that work.
