### ISSUE TITLE
`./dist/index.js` can't find node_module linked via yarn workspaces

### ISSUE THREAD

**Issue by geoyws** [vercel/pkg#899]
I've also tried:

```
  "pkg": {
    "targets": [
      "node12"
    ],
    "scripts": [
      "./node_modules/core--node/dist/**/*.js",
      "./node_modules/core--tooling/dist/**/*.js"
    ]
  },
```
and

```
  "pkg": {
    "targets": [
      "node12"
    ],
    "scripts": [
      "../../node_modules/core--node/dist/**/*.js",
      "../../node_modules/core--tooling/dist/**/*.js"
    ]
  },
```

but it doesn't work. Can anyone help? I'm running TypeScript, hence everything is compiled to `./dist`.

**Comment by Daniel-Olivier** [comment]
Which node_module specifically is it unable to find? Also can you please include the code that has the require/import statement attempting to load that module?

**Comment by hipstersmoothie** [comment]
No reproduction repo. If the issue persists feel free to open a new issue with a reproduction repo!
