### ISSUE TITLE
show  Linux command line window when run compiled node.js app

### ISSUE THREAD

**Issue by jomart-1985** [vercel/pkg#900]
hi i have this simple express js app after i  build using pkg  the window version it shows command line view when run the app which is nice i can turn off the app by closing the cmd window but in linux is run the app silently will run and no terminal view there , so my question how to enable Linux command line window when run the excusable file generated from pkg

**Comment by AndoGhevian** [comment]
Maybe this can help you - [OpenTerm](https://www.npmjs.com/package/open-term).
