### ISSUE TITLE
tesseract.js 2.1.1 failed to run with pkg

### ISSUE THREAD

**Issue by yassinevic** [vercel/pkg#903]
Hello 
When compiling with tesseract.js 2.1.1 pkg return with the bellow error:
I include the minumin project to reproduce the bug.

internal/modules/cjs/loader.js:983
  throw err;
  ^
Error: Cannot find module 'C:\Users\Yassine\Downloads\tesseractjs-pkg-master\--debug-port=9230'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

[index.js]
var path = require('path');
var Tesseract = require('tesseract.js');
var image = path.resolve(__dirname, 'hello.jpg');

Tesseract.recognize(image)
.then(data => {
	console.log('then\n', data)
})
.catch(err => {
  console.log('catch\n', err);
})
.finally(e => {
  console.log('finally\n');
});

[package.json]
{
  "name": "tesseract-pkg",
  "version": "1.0.0",
  "description": "Test application",
  "main": "index.js",
  "bin": "index.js",
  "scripts": {
    "start": "node .",
    "pkg": "pkg index.js --targets host",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tesseract.js": "^2.1.1"
  },
  "devDependencies": {},
  "pkg":{
    "targets": ["host"]
    }
}

**Comment by myishay** [comment]
I'm experiencing the same issue...

**Comment by robotic1** [comment]
I'm experiencing the same issue...

**Comment by marutichintan** [comment]
I am also facing Same Issue.

**Comment by talha0324** [comment]
is there any workaround for this?

**Comment by sRect** [comment]
how to solve

**Comment by hipstersmoothie** [comment]
No reproduction repo. If the issue persists feel free to open a new issue with a reproduction repo!

**Comment by MacroChip** [comment]
I have opened https://github.com/vercel/pkg/issues/1188 which has a reproduction repo link
