### ISSUE TITLE
child_process.fork with execArgv '--max-old-space-size' fail

### ISSUE THREAD

**Issue by RogerKang** [vercel/pkg#909]
test.js:
```
const cp = require('child_process');
cp.fork('./forkChild.js', [], {
  execArgv: ['--max-old-space-size=2048'],
});
```
forkChild.js:
```
console.log('print from child');
```
and pkg.json:
```
{
  "assets": ["forkChild.js"]
}
```

And build with pkg:
`pkg -t node12-macos-x64 -o test -c pkg.json test.js`
then run:
`./test`
Exception shown:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/xx/xx/pkgTest/--max-old-space-size=2048'
```

If we remove execArgv from test.js, it will be ok.
So I think this issue is caused by pkg's handling about child_process fork?

**Comment by perminoveugenehuawei** [comment]
Same issue. Any workarounds?

**Comment by perminoveugenehuawei** [comment]
I've found workaround - you can use worker_threads module and provide max old space size via resourceLimits option. https://nodejs.org/dist/latest-v12.x/docs/api/worker_threads.html#worker_threads_worker_resourcelimits
