### ISSUE TITLE
puppeteer-extra-stealth-plugin support?

### ISSUE THREAD

**Issue by EdwinJ0124** [vercel/pkg#910]
recently tried to run pkg with puppeteer stealth plugin however its just giving me the error with "A plugin listed 'puppeteer-extra-plugin-stealth/evasions/chrome.runtime' as dependency,
          which is currently missing. Please install it:"

**Comment by Dam998** [comment]
I fix this by importing the plugin that stealth reference 1 by 1 (they are 11)
Or you can change tool to create exe, nexe doesn't give this error

**Comment by DimitriCunev** [comment]
add this into your package.json
```
  "pkg": {
    "assets": "node_modules/puppeteer-extra-plugin-stealth/**/*.*"
  }
```

**Comment by Dam998** [comment]
Right @DimitriCunev 
I didn't try it but it can work

However in the end I changed from pkg to nexe because pkg have problem with some es6 syntax and I have always to use await eval(`es6 function`) and I don't like it

**Comment by apriady** [comment]
> I fix this by importing the plugins that stealth are referencing 1 by 1 (they are 11)
> Or you can change tool to create exe, nexe doesn't give this error

Hi, can you share how you import it?

**Comment by saveroo** [comment]
I have this problem as well but for serverless. 

> 2020-09-25T17:14:00.362Z	80e39902-c590-4d9d-aa95-a6350f029074	WARN	
>           A plugin listed 'puppeteer-extra-plugin-stealth/evasions/chrome.app' as dependency,
>           which is currently missing. Please install it:
>           yarn add puppeteer-extra-plugin-stealth
>           Note: You don't need to require the plugin yourself,
>           unless you want to modify it's default settings.
> 2020-09-25T17:14:00.364Z	80e39902-c590-4d9d-aa95-a6350f029074	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.app'\nRequire stack:\n- /var/task/node_modules/puppeteer-extra/dist/index.cjs.js\n- /var/task/libbitch/crap.js\n- /var/task/api/index.js\n- /var/task/___now_launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","reason":{"errorType":"Error","errorMessage":"Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.app'\nRequire stack:\n- /var/task/node_modules/puppeteer-extra/dist/index.cjs.js\n- /var/task/libbitch/crap.js\n- /var/task/api/index.js\n- /var/task/___now_launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","code":"MODULE_NOT_FOUND","requireStack":["/var/task/node_modules/puppeteer-extra/dist/index.cjs.js","/var/task/libbitch/crap.js","/var/task/api/index.js","/var/task/___now_launcher.js","/var/runtime/UserFunction.js","/var/runtime/index.js"],"stack":["Error: Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.app'","Require stack:","- /var/task/node_modules/puppeteer-extra/dist/index.cjs.js","- /var/task/libbitch/crap.js","- /var/task/api/index.js","- /var/task/___now_launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)","    at Function.Module._load (internal/modules/cjs/loader.js:841:27)","    at Module.require (internal/modules/cjs/loader.js:1025:19)","    at require (internal/modules/cjs/helpers.js:72:18)","    at PuppeteerExtra.resolvePluginDependencies (/var/task/node_modules/puppeteer-extra/dist/index.cjs.js:300:23)","    at PuppeteerExtra.launch (/var/task/node_modules/puppeteer-extra/dist/index.cjs.js:118:14)","    at hibp (/var/task/libbitch/crap.js:20:37)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async module.exports (/var/task/api/index.js:5:21)","    at async Server.<anonymous> (/var/task/___now_helpers.js:813:13)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.app'","Require stack:","- /var/task/node_modules/puppeteer-extra/dist/index.cjs.js","- /var/task/libbitch/crap.js","- /var/task/api/index.js","- /var/task/___now_launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
> Unknown application error occurred

**Comment by l10r** [comment]
> "assets": "node_modules/puppeteer-extra-plugin-stealth/**/*.*"

Thank you soo much

**Comment by mewforest** [comment]
> > "assets": "node_modules/puppeteer-extra-plugin-stealth/**/_._"
> 
> Thank you soo much

It doesn't work for me :(

**Comment by hipstersmoothie** [comment]
No reproduction repo. If the issue persists feel free to open a new issue with a reproduction repo!

**Comment by 4passenger** [comment]
This doesnt work for me , can anyone please help me with it ?

**Comment by dracoDevs** [comment]
None of the above solutions have worked for me.

**Comment by DimitriCunev** [comment]
> None of the above solutions have worked for me.



> This doesnt work for me , can anyone please help me with it ?

In the worst case scenario, you can include the whole node_modules into pkg, which is not good but should work.

```
"pkg": {
    "assets": "node_modules/**/*.*"
  }
```
I suppose you're doing something really wrong if it doesn't work for you.

**Comment by renandecarlo** [comment]
@DimitriCunev ended up being the only solution that worked for me

**Comment by olivertilk** [comment]
I had this issue and what worked for me was manually importing each of the missing packages mentioned in the errors:
```
require('puppeteer-extra-plugin-stealth/evasions/chrome.app');
require('puppeteer-extra-plugin-stealth/evasions/chrome.csi');
require('puppeteer-extra-plugin-stealth/evasions/chrome.loadTimes');
require('puppeteer-extra-plugin-stealth/evasions/chrome.runtime');
require('puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow');
require('puppeteer-extra-plugin-stealth/evasions/media.codecs');
require('puppeteer-extra-plugin-stealth/evasions/navigator.hardwareConcurrency');
require('puppeteer-extra-plugin-stealth/evasions/navigator.languages');
require('puppeteer-extra-plugin-stealth/evasions/navigator.permissions');
require('puppeteer-extra-plugin-stealth/evasions/navigator.plugins');
require('puppeteer-extra-plugin-stealth/evasions/navigator.vendor');
require('puppeteer-extra-plugin-stealth/evasions/navigator.webdriver');
require('puppeteer-extra-plugin-stealth/evasions/sourceurl');
require('puppeteer-extra-plugin-stealth/evasions/user-agent-override');
require('puppeteer-extra-plugin-stealth/evasions/webgl.vendor');
require('puppeteer-extra-plugin-stealth/evasions/window.outerdimensions');
```

**Comment by mewforest** [comment]
> No reproduction repo. If the issue persists feel free to open a new issue with a reproduction repo!

**I've made a reproduction repo with this bug:**
- https://github.com/mewforest/puppeteer-stealth-demo

Be note: all methods above aren't being a solution for this issue.

**Comment by IcyFrogs** [comment]
Any updates? None of the solutions worked for me

**Comment by kevinfengcs88** [comment]
I've tried all of the solutions above; some of them even lead to other errors that I wasn't able to resolve with stackoverflow/github posts

**Comment by IvanovskyOrtega** [comment]
@olivertilk solution works with @mewforest's code and worked for me. Just place the mentioned imports before the StealthPlugin import as follows:

```javascript
const puppeteer = require('puppeteer-extra')

// Add the Imports before StealthPlugin
require('puppeteer-extra-plugin-stealth/evasions/chrome.app')
require('puppeteer-extra-plugin-stealth/evasions/chrome.csi')
require('puppeteer-extra-plugin-stealth/evasions/chrome.loadTimes')
require('puppeteer-extra-plugin-stealth/evasions/chrome.runtime')
require('puppeteer-extra-plugin-stealth/evasions/defaultArgs') // pkg warned me this one was missing
require('puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow')
require('puppeteer-extra-plugin-stealth/evasions/media.codecs')
require('puppeteer-extra-plugin-stealth/evasions/navigator.hardwareConcurrency')
require('puppeteer-extra-plugin-stealth/evasions/navigator.languages')
require('puppeteer-extra-plugin-stealth/evasions/navigator.permissions')
require('puppeteer-extra-plugin-stealth/evasions/navigator.plugins')
require('puppeteer-extra-plugin-stealth/evasions/navigator.vendor')
require('puppeteer-extra-plugin-stealth/evasions/navigator.webdriver')
require('puppeteer-extra-plugin-stealth/evasions/sourceurl')
require('puppeteer-extra-plugin-stealth/evasions/user-agent-override')
require('puppeteer-extra-plugin-stealth/evasions/webgl.vendor')
require('puppeteer-extra-plugin-stealth/evasions/window.outerdimensions')


// Now you can import the StealthPlugin :D
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
// The rest of your code here :)
```

**Comment by yunlianwangluo** [comment]
> I had this issue and what worked for me was manually importing each of the missing packages mentioned in the errors:
> 
> ```
> require('puppeteer-extra-plugin-stealth/evasions/chrome.app');
> require('puppeteer-extra-plugin-stealth/evasions/chrome.csi');
> require('puppeteer-extra-plugin-stealth/evasions/chrome.loadTimes');
> require('puppeteer-extra-plugin-stealth/evasions/chrome.runtime');
> require('puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow');
> require('puppeteer-extra-plugin-stealth/evasions/media.codecs');
> require('puppeteer-extra-plugin-stealth/evasions/navigator.hardwareConcurrency');
> require('puppeteer-extra-plugin-stealth/evasions/navigator.languages');
> require('puppeteer-extra-plugin-stealth/evasions/navigator.permissions');
> require('puppeteer-extra-plugin-stealth/evasions/navigator.plugins');
> require('puppeteer-extra-plugin-stealth/evasions/navigator.vendor');
> require('puppeteer-extra-plugin-stealth/evasions/navigator.webdriver');
> require('puppeteer-extra-plugin-stealth/evasions/sourceurl');
> require('puppeteer-extra-plugin-stealth/evasions/user-agent-override');
> require('puppeteer-extra-plugin-stealth/evasions/webgl.vendor');
> require('puppeteer-extra-plugin-stealth/evasions/window.outerdimensions');
> ```

this solution works for me...

**Comment by aditodkar** [comment]
Did not work for me.
Code:
```
const chromium = require('chrome-aws-lambda');
const puppeteer = require('puppeteer-extra')

require('puppeteer-extra-plugin-stealth/evasions/chrome.app');
require('puppeteer-extra-plugin-stealth/evasions/chrome.csi');
require('puppeteer-extra-plugin-stealth/evasions/chrome.loadTimes');
require('puppeteer-extra-plugin-stealth/evasions/chrome.runtime');
require('puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow');
require('puppeteer-extra-plugin-stealth/evasions/media.codecs');
require('puppeteer-extra-plugin-stealth/evasions/navigator.hardwareConcurrency');
require('puppeteer-extra-plugin-stealth/evasions/navigator.languages');
require('puppeteer-extra-plugin-stealth/evasions/navigator.permissions');
require('puppeteer-extra-plugin-stealth/evasions/navigator.plugins');
require('puppeteer-extra-plugin-stealth/evasions/navigator.vendor');
require('puppeteer-extra-plugin-stealth/evasions/navigator.webdriver');
require('puppeteer-extra-plugin-stealth/evasions/sourceurl');
require('puppeteer-extra-plugin-stealth/evasions/user-agent-override');
require('puppeteer-extra-plugin-stealth/evasions/webgl.vendor');
require('puppeteer-extra-plugin-stealth/evasions/window.outerdimensions');

const StealthPlugin = require("puppeteer-extra-plugin-stealth");
puppeteer.use(StealthPlugin());


const browser = await puppeteer.launch({
                args: chromium.args,
                defaultViewport: chromium.defaultViewport,
                executablePath: await chromium.executablePath,
                headless: chromium.headless
            });
```

**Comment by aditodkar** [comment]
This solution worked for me:

```
const chromium = require('chrome-aws-lambda');
const { addExtra } = require('puppeteer-extra')
const puppeteerExtra = addExtra(chromium.puppeteer)

require('puppeteer-extra-plugin-stealth/evasions/chrome.app');
require('puppeteer-extra-plugin-stealth/evasions/chrome.csi');
require('puppeteer-extra-plugin-stealth/evasions/chrome.loadTimes');
require('puppeteer-extra-plugin-stealth/evasions/chrome.runtime');
require('puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow');
require('puppeteer-extra-plugin-stealth/evasions/media.codecs');
require('puppeteer-extra-plugin-stealth/evasions/navigator.hardwareConcurrency');
require('puppeteer-extra-plugin-stealth/evasions/navigator.languages');
require('puppeteer-extra-plugin-stealth/evasions/navigator.permissions');
require('puppeteer-extra-plugin-stealth/evasions/navigator.plugins');
require('puppeteer-extra-plugin-stealth/evasions/navigator.vendor');
require('puppeteer-extra-plugin-stealth/evasions/navigator.webdriver');
require('puppeteer-extra-plugin-stealth/evasions/sourceurl');
require('puppeteer-extra-plugin-stealth/evasions/user-agent-override');
require('puppeteer-extra-plugin-stealth/evasions/webgl.vendor');
require('puppeteer-extra-plugin-stealth/evasions/window.outerdimensions');
require('puppeteer-extra-plugin-stealth/evasions/defaultArgs');
require('puppeteer-extra-plugin-user-preferences');
require('puppeteer-extra-plugin-user-data-dir');

const StealthPlugin = require("puppeteer-extra-plugin-stealth");
puppeteerExtra.use(StealthPlugin());
```

package.json: 
```
 "engines": {
    "node": "^14"
  },
  "dependencies": {
    "chrome-aws-lambda": "^10.1.0",
    "puppeteer-core": "^10.4.0",
    "puppeteer-extra": "^3.3.4",
    "puppeteer-extra-plugin-stealth": "^2.11.1",
    "puppeteer-extra-plugin-user-data-dir": "^2.4.0",
    "puppeteer-extra-plugin-user-preferences": "^2.4.0"
  }
```

**Comment by RoHanh96** [comment]
> I have this problem as well but for serverless.
> 
> > 2020-09-25T17:14:00.362Z	80e39902-c590-4d9d-aa95-a6350f029074	WARN
> > A plugin listed 'puppeteer-extra-plugin-stealth/evasions/chrome.app' as dependency,
> > which is currently missing. Please install it:
> > yarn add puppeteer-extra-plugin-stealth
> > Note: You don't need to require the plugin yourself,
> > unless you want to modify it's default settings.
> > 2020-09-25T17:14:00.364Z	80e39902-c590-4d9d-aa95-a6350f029074	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.app'\nRequire stack:\n- /var/task/node_modules/puppeteer-extra/dist/index.cjs.js\n- /var/task/libbitch/crap.js\n- /var/task/api/index.js\n- /var/task/___now_launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","reason":{"errorType":"Error","errorMessage":"Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.app'\nRequire stack:\n- /var/task/node_modules/puppeteer-extra/dist/index.cjs.js\n- /var/task/libbitch/crap.js\n- /var/task/api/index.js\n- /var/task/___now_launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","code":"MODULE_NOT_FOUND","requireStack":["/var/task/node_modules/puppeteer-extra/dist/index.cjs.js","/var/task/libbitch/crap.js","/var/task/api/index.js","/var/task/___now_launcher.js","/var/runtime/UserFunction.js","/var/runtime/index.js"],"stack":["Error: Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.app'","Require stack:","- /var/task/node_modules/puppeteer-extra/dist/index.cjs.js","- /var/task/libbitch/crap.js","- /var/task/api/index.js","- /var/task/___now_launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)","    at Function.Module._load (internal/modules/cjs/loader.js:841:27)","    at Module.require (internal/modules/cjs/loader.js:1025:19)","    at require (internal/modules/cjs/helpers.js:72:18)","    at PuppeteerExtra.resolvePluginDependencies (/var/task/node_modules/puppeteer-extra/dist/index.cjs.js:300:23)","    at PuppeteerExtra.launch (/var/task/node_modules/puppeteer-extra/dist/index.cjs.js:118:14)","    at hibp (/var/task/libbitch/crap.js:20:37)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async module.exports (/var/task/api/index.js:5:21)","    at async Server. (/var/task/___now_helpers.js:813:13)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Cannot find module 'puppeteer-extra-plugin-stealth/evasions/chrome.app'","Require stack:","- /var/task/node_modules/puppeteer-extra/dist/index.cjs.js","- /var/task/libbitch/crap.js","- /var/task/api/index.js","- /var/task/___now_launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at process. (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
> > Unknown application error occurred

@saveroo 
Did you fix it?  I have same error

**Comment by RoHanh96** [comment]
> 

@yunlianwangluo 
Can you share your new Browser config?

**Comment by martin-dimi** [comment]
Same issue here...

**Comment by jeanhdev** [comment]
Any update ?
