### ISSUE TITLE
ref-napi native module prebuild

### ISSUE THREAD

**Issue by jkutianski** [vercel/pkg#912]
The [ref-napi module](https://github.com/node-ffi-napi/ref-napi) has prebuild native module.
When I run my code fails with this message (Yes I copied the .node on the same folder as exe).
This module is a subdependency of [active-win module](https://github.com/sindresorhus/active-win)

> (node:4824) UnhandledPromiseRejectionWarning: Error: No native build was found for platform=win32 arch=x64 runtime=node abi=72 uv=1 libc=glibc
    at Function.path (C:\snapshot\Nueva carpeta (4)\node_modules\node-gyp-build\index.js:56:9)
    at load (C:\snapshot\Nueva carpeta (4)\node_modules\node-gyp-build\index.js:21:30)    
    at Object.<anonymous> (C:\snapshot\Nueva carpeta (4)\node_modules\ref-napi\lib\ref.js:8:53)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18)

**Comment by Marksteinsong** [comment]
I have the same issue, do you fix it ?

**Comment by jkutianski** [comment]
> I have the same issue, do you fix it ?

Nope.

**Comment by Vlad-Apostolov** [comment]
I also hit the same problem.

**Comment by Vlad-Apostolov** [comment]
Ok, I figured it out. The .node files have to be in the same folder as the exe file, but they also need to be included in the package.json file. In my case I have 3 .node files:

  "pkg": {
      "assets": [
        "./public/**/*",
        "./libRtiProxy64.dll",
        "./node_modules/ffi-napi/prebuilds/win32-x64/node.napi.uv1.node",
        "./node_modules/ref/build/Release/binding.node",
        "./node_modules/ref-napi/prebuilds/win32-x64/node.napi.node"
      ]
  }

**Comment by jkutianski** [comment]
Doesn't work fo me.

**Comment by KSchala** [comment]
had the same problem, which was solved by adding the prebuilds to the assets in package.json
```
"assets": [
            "./node_modules/ffi-napi/prebuilds/**/*",
            "./node_modules/ffi-napi/node_modules/ref-napi/prebuilds/**/*",
            "./node_modules/ref-napi/prebuilds/**/*",
            "./node_modules/ref-wchar-napi/prebuilds/**/*",
            "./node_modules/ref-wchar-napi/node_modules/ref-napi/prebuilds/**/*"
]
```

**Comment by fishbone1** [comment]
@jkutianski I wonder why you expected this to work in October 2020 and how it could have worked for @Vlad-Apostolov as PR #837 has been merged in March 21. 

However I've had the same problem and resolved it by running `npx pkg .` instead of `npx pkg index.js`, otherwise the `assets` config in package.json won't be taken into account. You need an entry `"bin": "index.js"` in your package.json in order for this to work. And also be careful, because `npx pkg .` could produce a different binary file name. Mine was called `index-win.exe` first and later the name was inferred from package.json.

**Comment by jkutianski** [comment]
> @jkutianski I wonder why you expected this to work in October 2020 and how it could have worked for @Vlad-Apostolov as PR #837 has been merged in March 21.
> 
> However I've had the same problem and resolved it by running `npx pkg .` instead of `npx pkg index.js`, otherwise the `assets` config in package.json won't be taken into account. You need an entry `"bin": "index.js"` in your package.json in order for this to work. And also be careful, because `npx pkg .` could produce a different binary file name. Mine was called `index-win.exe` first and later the name was inferred from package.json.

Thank you very much I will try this.

**Comment by brandonros** [comment]
```
"assets": [
      "./node_modules/ffi-napi/**/*",
      "./node_modules/ref-napi/**/*"
    ],
```

this fixed it for me

**Comment by Faronsince2016** [comment]
Try to put "ref-napi" into “dependencies” instead of “devDependencies”
