### ISSUE TITLE
Can I read an apk file pkged in the snapshot file system with adb command?

### ISSUE THREAD

**Issue by cnyarx** [vercel/pkg#927]
I'm trying to package appium with pkg.
It can be launched after pkg, but get some error:

Error: Command '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s xxx install -g /snapshot/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' exited with code 1
[debug] [MJSONWP]     at ChildProcess.<anonymous> (/snapshot/appium/node_modules/teen_process/lib/exec.js:113:19)
[debug] [MJSONWP]     at ChildProcess.emit (events.js:311:20)
[debug] [MJSONWP]     at maybeClose (internal/child_process.js:1021:16)
[debug] [MJSONWP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

It seems the "adb" command can't read the "settings_apk-debug.apk" file in the snapshot.
Add -d option, and it shows all the .apk files have been packaged.

**Comment by rsmrahul1** [comment]
@cnyarx Me also facing the same problem? Got any solution ?
