### ISSUE TITLE
Can pkg exe can be opened?

### ISSUE THREAD

**Issue by flacohenao** [vercel/pkg#928]
After compiling and bundled all toghether using PKG i wonder is someone with enoguh tech knowledge can open my exe and see all my bundled files?

**Comment by marcj** [comment]
Yes

**Comment by flacohenao** [comment]
@marcj Any ideas how?

**Comment by marcj** [comment]
Yes, it's pretty easy. I won't write a how-to about that. Why do you ask?

**Comment by flacohenao** [comment]
Can you please contact me? danihenja@gmail.com?
