### ISSUE TITLE
Bug: Pkg does not create correct exe in docker

### ISSUE THREAD

**Issue by Barkole** [vercel/pkg#930]
I fail to build runnable binaries, if I run pkg on GitLab.com in a docker

I've <https://gitlab.com/Lepardo/simplewebspider-nodejs/-/blob/master/bin/build-pkg.sh> :

```sh
pkg . -t node12-linux-x64,node12-macos-x64,node12-win-x64,node12-alpine-x64 -o ./dist-binaries/sws "$@" --options --enable-source-maps
```

If I run it with `yarn build-pkg` on my local windows system. The exe file is running as expected.

In my gitlab build <https://gitlab.com/Lepardo/simplewebspider-nodejs/-/blob/master/.gitlab-ci.yml>

```yaml
image: "node:12-alpine"

Package:Pkg:
  script:
    - yarn global add pkg
    - yarn build-pkg -d
  artifacts:
    paths:
      - dist-binaries/
```

The exe file does start and end, but does not do anything.

The difference I see of the pkg debug output is
* only on my local machine I've the output
```txt
> [debug] Targets:
  [
  {
    "nodeRange": "node12",
    "platform": "linux",
    "arch": "x64",
    "output": "D://vscode//simplewebspider-nodejs//dist-binaries//sws-linux",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node12",
      "platform": "win",
      "arch": "x64",
      "forceBuild": false,
      "binaryPath": "C://Users//Mike//.pkg-cache//v2.6//fetched-v12.16.1-win-x64"
    },
    "binaryPath": "C://Users//Mike//.pkg-cache//v2.6//fetched-v12.16.1-linux-x64"
  },
  {
    "nodeRange": "node12",
    "platform": "macos",
    "arch": "x64",
    "output": "D://vscode//simplewebspider-nodejs//dist-binaries//sws-macos",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node12",
      "platform": "win",
      "arch": "x64",
      "forceBuild": false,
      "binaryPath": "C://Users//Mike//.pkg-cache//v2.6//fetched-v12.16.1-win-x64"
    },
    "binaryPath": "C://Users//Mike//.pkg-cache//v2.6//fetched-v12.16.1-macos-x64"
  },
  {
    "nodeRange": "node12",
    "platform": "win",
    "arch": "x64",
    "output": "D://vscode//simplewebspider-nodejs//dist-binaries//sws-win.exe",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node12",
      "platform": "win",
      "arch": "x64",
      "forceBuild": false,
      "binaryPath": "C://Users//Mike//.pkg-cache//v2.6//fetched-v12.16.1-win-x64"
    },
    "binaryPath": "C://Users//Mike//.pkg-cache//v2.6//fetched-v12.16.1-win-x64"
  },
  {
    "nodeRange": "node12",
    "platform": "alpine",
    "arch": "x64",
    "output": "D://vscode//simplewebspider-nodejs//dist-binaries//sws-alpine",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node12",
      "platform": "win",
      "arch": "x64",
      "forceBuild": false,
      "binaryPath": "C://Users//Mike//.pkg-cache//v2.6//fetched-v12.16.1-win-x64"
    },
    "binaryPath": "C://Users//Mike//.pkg-cache//v2.6//fetched-v12.16.1-alpine-x64"
  }
]
```
* And on my local machine, I get a log of 32.773 lines instead in my gitlab docker job of only 19.345

It looks like, that pkg just stops and fails, but no error and not error code

**Comment by Barkole** [comment]
Regarding the output it's only an GitLab issue, if I pipe the debug output into a file, everything is fine, also the mentioned last lines are there.

But still the exe is not working. I just get an empty output. As it would not start anything

**Comment by darrensapalo** [comment]
I also experience the same thing. I was hoping to build the executables on an alpine docker image and downloading the built files (exe, etc) but it doesn't appear to be packaging everything necessary for the produced executable to run on its own (See: native add-ons, it might be related to your case). Even when I manually copied in the native add-ons, it still did not work (and also did not throw any error messages that I could pursue/investigate).

However, when I run the same build script on my local windows, the executable works. 

Getting an executable from a gitlab-container made executable does not work.

**Comment by TimP4w** [comment]
Having the same problem here. Any ideas on how to fix this?

**Comment by MichaelLeeHobbs** [comment]
This is not limited to gitlab. The same issue in BitBucket build pipelines which uses Docker containers.

**Comment by absalomedia** [comment]
Can rconfirm this issue in Bitbucket Pipelines
