### ISSUE TITLE
Using node option --inspect

### ISSUE THREAD

**Issue by azryelryvel** [vercel/pkg#932]
Hello!

From what i read, I understand that you removed debugging for security reasons, but is there a way to make it work anyway ? I read #93 and I don't think it's up to date anymore.

I ran a node:12.16.1 container and installed pkg locally in it.  In `node_modules/pkg-fetch/patches/node.v12.16.1.cpp.patch` , I removed the node_options.cc block which seemed to me to be the one blocking the use of inspect.
Then i used the local pkg to build the application :
`node node_modules/pkg/lib-es5/bin.js path/to/server.js --debug -b -t host --options inspect`
But I still get `/root/.pkg-cache/v2.6/built-v12.16.1-linux-x64: bad option: --inspect` during compilation.
I looked at the node_options.cc file in `/tmp/VpJIGdcFfQzWrlk73Sd2/node/src/node_options.cc` and i don't see the `return` I removed, so I guess my patch modification worked but it was not enough ?
Am i missing something to change in the patch ? https://github.com/vercel/pkg-fetch/blob/master/patches/node.v12.16.1.cpp.patch

Or maybe there is already a baked-in way to make it work ? Like NODE_OPTIONS or SIGUSR1 ?

**Comment by josiahbryan** [comment]
:+1: Curious, did you ever find a way to do this?

**Comment by jcyh0120** [comment]
need a way to debug my node application with pkg. Anyway possible ways?

**Comment by devmondo** [comment]
thanks a lot for the awesome work on pkg

yes please, it is really critical to debug applications.

we have tried what was mentioned and it does not even build on windows giving error
`Error! Error: spawn patch ENOENT`

and this is blocker for us

**Comment by hughobrien** [comment]
apt install patch
