### ISSUE TITLE
Warning Cannot include addon %1 into executable?

### ISSUE THREAD

**Issue by yyyyffqqqq** [vercel/pkg#935]
> pkg@4.4.8
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: /Users/fqy/Downloads/mediasoup-demo-3/server/node_modules/fsevents/build/Release/fse.node
  %2: path-to-executable/fse.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: /Users/fqy/Downloads/mediasoup-demo-3/server/node_modules/heapdump/build/Release/addon.node
  %2: path-to-executable/addon.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: /Users/fqy/Downloads/mediasoup-demo-3/server/node_modules/websocket/build/Release/bufferutil.node
  %2: path-to-executable/bufferutil.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: /Users/fqy/Downloads/mediasoup-demo-3/server/node_modules/websocket/build/Release/validation.node
  %2: path-to-executable/validation.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: /Users/fqy/Downloads/mediasoup-demo-3/server/node_modules/mediasoup/worker/deps/libuv/libuv/test/fixtures/load_error.node
  %2: path-to-executable/load_error.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: /Users/fqy/Downloads/mediasoup-demo-3/server/node_modules/heapdump/build/Release/addon.node
  %2: path-to-executable/addon.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: /Users/fqy/Downloads/mediasoup-demo-3/server/node_modules/websocket/build/Release/bufferutil.node
  %2: path-to-executable/bufferutil.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: /Users/fqy/Downloads/mediasoup-demo-3/server/node_modules/websocket/build/Release/validation.node
  %2: path-to-executable/validation.node

**Comment by lselden** [comment]
That warning means you need to copy those .node files to be in the same directory as your generated .exe file

**Comment by VandeurenGlenn** [comment]
I'm having the same issue, after copy stil fails

**Comment by zhushenhang** [comment]
> That warning means you need to copy those .node files to be in the same directory as your generated .exe file

works for me . thank you

**Comment by kkoomen** [comment]
The command I use is `pkg dist/index.js -t node10-linux-x64,node10-macos-x64,node10-win-x64` and then I copied all my `.node` files from my node_modules directory into my dist folder + also my root folder where the `index-*` files will be, and still get this warning.

How can this be solved?

**Comment by realeve** [comment]
> The command I use is `pkg dist/index.js -t node10-linux-x64,node10-macos-x64,node10-win-x64` and then I copied all my `.node` files from my node_modules directory into my dist folder + also my root folder where the `index-*` files will be, and still get this warning.
> 
> How can this be solved?

same with you.

**Comment by kkoomen** [comment]
I can confirm that #837 can fix this problem.

**Comment by Anjr0o** [comment]
@VandeurenGlenn @kkoomen Updating to version 14 or 15 of node and compiling to "node12-win-x64" will fix the issue _after_ copying the .node files.  If you try to compile to node 13 or 14 it won't work.

**Comment by kkoomen** [comment]
@Anjr0o You can use [my fork](https://github.com/kkoomen/pkg) and then you are able to compile to any version.

**Comment by atulmahankal** [comment]
> @VandeurenGlenn @kkoomen Updating to version 14 or 15 of node and compiling to "node12-win-x64" will fix the issue _after_ copying the .node files. If you try to compile to node 13 or 14 it won't work.

I have node version 16.15.1 but silll having same issue.
