### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by NurMarvin** [vercel/pkg#941]
It seems like pkg doesn't include indirect dependencies when those were installed using the pnpm package manager.
If e.g. the `chalk` module was installed using `pnpm add chalk` and then the project gets packaged into an executable with pkg, the resulting executable will fail to run with the error `Error: Cannot find module 'ansi-styles'`.

For easier reproduction purposes, here's a link to a repository of a project which makes use of the `chalk` module:
https://github.com/NurMarvin/pkg-pnpm-bug-example

Steps to reproduce the bug:
1. Clone the repository provided above
2. Run `pnpm install`
3. Run `pkg .`
4. Try running one of the produced executables

While I'm by no means an expert in the area revolving around pnpm, if I had to make an educated guess, I would assume this happens because pnpm puts indirect dependencies into a separate folder inside of the `node_modules` folder called `.pnpm`, which pkg probably doesn't check for packages to include into the executable.

**Comment by rizkyramadhan** [comment]
Can we make this work, pretty please ?

**Comment by tvolodimir** [comment]
I have the same issue in my project. Does someone found a workaround for this?

**Comment by erossignon** [comment]
This is not stale

**Comment by xkn1ght** [comment]
help! npm is super slow!

**Comment by xencodes** [comment]
any updates?
