### ISSUE TITLE
Cannot find module 'es-get-iterator'

### ISSUE THREAD

**Issue by jgehrcke** [vercel/pkg#943]
Used pkg@4.4.9 to do a build with the `pkg ...package.json` entry point. Cannot share details of that package.

Initially I got the following error upon execution:
```
Error: Cannot find module 'es-get-iterator'
Require stack:
- /snapshot/opstrace/node_modules/deep-equal/index.js
...
```

That brought my attention to these two issues
- https://github.com/ljharb/es-get-iterator/issues/5
- https://github.com/vercel/ncc/issues/521

I managed to change our package in a way that we got rid of the `deep-equal` dependency, and therefore the `es-get-iterator` dependency. Subsequently, the pkg build worked just fine! (that is, this was the _only_ problem in a rather complex build).

**Comment by jonohayon** [comment]
That's interesting, I have the exact same issue but I thought it was specific to our project. I've been looking for a problem specific in my build for two days now and thought I was going nuts 😅

**Comment by ljharb** [comment]
This seems like a vercel bug. `deep-equal`, and its use of `es-get-iterator`, all works properly.

Note, though, that `es-get-iterator` makes extensive (backwards compatible) usage of the "browser" and "exports" fields, so perhaps vercel's support for those is buggy?

**Comment by JAGFx** [comment]
A solution have found ?

**Comment by WoodySlum** [comment]
Any update on this ?

**Comment by ljharb** [comment]
ping - the browser field has a spec, vercel should follow it.

(also, bots closing issues is user-hostile)

**Comment by leerob** [comment]
@ljharb This isn't a Vercel platform issue – this is related to `pkg` specifically. See README:

> pkg was created for use within containers and is not intended for use in serverless environments. For those using Vercel, this means that there is no requirement to use pkg in your projects as the benefits it provides are not applicable to the platform.

Using a stale bot is a common solution for maintaining open-source projects. Especially as we're trying to clean up years of issues here which haven't been responded to. Thanks for your feedback, though!

**Comment by leerob** [comment]
Locking this to prevent hostility - will re-open if there are more reports. Thank you!
