### ISSUE TITLE
Cannot use regedit with PKG

### ISSUE THREAD

**Issue by han0idx** [vercel/pkg#944]
Im trying to compress my app.js to a standalone exe , i use this simple command:
`pkg app.js`

But i keep having this error:
`Error: vbscript process reported unknown error code 1`

i tried other solution but nothing works :( anyone know how to solve this ?

**Comment by qmenoret** [comment]
The regedit module uses some scripts that needs to be found by your packaged output.
Try to have a look to: https://github.com/ironSource/node-regedit#a-note-about-electron
