### ISSUE TITLE
Issue with duplicate names for .Node files (packaging .Node files with distribution)

### ISSUE THREAD

**Issue by johnharden** [vercel/pkg#950]
I'm currently working through an issue with utilizing ref-napi & ffi-api and bundling an executable for Windows where there are two .Node files I need packaged that have the same name.

```
> pkg@4.4.9
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: ...\project\node_modules\ref-napi\prebuilds\win32-x64\electron.napi.node
  %2: path-to-executable/electron.napi.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: ...\project\node_modules\ref-napi\prebuilds\win32-x64\node.napi.node
  %2: path-to-executable/node.napi.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: ...\project\node_modules\ffi-napi\prebuilds\win32-x64\electron.napi.node
  %2: path-to-executable/electron.napi.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: ...\project\node_modules\ffi-napi\prebuilds\win32-x64\node.napi.node
  %2: path-to-executable/node.napi.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: ...\project\node_modules\os-service\build\Release\service.node
  %2: path-to-executable/service.node
> Warning Cannot include addon %1 into executable.
  The addon must be distributed with executable as %2.
  %1: ...\project\node_modules\iconv\build\Release\iconv.node
  %2: path-to-executable/iconv.node
```

The problem is that I cannot differentiate the `\ref-napi\prebuilds\win32-x64\node.napi.node` file and the `\ffi-napi\prebuilds\win32-x64\node.napi.node` file. This is causing me to be unable to package up my distribution. 

I'm working through the issue, but saw no solution to this problem in the docs. If I get an update I'll be certain to update it here and provide a resolution path, but thought the pkg community may have an idea how to get over this hurdle.

Thanks!

**Comment by johnharden** [comment]
Unsolved, but found a solution that worked easier with this issue utilizing nexe.

**Comment by btsimonh** [comment]
for me (I'm a modified Nexe with lockjs), at unpack I give .node files a unique name on disk, and then when at dlopen, use that unique name.
The problem I have not (yet) overcome is that some stuff I package up has .dll dependencies, and sometimes those conflict.  This is more of a problem, because I can't rename them :(.  So WHEN I get to resolving the issue, I'm going to unpack the native deps into their original (relative) folders, so avoiding both issues.

**Comment by johnharden** [comment]
@btsimonh , yeah I'm only utilizing native windows 32 APIs in my package and no customized DLLs. My problem with renaming the .Node files wasn't that it was challenging, but it really ended up dropping support for any further upgrades with dependencies. Fortunately nexe, you just packed up a node_modules/ dir with the exe and bundle it all together in a zip (will put into a MSI next step), then ship it. The node_modules/ dir is what's used when reaching out for .Node files, so even though they still have the same name, they're in different folder structures. 

(I know this doesnt help you directly, but hoping to help anyone who stumbles across this github post)

**Comment by shvc** [comment]
any plan to resolve this issue?  I really need this feat

**Comment by robertsLando** [comment]
PR?
