### ISSUE TITLE
Adding new files from client to public folder in packaged public folder not working

### ISSUE THREAD

**Issue by abdurrehman1998** [vercel/pkg#952]
Error: ENOENT: no such file or directory, open

**Comment by 1181649328** [comment]
+1

**Comment by 1181649328** [comment]
Error: ENOENT: no such file or directory, open 'C:\Windows\System32\index.exe'
[90m    at Object.openSync (fs.js:457:3)[39m
[90m    at internal/bootstrap/pkg.js:35:17[39m
[90m    at internal/bootstrap/pkg.js:43:4[39m
[90m    at internal/bootstrap/pkg.js:44:2[39m {
  errno: [33m-4058[39m,
  syscall: [32m'open'[39m,
  code: [32m'ENOENT'[39m,
  path: [32m'C:\\Windows\\System32\\index.exe'[39m

**Comment by 1181649328** [comment]
The program I packaged was 32-bit but ran on 64-bit, and it caused the error

**Comment by raphtlw** [comment]
+1 same issue here

**Comment by hipstersmoothie** [comment]
No reproduction repo. If the issue persists feel free to open a new issue with a reproduction repo!
