### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by CecleCW** [vercel/pkg#953]
My application was complied using PKG 4.3.8 with node.js version 10.4.1, also we applied native node module, but today my application was crashed, and here's the Windows event log

Faulting application name: worker.exe, version: 2.4.7.0, time stamp: 0x5b27ceab
Faulting module name: ntdll.dll, version: 6.3.9600.19153, time stamp: 0x5b93ffa7
Exception code: 0xc0000374
Fault offset: 0x00000000000f1cd0
Faulting process id: 0x1ad8
Faulting application start time: 0x01d661a2cd902073
Faulting application path: D:\worker.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 812393f4-cd9d-11ea-8177-ecf4bbdcaffd
Faulting package full name: 
Faulting package-relative application ID: 

And also the Minidump file

Dump Summary
------------
Dump File:	worker (2).DMP : D:\Dump\worker (2).DMP
Last Write Time:	7/24/2020 7:27:38 PM
Process Name:	worker.exe : D:\worker.exe
Process Architecture:	x64
Exception Code:	not found
Exception Information:	
Heap Information:	Present

System Information
------------------
OS Version:	6.3.9600
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
worker.exe	D:\worker.exe	2.4.7.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.3.9600.19153
kernel32.dll	C:\Windows\System32\kernel32.dll	6.3.9600.17415
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.3.9600.19178
sysfer.dll	C:\Windows\System32\sysfer.dll	14.2.880.100
dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.3.9600.17415
advapi32.dll	C:\Windows\System32\advapi32.dll	6.3.9600.18895
user32.dll	C:\Windows\System32\user32.dll	6.3.9600.18535
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.3.9600.18264
psapi.dll	C:\Windows\System32\psapi.dll	6.3.9600.17415
userenv.dll	C:\Windows\System32\userenv.dll	6.3.9600.17415
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.3.9600.18340
crypt32.dll	C:\Windows\System32\crypt32.dll	6.3.9600.18653
winmm.dll	C:\Windows\System32\winmm.dll	6.3.9600.17415
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.9600.17415
sechost.dll	C:\Windows\System32\sechost.dll	6.3.9600.17734
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.3.9600.19202
gdi32.dll	C:\Windows\System32\gdi32.dll	6.3.9600.19202
nsi.dll	C:\Windows\System32\nsi.dll	6.3.9600.17415
winnsi.dll	C:\Windows\System32\winnsi.dll	6.3.9600.17415
profapi.dll	C:\Windows\System32\profapi.dll	6.3.9600.17415
msasn1.dll	C:\Windows\System32\msasn1.dll	6.3.9600.17415
WINMMBASE.dll	C:\Windows\System32\WINMMBASE.dll	6.3.9600.17415
sspicli.dll	C:\Windows\System32\sspicli.dll	6.3.9600.17415
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	6.3.9600.17415
devobj.dll	C:\Windows\System32\devobj.dll	6.3.9600.17415
imm32.dll	C:\Windows\System32\imm32.dll	6.3.9600.17415
msctf.dll	C:\Windows\System32\msctf.dll	6.3.9600.18819
powrprof.dll	C:\Windows\System32\powrprof.dll	6.3.9600.17415
mswsock.dll	C:\Windows\System32\mswsock.dll	6.3.9600.18340
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.3.9600.17415
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.3.9600.17415
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.3.9600.18541
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.3.9600.17415
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.3.9600.18895
pcwum.dll	C:\Windows\System32\pcwum.dll	6.3.9600.16384
deasync.node	\\?\C:\node_modules\deasync\bin\win32-x64-node-10\deasync.node	0.0.0.0
dhcpcsvc6.DLL	C:\Windows\System32\dhcpcsvc6.DLL	6.3.9600.17415
dhcpcsvc.dll	C:\Windows\System32\dhcpcsvc.dll	6.3.9600.17415
NapiNSP.dll	C:\Windows\System32\NapiNSP.dll	6.3.9600.17415
nlaapi.dll	C:\Windows\System32\nlaapi.dll	6.3.9600.18895
dnsapi.dll	C:\Windows\System32\dnsapi.dll	6.3.9600.19060
winrnr.dll	C:\Windows\System32\winrnr.dll	6.3.9600.17415
ndata.node	\\?\D:\addon\ndata.node	0.0.0.0
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.3.9600.17415
combase.dll	C:\Windows\System32\combase.dll	6.3.9600.19178
rasadhlp.dll	C:\Windows\System32\rasadhlp.dll	6.3.9600.17415
FWPUCLNT.DLL	C:\Windows\System32\FWPUCLNT.DLL	6.3.9600.18229

**Comment by CecleCW** [comment]
@igorklopov any comments?

**Comment by hipstersmoothie** [comment]
No reproduction repo. If the issue persists feel free to open a new issue with a reproduction repo!
