### ISSUE TITLE
Error: No native build was found for runtime

### ISSUE THREAD

**Issue by NotMoni** [vercel/pkg#955]
![Screen Shot 2020-07-28 at 11 41 56 PM](https://user-images.githubusercontent.com/40552237/88754148-ec829080-d12b-11ea-938d-b02e5029b9ab.png)

I typed in `pkg src/block`.

Why does my binary files not work ?

**Comment by NotMoni** [comment]
it has something to do with the https://github.com/wadey/node-microtime pkg

**Comment by NotMoni** [comment]
cc/ @CombatCode

**Comment by BluLightShow** [comment]
What is your target platform and nodejs version

**Comment by NotMoni** [comment]
@BluLightShow My target platform is MacOS and Windows with NodeJS 14

**Comment by BluLightShow** [comment]
First I'd suggest trying NodeJS LTS v12

**Comment by NotMoni** [comment]
Sure thing I'll cc you with the results

**Comment by NotMoni** [comment]
Hey @BluLightShow 
Here are the results...

![Screen Shot 2020-08-04 at 4 50 58 PM](https://user-images.githubusercontent.com/40552237/89343692-ad47c880-d672-11ea-962e-d0e1543799ba.png)

**Comment by newtykins** [comment]
Did you ever find a fix for this? I'm having the same issue but with lzma-native
![image](https://user-images.githubusercontent.com/19301186/147030922-203a5aaf-0542-4e10-8f2e-3a8c5efe1e88.png)

**Comment by NotMoni** [comment]
> Did you ever find a fix for this? I'm having the same issue but with lzma-native ![image](https://user-images.githubusercontent.com/19301186/147030922-203a5aaf-0542-4e10-8f2e-3a8c5efe1e88.png)

Nope. Seems like its not possible.
