### ISSUE TITLE
How do i can protect my source code before packaging?

### ISSUE THREAD

**Issue by daraboon** [vercel/pkg#959]
Hi
It is necessary to protect my source codes before packaging projects.
Is that protect codes in this library(packaging) or not?
Thanks

**Comment by viiralelite** [comment]
no

**Comment by viiralelite** [comment]
if your really concerned just use an obfuscator

**Comment by omid-student** [comment]
> 
> 
> if your really concerned just use an obfuscator

Thank you, How can I obfuscate codes?

**Comment by josiahbryan** [comment]
https://lmgtfy.app/?q=obfuscate+javascript

**Comment by hktr92** [comment]
@omid-student i just paired pkg with esbuild in two steps: first, the bundling with minification. then, pkg comes in action for this file and does the job nicely. i am, though, concerned about some js code that is not minified in the binary file, having 72 mb of file in the end. but still, it's cool to have this library at all. :)

**Comment by Hello-GBY** [comment]
Hi
It won't compile after obfuscation
How to solve it?
Thanks

**Comment by omid-student** [comment]
> 
> 
> Hi
> It won't compile after obfuscation
> How to solve it?
> Thanks

You right
Thanks

**Comment by therealtear** [comment]
> Hi
> It won't compile after obfuscation
> How to solve it?
> Thanks

Jfc no instead of compiling just obfuscate if you don’t want your code stolen

**Comment by iranapporg** [comment]
در اولین فرصت به پیام شما پاسخ داده خواهد شد
با تشکر از پیام شما مدیریت کامپیوتر دانشجو
www.iranapp.org
