### ISSUE TITLE
Can i run command line with executable file in snapshot file system?

### ISSUE THREAD

**Issue by lebanggit** [vercel/pkg#960]
I have small tool compress image with **[compress-images](https://www.npmjs.com/package/compress-images)**

I work fine via nomarl run ex: node img-compress.js.

However, It is  error with executable file made by pkg.

On log i see it run command line:

`F:\snapshot\compress-images\node_modules\mozjpeg\vendor\cjpeg.exe -quality 60 -outfile C:/image/13933686331665122661-
compress/0001.jpeg C:/image/13933686331665122661/0001.jpeg`

And drop error:

`Error: spawn F:\snapshot\compress-images\node_modules\mozjpeg\vendor\cjpeg.exe ENOENT
       at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
       at onErrorNT (internal/child_process.js:415:16)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     errno: 'ENOENT',
     code: 'ENOENT',`

So.... how can i complete my app.... Please help me.

**Comment by miraclx** [comment]
> That's probably the case, pkg probably just intercepts fs calls to `/snapshot` and resolves it with internal data.
>
> For this use case, the first time your executable is run, you can get readable streams to the assets (binaries) you want, and write them into an external staged directory (maybe even a temp dir), or if you embedded a zip file, extract that into your staged dir.
>
> Then you can spawn the executables with that path on your actual local filesystem.
>
> To speed things up (especially at startup), maybe don't use a random temp dir for each run.
>
> So you can use the assets from the previous extraction. (to save having to extract on every run)

_Originally posted by @miraclx in https://github.com/vercel/pkg/issues/1001#issuecomment-775071226_
