### ISSUE TITLE
having issues adding and using fs 

### ISSUE THREAD

**Issue by therealtear** [vercel/pkg#962]
im receiving this error
An error occurred:
Error: File or directory '/**/Tear#1261/codes.json' was not included into executable at compilation stage. Please recompile adding it as asset or script.
this is my package.json
 "bin": "./app.js",
  "pkg": {
    "assets": [
      "*html",
      "libs/*",
      "utils/*",
      "docs/*",
      "images/*",
      "util/*",
      "node_modules/**/*",
      "/**/Tear#1261/codes.json",
      "Tear#1261/*"
    ]
  },

this is my code
const cxdes = __dirname + "/codes.json";
 fs.writeFileSync(cxdes, JSON.stringify(working, null, 4));

**Comment by davidlares** [comment]
+1

**Comment by hipstersmoothie** [comment]
You should configure that file as an asset for pkg. See readme
