### ISSUE TITLE
I want to compile all my files in ./commands/**/*.js

### ISSUE THREAD

**Issue by amitco2468** [vercel/pkg#963]
I want to compile all my files in ./commands/**/*.js I try to add it in scripts but it's show the error of dynamic files.
and I dont want to require all my files cuz i have A LOT of files.
I just want it to be automuticly.

Thanks for helping.

**Comment by 313364973** [comment]
thanks too

**Comment by DJCoolDev** [comment]
Take a look at https://github.com/vercel/pkg#assets
