### ISSUE TITLE
Fail to compile armv7 linux

### ISSUE THREAD

**Issue by ctsdickson** [vercel/pkg#967]
My project can be built under macos environment, but fail to build nodexx-linux-armv7 under Raspberrypi 5.4.51-v7 armv7l Machine, which hang in "make" command a very long time with zero progress over 1 hour.

Command line: 
      pkg -t node12-linux-armv7 

Output: 
> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.18.1-linux-armv7 [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.18.1-linux-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.18.1-linux-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.18.1-linux-armv7"}
> Building base binary from source:
  built-v12.18.1-linux-armv7
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v12.18.1
> Applying patches
> Compiling Node.js from sources...
  make                         [                    ] 0%^C

**Comment by JeanCarlosChavarriaHughes** [comment]
I am receiving a similar issue for target: node12-linux-armv7.

```
> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.18.1-linux-armv7 [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.18.1-linux-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.18.1-linux-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.18.1-linux-armv7"}
> Building base binary from source:
  built-v12.18.1-linux-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'
```

**Comment by ctsdickson** [comment]
I confirmed that it cannot do cross compile armv7 in other OS like macos.

And I can build armv7 version at Raspberry Pi now, last time fail just because I don't have patient to wait for the result, it require several hours to compile the node js in Pi4. After compile succeed, node js bin will be installed in the hidden directory "/home/pi/.pkg-cache/v2.6/built-v12.18.1-linux-armv7", so rebuild nodejs only need once.

**Comment by Reda1000** [comment]
Looks like you solved your issue?

Be aware that cross-cpu-compilation is not possible (refer https://github.com/vercel/pkg/issues/605) - I guess your macos is not running on armv7 to "cross-compile" for linux armv7. 

Otherwise you are right the build on raspberry takes quite some hours.

**Comment by jailsonsilveira** [comment]
The build process on raspberry took hours and the make compilation of node binaries stucks in 0% and literally jumps to 100% after some hours. But the process works

**Comment by kaziu687** [comment]
The same on latest Raspbian on pi 4 (with node 14).

**Comment by jrj2211** [comment]
I too am having this issue on my RPI 4. Make stuck at 0% for 20 minutes now, I guess I'll let it keep going as others said it eventually finishes. Maybe I'll just downgrade to 12.2 since theres a precompiled version of that for ARMv7.

**Comment by jesec** [comment]
Superseded by #1148. 

Note that maintainers do not have enough resources to support armv7. It has been deprecated in 5.0.
