### ISSUE TITLE
Target parses wrong platform -> impossible arm builds

### ISSUE THREAD

**Issue by cupcakearmy** [vercel/pkg#969]
## Problem

The `--target` directive parses the input bad, making arm build on macOS basically impossible.

The latest release from https://github.com/vercel/pkg-fetch/releases for armv7 is: `node-v12.2.0-linux-armv7`

## Reproduce

```bash
yarn add pkg
# installed pkg@4.4.9
```

```js
// index.js
console.log('Hello')
```

```bash
yarn pkg -t node12.2.0-linux-armv7 index.js
# tries to download the macos arm version: uploaded-v2.6-node-v12.2.0-macos-armv7

yarn pkg -t node12-linux-armv7 index.js
# version 12 points to a bad version: uploaded-v2.6-node-v12.18.1-linux-armv7

yarn pkg -t latest-linux-armv7 index.js
# same with latest: uploaded-v2.6-node-v14.4.0-linux-armv7
```

Is there a way to simply set the download version manually?

**Comment by chainhead** [comment]
The [`pkg-binaries`](https://github.com/robertsLando/pkg-binaries) repo has pre-built binaries. You could download and save it in the `.pkg-cache/vx.x` folder and then try to build. You will have to rename the binary into something that `pkg` expects.

**Comment by RogerKang** [comment]
Met same issue. 
When I specify targrt to armv7 on Macos, it will always try to fetch both armv7 & macos binaries which will definitely fail because there is no macos built binaris based on arm right now(yes, it will in the future because Apple has launch its arm based Mac project).
basically:

pkg --targets node12.2.0-linux-armv7 index.js
> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.2.0-linux-armv7  [====================] 100%
  fetched-v12.2.0-macos-armv7  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-macos-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-armv7"}
> Building base binary from source:
  built-v12.2.0-macos-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'

we cans see that it try to down load two binaries:
fetched-v12.2.0-linux-armv7
fetched-v12.2.0-macos-armv7
The second one will always failed.

**Comment by cupcakearmy** [comment]
Not resolved, tested it a few weeks ago

**Comment by robertsLando** [comment]
@cupcakearmy Please try to test this again, it should be fixed in 4.5.0

**Comment by cupcakearmy** [comment]
Just tried with `4.5.0`

**node12.2.0-linux-armv7**

```
yarn pkg dist/index.js --targets node12.2.0-linux-armv7 --out-path bin                             718ms  Thu Mar 25 08:52:56 2021
yarn run v1.22.10
$ /Users/****/node_modules/.bin/pkg dist/index.js --targets node12.2.0-linux-armv7 --out-path bin
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.2.0-linux-armv7  [====================] 100%
  fetched-v12.2.0-macos-armv7  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-macos-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-armv7"}
> Building base binary from source:
  built-v12.2.0-macos-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**node12-linux-armv7**

```
yarn pkg dist/index.js --targets node12-linux-armv7 --out-path bin                                 13.5s  Thu Mar 25 08:53:16 2021
yarn run v1.22.10
$ /Users/****/node_modules/.bin/pkg dist/index.js --targets node12-linux-armv7 --out-path bin
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.18.1-linux-armv7 [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.18.1-linux-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.18.1-linux-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.18.1-linux-armv7"}
> Building base binary from source:
  built-v12.18.1-linux-armv7
> Error! Not able to build for 'linux' here, only for 'macos'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**latest-linux-armv7**

```
yarn pkg dist/index.js --targets latest-linux-armv7 --out-path bin                                2264ms  Thu Mar 25 08:55:00 2021
yarn run v1.22.10
$ /Users/****/node_modules/.bin/pkg dist/index.js --targets latest-linux-armv7 --out-path bin
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-linux-armv7  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.4.0-linux-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-armv7"}
> Building base binary from source:
  built-v14.4.0-linux-armv7
> Error! Not able to build for 'linux' here, only for 'macos'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The most relevant maybe is the target `node12.2.0-linux-armv7` where it downloads the binary correctly but then goes on wanting to download `uploaded-v2.6-node-v12.2.0-macos-armv7` which is clearly still the bug of wrongly parsing the target.

**Comment by robertsLando** [comment]
What's the output of `uname -a` command?

**Comment by cupcakearmy** [comment]
Darwin 20.3.0 on x86. I'm on macOS

**Comment by robertsLando** [comment]
@cupcakearmy Could yu try with `yarn pkg dist/index.js --target node12.2.0-linux-armv7 --out-path bin` ? 

Note `--target` instead of `--targets`

**Comment by cupcakearmy** [comment]
No luck unfortunately

```
yarn pkg dist/index.js --target node12.2.0-linux-armv7 --out-path bin  Thu Mar 25 10:09:23 2021
yarn run v1.22.10
$ /Users/****/node_modules/.bin/pkg dist/index.js --target node12.2.0-linux-armv7 --out-path bin
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.2.0-macos-armv7  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-macos-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-armv7"}
> Building base binary from source:
  built-v12.2.0-macos-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by robertsLando** [comment]
I have a feeling that the probelm could be due to the `yarn run` command. 

Just to be sure could you try to install pkg globally and retry the command? 

```
npm install -g pkg
pkg dist/index.js -t node12.2.0-linux-armv7 --out-path bin  

```

**Comment by cupcakearmy** [comment]
```
pkg dist/index.js --target node12.2.0-linux-armv7 --out-path bin7.9s  Thu Mar 25 10:24:17 2021
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.2.0-macos-armv7  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-macos-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.2.0-macos-armv7"}
> Building base binary from source:
  built-v12.2.0-macos-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'
```

**Comment by robertsLando** [comment]
@cupcakearmy I cannot undesrtand why the targets are wrongly parsed from the command you are sending... what I could suggest you is to manually debug it on your side by placing a breakpoint [here](https://github.com/vercel/pkg/blob/master/lib/index.js#L38) and see where the parse is failing

**Comment by jesec** [comment]
Refs: #457 #1182

By default, `pkg` will run the executable of the target architecture to generate bytecodes.

You can choose to expose source codes and disable bytecode generation: `--no-bytecode --public-packages "*" --public`.

Closing in favor of #457. `pkg` parses the platform correctly.
