### ISSUE TITLE
Cannot compile v12 for armv7 because it is trying to download non existing windows binary

### ISSUE THREAD

**Issue by vitaly-agriocom** [vercel/pkg#972]
![image](https://user-images.githubusercontent.com/71056826/92680792-61b5c800-f35e-11ea-9f32-bdac8c772ce8.png)

**Comment by josiahbryan** [comment]
Only way I've been able to build for armv7 is using a linux build host. Go grab a Digitial Ocean VM for $5 USD/mo or something and build on that ...works great. Personally, I have an old linux laptop on my wifi in my closet that I use as a build host - wrote a simple bash script to copy the javascript to build to the linux laptop, build the arm binary, then download the arm binary back to my Mac.
