### ISSUE TITLE
Can't pkg with playwright framework

### ISSUE THREAD

**Issue by sunaram** [vercel/pkg#975]
I am trying to package my script that uses playwright (https://github.com/microsoft/playwright) into an exe file.
I am using pkg v4.4.9
My pkg config looks like this
```
"pkg": {
    "assets": [
      "node_modules/playwright-firefox/bin/PrintDeps.exe"
    ],
    "targets": [
      "node12-win-x64"
    ]
  }
```
When I try to execute the exe file, it gives an error message like this
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn E:\snapshot\MyProject\node_modules\playwright-firefox\bin\PrintDeps.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn E:\\snapshot\\MyProject\\node_modules\\playwright-firefox\\bin\\PrintDeps.exe',
  path: 'E:\\snapshot\\MyProject\\node_modules\\playwright-firefox\\bin\\PrintDeps.exe',
  spawnargs: [
    'C:\\Users\\username\\AppData\\Local\\ms-playwright\\firefox-1144\\firefox\\Accessible.tlb'
  ]
}
```

What do you think should I be doing to fix this?

**Comment by redbrain** [comment]
take a look at #420 , it might work for you to bundle complex things like runtimes

**Comment by sunaram** [comment]
> take a look at #420 , it might work for you to bundle complex things like runtimes

Thanks. I just needed to use environment variable to set the correct path to the executable and it took care of everything.
I added the following code at the top of the entry script (app.js in my case)
```
const path = require("path");
process.env.PLAYWRIGHT_BROWSERS_PATH = path.join(process.cwd(), "/pw-browsers");
```
Of course, I installed my browser executables by setting the path to "pw-browsers" dir in the script directory.
