### ISSUE TITLE
Create exe with txt file in it too

### ISSUE THREAD

**Issue by MegaGangster** [vercel/pkg#980]
I'm creating a account generator and I want to make it exe pkg, but the problem is that my code takes the accounts from a accounts.txt file so when I make it exe it will not find the txt file, there is any solutions?

**Comment by aateek-albanero** [comment]
I don't know if you have tried assets. I had a similar use case where I wanted fetch a `.env` file.
Just try to refer it in related .js file using path.join(), see [Detecting assets in source code](https://www.npmjs.com/package/pkg#detecting-assets-in-source-code)

**Comment by sunaram** [comment]
> I'm creating a account generator and I want to make it exe pkg, but the problem is that my code takes the accounts from a accounts.txt file so when I make it exe it will not find the txt file, there is any solutions?

Let's assume your  entry script app.js needs to load accounts.txt, rather than doing
`const filePath = "accounts.txt";`
do
```
const path = require("path");
const filePath = path.join(process.cwd(), "/accounts.txt");
```
Assuming accountx.txt  is in the root folder
