### ISSUE TITLE
NodeJS 14 targets: out-of-date binaries (14.4.0 vs 14.14.0)

### ISSUE THREAD

**Issue by jgehrcke** [vercel/pkg#986]
This is about the "base binaries" that are described in this paragraph (https://github.com/vercel/pkg#build):

> pkg has so called "base binaries" - they are actually same node executables but with some patches applied. They are used as a base for every executable pkg creates. pkg downloads precompiled base binaries before packaging your application. 

When using `--targets node14-linux-x64 node14-macos-x64` we -- as of today -- by default get NodeJS 14.4.0-based binaries. This has been the case for a while and I was hoping for an update of these binaries to happen at some point.

When will you update these binaries to be based on a more recent NodeJS 14.x release? Is there a process for that? Are you waiting for questions like this? :-)

Thanks for the work on pkg!

**Comment by monotykamary** [comment]
You probably have to refer to the [https://github.com/vercel/pkg-fetch](pkg-fetch) repository as that is where the patches are applied to the base source.

If you have time, you can contribute and help out; I honestly think they need to setup a more convenient way to CI their patch rebases, but testing and fixing patches is not trivial, especially when there are new Node releases practically every week.

**Comment by jgehrcke** [comment]
Thanks for the comment @monotykamary!

**Comment by arminbarazesh** [comment]
@jgehrcke  do you have any suggestion for building a node version 15 app?
it seems pkg doesn't support version above 12!
