### ISSUE TITLE
د

### ISSUE THREAD

**Issue by Anouomgharbivsseagjdzzvz** [vercel/pkg#988]
ملتقط بواسطة XRecorder: https://recorder.page.link/Best![Edited_٢٠٢٠١٠٢٣_٠٠٣٧٠٨.jpg](https://user-images.githubusercontent.com/18543862/96932758-139cf400-14c8-11eb-90cd-e2157c94e00d.jpg)د

**Comment by somuelle-tmt** [comment]
?
