### ISSUE TITLE
Error: Cannot find module 'C:UsersMeDesktopDiscord Bot.config.json'

### ISSUE THREAD

**Issue by ant2006** [vercel/pkg#993]
I'm trying to make a simple discord bot, code is here: https://pastebin.pl/view/70d6f679

And i get this error: https://pastebin.pl/view/b73c9bd1

My config.json file is in the same folder as the main bot file, the config is saved as config.json, i can't think of anything else to try to fix it.

Note: I'm very new to js, so please clearly explain your answers. Thanks!

**Comment by DJCoolDev** [comment]
This error means that pkg couldn't find your file, so pkg couldn't find your config, this is because you probably only converted the file without the config. To fix this error, take a look at the https://github.com/vercel/pkg#Config and https://github.com/vercel/pkg#assets

**Comment by redbrain** [comment]
If you're on Windows, try doubling the slashes in your file path
