### ISSUE TITLE
[Question] can I put my secrets in the compiled .exe file 

### ISSUE THREAD

**Issue by saostad** [vercel/pkg#994]
Hi,
can I put my secrets like DB passwords in the compiled .exe file? 
I know technically I can put anything in my code and compile it but want to know is it recommended or not? 
and how easy is to read the code content from the .exe file after I compile it?

**Comment by lselden** [comment]
See #340 - Don't do it!

**Comment by saostad** [comment]
I understood the source code is available to end-user if they open the .exe file in hex editor like vscode.
one solution is to use tools like [JavaScript Obfuscator Tool](https://obfuscator.io/)
