### ISSUE TITLE
Prebuilt ARMv7 binaries are very old and affected by "Random call stack size exceeded" error on NodeJs 12.2.0

### ISSUE THREAD

**Issue by Ks89** [vercel/pkg#995]
Is it possible to update prebuilt binaries for ARMv7? The current version on NodeJs 12.2.0 is affected by this frustrating issue https://github.com/vercel/pkg/issues/681.

Could you upload prebuilt binaries for NodeJs 12.x.x LTS (latest version) and NodeJs 14.x.x LTS (latest version)?

thank you.

**Comment by domingguss** [comment]
in case anyone's still wandering - this for me works:
 i downloaded and use the static libs from here:

https://github.com/Hypfer/pkg-fetch/releases/tag/v3.0.4-valetudo
