### ISSUE TITLE
How to build the binary same as uploaded-v2.6-node-v10.17.0-win-64

### ISSUE THREAD

**Issue by 3DGISKing** [vercel/pkg#998]
Hi,
Thank you for this great project.
I need to build the binary based on Node js 10.17.0 from scratch on Windows 64.
Actually, I want to build and get the result the same as uploaded-v2.6-node-v10.17.0-win-64 from the source.
But the result was different from the uploaded-v2.6-node-v10.17.0-win-64.
They are different in raw size.

What I tried
1 Install pkg-fetch 2.6.4
2 install Python 2.7.17
3 install NASM 2.13
4 install Visual Studio 2017 Community
5 manually get Node js 10.17.0 source (I used the source cloned by pkg-fetch 2.6.4 's build step )
6 manually apply patch : node.v10.17.0.cpp.patch from pkg-fetch 2.6.4 source.
7 build
I used the same command as pkg-fetch 2.6.4 for the build.
“cmd /c vcbuild.bat x64 noetw nosign noperfctr”

![image](https://user-images.githubusercontent.com/26606704/98262207-4d89f200-1fc0-11eb-8b2d-a6f9d47c2b08.png)

**Comment by gireeshpunathil** [comment]
short answer: download and unzip this and build from it:
https://nodejs.org/download/release/v10.17.0/node-v10.17.0.tar.gz

long answer:
 - https://nodejs.org/
 - other download option
 - previous releases
 - select `Node.js 10.17.0` or any desired version
 - select `downloads` link
 - along with the built binaries, the source tar is also provided

hope this helps!

**Comment by 3DGISKing** [comment]
thank you for your response.
but I have already tried this. 
but my build output was different from the pre-built binary by pkg-fetch in size.
any tip? 

is the following build command right?
cmd /c vcbuild.bat x64 noetw nosign noperfctr

**Comment by gireeshpunathil** [comment]
> but my build output was different from the pre-built binary by pkg-fetch in size.

that I don't know, from the source perspective, they should be the same

I think they (Node.js release team) builds with just `vcbuild.bat` , and with no params. (I am not 100% sure though), may be worth trying that

**Comment by 3DGISKing** [comment]
thanks

**Comment by leerob** [comment]
Support will be for Node 12 and 14 going forward. Thanks!

https://endoflife.date/nodejs
