### ISSUE TITLE
Excessively large binaries being created?

### ISSUE THREAD

**Issue by redbrain** [vercel/pkg#999]
A 'hello world' in Node.js taking less than 1 KB has a 69 MB binary when compiled using pkg.
For your convenience, you can see the source, steps I took, and resulting binary [here](https://github.com/redbrain/helloworldpkg/).
I'm assuming this is because pkg is forced to bundle all of Node.js with the binaries.
**Is there a way to make simple binaries smaller**, maybe by using a smaller Node source? Thanks in advance.

**Comment by simonnilsson** [comment]
Compiling Node.js with `--without-intl` will reduce the size considerably. With the downside of the Internationalization API being unavailable. So if not using Intl (or modules that depend on it) this could be an option.

Using current master branch of Node.js (v16.0.0-pre)
* Normal: **74MB**
* Without Intl: **41MB**

It would be nice if pkg had an argument to use such a build, and also include them among the pre-built binaries.

**Comment by redbrain** [comment]
Thanks. I'll try to find a way to get pkg to accept a smaller/custom node source, and if it does I might write a PR

**Comment by ArkadiuszMichalski** [comment]
In future please consider adding to pkg some switch to not include this Internationalization API, even `node.exe` downloaded from official server weighs only 55 MB.

**Comment by Slapbox** [comment]
@hipstersmoothie is this actually completed? If so, can you please share how to use this option?
